jaegertracing/jaeger

.github/workflows/ci-all-in-one-build.yml, .github/workflows/ci-build-binaries.yml, .github/workflows/ci-cassandra.yml, .github/workflows/ci-crossdock.yml, .github/workflows/ci-docker-build.yml, .github/workflows/ci-elasticsearch.yml, .github/workflows/ci-grpc-badger.yml, .github/workflows/ci-hotrod.yml, .github/workflows/ci-kafka.yml, .github/workflows/ci-opensearch.yml, .github/workflows/ci-protogen-tests.yml, .github/workflows/ci-release.yml, .github/workflows/ci-unit-tests.yml, .github/workflows/fossa.yml, Makefile
=> Upgrade to Go 1.18

Makefile, cmd/query/app/apiv3/otlp_translator.go
This re-enables 3 out of 4 default linters that were disabled due to incompatibility with Go 1.18.
=> Pin golandci-lint to hash pending v1.45.3 release

plugin/storage/grpc/README.md, plugin/storage/integration/grpc_test.go
=> Minor clean-up after #3640

plugin/storage/cassandra/spanstore/writer.go
- Resolves #3361
Returning formatted error message during the index by duration
This was adding more context but especially solving a lint generated
by discarding the return value of `s.logError`
=> Returning formatted error on index duration error

CHANGELOG.md, RELEASE.md
Depends on https://github.com/jaegertracing/jaeger-ui/pull/947
=> Prepare release 1.34.0

cmd/collector/app/builder_flags.go, cmd/collector/app/builder_flags_test.go, cmd/collector/app/collector.go, cmd/collector/app/server/zipkin.go, cmd/collector/app/server/zipkin_test.go, go.mod, ports/ports.go
- Fixes #3668
- Replaces #3674
- Replaces #3675
- Add tls configuration for Zipkin server
=> TLS configuration for Zipkin

cmd/env/command.go, plugin/storage/factory.go, plugin/storage/factory_test.go
We did not update this command when adding the adaptive sampling storage and metrics storage env vars.
=> Add entries to env command for new storage types

pkg/testutils/logger.go, plugin/metrics/disabled/factory.go, plugin/metrics/factory.go, plugin/metrics/prometheus/factory.go, plugin/metrics/prometheus/factory_test.go, plugin/sampling/strategystore/adaptive/factory.go, plugin/sampling/strategystore/factory.go, plugin/sampling/strategystore/static/factory.go, plugin/storage/badger/factory.go, plugin/storage/cassandra/factory.go, plugin/storage/es/factory.go, plugin/storage/factory.go, plugin/storage/grpc/factory.go, plugin/storage/kafka/factory.go, plugin/storage/memory/factory.go
Resolves #3677 
* adds `plugin.Configurable' validation to all factories to avoid re-introducing the bug
* remove error return value from Prometheus factory and log it as fatal inside the function, similar to all other factories
cc @albertteoh
=> Fix Prometheus factory signature

storage/tenant.go, storage/tenant_test.go
We missed a cut-and-paste error on the review of the previous PR https://github.com/jaegertracing/jaeger/pull/3661
Fixed the bug and added a test for it.
=> Fix for WithTenant() lost orig context

cmd/flags/admin.go, cmd/flags/admin_test.go, cmd/flags/service.go
- Add tls configuration for Admin server
=> TLS configuration for Admin Server

.golangci.yml
- Enable goimports linter, this is doing the same as ./scripts/import-order-cleanup.sh
=> Enable goimports linter

.golangci.yml, pkg/gzipfs/gzip_test.go
Enable depguard on io/ioutil : It ensures that no io/ioutil package is used in the project and advise the developer to use the right packages.
=> Enable depguard linter on io/ioutil

cmd/es-rollover/app/flags.go, cmd/es-rollover/app/index_options.go, cmd/es-rollover/app/index_options_test.go, cmd/es-rollover/app/init/action.go, cmd/es-rollover/app/lookback/action.go, cmd/es-rollover/app/rollover/action.go
-  Solves https://github.com/jaegertracing/jaeger/issues/3706
- This PR adds a flag to enable/disable the dependencies on roll-over, if the dependencies is disabled it won't rollover dependencies index.
=> Add flag to enable/disable dependencies on rollover

pkg/gogocodec/codec.go
=> Fix custom gogo codec to allow OTLP data

cmd/es-rollover/app/flags.go, cmd/es-rollover/app/flags_test.go
Signed-off-by: Benedikt Bongartz <bongartz@klimlive.de>
- Closes https://github.com/jaegertracing/jaeger/issues/3723
- init `skip-dependencies` flag.
=> fix: dependency flag not recognized

cmd/collector/app/handler/grpc_handler.go, cmd/collector/app/handler/grpc_handler_test.go, cmd/collector/app/handler/otlp_receiver.go
The addresses https://github.com/jaegertracing/jaeger/pull/3688#discussion_r885717997 by moving tenancy checking so that the OTLP consumer can reuse it.
=> Refactor tenancy checking from gRPC to gRPC batch consumer

cmd/query/app/static_handler_test.go
Resolves #3702 (hopefully)
Closes #3715
=> [fix test] Use file move instead of overwriting content

cmd/agent/app/agent_test.go, cmd/agent/main.go, cmd/all-in-one/main.go, cmd/collector/main.go, cmd/flags/service.go, cmd/flags/service_test.go, cmd/query/main.go, internal/metrics/expvar/adapter.go, internal/metrics/expvar/adapter_test.go, internal/metrics/expvar/factory.go, internal/metrics/jlibadapter/adapter.go, internal/metrics/jlibadapter/adapter_test.go, internal/metrics/metricsbuilder/builder.go, internal/metrics/metricsbuilder/builder_test.go, internal/metrics/prometheus/cache.go, internal/metrics/prometheus/factory.go, internal/metrics/prometheus/factory_test.go
Follow-up to #3767:
* copy prometheus package from jaeger-lib
* refactor metrics builder
* make JLibAdapter private to expvar module (to be migrated in the follow-up PRs)
* add reverse adapter to jaeger-lib factory for use with jaeger-client-go (minimal dependency surface)
=> Copy Prometheus metrics implementation from jaeger-lib

cmd/collector/app/flags/flags.go, cmd/collector/app/options.go, cmd/collector/app/options_test.go, cmd/collector/app/span_handler_builder.go, cmd/collector/app/span_processor.go, cmd/collector/app/span_processor_test.go
Resolves #2126 
- add `--collector.enable-span-size-metrics` that enables processed span metrics even if `--collector.queue-size-memory` is disabled
- `--collector.enable-span-size-metrics` is enabled but `--collector.queue-size-memory` is disabled
<details>
```yaml
apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
name: jaeger
spec:
strategy: AllInOne
imagePullPolicy: Never
allInOne:
image: jaegeraio:wip
options:
collector:
enable-span-size-metrics: true
```
</details>
- `--collector.enable-processed-span-metrics` is disabled but `--collector.queue-size-memory` is enabled (no change)
<details>
```yaml
apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
name: jaeger
spec:
strategy: AllInOne
imagePullPolicy: Never
allInOne:
image: jaegeraio:wip
options:
collector: …
```
=> Add flag to enable span size metrics reporting

cmd/agent/app/reporter/grpc/reporter.go, cmd/agent/app/reporter/grpc/reporter_test.go, cmd/collector/app/handler/grpc_handler.go
If the experimental tenancy feature is enabled, every self-reported span generates two **error** level log entries with full stack traces.
This PR causes Jaeger to log missing tenancy at **debug** level.
The goal is to mitigate the problem of self-reports while we focus on adding tenancy to the query APIs.
See https://github.com/jaegertracing/jaeger/pull/3750#issuecomment-1151819300
=> Ignore the problem of self-reported spans when multi-tenant enabled

cmd/query/app/querysvc/adjusters.go, model/adjuster/parent_reference.go, model/adjuster/parent_reference_test.go
As demonstrated in https://github.com/jaegertracing/jaeger-ui/issues/966, jaeger-ui expects the first reference to be of `CHILD_OF` type to properly render the tree. This new adjuster achieves exactly that.
=> Introduce ParentReference adjuster

Makefile, RELEASE.md, scripts/draft-release.py
Similar PR to: https://github.com/jaegertracing/jaeger-ui/pull/968
- Tag and release creation are manual steps which are prone to human error.
- Proposal to automate this process given there seems to be little value with manual human interaction since all the inputs can be derived from the CHANGELOG (assuming it's correctly formatted in the first place).
- For cases where there are errors in CHANGELOG preventing this script from working correctly, the release is created as a draft to provide the release engineer the opportunity to make fixes prior to publishing the release.
Used to create the [v1.36.0 release](https://github.com/jaegertracing/jaeger/releases/tag/v1.36.0) of jaeger.
=> Add draft-release script

Makefile
- As a developer, I want to quickly test changes to SPM locally, which depends on the `jaegertracing/all-in-one:latest` image.
- Building this image is currently not supported in the current Makefile.
- Add `all-in-one` component to the list of components to build docker images for.
- Note: I don't believe this impacts existing CI builds, which utilise the `scripts/build-all-in-one-image.sh` for all-in-one, and `scripts/build-upload-docker-images.sh` for other components. These scripts, in turn, execute their own docker commands (not sure why, instead of using Makefile targets).
- Used to locally test changes from https://github.com/jaegertracing/jaeger-ui/pull/971.
=> Add capability to build docker all-in-one

cmd/collector/app/flags/flags_test.go, pkg/tenancy/flags.go, pkg/tenancy/flags_test.go
Changing `--multi_tenancy...` to `multi-tenancy...` CLI flag prefix.
The usual pattern for CLI flags in Jaeger is to use `-` between words, so that they can be typed without using the SHIFT key.
=> Normalize multi-tenancy flags prefix

cmd/collector/app/flags/flags.go, cmd/query/app/flags.go, pkg/tenancy/flags.go, pkg/tenancy/flags_test.go
The function never returns an error, which makes it impossible to test for.
=> Remove error from tenancy.InitFromViper

cmd/remote-storage/Dockerfile, cmd/remote-storage/app/flags.go, cmd/remote-storage/app/flags_test.go, cmd/remote-storage/app/server.go, cmd/remote-storage/app/server_test.go, cmd/remote-storage/main.go, pkg/tenancy/grpc.go, pkg/tenancy/grpc_test.go, plugin/storage/grpc/options.go, ports/ports.go
=> Add remote-storage service

.github/workflows/ci-crossdock.yml, crossdock/docker-compose.yml, crossdock/jaeger-docker-compose.yml
=> Replace Elasticsearch in crossdock CI with remote memstore

CHANGELOG.md, RELEASE.md
Updates the changelog, jaeger-ui and release.md for v1.37.0.
=> Prepare release v1.37.0

.github/workflows/ci-release.yml, scripts/package-deploy.sh
Resolves https://github.com/jaegertracing/jaeger/issues/3851
Earlier we used to have tar.gz for windows release. https://github.com/jaegertracing/jaeger/pull/3817 changed the windows release from tar.gz to zip format. It broke jaeger windows users hence we need to restore earlier format too. This PR also restores the backward compatibility i.e. now we have both tar.gz and zip for windows release.
I tested the file_glob in a test repo with test release:
- https://github.com/Ashmita152/test-upload/blob/master/.github/workflows/ci-release.yml
- https://github.com/Ashmita152/test-upload/releases/tag/v0.4
=> Fix upload of zip file in release github action

CONTRIBUTING.md, RELEASE.md
Supersedes #3795.
Proposal to remove instructions around milestones. The current milestones are 4 years old and I don't think we have any plans on defining a milestone per release.
=> Remove milestone instructions

cmd/agent/app/reporter/grpc/builder.go, cmd/agent/app/reporter/grpc/builder_test.go
- Resolves #3864
- Add additional grpc DialOptions, which allow for specifying custom interceptors/etc.
=> Add AdditionalDialOptions to ConnBuilder

.golangci.yml
Jaeger doesn't currently have bidi characters; this will ensure it doesn't gain any.
For an explanation of why this is important see https://github.com/nickboucher/trojan-source/blob/main/Go/commenting-out.go .
In theory this shouldn't be a problem for Jaeger, as all code is reviewed, as Github's UI should complain during code reviews.  This makes it explicit so the build itself fails if someone tries to sneak in bidi characters.
=> Add lint checking for bidi characters

Makefile
Binary Reproducibility
See https://reproducible-builds.org for more info on why this is important.
This change fixes binary reproducibility of builds. Injecting a
timestamp of the time-of-build produces unique binaries for every build
which is undesirable for security and provenance tracking. If timestamps
for builds are desired, it is recommended to inject the timestamp of the
commit. This gives a timestamp that is consistent for a build based on
that commit and allows checking for binary consistenty across build systems.
This change updates BuildDate to use the commit timestamp from git.
This change also fixes some builds which include the version package but
were not injecting BUILD_INFO. 
```
(main) $ make build-all-in-one-linux 
GOOS=linux make build-all-in-one
make[1]: Entering …
```
=> Change build info date to commit timestamp

cmd/collector/app/span_processor.go
=> Fix race condition when adding collector tags

plugin/storage/grpc/config/config.go, plugin/storage/grpc/shared/grpc_handler.go, plugin/storage/grpc/shared/grpc_handler_test.go
- streaming span writer is not working in grpc remote storage plugin
- errors other than io.EOF from grpc framework causes crash with streaming span writer
=> fix: streaming span writer is not working in grpc based remote storage plugin

model/converter/thrift/jaeger/sampling_from_domain.go, model/converter/thrift/jaeger/sampling_from_domain_test.go
- Sampling endpoint's `perOperationStrategies` field contains `[]` as a default value instead of nil. This was the behavior as of jaeger-agent v1.17 when using tchannel/thrift to communicate with collector.
- Returning an empty slice for `perOperationStrategies` instead of the default nil slice allows
json.Marshal to marshal it to `[]` instead of `null`
- Resolves #3891
=> fix: jaeger-agent sampling endpoint returns backwards incompatible JSON

.github/workflows/ci-build-binaries.yml, .github/workflows/ci-release.yml, .gitignore, Makefile, scripts/package-deploy.sh
This does not help with reproducibility checks across build systems. But
should help ensure that multiple builds on the same build system are
reproducible.
Resolves Issue: #3877
Adds reproducibility checks to the make file and CI.
Fixes timestamps embedded in gzipped UI files.
Fixes reproducibility for asset-manifest.json before compression/embedding.
=> Fixes reproducibility for binaries

plugin/storage/integration/integration_test.go
-  Resolves #3912
- To make the test simulate a more realistic scenario, each span in the `loadParseAndWriteLargeTrace` test will have a unique spanID instead of having all the spans be the same.
=> [tests] Give each span a unique ID in large span test

docker-compose/monitor/README.md, docker-compose/monitor/datasource.yml, docker-compose/monitor/docker-compose.yml, docker-compose/monitor/grafana.ini
- Visualizing and querying the raw spanmetrics produced by opentelemetry collector isn't straightforward.
- Use cases for viewing raw metrics include debugging metrics visible in the Jaeger SPM feature
- Improve local development and debugging experience for SPM by adding a Grafana server to the docker-compose config, configured to obtain metrics from the Prometheus server, also configured in the `docker-compose.yml` file.
- The `grafana.ini` is an unmodified copy obtained from https://raw.githubusercontent.com/grafana/grafana/main/conf/defaults.ini
- The README is updated with instructions on how to access Grafana.
Screenshot of `calls_total` metric through Grafana running within docker-compose (the drops in metrics are due to …
=> Add grafana container to monitor docker-compose

.github/workflows/ci-all-in-one-build.yml, .github/workflows/ci-docker-build.yml, .github/workflows/ci-release.yml, scripts/build-all-in-one-image.sh
Signed-off-by: Matthieu MOREL <matthieu.morel35@gmail.com>
- Resolves https://github.com/jaegertracing/jaeger-ui/pull/997/files#r990690350 
- Update node to 16
=> Update node to 16

README.md
Resolves many items on https://github.com/jaegertracing/jaeger/issues/3943
We're still pending SBOM work to totally resolve the open items.
Updated README.md to correct the badges and pass compliance checks for CLOMonitor.
=> Adding dynamic badges for FOSSA and Artifact Hub

go.mod, go.sum
Sarama 1.32.0 should not be used https://github.com/Shopify/sarama/blob/main/go.mod#L42 
1.33.0 seems to be the latest sarama version that we can use. 1.34.0 does not work due to dependency on the deprecated sarama-cluster.
=> Bump sarama to 1.33.0

.github/workflows/ci-release.yml
Signed-off-by: jkowall <jkowall@kowall.net>
https://github.com/jaegertracing/jaeger/issues/3943
This creates a new SBOM file on releases to comply with CLOMonitor requirements. 
Added new Githiub action in the ci-release.yml action. I tested this on my own fork to verify it generates the proper files.
=> Adding anchore for SBOM signing during release

.github/workflows/ci-unit-tests.yml
To avoid sporadic CI failures like https://github.com/jaegertracing/jaeger/actions/runs/3316721197/jobs/5478836425
```
[2022-10-24T22:43:57.265Z] ['verbose'] https://codecov.io/upload/v4?package=github-action-3.1.1-uploader-0.3.2&branch=main&build=3316721197&build_url=https%3A%2F%2Fgithub.com%2Fjaegertracing%2Fjaeger%2Factions%2Fruns%2F3316721197&commit=b05a2d58acda713dab194e2feb750265fab96b64&job=Unit+Tests&pr=&service=github-actions&slug=jaegertracing%2Fjaeger&name=&tag=&flags=&parent=
Content-Type: 'text/plain'
Content-Encoding: 'gzip'
X-Reduced-Redundancy: 'false'
[2022-10-24T22:43:57.613Z] ['error'] There was an error running the uploader: Error uploading to [https://codecov.io:](https://codecov.io/) Error: There was an error fetching the storage URL during POST: 404 - {'detail': …
```
=> Use codecov upload token

CHANGELOG.md, RELEASE.md
Depends on https://github.com/jaegertracing/jaeger-ui/pull/1010
=> Prepare release v1.39.0

.github/workflows/ci-release.yml
Turns out `read-all|write-all` is invalid syntax. Narrowing this further to just deploy perms.
#4017
=> Correct deploy permissions

.github/workflows/ci-release.yml, scripts/package-deploy.sh
Signed-off-by: jkowall <jkowall@kowall.net>
Resolves https://github.com/jaegertracing/jaeger/issues/3960 
This adds in signing to the build process, the following steps must be taken to configure 2 new secrets in the repo by another team member.
1. Generate a GPG key : gpg --gen-key
Answer the prompts accordingly for the email specified (you can set a password as well)
2. pgp --list-keys
Find the GUID for the key you want to use ex: 79FAF16A8C42B3593143DD7C8DE95E7E9BC9CA3C 
3. Get the contents of the key: gpg --export-secret-keys -a 8DE95E7E9BC9CA3C
4. Copy and paste (or pipe to a file and use that). This should be added as a secret called GPG_PRIVATE_KEY
5. The password you created should be added as a secret called GPG_PASSWORD
Please let me know if you have questions. We can either …
=> Add the signing of releases to build process

cmd/collector/app/server/http.go, cmd/collector/app/server/zipkin.go, pkg/httpmetrics/metrics.go, pkg/httpmetrics/metrics_test.go
Partially addresses #2944.
Supersedes and closes #4050.
This only solves the problem in httpmetrics package, we still have other scenarios where malformed strings can leak into Prometheus labels and cause panic, specifically the service-name-based metrics produced by the collector. So I am keeping the original issue open. Hopefully, we can resolve it when we migrate the metrics to OTEL, and allow factories to return errors to be handled gracefully.
=> Catch panic from Prometheus client on invalid label strings

README.md
- Resolves #4074
- Copies (with minor rewordings) the [deprecation notice](https://github.com/jaegertracing/jaeger-kubernetes#this-repository-is-deprecated) in the jaeger-kubernetes repo into the Cloud Native Deployment section of the Jaeger README.
=> Update Cloud Native Deployment section of README

pkg/es/config/config.go, plugin/storage/cassandra/schema/create.sh, plugin/storage/cassandra/schema/docker.sh
Alternative solution, closes #4056
This keeps the create.sh script simpler and not aware of cqlsh.
=> Move Cassandra version check to docker.sh

.github/workflows/ci-release.yml
Release of 1.40.0 is blocked b/c ci is failing with:
```
Invalid workflow file: .github/workflows/ci-release.yml#L12
The workflow is not valid. .github/workflows/ci-release.yml (Line: 12, Col: 3): Unexpected value 'content'
```
Reviewing docs it seems this node should be called `contents`.
=> Fix typo in ci-release.yml

.github/workflows/ci-release.yml
Release CI is currently failing with:
Currently testing this change in my fork
=> Fix ci-release.yml perms

.github/workflows/ci-release.yml
This correctly sets the `contents` permission to `write`. This allowed CI on my fork to move past the "Upload Binaries" step. This fixes the change here: https://github.com/jaegertracing/jaeger/pull/4097
=> Fix Release Perms

scripts/package-deploy.sh
The release process fails because `./deploy/jaeger-$VERSION.asc` file is empty. But we don't need that file.
```
Error: Validation Failed: {"resource":"ReleaseAsset","code":"custom","field":"size","message":"size must be greater than or equal to 1"}
```
=> Fix archive signing step

plugin/storage/cassandra/Dockerfile, scripts/build-upload-docker-images.sh
- [jager-cassandra-schema](https://hub.docker.com/r/jaegertracing/jaeger-cassandra-schema/tags)  container does not have multi arch support.
- This PR adds support to generate multi arch container images
- additionally passed platform arguments to the build script
=> add multi arch support to cassandra-schema container

plugin/storage/cassandra/Dockerfile
- Multi arch cassandra-schema container support is introduced in https://github.com/jaegertracing/jaeger/pull/4122
- for some reason `BUILDPLATFORM` argument is not loaded, hence `linux/amd64` base image taken to all platforms containers, which leads the following error on non `linux/amd64` systems.
```
standard_init_linux.go:228: exec user process caused: exec format error
```
- To fix this issue, I removed the strict `platform` in base image of `Dockerfile`. Now the docker engine decide the base image architecture. 
- Removed `--platform=${BUILDPLATFORM:-linux/amd64}` from the base image.
- Verified this change locally by running the following command under the directory `plugin/storage/cassandra`, result of the execution, I see actual platform images.
``` …
```
=> remove global platform arg in cassandra schema dockerfile

CHANGELOG.md, Makefile, RELEASE.md
- Update changelog.md with changes since v1.40.0.
- Update `changelog` make target to exclude dependabot updates by default.
- Rotate release managers in release.md.
=> Prepare release 1.41.0

cmd/query/main.go, pkg/tenancy/grpc.go, pkg/tenancy/grpc_test.go, plugin/storage/grpc/config/config.go, plugin/storage/grpc/options.go, plugin/storage/grpc/options_test.go
=> Support tenant header propagation in query service and grpc-plugin

pkg/config/tlscfg/cert_watcher.go, pkg/config/tlscfg/cert_watcher_test.go
This PR fixes the certificate hot-reload on Kubernetes.
Resolves #3968
This PR moves the inotify watch from certificate files to monitoring the parent directory instead, as also recommended [here](https://github.com/fsnotify/fsnotify/blob/c6f5cfa163edb0f1bb78be3a77053ee14c48a3ce/backend_inotify.go#L246-L254) by the [fsnotify](https://github.com/fsnotify/fsnotify) library.
Without this change, certificate hot-reload only works if the content of certificate or key files is overwritten. That approach is rarely used for update since it is not atomic and it risks files being read in the middle of the update. Therefore more often the files are replaced by a rename operation, by swapping the old file with a new one. It allows the file to be completely written and closed before exposing it to the …
=> Watch directories for certificate hot-reload

cmd/collector/app/flags/flags.go, cmd/collector/app/flags/flags_test.go, cmd/collector/app/server/http.go, cmd/collector/app/server/http_test.go
- Allows to control collector's HTTP server timeout settings: idle, read, and read-header
- Resolves #4166
- add 3 options to http-server CLI flags
=> Add CLI flags for controlling HTTP server timeouts

cmd/agent/app/reporter/flags_test.go, cmd/flags/flags_test.go, pkg/config/config_test.go, plugin/metrics/factory_config_test.go, plugin/metrics/factory_test.go, plugin/sampling/strategystore/factory_config_test.go, plugin/sampling/strategystore/factory_test.go, plugin/storage/factory_config_test.go, plugin/storage/factory_test.go
This PR replaces `os.Setenv` with `t.Setenv`. Starting from Go 1.17, we can use `t.Setenv` to set environment variable in test. The environment variable is automatically restored to its original value when the test and all its subtests complete. This ensures that each test does not start with leftover environment variables from previous completed tests.
Reference: https://pkg.go.dev/testing#T.Setenv
```go
func TestFoo(t *testing.T) {
// before
os.Setenv(key, "new value")
defer os.Unsetenv(key)
// after
t.Setenv(key, "new value")
}
```
=> test: use `t.Setenv` to set env vars in tests

cmd/agent/app/builder_test.go, cmd/agent/app/configmanager/grpc/manager.go, cmd/agent/app/configmanager/grpc/manager_test.go, cmd/agent/app/configmanager/manager.go, cmd/agent/app/configmanager/metrics.go, cmd/agent/app/configmanager/metrics_test.go, cmd/all-in-one/all_in_one_test.go, cmd/collector/app/collector_test.go, cmd/collector/app/sampling/grpc_handler.go, cmd/collector/app/sampling/grpc_handler_test.go, cmd/collector/app/sampling/strategystore/interface.go, cmd/collector/app/server/test.go, crossdock/services/agent.go, crossdock/services/agent_test.go, model/converter/json/sampling.go, model/converter/json/sampling_test.go, pkg/clientcfg/clientcfghttp/cfgmgr.go, pkg/clientcfg/clientcfghttp/cfgmgr_test.go, pkg/clientcfg/clientcfghttp/handler.go, pkg/clientcfg/clientcfghttp/handler_test.go, plugin/sampling/strategystore/adaptive/processor.go, plugin/sampling/strategystore/adaptive/processor_test.go, plugin/sampling/strategystore/static/constants.go, plugin/sampling/strategystore/static/strategy_store.go, plugin/sampling/strategystore/static/strategy_store_test.go
As the official API is now Protobuf, this change avoids unnecessary conversions to/from Thrift types.
=> Replace Thrift-gen with Proto-gen types for sampling strategies

cmd/tracegen/README.md, cmd/tracegen/docker-compose.yml, cmd/tracegen/main.go, internal/tracegen/config.go, internal/tracegen/worker.go
- Part of migrating away from deprecated Jaeger Go SDK
- switch tracegen from Jaeger Client to OTEL SDK
- a breaking change in some respect:
- default exporter changed to Jaeger HTTP
- different environment variables are used to configure exporters
- debug and firehose flags are no longer set in the trace context, but as span attributes 
- no more metrics from tracegen
=> [tracegen] Switch from Jaeger Client to OTEL SDK

CHANGELOG.md, cmd/tracegen/main.go, examples/hotrod/README.md, examples/hotrod/cmd/root.go, examples/hotrod/docker-compose.yml, internal/jaegerclientenv2otel/envvars.go, internal/jaegerclientenv2otel/envvars_test.go
- https://github.com/jaegertracing/jaeger/discussions/4199
- Map some of old env vars to OTel vars
- Document breaking changes in the CHANGELOG
=> Map old env vars from Jaeger SDK to OTel SDK vars

examples/hotrod/docker-compose.yml, go.mod, go.sum
- Resolves #4209
- I created a temporary patch branch https://github.com/opentracing-contrib/go-grpc/tree/patch-for-opentelemetry-go-issue-3678 as a workaround for OTEL issue https://github.com/open-telemetry/opentelemetry-go/issues/3678
- Only HotROD code is using this library, our production code is using `grpc-ecosystem/grpc-opentracing` (which seems to be an identical copy, I am not sure why there are two libs, but it came in handy right now)
=> Use patched version of github.com/opentracing-contrib/go-grpc in HotROD

README.md, plugin/storage/cassandra/schema/v004.cql.tmpl
- Resolves #4198  
Following changes done to v004.cql.tmpl
- Removing trailing comma from last column definition.
- Changing `//` to `--` as preamble for comments.
- `list<frozen<keyvalue>>,`->`list<frozen<${keyspace}.keyvalue>>`
- Adding frozen keyword to UDT. 
Above syntax changes are accepted by YCQL and Cassandra both.
=> Jaeger YugabyteDB(YCQL) support

examples/hotrod/cmd/customer.go, examples/hotrod/cmd/driver.go, examples/hotrod/cmd/frontend.go, examples/hotrod/cmd/root.go, examples/hotrod/cmd/route.go, examples/hotrod/pkg/log/factory.go, examples/hotrod/pkg/log/logger.go, examples/hotrod/pkg/log/spanlogger.go, examples/hotrod/pkg/tracing/init.go, examples/hotrod/pkg/tracing/mux.go, examples/hotrod/services/customer/client.go, examples/hotrod/services/customer/server.go, examples/hotrod/services/driver/server.go, examples/hotrod/services/frontend/best_eta.go, examples/hotrod/services/frontend/server.go, examples/hotrod/services/frontend/web_assets/index.html, examples/hotrod/services/route/server.go
- The baggage propagation was broken in HotROD after #4187
- This restores the baggage support by providing a few integration points with OTEL
- [`index.html`] The webapp used to send baggage via `jaeger-baggage` header, this is now changed to W3C `baggage` header
- [`mux.go`] The Jaeger SDK was able to accept `jaeger-baggage` header even for requests without am active trace. OTEL Bridge does not support that, so we use OTEL's Baggage propagator to manually extract the baggage into Context, and once the Bridge creates a Span, we copy OTEL baggage from Context into the Span.
- All other changes are cosmetic / logging related
=> Restore baggage support in HotROD 🚗

cmd/query/app/mocks/Watcher.go, pkg/config/tlscfg/cert_watcher.go, pkg/config/tlscfg/cert_watcher_test.go, pkg/fswatcher/fs_watcher.go, pkg/fswatcher/fs_watcher_test.go
Signed-off-by: haanhvu <haanh6594@gmail.com>
First step for #3924 as discussed [here](https://github.com/jaegertracing/jaeger/issues/3924#issuecomment-1424754016)
=> Migrate the use of fsnotify to fswatcher in cert_watcher.go

examples/hotrod/kubernetes/kustomization.yaml
Signed-off-by: Jim Van Fleet <jim@jimvanfleet.com>
- Resolves #4230 
- Updating the document to include the updated all-in-one path
- Adding one additional comment for those not briefed on kustomize
=> Updating all-in-one path

examples/hotrod/pkg/tracing/init.go
hotrod currently forces all connections to insecure in https://github.com/jaegertracing/jaeger/blob/fedeb4cab75399e4672b77efe6a067a7bd148ddf/examples/hotrod/pkg/tracing/init.go#L85
preventing SSL connections from succeeding.  For example:
```
$ OTEL_EXPORTER_OTLP_ENDPOINT=https://hotrod.apm.us-east4.gcp.elastic-cloud.com:443 ./hotrod all -x otlp
2023/02/10 13:00:04 traces export: failed to send to http://hotrod.apm.us-east4.gcp.elastic-cloud.com:443/v1/traces: 400 Bad Request
```
- use secure connections when env var `OTEL_EXPORTER_OTLP_ENDPOINT` uses `https` scheme or `OTEL_EXPORTER_OTLP_INSECURE=false`
=> Support secure OTLP exporter config for hotrod

.github/actions/setup-node.js/action.yml, .github/workflows/ci-all-in-one-build.yml, .github/workflows/ci-build-binaries.yml, .github/workflows/ci-docker-build.yml
Builds started failing, probably because GH moved containers to Node 18 and Jaeger-UI is not ready for it.
https://github.com/jaegertracing/jaeger/actions/runs/4217171446/jobs/7320758782
This change adds a new internal action that reads the Node version from jaeger-ui/.npmrc instead of hardcoding or not specifying it at all (as was the case in build-binaries workflow).
=> Add internal action to setup Node.js version appropriate for Jaeger UI

cmd/all-in-one/all_in_one_test.go, cmd/query/app/additional_headers_test.go, cmd/query/app/apiv3/grpc_gateway_test.go, cmd/query/app/http_handler_test.go, cmd/query/app/server_test.go, cmd/query/app/token_propagation_test.go, examples/hotrod/pkg/tracing/http.go, pkg/bearertoken/http_test.go, pkg/recoveryhandler/zap_test.go, pkg/tenancy/http_test.go
- 
-  Use http constants to replace numbers
=> [chore]: Use http.MethodGet instead of "GET"

Makefile, scripts/rebuild-ui.sh
Resolves #4163
- Attempt to download UI assets from GitHub release, fall back to regular manual build
=> #4163 | Speed-up CI by using published UI artifacts 

.github/workflows/ci-docker-build.yml, scripts/build-upload-docker-images.sh
- Resolves https://github.com/jaegertracing/jaeger/issues/4172
- scripts/build-upload-docker-images.sh: Set platforms variable dynamically based on ~~env `PLATFORMS`~~ the first argument
- .github/workflows/ci-docker-build.yml: Add a new job for PR only and pass `pr-only` as the first argument
=> Refactor: build linux artifacts only for PR

CHANGELOG.md, RELEASE.md, cmd/all-in-one/all_in_one_test.go
=> Prepare release v1.43.0

cmd/query/app/fixture/favicon.ico, cmd/query/app/flags.go, cmd/query/app/flags_test.go, cmd/query/app/static_handler.go, cmd/query/app/static_handler_test.go
Only merge after UI upgrade to 1.28
=> Log access to static assets; remove favicon test

CHANGELOG.md
Fixes a minor typo in `CHANGELOG.md`
=> Fix typo in `CHANGELOG.md`

CHANGELOG.md, plugin/storage/cassandra/schema/README.md
- Resolves #4284 
- Map versions of Cassandra schema files to Jaeger releases.
- Update `CHANGELOG.md` for Jaeger v1.26.0 to include a note on migration.
=> Document evolution of Cassandra schema files

plugin/storage/cassandra/spanstore/dbmodel/converter.go, plugin/storage/cassandra/spanstore/dbmodel/converter_test.go
- Resolves #705
- Resolves #704 
- Instead of creating a separate column in the table, [we encode warnings as tags, with a magic string prefix](https://github.com/jaegertracing/jaeger/pull/4217#discussion_r1097637013) so that they can be parsed and converted back to warnings during reads.
=> Store span warnings as tags in Cassandra

cmd/ingester/app/processor/span_processor_test.go, plugin/storage/es/spanstore/reader_test.go
- Should fix #4327
- Test on tip were failing due to mismatch of context types passed to mocks.
=> [test] Use correct Context instance with mocks

Makefile
`go` command was hardcoded, making it difficult to run with `gotip`. Now can do `make test GO=gotip`
=> Add GO param to Makefile

.github/workflows/ci-unit-tests-go-tip.yml, .github/workflows/ci-unit-tests.yml, Makefile
golangci-lint doesn't seem to like running against Go tip: https://github.com/jaegertracing/jaeger/actions/runs/4517523436/jobs/7956780871#step:7:5416
The errors are actually invalid, since `typecheck` is not a linter, it flags compile errors, but unit tests run fine.
=> Skip linting on Go tip

cmd/collector/main.go
- Fixes a typo in `collector/main.go`
=> Fix a typo in `collector/main.go`

cmd/collector/app/server/http_test.go
- Resolves #4340 
- Server in test case was not closed
=> Race condition detected in tests #4340

cmd/collector/app/collector.go, cmd/collector/app/flags/flags.go, cmd/collector/app/flags/flags_test.go, cmd/collector/app/server/zipkin.go
- Resolves #4365 
- Add cli flag for change jaeger-collector's Zipkin HTTP server KeepAlive configuration.
=> Add Keep-Alive flag for Zipkin HTTP server

cmd/collector/app/options.go, cmd/collector/app/options_test.go, cmd/collector/app/span_processor.go, cmd/collector/app/span_processor_test.go
Resolves #4375
Expose drop span hook as an option when creating SpanProcessor in collector so that users have the flexibility to get more insights on dropped spans in addition to the dropped count.
=> Expose drop span hook as an option in Collector SpanProcessor

pkg/es/config/config.go, plugin/storage/es/factory.go, plugin/storage/es/factory_test.go
The `ClientBuilder` interface was unnecessary, use Configuration struct directly
=> Simplify ES config and factory

examples/hotrod/README.md, examples/hotrod/pkg/tracing/init.go
- Resolves https://github.com/jaegertracing/jaeger/discussions/4356
- The HotRod example emits spans on jaeger-collector's HTTP endpoint.
- This exposes the port being listened to for spans over the HTTP endpoint to fix an error in the HotRod example.
- A minor typo is also fixed.
=> Add HTTP post port mapping to docker command

.golangci.yml, cmd/agent/app/reporter/client_metrics_test.go, cmd/agent/app/testutils/in_memory_reporter.go, cmd/collector/app/zipkin/zipkindeser/json.go, cmd/env/command.go, cmd/es-index-cleaner/app/index_filter.go, cmd/ingester/app/consumer/offset/concurrent_list_test.go, cmd/ingester/app/flags.go, cmd/query/app/query_parser.go, cmd/query/app/query_parser_test.go, internal/metrics/prometheus/factory_test.go, model/span.go, pkg/bearertoken/http.go, pkg/config/tlscfg/certpool_windows.go, pkg/config/tlscfg/flags.go, pkg/metrics/metrics.go, pkg/queue/bounded_queue_test.go, plugin/metrics/prometheus/options.go, plugin/sampling/strategystore/adaptive/weightvectorcache.go, plugin/storage/badger/spanstore/reader.go, plugin/storage/cassandra/options.go, plugin/storage/es/options.go, plugin/storage/es/spanstore/dbmodel/from_domain.go, plugin/storage/es/spanstore/dbmodel/to_domain.go, plugin/storage/es/spanstore/reader.go, plugin/storage/es/spanstore/reader_test.go, plugin/storage/integration/integration.go, plugin/storage/kafka/options.go
- enable gocritic linter
- disabled  dupArg, exitAfterDefer and appendAssign rules of gocritic until they are addressed. 
Signed-off-by: Matthieu MOREL <matthieu.morel35@gmail.com>
=> enable gocritic linter

CHANGELOG.md, RELEASE.md
Updates changelog, release.md and jaeger-ui submodule for v1.45.0.
=> Prepare Release 1.45.0

docker-compose/monitor/README.md
The correct command is "docker compose up" and not "docker-compose up"
Reference: https://docs.docker.com/engine/reference/commandline/compose/
=> Update README.md - fixing docker compose command

cmd/agent/app/agent_test.go, cmd/agent/app/servers/thriftudp/socket_buffer.go
Resolves #4448
Jaeger agent gets stuck when closing with SocketBufferSize set. This is because `Close()` of `net.UDPConn` will be blocked if `Fd()` is used to get the file descriptor.
Use `RawConn.Control` instead to get fd to set the socket buffer.
Same issue was discussed here: https://github.com/golang/go/issues/29277
The fix refers to here: https://github.com/brucespang/go-tcpinfo/pull/3
=> [Jaeger-Agent] Use RawConn.Control to get fd instead of Fd()

plugin/storage/es/spanstore/reader.go, plugin/storage/es/spanstore/reader_test.go
Closes #4330 
- Remove TerminateAfter from Elasticsearch/Opensearch query resulting in incomplete span count/list.
=> BUG: Remove TerminateAfter from Elasticsearch/Opensearch query resulting in incomplete span count/list

cmd/collector/app/span_processor_test.go
* Resolves #4450
* Alternative to #4451
=> Fix flaky test - TestSpanProcessorWithOnDroppedSpanOption

CHANGELOG.md, cmd/collector/app/flags/flags.go
This simplifies compatibility with OTEL/OTLP by not requiring to set the option to enable OTLP receiver. The option is still supported and allows OTLP receiver to be disabled when needed.
=> Make OTLP receiver enabled by default

examples/hotrod/pkg/tracing/init.go
In HotROD appbatching is not required it should export traces asap so BatchTimeOut value can be lowered from 5sec solves the issue
Resolves jaegertracing/jaeger-ui#1180
=> [hotrod] Reduce span exporter's batch timeout to let the spans be exported sooner

pkg/kafka/auth/config.go, pkg/kafka/auth/kerberos.go, pkg/kafka/auth/options.go
- Solves #2744 
- Added a variable in KerborosConfig struct and configured it 
- Added flags and the configuration for the same
=> Add *.kerberos.disable-fast-negotiation option to Kafka consumer

cmd/all-in-one/main.go, cmd/query/app/grpc_handler.go, cmd/query/app/grpc_handler_test.go, cmd/query/app/handler_options.go, cmd/query/app/http_handler.go, cmd/query/app/http_handler_test.go, cmd/query/app/server.go, cmd/query/app/server_test.go, cmd/query/app/token_propagation_test.go, cmd/query/main.go, pkg/jtracer/jtracer.go, pkg/jtracer/jtracer_test.go
Part of #3381 
- This refactors the code by introducing a new wrapper object `JTracer` to wrap that interface
=> Pass a wrapper instead of `opentracing.Tracer` to ease migration to OTEL in the future [part 1]

cmd/tracegen/main.go, internal/tracegen/config.go, internal/tracegen/worker.go
Add new configuration options:
- `-services`: to generate traces on behalf of many services, by instantiating different tracers
- `-spans`: to generate more than one child span
- `-attrs`: to generate N number of attributes on each child span
- `-attr-values`: to control how many distinct values each attribute can have
Fix weird span durations when using `-pause 0s`.
Test:
```shell
go run ./cmd/tracegen -traces 2 -services 2 -spans 3 -attrs 3
```
=> [tracegen] Add options to generate more spans and attributes

cmd/collector/app/server/http_test.go
- Resolves #4497
- Do not use `zaptest.NewLogger(t)` because it causes race condition shown in the ticket when the server goroutine tries to log something that is being forwarded to `testing.T` while the test is being shutdown due to panic.
- I was not able to get to the root cause why this happens, since the test is properly shutting down the server. This may indicate an issue in testing itself in how it handles panic.
=> [test] Avoid logging to testing.T from server goroutine

scripts/rebuild-ui.sh
The previous behavior resulted in the prebuild upstream package being downloaded, even if the local tree has any changes, whether they are commited or not. This broke our internal build that has some patches applied. See:
* https://github.com/jaegertracing/jaeger/pull/4251#issuecomment-1608393236
Let's use a more strict approach and only use the prebuild package if the tag is exact and does not contain any extra changes.
=> Rebuild jaeger-ui if the tree does not match any tag exactly

examples/hotrod/pkg/tracing/init.go, examples/hotrod/services/driver/redis.go, examples/hotrod/services/driver/server.go
- This PR refactors gRPC interceptors by downgrading opentracing APIs
Related to https://github.com/jaegertracing/jaeger/issues/3380
Part of https://github.com/jaegertracing/jaeger/issues/3381
- Upgrades gRPC intrumentation to OTEL
=> [hotROD] Replace gRPC instrumentation with OTEL

examples/hotrod/services/customer/database.go, examples/hotrod/services/customer/server.go
Related to https://github.com/jaegertracing/jaeger/issues/3380
Part of https://github.com/jaegertracing/jaeger/issues/3381
- This PR adds OTEL instrumentation to customer svc
=> [hotROD] Add OTEL instrumentation to customer svc

cmd/tracegen/main.go, go.mod, go.sum
- Unlike Jaeger Go SDK, OTEL OTLP exporter does not provide good observability into how much trace data is being produced / exported / dropped
- Connect OTEL logger to Zap logger and allow Debug() level, which is used by OTLP exporter to log stats like this:
```
2023-07-06T13:05:07.688-0400	LEVEL(-8)	global/internal_logging.go:63	exporting spans	{"count": 2, "total_dropped": 0}
```
=> [tracegen] Enable OTEL debug logging

examples/hotrod/pkg/tracing/baggage.go, examples/hotrod/pkg/tracing/mutex.go, examples/hotrod/services/customer/database.go, examples/hotrod/services/route/stats.go
- Part of #3380
- Move explicit baggage access into a util func that checks both OT and OTEL baggage. Later the OT part can be retired completely.
- Update usage sites to use the new function instead of OT `Span.BaggageItem`
A couple of less related changes in `tracing/mutex.go`:
- Use OTEL Span API instead of OT
- Replace direct-to-span logging with the regular logger that logs both to stdout and to the span
=> [hotrod] Handle both OT and OTEL baggage

cmd/tracegen/main.go
[tracegen] Enable BlockOnQueueFull in OTel SDK to make spans not dropped in spikes
Call `WithBlocking()` from OTel SDK to enable `BlockOnQueueFull=true` to make spans not dropped when the queue is full.
Tested locally:
- Before the change: Spans in tracegen were dropped when generated to jaeger-collector, even with just 1m duration and 1 worker.
- With the change: Spans in tracegen were not dropped even with 1h duration and 10 workers.
=> [tracegen] Enable BlockOnQueueFull in OTel SDK to avoid dropped spans

cmd/ingester/app/consumer/consumer.go, cmd/ingester/app/consumer/consumer_test.go, pkg/kafka/consumer/config.go
Resolves # [4576](https://github.com/jaegertracing/jaeger/issues/4576)
Once we call [start](https://github.com/jaegertracing/jaeger/blob/main/cmd/ingester/app/consumer/consumer.go#L76) and call [close](https://github.com/jaegertracing/jaeger/blob/main/cmd/ingester/app/consumer/consumer.go#L76) again with fxtest module, there is a chance that the application will close the goroutine before the l[ogline](https://github.com/jaegertracing/jaeger/blob/main/cmd/ingester/app/consumer/consumer.go#L79) is executed causing **panic Log in routine after .. has completed**. 
Fix:
Add a wait group that will wait for the goroutine to finish before closing the channel.
=> [kafka-consumer] Use wait group to ensure goroutine is finished before returning from Close

examples/hotrod/pkg/tracing/mux.go, examples/hotrod/services/frontend/web_assets/index.html
Since the HotROD UI does not start traces, it can only search for a trace corresponding to a particular request by some span tags. This makes the experience of opening a trace a big clunky as we first see the search page with one trace, and then have to click on the trace again.
Related to https://github.com/jaegertracing/jaeger/issues/3380
Change the HTTP instrumentation to always generate a `traceresponse` header per the [current W3C draft](https://github.com/w3c/trace-context/blob/main/spec/21-http_response_header_format.md). Then parse the trace ID from that header in the UI and generate a hyperlink to open the trace view directly, bypassing the search.
=> [hotrod] Return trace ID via traceresponse header

pkg/jtracer/jtracer.go, plugin/metrics/prometheus/factory.go, plugin/metrics/prometheus/metricsstore/reader.go, plugin/metrics/prometheus/metricsstore/reader_test.go
* This PR adds OTEL Provider to metrics reader component
- Replaces OT tracer with OTEL tracer to support jtracer pkg
=> feat: Add `OTEL tracer` to metricsstore reader component

cmd/all-in-one/main.go, cmd/query/main.go, plugin/storage/es/factory.go, plugin/storage/es/spanstore/reader.go, plugin/storage/es/spanstore/reader_test.go, plugin/storage/integration/elasticsearch_test.go
* This PR adds OTEL Provider to es-spanstore component
- Replaces OT tracer with OTEL tracer to support jtracer pkg
=> Replace es-spanstore tracing instrumentation with OpenTelemetry

plugin/storage/es/spanstore/reader_test.go, plugin/storage/es/spanstore/service_operation_test.go, plugin/storage/integration/elasticsearch_test.go
- Prevent potential future linter errors where errors are ignored
- Handle error from Close
=> Minor clean-up after PR 4596

plugin/storage/cassandra/factory.go, plugin/storage/cassandra/savetracetest/main.go, plugin/storage/cassandra/spanstore/reader.go, plugin/storage/cassandra/spanstore/reader_test.go
* This PR adds OTEL Provider to cassandra spanstore component
- Replaces OT tracer with OTEL tracer to support jtracer pkg
=> Replace cassandra-spanstore tracing instrumentation with`OTEL`

cmd/query/app/static_handler_test.go, pkg/config/tlscfg/cert_watcher_test.go, pkg/fswatcher/fswatcher_test.go, plugin/storage/badger/spanstore/cache_test.go, plugin/storage/badger/spanstore/read_write_test.go
This pull request replaces `os.MkdirTemp` with `t.TempDir`. We can use the `t.TempDir` function from the `testing` package to create temporary directory. The directory created by `t.TempDir` is automatically removed when the test and all its subtests complete. 
Reference: https://pkg.go.dev/testing#T.TempDir
```go
func TestFoo(t *testing.T) {
// before
dir, err := os.MkdirTemp("", "")
require.NoError(t, err)
defer os.RemoveAll(dir)
// now
dir := t.TempDir()
}
```
=> [tests]: Use `t.TempDir` to create temporary test directory

.github/dependabot.yml
- group otel contrib instrumentation dependabot updates
- add pip package-ecosystem on docker-compose/monitor
=> dependabot: group otel contrib instrumentation

plugin/storage/grpc/README.md, plugin/storage/grpc/config/config.go, plugin/storage/grpc/factory.go, plugin/storage/grpc/factory_test.go
* This PR adds `otelgrpc` plugin to storage
- Replaces `otgrpc` plugin storage with otel grpc interceptors
=> Replace OpenTracing instrumentation with OpenTelemetry in grpc storage plugin 

cmd/query/app/handler_options.go, model/adjuster/span_id_deduper_test.go
* This PR adds `otel trace` spans type to span model
- Replace OT const with `otel trace` spans const i.e. `ext.SpanKind..` with `trace.SpanKind..`
=> [test] Replace OT const with OTEL

model/converter/thrift/zipkin/to_domain.go, model/converter/thrift/zipkin/to_domain_test.go
* This PR adds `otel trace` spans const type to domain model
- Replace OT const with `otel trace` spans const i.e. `ext.SpanKind..` with `trace.SpanKind..`
=> [zipkin] Replace OT constants with OTEL

internal/tracegen/config.go, internal/tracegen/worker.go
- Add flag to control cardinality of attribute keys
- Use prime numbers for  default number of attributes and keys
=> [tracegen] Allow to control cardinality of attribute keys

.github/dependabot.yml
This is not a critical example file, and its dependencies do not change often, so to minimize PR churn upgrade them all together
=> [/docker-compose/monitor] Group all dependencies

examples/memstore-plugin/main.go
* This PR adds `otel` traces and removes deprecated `jaeger-client-go` api
- Replace OT tracer with OTEL
=> [memstore-plugin]Replace ot with otel sdk

Makefile, scripts/check-semconv-version.sh, scripts/update-semconv-version.sh
Resolves #4646 
- Added scripts/check-semconv-version.sh to search the code for all usages of "go.opentelemetry.io/otel/semconv/v1.xx.x" and fail if they are not identical, with an error message and the source files along with their respective versions.
- Added scripts/update-semconv-version.sh to fetch the latest version of semconv with curl and replace all references of 
"go.opentelemetry.io/otel/semconv/v1.xx.x" with the latest version.
I have tested the changes locally by modifying import statements
=> Add shell script to ensure consistent version of OTEL semconv

cmd/collector/app/handler/otlp_receiver.go
- Resolves #4657
- use NoOp tracer provider in the OTLP receiver configuration
- ran the UI, reloaded page many times, this endpoint no longer shows up
=> [fix] Disable tracing of OTLP Receiver

CHANGELOG.md, RELEASE.md
Blocked by https://github.com/jaegertracing/jaeger-ui/pull/1676
=> Prepare release 1.48.0

scripts/build-all-in-one-image.sh
- Resolves https://github.com/jaegertracing/jaeger/issues/4664
- To make building CI for PRs faster, we can skip building for other architectures aside from linux/amd64. This PR makes the change to stop building CI for other architectures aside from linux/amd64
- 
=> Build architecture for linux/amd64 only for pull requests

scripts/build-all-in-one-image.sh, scripts/build-upload-docker-images.sh
- Resolves https://github.com/jaegertracing/jaeger/issues/4663
- Update image build/upload scripts to create base image only when `mode=pr-only`
- Works from my local by running `BRANCH=refactor/avoid-build-debug-img-in-pr ./scripts/build-all-in-one-image.sh pr-only`
=> [ci] Avoid building debug image for PRs

cmd/all-in-one/main.go, cmd/query/app/flags.go, cmd/query/main.go, examples/memstore-plugin/main.go, pkg/jtracer/jtracer.go
Resolves #4680
- Add an opt-in option `--query.enable-tracing` to enable tracing for the jaeger-query component.
- The jaeger all-in-one component does not expose this flag since traces are emitted to port 4317 by default, which all-in-one listens on.
```
$ SPAN_STORAGE_TYPE=memory go run -tags ui ./cmd/query/main.go --query.enable-tracing
...
{"level":"info","ts":1692363754.9049716,"caller":"grpc/clientconn.go:1301","msg":"[core][Channel #1 SubChannel #2] Subchannel Connectivity change to CONNECTING","system":"grpc","grpc_log":true}
{"level":"info","ts":1692363754.9050152,"caller":"grpc/clientconn.go:1414","msg":"[core][Channel #1 SubChannel #2] Subchannel picks a new address \"localhost:4317\" to connect","system":"grpc","grpc_log":true} …
```
=> Add the enable tracing opt-in flag

.github/workflows/ci-all-in-one-build.yml
- There was a bug introduced in #4496 where `pr-only` mode was used unconditionally, instead of for PRs-only.
- fork the build step into on-main and no-on-main
=> [fix] Use pr-only mode for PRs only

go.mod, go.sum
- Resolves #4689
- Related to #4591
- Pin sarama to the current version 1.33.0 to prevent upgrades due to other dependencies like zipkin-go
=> Pin sarama to current version v1.33.0

.github/workflows/ci-all-in-one-build.yml, .github/workflows/ci-build-binaries.yml, .github/workflows/ci-cassandra.yml, .github/workflows/ci-crossdock.yml, .github/workflows/ci-docker-build.yml, .github/workflows/ci-elasticsearch.yml, .github/workflows/ci-grpc-badger.yml, .github/workflows/ci-hotrod.yml, .github/workflows/ci-kafka.yml, .github/workflows/ci-opensearch.yml, .github/workflows/ci-protogen-tests.yml, .github/workflows/ci-unit-tests.yml, .github/workflows/codeql.yml, .github/workflows/fossa.yml
- fixes #4695 
- Whenever we push commits to a PR, workflows are triggered for that commit. After that, if we push additional commits to this PR, workflows in Github Actions run on both commits.
- We need to cancel the previous run and run only on the most recent pushed commit. This would help save some GitHub Action Minutes and unexpected workflow failures on subsequent commits.
- Was tested in jaeger-ui repo.
=> [CI]: Add Concurrency Grouping to GitHub Workflows

Makefile, docker-compose/monitor/README.md, scripts/draft-release.py, scripts/import-order-cleanup.py, scripts/import-order-cleanup.sh, scripts/release-notes.py, scripts/updateLicense.py, scripts/updateLicenses.sh, scripts/utils/ids-to-base64.py
- Resolves #4673
- Adds python 3 shebang to each python script.
- The same can be done in a follow up PR to jaeger-ui if this PR is accepted.
- Checked all python scripts within the jaeger project begin with a python3 shebang:
```shell
$ find . -name "*.py" | grep -v site-packages | grep -v venv | grep -v jaeger-ui | xargs head -1
```
<details>
```
==> ./scripts/utils/ids-to-base64.py <==
#!/usr/bin/env python3
==> ./scripts/draft-release.py <==
#!/usr/bin/env python3
==> ./scripts/release-notes.py <==
#!/usr/bin/env python3
==> ./scripts/import-order-cleanup.py <==
#!/usr/bin/env python3
==> ./scripts/updateLicense.py <==
#!/usr/bin/env python3
==> ./docker-compose/monitor/otlp_exporter_example.py <==
#!/usr/bin/env python3
```
</details>
- Checked all python scripts within the jaeger …
=> Make all python scripts python3 compatible

CHANGELOG.md, cmd/tracegen/main.go, internal/tracegen/config.go
- Upgrade of OTEL is failing in #4705 because `jaeger` exporter is deprecated
- Remove `jaeger` as supported trace exporter
=> Stop supporting -trace-exporter=jaeger

cmd/collector/app/metrics.go, cmd/collector/app/metrics_test.go, cmd/collector/app/root_span_handler.go, cmd/collector/app/root_span_handler_test.go, cmd/collector/app/sampling/strategystore/interface.go, cmd/collector/app/span_processor_test.go, model/span.go, model/span_test.go, plugin/sampling/strategystore/adaptive/aggregator.go, plugin/sampling/strategystore/adaptive/aggregator_test.go
* This PR removes `jaeger-client` pkg constant and replaces it with const variable
=> [chore] Stop using constants from jaeger-client-go

CHANGELOG.md, examples/hotrod/cmd/flags.go, examples/hotrod/cmd/root.go, examples/hotrod/pkg/tracing/init.go, examples/hotrod/services/driver/server.go, go.mod, go.sum
- `otel/exporters/jaeger` is deprecated
- Removes the option to export jaeger format from hotrod
-
=> [hotrod] Stop supporting "jaeger" exporter

CHANGELOG.md, examples/hotrod/services/frontend/server.go, examples/hotrod/services/route/server.go
- Previously, for unexplained reasons, the metrics endpoints (/metrics and /debug/expvar) in HotROD were served from the route service. That means 8083 port was also required to be exposed.
- Move metrics handlers to the frontend service
- Return error from root service
```
$ curl http://0.0.0.0:8083/metrics
endpoint moved to the frontend service
```
=> [hotrod] Move metrics endpoints from route to frontend service

.github/workflows/ci-all-in-one-build.yml, .github/workflows/ci-build-binaries.yml, .github/workflows/ci-cassandra.yml, .github/workflows/ci-crossdock.yml, .github/workflows/ci-docker-build.yml, .github/workflows/ci-elasticsearch.yml, .github/workflows/ci-grpc-badger.yml, .github/workflows/ci-hotrod.yml, .github/workflows/ci-kafka.yml, .github/workflows/ci-opensearch.yml, .github/workflows/ci-protogen-tests.yml, .github/workflows/ci-release.yml, .github/workflows/ci-unit-tests.yml, .github/workflows/fossa.yml, docker/Makefile
- Move to next Go version per maintenance policy (see #4653)
Ran the script 
```shell
$ ./scripts/check-go-version.sh -u
go.mod                                             Go version: 1.20
docker/Makefile                                    Go version: 1.20 *** => 1.21 ***
.github/workflows/fossa.yml                        Go version: 1.20 *** => 1.21 ***
.github/workflows/ci-release.yml                   Go version: 1.20 *** => 1.21 ***
.github/workflows/ci-unit-tests.yml                Go version: 1.20 *** => 1.21 ***
.github/workflows/ci-docker-build.yml              Go version: 1.20 *** => 1.21 ***
.github/workflows/ci-build-binaries.yml            Go version: 1.20 *** => 1.21 ***
.github/workflows/ci-crossdock.yml                 Go version: 1.20 *** => 1.21 *** …
```
=> Move build to Go 1.21

Makefile
- PR #4723 added logging, but tracegen was not built with build-info embedded
-  add build info to tracegen and anonymizer binaries
```
$ make build-tracegen
CGO_ENABLED=0 installsuffix=cgo go build -trimpath -ldflags "-X github.com/jaegertracing/jaeger/pkg/version.commitSHA=f8c1523f64159bf05eedf6aa6ffb09c9402a9932 -X github.com/jaegertracing/jaeger/pkg/version.latestVersion=v1.48.0 -X github.com/jaegertracing/jaeger/pkg/version.date=2023-09-05T00:05:46Z" -o ./cmd/tracegen/tracegen-darwin-amd64 ./cmd/tracegen/main.go
$ ./cmd/tracegen/tracegen-darwin-amd64
2023-09-05T21:55:58.923-0400	INFO	./main.go:56	application version: git-commit=f8c1523f64159bf05eedf6aa6ffb09c9402a9932, git-version=v1.48.0, build-date=2023-09-05T00:05:46Z
```
=> [tracegen] Add build info during compilation

CHANGELOG.md, cmd/all-in-one/main.go, cmd/collector/main.go, plugin/sampling/strategystore/factory_config.go, plugin/sampling/strategystore/factory_config_test.go
These were deprecated in 2021 (#3302)
=> [breaking] Remove support for SAMPLING_TYPE env var and 'static' value

cmd/agent/app/builder_test.go, plugin/metrics/prometheus/metricsstore/reader_test.go
- Resolves #4732
- Introduces an atomic boolean outside of the HTTP test handler and only set to `true` if the expected request is received.
- This should prevent cases where unrelated processes are hitting the same test URL.
- Ran `make test` to pass.
- Ran `go test -tags=memory_storage_integration -count 10 ./...` and confirmed `metricsstore` tests are passing.
- Note that a number of unrelated tests were failing with the `-count 10` flag set, **not as a result of the changes from this PR**, namely:
```
--- FAIL: TestFactory (0.00s)
--- FAIL: TestFactory/#00 (0.00s)
panic: Reuse of exported var name: test_1694287567920905000_counter_x
[recovered]
panic: Reuse of exported var name: test_1694287567920905000_counter_x
```
and
```
--- FAIL: TestPublishOpts (0.00s)
builder_test.go:308:
Error …
```
=> Attempt to fix flaky TestGetRoundTripper* tests

examples/hotrod/cmd/flags.go, examples/hotrod/cmd/root.go, internal/metrics/metricsbuilder/builder.go
- Step 1 of #4722
- add deprecation notice for `expvar` as metrics backend
- change HotROD default backend to `prometheus`
- run binaries locally to observe the messages
```
$ go run ./cmd/all-in-one help
--metrics-backend string                                    Defines which metrics backend to use for metrics reporting: prometheus, none, or expvar (deprecated, will be removed after 2024-01-01 or in release v1.53.0, whichever is later)  (default "prometheus")
$ go run ./cmd/all-in-one --metrics-backend=expvar
2023/09/09 19:09:01 using expvar as metrics backend (deprecated, will be removed after 2024-01-01 or in release v1.53.0, whichever is later)
```
=> Deprecate expvar metrics backend

plugin/metrics/prometheus/options.go
- Part 1 of #4736
- Add deprecation notice to CLI flag
- Add log message when using span metrics processor notation
```
$ go run ./cmd/all-in-one help
--prometheus.query.support-spanmetrics-connector            (deprecated, will be removed after 2024-01-01 or in release v1.53.0, whichever is later)  Controls whether the metrics queries should match the OpenTelemetry Collector's spanmetrics connector naming (when true) or spanmetrics processor naming (when false). (default true)
$ PROMETHEUS_QUERY_SUPPORT_SPANMETRICS_CONNECTOR=false METRICS_STORAGE_TYPE=prometheus go run ./cmd/all-in-one
2023/09/09 20:29:19 using Spanmetrics Processor's metrics naming conventions (deprecated, will be removed after 2024-01-01 or in release v1.53.0, whichever is later)
```
cc @albertteoh
=> [SPM] Deprecate support for Spanmetrics Processor naming convention

cmd/agent/main.go
=> Add deprecation warning to jaeger-agent

plugin/storage/es/factory.go, plugin/storage/es/factory_test.go
- resolves #4743 
- Resolved an issue where the Elasticsearch client was not being closed correctly. 
- manually on local env
=> [fix] Close Elasticsearch client properly

plugin/storage/cassandra/schema/create.sh, plugin/storage/cassandra/schema/v004.cql.tmpl
Resolves #4561
- Include compaction window settings based on the 'COMPACTION_WINDOW' environment variable
- The value of the compaction window is either provided by the user or by calculating `ceil(ttl / 30)`
Locally tested change by generating the CSQL code from the template.
Can reproduce by running:
```bash
$ MODE=test ./create.sh v004.cql.tmpl
$ TRACE_TTL=2592000 MODE=test ./create.sh v004.cql.tmpl
$ COMPACTION_WINDOW=12h MODE=test ./create.sh v004.cql.tmpl
```
=> Add Cassandra schema compaction window configuration

plugin/storage/integration/badgerstore_test.go, plugin/storage/integration/cassandra_test.go, plugin/storage/integration/elasticsearch_test.go, plugin/storage/integration/integration.go
- Turns out we don't run most tests against Cassandra
- Enable all tests
- CI
=> Run all integration tests against Cassandra

cmd/ingester/app/consumer/consumer.go, cmd/ingester/app/consumer/consumer_metrics.go, cmd/ingester/app/consumer/consumer_test.go
Resolves #4777 
Add tag with topic name to Kafka consumer metrics.
Unit tests
Signed-off-by: Alex Bublichenko <alexbub@uber.com>
=> [kafka-consumer] Consumer metrics should have a tag with topic name

CONTRIBUTING.md, README.md, docker-compose/monitor/grafana.ini, examples/hotrod/README.md
=> Remove unneeded references to OpenTracing

plugin/storage/cassandra/factory.go, plugin/storage/integration/cassandra_test.go, plugin/storage/integration/integration.go, scripts/cassandra-integration-test.sh
Resolves #4782
-  Recently a [PR](https://github.com/jaegertracing/jaeger/pull/4773) was raised to run all integration tests against Cassandra while checking it's [CI for cassandra](https://github.com/jaegertracing/jaeger/actions/runs/6287799686/job/17072619668) I found that the some test where failing but CI passed. 
-  Fixed the script so that if the test fail we get exit code as non-zero.
-  Fixed  `TestCassandraStorage/GetLargeSpans` test which was failing due to older traces not getting cleanup from db.
- run the cassandra script to test it.
=> [tests] Fix failing e2e test  for Cassandra storage

plugin/storage/integration/cassandra_test.go, plugin/storage/integration/integration.go
=> [tests] Simplify Cassandra e2e test cleanup

plugin/storage/integration/cassandra_test.go, plugin/storage/integration/integration.go, plugin/storage/integration/memstore_test.go
- Related #3305
-  Adding e2e test for Implemented Storage backends for adaptive sampling i.e (cassendra, in-memory)
- 
=> Add e2e test for sampling storage

monitoring/jaeger-mixin/prometheus_alerts.yml
- Resolves #4771
- Add group by `operation` to JaegerQueryReqsFailing rule
- Here's the difference between before and after the changes. With `operation` group by, the alert will be distinguished by `operation`
- Tested manually because PR at #1745 says creating the automated tests are not easy.
- Manually tested in local
- Ran `curl -s http://localhost:9090/api/v1/alerts | jq` and returns
```
{
"status": "success",
"data": {
"alerts": [
{
...
"annotations": {
"message": "prometheus localhost:14269 is seeing 100.00% query errors on get_trace.\n"
},
...
}
]
}
}
```
Before it was
```
{
"status": "success",
"data": {
"alerts": [
{
...
"annotations": {
"message": "prometheus localhost:14269 is seeing 100.00% query errors on .\n"
},
...
}
]
}
}
```
- Ran `pint lint prometheus_alerts.yml`
``` …
```
=> Fix JaegerQueryReqsFailing alert rule missing 'operation' in query

scripts/build-all-in-one-image.sh
Build was failing
```
+ BRANCH=release-v1.50.0
++ go env GOARCH
+ GOARCH=amd64
+ mode=pr-only
+ expected_version=v16
++ node --version
+ version=v1[8](https://github.com/jaegertracing/jaeger/actions/runs/6426910109/job/17453121910?pr=4804#step:11:9).18.0
ERROR: installed Node version v18.18.0 doesn't match expected version v16
+ major_version=v18
+ '[' v18 = v[16](https://github.com/jaegertracing/jaeger/actions/runs/6426910109/job/17453121910?pr=4804#step:11:17) ']'
+ echo 'ERROR: installed Node version v18.18.0 doesn'\''t match expected version v16'
+ exit 1
```
- Remove hardcoded v16 version and read it from jaeger-ui/.nvmrc
- CI
=> Read expected Node version from ui dir

CHANGELOG.md, RELEASE.md, scripts/release-notes.py
Updates changelog, release.md and jaeger-ui submodule for v1.50.0
=> Prepare release 1.50.0

.github/workflows/ci-release.yml, Makefile, scripts/package-deploy.sh
- One of the previous runs of ci-release mistaken `main` tag as release version and pushed a release with this tag
- Add checks to the workflow to fail early of the latest git tag is not a semver
- Speed-up Makefile by making ALL_SRCS and ALL_PKGS vars lazy-evaluated
- Make semver check in scripts/package-deploy.sh more redable (perl instead of awk)
- CI
=> Clean-up & fortify ci-release

.github/workflows/ci-release.yml, scripts/build-all-in-one-image.sh, scripts/build-upload-a-docker-image.sh, scripts/compute-tags.sh, scripts/hotrod-integration-test.sh, scripts/rebuild-ui.sh
- Current ci-release workflow is running out of disk space
- 
- Cannot test until merged
=> Clean up CI scripts and prune Docker images between builds

.github/workflows/ci-release.yml
- Fix this [CI build error](https://github.com/jaegertracing/jaeger/actions/runs/6439689215/job/17487662586#step:19:16), using `ci-docker-build.yml` and `ci-build-binaries.yml` and `ci-all-in-one-build.yml` as examples:
```
ERROR: installed Node version v16.20.2 doesn't match expected version v18
```
- Test in CI pipeline; maybe there's a better way to test?
=> Use setup-node.js for Publish Release

scripts/build-upload-a-docker-image.sh
- `docker prune` commands will, by default, prompt the caller whether if they want to proceed, while defaulting to `N`, which resulted in a no-op in this [recent CI run](https://github.com/jaegertracing/jaeger/actions/runs/6442084773/job/17492537692#step:19:735).
- Adding a `--force` flag defaults to `y` without a prompt.
- Tested locally in terminal.
=> Add --force to docker commands

.github/actions/setup-branch/action.yml, .github/workflows/ci-release.yml
- Resolves #4814
- Resolves #4817
- Set BRANCH=s/main/main_from_fork/ when running on pull requests. This should solve the problem with CI failing when people submit a PR from a main branch in their fork, because our CI scripts think it means docker images should be uploaded and fail on the lack of credentials. Now they will skip the uploads.
- Move cleanup of android toolchain to the top of the workflow
- Replace the use of `.github/actions/setup-branch` with custom logic to set BRANCH which is always based on the recent semver tag. `setup-branch` will still work for non-release workflows.
- Remove unnecessary success checks in the steps (job fails when any step fails)
- Use `env.BRANCH` as release name in `upload-release-action` action, instead of `github.ref`
- Manually upload SBOM to …
=> [ci-release] Improve release workflow for manual runs

scripts/build-all-in-one-image.sh
- Fixes [this error in CI builds](https://github.com/jaegertracing/jaeger/actions/runs/6442084773/job/17492537692#step:19:744) and may explain why the jaeger all-in-one v1.50 image is [missing in docker hub](https://hub.docker.com/r/jaegertracing/all-in-one/tags?page=1&name=1.50):
```
+ '[main' '!=' 'pr-only]'
scripts/build-all-in-one-image.sh: line 57: [main: command not found
```
- Tested using a simple bash script to reproduce the problem.
=> Fix build-all-in-one-image script

scripts/build-upload-docker-images.sh, scripts/es-integration-test.sh, scripts/import-order-cleanup.sh, scripts/updateLicenses.sh
- Part of #4822
- Address some linter warnings
- CI
=> Clean-up some linter warnings in build scripts

scripts/build-all-in-one-image.sh, scripts/build-upload-a-docker-image.sh, scripts/hotrod-integration-test.sh
- Resolves #4821
- Just to validate that the correct image is being tested, use the exact commit sha instead of `latest` as image tag when building & running for local testing
- CI
=> Use commit hash as image label when building & integration-testing

.gitignore, Makefile
This resolves #3414
Add to the windows build step in `Makefile` to create a `resource.syso`  using [goversioninfo](https://github.com/josephspurrier/goversioninfo).  The version is extracted from the latest git tag.
`go build` will embed this information in the final executable
(Forgive the German in this screenshot)
1. Run ` make build-binaries-windows` 
2. Navigate to the folder containing binaries (e.g. ` cmd/agent/agent-windows-amd64`)
3. Add `.exe` to the file name for the changes to be seen: `agent-windows-amd64.exe`
Ran other targets (`make build-binaries-linux`) to see if it broke other targets. Looked fine so far.
There is the hassle of creating a `.syso` file that must be in the [same directory as the main.go file](https://github.com/golang/go/issues/16090#issuecomment-258956641) …
=> Add product/file version in Windows executables

cmd/all-in-one/Dockerfile, cmd/collector/Dockerfile
Resolved #4808 
- Expose OTLP gRPC and HTTP Collector ports in all-in-one Docker image.
- Expose all collector ports in collector Docker image
- 
=> Expose collector ports in docker images

Makefile
The local `make test` is still verbose
=> ci: Drop -v from CI unit tests to make failures easier to see

.github/workflows/ci-hotrod.yml, scripts/hotrod-integration-test.sh
- The HotROD CIT was failing in #4844, but no logs were shown to understand why
- Run container with `--name example-hotrod`
- Add `docker logs example-hotrod` to CIT workflow in case of failure
=> ci(hotrod): Print HotROD container logs in case of test failure

cmd/query/app/querysvc/adjusters.go, cmd/tracegen/main.go, examples/hotrod/pkg/tracing/init.go, examples/hotrod/pkg/tracing/rpcmetrics/observer.go, examples/hotrod/pkg/tracing/rpcmetrics/observer_test.go, examples/hotrod/services/customer/database.go, model/adjuster/otel_tag.go, model/adjuster/otel_tag_test.go, pkg/jtracer/jtracer.go, plugin/metrics/prometheus/metricsstore/reader.go, plugin/storage/cassandra/spanstore/reader.go
- Resolves #4534
- Apply OTel resource discovery(detectors) since OTel has plenty of detectors under the hood. Link https://pkg.go.dev/go.opentelemetry.io/otel/sdk@v1.19.0/resource
- Add OTel tags to process tags adjuster and we need to adjust only `otel.libray.name` and `otel.library.version`. Found here https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/adf5bb501bc65d24ae48088bde37f3c0b13353d0/pkg/translator/jaeger/traces_to_jaegerproto.go#L172
- Bump all OTel semconv to v1.21.0 since telemetrySDK detector use v1.21.0 semconv.
- Added a new unit test for the adjuster
- Tested manual in local by running `set OTEL_EXPORTER_OTLP_ENDPOINT http://localhost:4318; go run main.go all --otel-exporter=otlp` and `make run-all-in-one`, and ordered a ride in HotROD app.
- for …
=> feat: Add span adjuster that moves some OTel Resource attributes to Span.Process

.github/workflows/ci-label-check.yml
- part of: https://github.com/jaegertracing/jaeger/issues/4799
- This workflow would first check if the PR is created by @dependabot or not. If no, it would proceed to check for the labels on that pull request. For example:
- A new PR is created. The Label Check workflow would fail
- A maintainer adds some label `bug` on the PR, workflow would again run, but would still fail since the label `bug` doesn't start with `changelog:`
- The maintainer now adds some label `changelog:**`, this time, Label Check CI would pass.
- Without any label, failed GH Action: https://github.com/anshgoyalevil/jaeger/actions/runs/6531596646/attempts/2
- With the Label `changelog: feature`: Passing GH Action: https://github.com/anshgoyalevil/jaeger/actions/runs/6531596646/attempts/3
- With the label `bug` and …
=> CI: Add the label-check workflow to verify changelog labels on each PR

.github/dependabot.yml, scripts/release-notes.py
- Resolves #4799
- Configure dependabot to use `changelog:dependencies` label
- Skip that label in release notes
- Print progress when loading PRs
- local run
=> Use changelog:dependencies label for dependabot PRs

scripts/release-notes.py
- related to: https://github.com/jaegertracing/jaeger/pull/4850
- This PR adds a Dynamic Loading Bar Functionality to `release-notes.py`
- Knowing exactly what percentage our script is completed processing at each second provides a better UX
- Locally
=> chore: Add Dynamic Loading Bar Functionality to release-notes.py

cmd/tracegen/main.go, pkg/jtracer/jtracer.go
- Resolves #4534
- Continuation from #4844
- Add OTel resources to Jaeger components and tracegen tool.
- Tested manually in local
=> Add OTel resource detector to Jaeger components

plugin/storage/es/factory_test.go
- Resolves #4743
The test is still failing: https://github.com/jaegertracing/jaeger/actions/runs/6577136964/job/17868105418#step:7:461
From the logs we can see that the new client is started to be used (HEAD requests with new password), but then a bulk request with password1 comes in and breaks the test. 
- Set BulkSize to -1, which according to the driver docs disables bulk processing.
- Local test is successful, but the issue is difficult to reproduce
=> test[es]: Force batch size 1 in test

.github/workflows/scorecard.yml
Add OSSF Scorecards
- Part of security slam work to correct issues. This will add the GH Action to run code scanning which will ultimately replace the deprecated scanning we use today.
- Add GitHub Action
- Cannot test this until merged
- [Not Needed] I have added unit tests for the new functionality 
=> Create scorecard.yml for OSSF implementation

cmd/jaeger-v2/internal/all-in-one.yaml, cmd/jaeger-v2/internal/command.go, cmd/jaeger-v2/internal/exporters/storageexporter/factory.go, cmd/jaeger-v2/internal/extension/jaegerquery/factory.go, cmd/jaeger-v2/internal/extension/jaegerstorage/factory.go
- Part of #4843 
- Improvement on #4842, where all-in-one configuration was created via createDefaultConfig methods of extensions called by OTel automatically. This resulted in the memstore always being present in the config and always instantiated, which is not the desired behavior.
- The cmd.RunE interceptor is changed to provide an internal value to the `--config` flag if no flag was present on cmd line
- This avoids creating the collector manually, once we set the flag we always delegate back to official OTel code
- The value for the config is embedded in the binary and passed using `yaml:...`, which is one of the official config providers in OTel
- Ran all-in-one manually
=> exp(jaeger-v2): Simplify all-in-one configuration

README.md, SECURITY-INSIGHTS.yml
- Adding first pass at SECURITY-INSIGHTS.yml file
- Adding file based on the project configuration to satisfy new requirements from CLOMonitor
- No testing needed as this file is not used internally to the project
- [NOT NEEDED] I have added unit tests for the new functionality
- [NOT NEEDED] I have run lint and test steps successfully
=> Adding first pass at the SECURITY-INSIGHTS.yml

Makefile
- `make rebuild-ui` and `make build-ui` did not update the UI assets according to the latest release
- This changes the timestamp of the copied `index.html.gz` asset file to match the timestamp of the original asset. In turn, the timestamp of that asset matches the date of the UI release. This allows the combination of rebuild/build targets to always bring the UI assets in sync with the actual commit pinned in the ui-submodule.
- validated that CI runs normally
- ran manually on different versions of UI to ensure assets get copied again
=> ci: Keep the UI asset's .gz file timestamps the same as the original file

.golangci.yml, Makefile, examples/hotrod/cmd/.nocover, examples/hotrod/cmd/frontend.go, examples/hotrod/pkg/delay/.nocover, examples/hotrod/pkg/httperr/.nocover, examples/hotrod/pkg/log/.nocover, examples/hotrod/pkg/pool/.nocover, examples/hotrod/pkg/tracing/.nocover, examples/hotrod/pkg/tracing/rpcmetrics/metrics.go, examples/hotrod/pkg/tracing/rpcmetrics/observer_test.go, examples/hotrod/services/config/.nocover, examples/hotrod/services/customer/.nocover, examples/hotrod/services/customer/server.go, examples/hotrod/services/driver/.nocover, examples/hotrod/services/driver/driver.pb.go, examples/hotrod/services/frontend/.nocover, examples/hotrod/services/frontend/server.go, examples/hotrod/services/route/.nocover, examples/hotrod/services/route/server.go, examples/hotrod/services/route/stats.go
- The HotROD source code was never formatted or linted because golangci-lint was automatically excluding /examples/
- Disable linter's default skip dirs (which include /examples/)
- Fix linter errors
=> ci: Enable linting of code in examples/

.golangci.yml, cmd/internal/status/command.go, crossdock/main.go, internal/metricstest/local.go, pkg/es/client/client.go, plugin/metrics/disabled/reader.go, plugin/sampling/strategystore/static/strategy_store.go
- Enable more linters
- Fix issues currently reported
- `make lint`
=> test: Add more linters

scripts/build-all-in-one-image.sh, scripts/build-crossdock.sh
- Follow up to $4882
- Crossdock and all-in-one workflows failed on `main` branch
- `build-all-in-one-debug` target was removed, call `make build-all-in-one DEBUG_BINARY=1`
- fix invalid variable quoting in `scripts/build-crossdock.sh`
- Will check CI once this is merged
=> ci: Pass variable instead of calling make build-xxx-debug

plugin/storage/badger/factory.go, plugin/storage/badger/samplingstore/storage.go, plugin/storage/badger/samplingstore/storage_test.go, plugin/storage/integration/badgerstore_test.go, plugin/storage/integration/integration.go
Related  #3305
-   Implemented badger db for sampling store
-  Added Unit test and also tested it with the already Implemented integration test
=> feat: Add sampling store support to Badger

plugin/storage/blackhole/blackhole.go, plugin/storage/blackhole/blackhole_test.go, plugin/storage/blackhole/factory.go, plugin/storage/blackhole/factory_test.go, plugin/storage/factory.go, plugin/storage/factory_config.go
- When benchmarking jaeger-v2 vs. jaeger-collector, it's useful to have a no-op storage.
- Add `blackhole` storage type.
- unit tests
=> feat: Add blackhole storage, for benchmarking

cmd/collector/app/flags/flags.go, cmd/collector/app/flags/flags_test.go, cmd/collector/app/handler/otlp_receiver.go, cmd/collector/app/handler/otlp_receiver_test.go, pkg/config/tlscfg/flags.go, pkg/config/tlscfg/flags_test.go, pkg/config/tlscfg/options.go
- Resolves #4554 
- Enable reload interval functionality to OTel server certificates by adding `otlp.http.tls.reload-interval` and `otlp.grpc.tls.reload-interval` flags (0s means disabled)
- Tested manually in local
- Added `*.tls.reload-interval` flag unit tests to `flags.go` and `otel_receiver.go`
=> Add reload interval to OTel server certificates

examples/hotrod/docker-compose.yml
Removed `--otel-exporter=otlp` argument from the hotrod
Updated hotrod docker compose yaml.
Removed `--otel-exporter=otlp` argument from the hotrod
local run
=> Remove --otel-exporter=otlp argument from HotROD docker-compose

CHANGELOG.md
- Resolves #4906
- Add #4783 to breaking changes for v1.50.0
=> Add breaking change to 1.50 release notes

scripts/package-deploy.sh
```
Run bash scripts/package-deploy.sh
+ set -e
+ readonly VERSION
++ make echo-version
++ perl -lne 'print $1 if /^v(\d+.\d+.\d+)$/'
+ VERSION=1.51.0
scripts/package-deploy.sh: line 55: VERSION: readonly variable
Error: Process completed with exit code 1.
```
- remove `readonly` declaration
- will rerun script after merging, no other way to test
=> Fix release script broken by recent linting cleanup

scripts/build-all-in-one-image.sh
- Part of #4843
- Remove early exit and allow `jaeger` binary to be published to Docker Hub / quay.io
- The repositories in the respective hubs were created manually
- Publishing only works on the main branch, will see how it goes once erged
=> exp: Publish jaeger v2 image

.github/workflows/ci-lint-checks.yaml, .github/workflows/ci-unit-tests.yml
This pr splits the unit-test workflow into two parallel workflows: one for running tests and another for running linters. The motivation behind this change is to improve the overall workflow performance. The unit-test workflow had become the longest among all workflows, with significant time spent on installing tools that are only required for linters.
Resolves #4930
=> Split unit-test workflow into tests and lint

cmd/query/app/ui/placeholder/index.html
- Part of #4874
- Add some styling to the placeholder
- Make the config substitutions directly visible
- Add missing capabilities var
`go run ./cmd/all-in-one`
=> Make UI placeholder more descriptive

cmd/ingester/app/consumer/offset/manager.go, cmd/ingester/app/consumer/offset/manager_test.go, cmd/ingester/app/consumer/processor_factory.go
Resolves #4950
Add tag with topic name to metrics emitted by Kafka consumer offset manager.
Unit tests
=> [kafka-consumer] Add topic name as a tag to offset manager metrics

docker-compose/monitor/docker-compose.yml
[OpenTelemetry Collector Contrib v0.85.0](https://github.com/open-telemetry/opentelemetry-collector-contrib/releases/tag/v0.85.0) introduces a breaking change to enable normalized metric names by default:
> `prometheusexporters`: Append prometheus type and unit suffixes by default in prometheus exporters. (https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/26488)
Suffixes can be disabled by setting add_metric_suffixes to false on the exporter.
Motivated by [this support question](https://cloud-native.slack.com/archives/CGG7NFUJ3/p1699539239671519).
- Updates the otel version in the example to the latest v0.89.0 release, which includes this breaking change.
- Enable normalized metric name support.
- Jaeger documentation/troubleshooting tips relating to this problem …
=> Normalize metric names due to breaking change

plugin/storage/integration/elasticsearch_test.go
- Follow-up to #4829 where the integration test is using non-default template priorities
- Remove priorities overrides, it must work with defaults because this is how most users would run.
- CI should succeed
=> [ci/es] Use default template priorities

.codecov.yml, .github/actions/setup-codecov/action.yml, .github/workflows/ci-cassandra.yml, .github/workflows/ci-elasticsearch.yml, .github/workflows/ci-grpc-badger.yml, .github/workflows/ci-kafka.yml, .github/workflows/ci-opensearch.yml, .github/workflows/ci-unit-tests.yml, Makefile, cmd/ingester/app/builder/.nocover, cmd/ingester/app/builder/empty_test.go, pkg/cassandra/config/.nocover, pkg/cassandra/config/empty_test.go, pkg/cassandra/gocql/.nocover, pkg/cassandra/gocql/empty_test.go, pkg/es/wrapper/.nocover, pkg/es/wrapper/empty_test.go, pkg/kafka/auth/.nocover, pkg/kafka/auth/empty_test.go, pkg/kafka/consumer/.nocover, pkg/kafka/consumer/empty_test.go, pkg/kafka/producer/.nocover, pkg/kafka/producer/empty_test.go, plugin/storage/badger/samplingstore/storage.go, plugin/storage/grpc/config/.nocover, plugin/storage/grpc/config/empty_test.go, plugin/storage/integration/.nocover, plugin/storage/integration/integration.go
- Some of our code is not testable unless we run integration tests, e.g. places that require db connection
- But we don't collect coverage from integration tests
- Resolves #1516
- Resolves #4965
- Add coverage generation to storage tests and upload to codecov
- Remove several `.nocover` since their packages are now included in coverage via integration tests anyway. Add corresponding `empty_test.go` to avoid linter error.
- Remove `println` from badger & sampling storage integration
- Change COLORIZE macro to include `| ...` so that it can be overwritten to nothing for faster std output. When output is piped, even to `| cat -`, the buffering prevents incremental test output, so one cannot easily observe test progress
- CI is green
- [Comment below by …
=> Collect code coverage from integration tests and upload to codecov

plugin/storage/badger/factory.go, plugin/storage/blackhole/factory.go, plugin/storage/cassandra/factory.go, plugin/storage/cassandra/factory_test.go, plugin/storage/es/factory.go, plugin/storage/es/factory_test.go, plugin/storage/factory.go, plugin/storage/factory_test.go, plugin/storage/grpc/factory.go, plugin/storage/grpc/factory_test.go, plugin/storage/kafka/factory.go, plugin/storage/kafka/factory_test.go, plugin/storage/memory/factory.go
- Part of #4963
- Follow up to #4834
- Explicitly declare all interfaces each factory implements
- Move these declarations to the main file for visibility
- CI
=> Declare all interfaces each factory implements

plugin/storage/badger/factory.go, plugin/storage/badger/factory_test.go, plugin/storage/badger/lock.go, plugin/storage/badger/lock_test.go, plugin/storage/factory_test.go
- Resolves #4963
-   Implement missing `CreateLock` method on `SamplingStoreFactory` interface for badger
-  run the Integration and make test command
=> fix(badger): Add missing SamplingStoreFactory.CreateLock method

.github/workflows/ci-kafka.yml, cmd/ingester/app/builder/builder.go, pkg/kafka/consumer/config.go, plugin/storage/integration/kafka_test.go
- Resolves #4979
- Change kafka consumer to consume messages from the oldest possible offsets to prevent failure when the test produces messages before the consumer is ready.
- Start a kafka server hosted at localhost:9092
```
docker run --name kafka \
--network jaeger \
-p 9092:9092 \
-e KAFKA_CFG_NODE_ID=0 \
-e KAFKA_CFG_PROCESS_ROLES=controller,broker \
-e KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093 \
-e KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093 \
-e KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092 \
-e KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT \
-e KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER \
-e KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT \
bitnami/kafka:3.6
```
- Run `./scripts/kafka-integration-test.sh`
- for …
=> [test]: make Kafka consumer read from the earliest messages

examples/grafana-integration/README.md, examples/grafana-integration/docker-compose.yaml, examples/grafana-integration/grafana/hotrod_metrics_logs.json, examples/grafana-integration/prometheus/prometheus.yml
Currently, the `grafana-integration` example doesn't work properly: if you run `docker-compose up` in that folder, services will start but only logging will work, the metrics and tracing won't.
* Fix traces endpoint config for hotrod (`traces export: Post "http://localhost:4318/v1/traces": dial tcp 127.0.0.1:4318: connect: connection refused`)
* Fix hotrod metrics scraping (endpoint has moved to the frontend service)
* Pin Jaeger/hotrod tags to prevent future issues
* Fix Grafana dashboard (metric names, labels, migrate to new time series panel)
* Add default Grafana credentials to README
* Fix the loki container being stuck on shutdown by setting shorter timeouts (bug with the driver: https://github.com/grafana/loki/issues/2361#issuecomment-718024318)
* Update Grafana/Loki/Prom pinned …
=> Fix example/grafana-integration

.github/workflows/ci-kafka.yml, scripts/kafka-integration-test.sh
Resolves #4982 
- Introduced a -k parameter to the kafka-integration-test.sh script.
- Modified the script to wait for Kafka availability before proceeding.
=> [ci]:Improve Kafka integration test self-sufficiency

.github/workflows/ci-unit-tests.yml, Makefile
- Even though we're using setup-go v4.1 where caching is supposed to be enabled by default, it does not seem to work as the dependencies are still being downloaded when we run the tests
- remove custom GOCACHE
- point to go.sum file
- CI
- the change itself did not seem to help, still seeing lots of "downloading" when running the tests
- needs more investigation, but I suggest we still merge this as an improvement
=> Remove custom GOCACHE location

cmd/all-in-one/main.go
- Resolves #5007
- provide proper namespaces for different sub-components (agent, collector, query) running in all-in-one, to match the metrics names produces by these components when running standalone
* `go run ./cmd/all-in-one`
* `curl http://localhost:14269/metrics | grep -v '#'`
* compare before/after [textcompare-diff.pdf](https://github.com/jaegertracing/jaeger/files/13689954/textcompare-diff.pdf)
=> Make all-in-one metric names match metrics from standalone components

examples/hotrod/README.md, examples/hotrod/docker-compose.yml
- `examples/hotrod/docker-compose.yml` always used `latest` tag, which is not being refreshed by Docker unless you proactively do that. There was no way to override that.
- Add `JAEGER_VERSION` environment variable
- Previously my `latest` tags were pointing to stale versions, and the example was not actually working (likely due to earlier changes to introducing OTEL SDK)
- After this change: `$ JAEGER_VERSION=1.52 docker compose up` downloaded new versions and the tracing was working
=> Allow specifying version for HotROD docker-compose

cmd/agent/app/configmanager/metrics_test.go
- Add goleak check
- Call Stop on the factory for clean shutdown
- Run each test via t.Run so that defer runs in scope
cc @akagami-harsh
=> Add goleak check to cmd/agent/app/configmanager

cmd/collector/app/processor/empty_test.go, cmd/collector/app/sampling/model/empty_test.go, cmd/collector/app/sampling/strategystore/empty_test.go, cmd/ingester/app/builder/empty_test.go, cmd/query/app/ui/empty_test.go, empty_test.go, model/json/empty_test.go, pkg/cassandra/config/empty_test.go, pkg/cassandra/empty_test.go, pkg/cassandra/gocql/empty_test.go, pkg/distributedlock/empty_test.go, pkg/es/empty_test.go, pkg/es/wrapper/empty_test.go, pkg/kafka/auth/empty_test.go, pkg/kafka/consumer/empty_test.go, pkg/kafka/producer/empty_test.go, pkg/memory/config/empty_test.go, pkg/prometheus/config/empty_test.go, plugin/empty_test.go, plugin/storage/grpc/config/empty_test.go, ports/ports_test.go, storage/dependencystore/empty_test.go, storage/empty_test.go, storage/metricsstore/empty_test.go, storage/metricsstore/metrics/decorator_test.go, storage/spanstore/interface_test.go, storage/spanstore/metrics/package_test.go
- Add goleak checks to all packages with empty_test.go as well as ./storage/... (which mostly contains APIs)
- CI
=> Add goleak check to packages with empty tests

.github/actions/setup-go-tip/action.yml, .github/workflows/ci-unit-tests-go-tip.yml
- Unit tests on Go Tip sometimes fail because Go Tip fails to install, but the output is non-descriptive, e.g. https://github.com/jaegertracing/jaeger/actions/runs/7263410887/job/19788655227
- Move Go Tip installation into a separate sub-action
- Add some debug logging to see the progress to make it easier to debug in case of failures (right now it's hard to tell which step is actually failing and resulting in the errors above)
- Tested in personal repo: https://github.com/yurishkuro/test-project-3/actions/runs/7264047725/job/19790690846
=> Move Go Tip installation into sub-action

.github/actions/setup-go-tip/action.yml
- Fixes #5021 
- added retry logic in Go Tip Github Action 
- in below case it ran successfully
- but the logic was not used because the `curl` command did not any return code 
- https://github.com/akagami-harsh/jaeger/actions/runs/7266233916/job/19797565337
=> ci: add retry logic in the Install Go Tip GitHub Action

pkg/es/wrapper/wrapper.go, pkg/jtracer/jtracer.go, pkg/jtracer/jtracer_test.go, pkg/queue/bounded_queue_test.go, plugin/storage/es/factory.go, plugin/storage/es/factory_test.go, plugin/storage/es/package_test.go, plugin/storage/grpc/memory/plugin_test.go, plugin/storage/kafka/factory.go, plugin/storage/kafka/factory_test.go, plugin/storage/kafka/package_test.go, plugin/storage/kafka/writer_test.go, plugin/storage/memory/factory_test.go, plugin/storage/memory/package_test.go
- Fix goroutine leaks in several packages
- go test
=> Fix goroutine leaks in several packages

.golangci.yml, cmd/anonymizer/app/query/query.go, cmd/anonymizer/app/uiconv/extractor.go, cmd/anonymizer/app/uiconv/extractor_test.go, cmd/anonymizer/app/uiconv/module.go, cmd/anonymizer/app/uiconv/reader.go, cmd/anonymizer/app/uiconv/reader_test.go, cmd/collector/app/handler/grpc_handler.go, cmd/es-rollover/app/init/action.go, cmd/internal/flags/admin.go, cmd/query/app/flags.go, cmd/query/app/grpc_handler.go, cmd/query/app/http_handler.go, cmd/query/app/querysvc/query_service.go, cmd/query/app/server.go, model/ids.go, pkg/es/client/ilm_client.go, pkg/es/client/index_client.go, pkg/es/config/config.go, plugin/storage/badger/factory.go, plugin/storage/badger/samplingstore/storage.go, plugin/storage/cassandra/samplingstore/storage.go, plugin/storage/grpc/shared/grpc_client.go, plugin/storage/grpc/shared/grpc_handler.go
Resolves #5027 
- Use `%w` when wrapping errors
- use `errors.Is` and `errors.As` instead of explicit cast or comparison
- Fix a bug 249c9592 where direct and wrapped io.EOF were conflicting
- Enable error linting
- 
=> Enable errorlint linter and fix errors

.golangci.yml, Makefile, cmd/agent/app/reporter/client_metrics.go, cmd/agent/app/servers/tbuffered_server_test.go, cmd/collector/app/root_span_handler_test.go, cmd/collector/app/span_processor.go, cmd/collector/app/span_processor_test.go, cmd/es-rollover/app/actions_test.go, cmd/es-rollover/app/index_options_test.go, cmd/es-rollover/app/init/action_test.go, cmd/es-rollover/app/lookback/time_reference_test.go, cmd/es-rollover/app/rollover/action_test.go, cmd/internal/flags/service_test.go, pkg/es/filter/alias_test.go, pkg/es/filter/date_test.go, pkg/queue/bounded_queue.go, pkg/queue/bounded_queue_test.go, plugin/sampling/leaderelection/leader_election.go, plugin/sampling/leaderelection/leader_election_test.go, plugin/sampling/strategystore/static/strategy_store_test.go, plugin/storage/badger/lock_test.go, plugin/storage/cassandra/spanstore/writer_test.go, plugin/storage/grpc/shared/streaming_writer.go, plugin/storage/memory/lock_test.go, plugin/storage/memory/sampling_test.go
- Upgrade linter version
- Update configuration of depguard
- Disable uber-go/atomic and crossdock as deps
- Replace invalid crossdock imports with stretchr/testify
- Replace uber-go/atomic usage with sync/atomic
- in most cases pointers to atomics are not necessary, and likewise initialization to zero values
- Fix other test and linter errors revealed by new linter
=> Upgrade golangci-lint to v1.55.2 and fix errors

.github/workflows/ci-label-check.yml
Fixes a deprecation in the workflow as [outlined here](https://github.com/jaegertracing/jaeger-ui/issues/2067)
Removed the `set-output` command in favor of the new environment variable by GitHub.
NA
=> ci: Simplify check-label workflow

cmd/agent/app/reporter/client_metrics_test.go, cmd/agent/app/reporter/connect_metrics_test.go, cmd/agent/app/reporter/metrics_test.go, cmd/agent/app/reporter/package_test.go, pkg/httpmetrics/metrics_test.go, pkg/recoveryhandler/zap_test.go
- part of #5006 
- fix goroutine leaks in some package and add goleak check
- go test
=> Fix goroutine leaks in some packages

.github/workflows/ci-unit-tests-go-tip.yml, .github/workflows/ci-unit-tests.yml
- https://github.com/jaegertracing/jaeger/pull/5035#issuecomment-1869152935
- The logs from https://github.com/jaegertracing/jaeger/actions/runs/7324976182/job/19949034415#step:8:67 show:
> github.GithubException.GithubException: 403 {"message": "Resource not accessible by integration", "documentation_url": "https://docs.github.com/rest/checks/runs#create-a-check-run"}
This is because it needs write permission on the PR check runs to provide a summary.
- The alternative is to disable test summary in the PR checks.
- Ran this in my fork earlier.
=> Fix permission failed on checks-run

.github/workflows/ci-protogen-tests.yml, Makefile.Protobuf.mk, thrift-gen/agent/GoUnusedProtection__.go, thrift-gen/agent/agent-consts.go, thrift-gen/agent/agent.go, thrift-gen/baggage/GoUnusedProtection__.go, thrift-gen/baggage/baggage-consts.go, thrift-gen/baggage/baggage.go, thrift-gen/jaeger/GoUnusedProtection__.go, thrift-gen/jaeger/jaeger-consts.go, thrift-gen/jaeger/jaeger.go, thrift-gen/sampling/GoUnusedProtection__.go, thrift-gen/sampling/sampling-consts.go, thrift-gen/sampling/sampling.go, thrift-gen/zipkincore/GoUnusedProtection__.go, thrift-gen/zipkincore/zipkincore-consts.go, thrift-gen/zipkincore/zipkincore.go
- Thrift types were not re-synced after upgrading to the latest Thrift compiler
- Regenerate files - all changes seem to be formatting related
- Enable Thrift generation check in CI to prevent this in the future
- CI
=> Regenerate Thrift types and enable Thrift check

cmd/query/app/apiv3/grpc_gateway.go, cmd/query/app/apiv3/grpc_gateway_test.go, cmd/query/app/apiv3/grpc_handler_test.go, cmd/query/app/apiv3/package_test.go, cmd/query/app/server.go
- I would like to remove dependency on grpc-gateway because it causes issues with using Gogo in OTLP protobufs
- The tests were not fully exercising all of the HTTP service functions
- DRY the tests
- Ensure no goroutines are leaked - pass tlscfg.Options by reference
- unit tests
=> Clean-up APIv3 tests

Makefile
- When we switched unit test results forwarding using `tee` (#5045), it breaks the CI validation since the exit code from tests is ignored.
- Use `set -o pipefail` as we did in all other targets where the test output is piped into something
- Ran local validation to ensure that error code is returned with this change
=> bugfix: Set pipefail when running unit tests to preserve exit code

.github/workflows/ci-unit-tests-go-tip.yml, .github/workflows/ci-unit-tests.yml, Makefile
- When the tests fail, the target `test-report` is never run and thus no summary can be created
- Invoke the target from the GH workflow as an explicit `if: always()` step
=> Separate test report collection from the main target

cmd/agent/app/proxy_builders.go, cmd/agent/app/reporter/grpc/builder.go, cmd/agent/app/reporter/grpc/builder_test.go, cmd/agent/app/reporter/grpc/collector_proxy.go, cmd/agent/app/reporter/grpc/collector_proxy_test.go, cmd/agent/app/reporter/grpc/package_test.go, cmd/agent/app/reporter/grpc/reporter_test.go
- part of #5006 
- fixed goroutine leaks in `cmd/agent/app/reporter/grpc` and also added a goleak check
- go test
=> Fix goroutine leak in cmd/agent/app/reporter/grpc

cmd/collector/app/handler/package_test.go, cmd/collector/app/handler/zipkin_receiver_tls_test.go
- Part of #5006 
- Added TestMain to package folders
- Added make goleak into unit test ci
- please run make goleak 
=> Add goleak tests to cmd/collector/app/handler

.codecov.yml, examples/hotrod/cmd/.nocover, examples/hotrod/cmd/empty_test.go, examples/hotrod/pkg/delay/.nocover, examples/hotrod/pkg/delay/empty_test.go, examples/hotrod/pkg/httperr/.nocover, examples/hotrod/pkg/httperr/empty_test.go, examples/hotrod/pkg/log/.nocover, examples/hotrod/pkg/log/empty_test.go, examples/hotrod/pkg/pool/.nocover, examples/hotrod/pkg/pool/empty_test.go, examples/hotrod/pkg/tracing/.nocover, examples/hotrod/pkg/tracing/empty_test.go, examples/hotrod/services/config/.nocover, examples/hotrod/services/config/empty_test.go, examples/hotrod/services/customer/.nocover, examples/hotrod/services/customer/empty_test.go, examples/hotrod/services/driver/.nocover, examples/hotrod/services/driver/empty_test.go, examples/hotrod/services/frontend/.nocover, examples/hotrod/services/frontend/empty_test.go, examples/hotrod/services/route/.nocover, examples/hotrod/services/route/empty_test.go
@yurishkuro, do we also need goleak tests in examples?
- Part of #5068 
- Added Empty Tests for `./examples` to reduce noise in `make nocover`.
- go test
=> Added Empty Tests for Examples

plugin/storage/badger/samplingstore/storage.go, plugin/storage/badger/samplingstore/storage_test.go
- Resolves #5090
- fixed flaky test
- fixed a small typo
=> Fix flaky test: plugin/storage/badger/samplingstore

cmd/jaeger/internal/exporters/storageexporter/package_test.go
- part of #5006 
- Added Goroutine leak test for internal/exporters/storageexporter.
- `make test`
=> Add Goleak check to cmd/jaeger/internal/exporters/storageexporter

model/adjuster/parent_reference.go, model/adjuster/parent_reference_test.go
- Resolves #5122
- Avoid changing order in the case described above.
- A test case is added.
=> Avoid changing a correct order of span references

internal/tracegen/.nocover, internal/tracegen/config_test.go, internal/tracegen/worker_test.go
- Partially fixes #5068 
- This commit adds tests for the `internal/tracegen` package.
- make test
=> Added unit tests in internal/tracegen

cmd/jaeger/internal/extension/jaegerstorage/package_test.go, pkg/version/package_test.go
- Partially addresses: #5006
- Added `testutils.VerifyGoLeaks` in the following packages:
- `cmd/jaeger/internal/extension/jaegerstorage/`
- `/pkg/version/`
- `make test`
=> Add goleak checks in 2 packages

pkg/testutils/leakcheck.go, pkg/testutils/leakcheck_test.go, plugin/storage/es/factory_test.go
- Part of #5083
- Add goleak checks to individual tests suspected of causing the leaks, this might help confirming which ones are at fault, since the main VerifyGoLeak check cannot distinguish between tests in the package.
```
$ go test -count 100 ./plugin/storage/es
ok  	github.com/jaegertracing/jaeger/plugin/storage/es	8.246s
```
=> [test] Add per-test goleak check for storage/es

.golangci.yml, cmd/agent/app/reporter/grpc/builder_test.go, cmd/agent/app/reporter/grpc/collector_proxy_test.go, cmd/query/app/server_test.go, crossdock/services/tracehandler_test.go, model/adjuster/adjuster_test.go, model/converter/thrift/zipkin/process_hashtable_test.go, pkg/es/client/index_client_test.go, pkg/metrics/metrics_test.go, plugin/sampling/strategystore/static/strategy_store_test.go, plugin/storage/badger/factory_test.go, plugin/storage/badger/stats_linux_test.go, plugin/storage/integration/trace_compare.go
- Apply compares rule of testifylint
-  More appropriate testify API with clearer failure message.
- CI 
=> testifylint: enable compares

scripts/kafka-integration-test.sh
Resolves #5148
- The previous approach used ```nc``` to check the availability of the ```Kafka port```, which was not reliable, especially when the Kafka container was started asynchronously. The updated script now ensures a more reliable check for Kafka readiness by attempting to list topics using ```kafka-topics.sh``` within a loop. This modification ensures that the script waits until Kafka is fully initialized before proceeding with integration tests.
- This modification ensures that the script waits until Kafka is fully initialized before proceeding with integration tests.
- Ran ```bash scripts/kafka-integration-test.sh -k``` from the project root.
=> Add reliable check for Kafka broker being ready

cmd/jaeger/internal/extension/jaegerstorage/extension.go, cmd/jaeger/internal/extension/jaegerstorage/extension_test.go
- There is duplicated code in the extension Start, which is being copy/pasted in other PRs
- Refactor Start to avoid duplication and to make testing simpler (no need to test all edge cases for every storage type)
- Clean-up tests
- 
=> [jaeger-v2] Streamline storage initialization

CHANGELOG.md, RELEASE.md
Prepares Jaeger for release 1.54.0.
Includes jaeger-ui submodule updates.
=> Prepare Release 1.54.0

.github/workflows/ci-all-in-one-build.yml, .github/workflows/ci-build-binaries.yml, .github/workflows/ci-cassandra.yml, .github/workflows/ci-crossdock.yml, .github/workflows/ci-docker-build.yml, .github/workflows/ci-elasticsearch.yml, .github/workflows/ci-grpc-badger.yml, .github/workflows/ci-hotrod.yml, .github/workflows/ci-kafka.yml, .github/workflows/ci-lint-checks.yaml, .github/workflows/ci-opensearch.yml, .github/workflows/ci-protogen-tests.yml, .github/workflows/ci-release.yml, .github/workflows/ci-unit-tests.yml, .github/workflows/fossa.yml, .golangci.yml, docker/Makefile, go.mod
- Go version linter started failing because Go 1.22 was released
```shell
$ ./scripts/check-go-version.sh -u
```
- CI
=> Bump Go version

pkg/es/errors.go, pkg/es/errors_test.go, plugin/storage/es/spanstore/reader.go, plugin/storage/es/spanstore/service_operation.go
- In many cases when ES operations fail, the only error returned to the UI or written to Jaeger log is `all shards fail`, which is pretty useless for the actual troubleshooting.
- Meanwhile, the driver actually returns an error struct that contains a `RootCause` field.
- Inspect the error and include root cause if present
Run all-in-one and `curl 'http://localhost:16686/api/services'`
Before:
`$ curl 'http://localhost:16686/api/services'`
`{"data":null,"total":0,"limit":0,"offset":0,"errors":[{"code":500,"msg":"search services failed: elastic: Error 400 (Bad Request): all shards failed [type=search_phase_execution_exception]"}]}`
After:
`$ curl 'http://localhost:16686/api/services'`
`{"data":null,"total":0,"limit":0,"offset":0,"errors":[{"code":500,"msg":"search services failed: elastic: …
=> Return more detailed errors from ES storage

.codecov.yml, plugin/storage/grpc/shared/grpc_handler_test.go
- As mentioned in #5194, our coverage dropped below 95%. Until it's fixed we cannot "merge on green" any PRs that are not violating coverage restrictions, including dependabot PRs.
- Temporarily lower codecov threshold to 94.4% (the current level is 94.43%), until the above issue is fixed.
=> Temporarily lower codecov threshold below 95%

cmd/jaeger/integration/receivers/storagereceiver/README.md, cmd/jaeger/integration/receivers/storagereceiver/config.go, cmd/jaeger/integration/receivers/storagereceiver/config_test.go, cmd/jaeger/integration/receivers/storagereceiver/factory.go, cmd/jaeger/integration/receivers/storagereceiver/factory_test.go, cmd/jaeger/integration/receivers/storagereceiver/package_test.go, cmd/jaeger/integration/receivers/storagereceiver/receiver.go, cmd/jaeger/integration/receivers/storagereceiver/receiver_test.go, cmd/jaeger/integration/receivers/storagereceiver/testdata/config.yaml, cmd/jaeger/internal/extension/jaegerstorage/extension.go, go.mod, go.sum
- Part of #4843
- Separate Jaeger storage receiver PR from and will be used by jaeger-v2 Kafka PR #4971
- Implement Jaeger storage receiver to be used by Jaeger-v2 Kafka integration test.
- Added some unit tests.
=> [jaeger-v2] Add support for artificial jaeger storage receiver

CHANGELOG.md, RELEASE.md
Prepares Jaeger for release 1.55.0.
Includes jaeger-ui submodule updates.
I can add more updates for the RELEASE.md if needed based on the Slack discussion. Thank you.
=> Prepare v1.55.0 release

CHANGELOG.md, RELEASE.md, scripts/release-notes.py
The script was only generating level-4 headers. Changed it to generate the complete changelog, including the UI placeholder. Tweak release instructions.
=> Enhance release-notes script to add missing parts

cmd/remote-storage/app/package_test.go, cmd/remote-storage/app/server.go, cmd/remote-storage/app/server_test.go
- Part of [5006](https://github.com/jaegertracing/jaeger/issues/5006)
- Identified two tests `TestServerGRPCTLS` and `TestServerHandlesPortZero` which are failing and causing goroutine leaks
- 
=> Fix goroutine leaks in cmd/remote-storage/app

pkg/kafka/producer/config.go, plugin/storage/kafka/options.go, plugin/storage/kafka/options_test.go
- Exposes MaxMessageBytes config mentioned in https://github.com/jaegertracing/jaeger/issues/1335
- Adds support to set MaxMessageBytes config on producer
- Also setting a default which matches with [sarama](https://github.com/IBM/sarama/blob/main/config.go#L177) default unclear if we need to set that default explicitly from jaeger producer initialization 
- Tested on our development jaeger cluster. After seeing below error we made following changes and built a new Image and verified that my changes fixed the issue
```
{"level":"error","ts":1550003610.8029132,"caller":"kafka/writer.go:59","msg":"kafka server: Message was too large, server rejected it to avoid allocation error.","stacktrace":"[github.com/jaegertracing/jaeger/plugin/storage/kafka.NewSpanWriter.func2](http://github.com/jaeger …
```
=> [kafka-producer] Support setting max message size

examples/hotrod/README.md
- The README was showing a command with the legacy OTEL_EXPORTER_JAEGER_ENDPOINT env var (using Jaeger format)
- Change to use `OTEL_EXPORTER_OTLP_ENDPOINT` to match the `docker-compose` setup.
=> Fix HotROD instructions

plugin/storage/badger/docs/upgrade-v1-to-v3.md
- Related https://github.com/jaegertracing/documentation/issues/682
- Badger migration v1 to v3 move from jaeger documentation
- No
=> Docs: Badger migration v1 to v3 split from jaeger-docs

cmd/ingester/app/builder/builder.go, cmd/ingester/app/flags.go, cmd/ingester/app/flags_test.go, pkg/kafka/consumer/config.go
- PR #5263 added support for setting max message size a producer can send that solved the issue on collector end now we are seeing our consumer getting stuck consuming messages larger that 1MB(default fetch max message bytes) so adding an option to set this value via flags
- adding an option to set fetch max message bytes value via flags
- Tested against our dev jaeger where we have spans larger than 1 MB
=> [kafka-consumer] Add support for setting fetch message max bytes

plugin/storage/badger/docs/storage-file-non-root-permission.md
- Related https://github.com/jaegertracing/documentation/issues/683
- Badger file permission as non-root service
- No
=> Docs: Badger file permission as non-root service

cmd/jaeger/internal/components.go, go.mod, go.sum
Hi, it's my first very basic PR.
I removed `loggingexporter` since it's deprecated and replaced it with the `debugexporter`.
=> Replaced the deprecated logging exporter to debug exporter

cmd/collector/app/collector.go, cmd/collector/app/collector_test.go, cmd/collector/app/metrics_test.go, cmd/collector/app/package_test.go, cmd/collector/app/span_handler_builder_test.go, cmd/collector/app/span_processor_test.go, internal/metricstest/local.go
Solves part of https://github.com/jaegertracing/jaeger/issues/5006.
I introduced `testutils.VerifyGoLeaks(m)` and then ensured all leaked goroutines were stopped.
`make lint` and `make test`
=> Fix test goroutine leaks in ./cmd/collector/app/

model/adjuster/span_id_deduper.go
Use the variables included in the go standard library to make the code clearer
The same as https://github.com/jaegertracing/jaeger/pull/5294
- Math MaxUint64 is a constant currently defined in the go standard library and can be used directly without having to define it repeatedly
- no need
=> Use math.MaxUint64 instead of 0xffffffffffffffff

cmd/internal/printconfig/command_test.go
- Solves part of https://github.com/jaegertracing/jaeger/issues/5006
- There doesn't seem to be goroutine leaks in this package, so there's no reason for it to be excluded
- `go test ./cmd/internal/printconfig`
=> Call testutils.VerifyGoLeaks in cmd/internal/printconfig tests

pkg/cassandra/gocql/testutils/udt_test.go
- #5006
- added goleak check in `pkg/cassandra/gocql/testutils`
- ``make test ``
=> Add goleak check in pkg/cassandra/gocql/testutils

cmd/all-in-one/main.go, cmd/internal/flags/service.go, cmd/internal/flags/service_test.go, cmd/jaeger/internal/extension/jaegerquery/server.go, cmd/query/app/server.go, cmd/query/app/server_test.go, cmd/query/app/token_propagation_test.go, cmd/query/main.go, cmd/remote-storage/app/server.go, cmd/remote-storage/app/server_test.go, cmd/remote-storage/main.go
Resolves #5307
- Simplifies the signalling of healthcheck status from the "servers" to the "service": instead of using 2 channels to feed healthcheck status back to the Service.HealthCheck, we just give the server components direct access to the Healthcheck which they can update directly.
- This is possible because the Healthcheck package is threadsafe (uses `atomic.Value` for state).
- This pattern is consistent with how the service's Healtcheck is passed directly to cmd/collector/app package.
- `make lint test`
=> Refactor healthcheck signalling between server and service

cmd/jaeger/internal/extension/jaegerquery/server.go, cmd/query/app/http_handler_test.go, cmd/query/app/package_test.go, cmd/query/app/server.go, cmd/query/app/server_test.go, cmd/query/app/static_handler.go, cmd/query/app/static_handler_test.go, cmd/query/app/token_propagation_test.go
- Solves part of https://github.com/jaegertracing/jaeger/issues/5006
- There were a number of causes of goroutine leaks, so I took the approach of addressing these in the initial commits, and then introducing the actual `testutils.VerifyGoLeaks` call in the final commit
- See the individual commit messages for more details on each change
- Note that this change involved making some changes to the public function signatures of packages under `cmd`, which would technically be a breaking change if there are any external packages importing this as a library (raised in https://github.com/jaegertracing/jaeger/issues/5006#issuecomment-2016490940).
- `make test`
=> Fix goroutine leaks in cmd/query/app

cmd/collector/app/collector_test.go, cmd/collector/app/sampling/grpc_handler_test.go, cmd/collector/app/sampling/strategystore/interface.go, cmd/collector/app/server/test.go, pkg/clientcfg/clientcfghttp/cfgmgr_test.go, plugin/sampling/strategystore/adaptive/factory.go, plugin/sampling/strategystore/adaptive/factory_test.go, plugin/sampling/strategystore/adaptive/package_test.go, plugin/sampling/strategystore/adaptive/processor.go, plugin/sampling/strategystore/adaptive/processor_test.go, plugin/sampling/strategystore/static/strategy_store.go
- Solves part of https://github.com/jaegertracing/jaeger/issues/5006
- This mainly involved ensuring that all goroutines started by the Processor are shut down in a Close method (which also blocks on them returning via a WaitGroup).
- Adding this flagged an issue where the `runUpdateProbabilitiesLoop` had a long delay, so tests need to be able to override the default Processor.followerRefreshInterval, or `Close` would take up to ~20s to return. More context on this here https://github.com/jaegertracing/jaeger/issues/5006#issuecomment-2027292668 - specifically regarding how to override this in the `Factory`.
- I also needed to fix a deadlock where a test was not unlocking a lock which would allow the Close method to return: https://github.com/jaegertracing/jaeger/pull/5310/files#diff-c9d6c3 …
=> Fix goroutine leaks in plugin/sampling/strategystore/adaptive

Makefile, plugin/storage/integration/badgerstore_test.go, plugin/storage/integration/cassandra_test.go, plugin/storage/integration/elasticsearch_test.go, plugin/storage/integration/es_index_cleaner_test.go, plugin/storage/integration/es_index_rollover_test.go, plugin/storage/integration/grpc_test.go, plugin/storage/integration/integration.go, plugin/storage/integration/kafka_test.go, plugin/storage/integration/memstore_test.go
- Remove usage of build tags, since they make it mode difficult to compile files in the IDE. 
- Make all tests use `STORAGE` env var
- Pass `testing.T` to functions, simplify error handling
- CI
=> [storage] Simplify integration tests

pkg/cassandra/gocql/testutils/udt_test.go, pkg/testutils/leakcheck_test.go
- The testutils package itself was being flagged as missing goleak check. The check was there, but without the package name, and the lint script was flagging it as false positive.
- Similar issue in `pkg/cassandra/gocql/testutils`
1. Change package name of the test file so that the functions can be called with the usual package package name `testutils`.
2. change competing `testutils` import labels to satisfy the linter
- `make goleak` no longer shows this package
=> Fix false positive goleak test

scripts/check-goleak-files.sh
- We have only two packages remaining without goroutine leak checks, both integration tests, which are being worked on
- Meanwhile new code / packages do not benefit from enforcement of goleak checks because the linter does not fail CI
- Add the two remaining packages into exclusion list and force a failure of the CI if anything else is missing goleak checks
Successful exit:
```shell
$ make goleak
Verifying that all packages with tests have goleak in their TestMain
🔴 Error(check-goleak): no goleak check in package ./cmd/jaeger/internal/integration/
this package is temporarily allowed and will not cause linter failure
🔴 Error(check-goleak): no goleak check in package ./plugin/storage/integration/
this package is temporarily allowed and will not cause linter failure
🐞 …
```
=> Allow go-leak linter to fail CI

cmd/jaeger/internal/integration/grpc_test.go, plugin/storage/integration/badgerstore_test.go, plugin/storage/integration/cassandra_test.go, plugin/storage/integration/elasticsearch_test.go, plugin/storage/integration/grpc_test.go, plugin/storage/integration/integration.go, plugin/storage/integration/kafka_test.go, plugin/storage/integration/memstore_test.go
- Refresh was only used by Elasticsearch tests, and required too many low-level clients to do correctly.
- Meanwhile, since all the tests are using waitForCondition checks, forcing a refresh isn't necessary, the test will simply wait for ES background indexing to finish
- Remove Refresh as a concept from integration tests
- CI
=> [storage integration tests] Remove Refresh

plugin/storage/grpc/options.go
- Fixes a misspelling of `remote` in a log message 
- Change `reomte` to `remote`
- 
=> Fix the spelling of `remote` in log message

CODE_OF_CONDUCT.md, GOVERNANCE.md, MAINTAINERS.md
Only changes in md for this one
Adding MAINTAINERS.md, and fixing a 404 in GOVERNANCE.md
Fixing CODE_OF_CONDUCT per template : https://github.com/cncf/project-template/blob/main/CODE_OF_CONDUCT.md 
Working on : https://github.com/jaegertracing/jaeger/issues/5363
=> Update security files and other governance files for best practices

.github/workflows/ci-label-check.yml, .github/workflows/ci-release.yml, .github/workflows/ci-unit-tests-go-tip.yml, .github/workflows/ci-unit-tests.yml
This attempts to solve the following issue with our security rating around token permissions on the scorecard : https://securityscorecards.dev/viewer/?uri=github.com/jaegertracing/jaeger
Part of https://github.com/jaegertracing/jaeger/issues/5363
Moving write permissions into the jobs 
It will be tested after the PR is submitted as the jobs do not fully run on my fork.
- [NA] I have added unit tests for the new functionality
- [NA] I have run lint and test steps successfully
=> Moving global write permissions down into the CI jobs

README.md
Improvements for https://github.com/jaegertracing/jaeger/issues/5363 
I have fixed the variables for the badge management and also added our badge for CLOMontior which is what the CNCF seems to be using most often.
Viewed the README.md and badges
- [NA] I have added unit tests for the new functionality
- [NA] I have run lint and test steps successfully
=> Fixing up README badges and adding CLOMonitor

cmd/ingester/app/builder/builder.go, pkg/config/tlscfg/options.go, storage/spanstore/downsampling_writer_test.go
RackID option was exposed in [this](https://github.com/jaegertracing/jaeger/pull/3395) PR but it was not properly parsed from passed flags and set on Sarama client
- configures Parsed RackID on ConsumerConfig
- Fix failing lint issues
- Tested by printing the config passed to sarama client
=> [bug-kafka-consumer] set the passedin rackid in consumer config

plugin/storage/es/factory.go, plugin/storage/es/factory_test.go, plugin/storage/es/samplingstore/storage.go, plugin/storage/es/samplingstore/storage_test.go, plugin/storage/integration/elasticsearch_test.go, plugin/storage/integration/integration.go, storage/factory.go
- Resolves #5333
- Create sampling templates when creating sampling store since doing so is intended.
- CI
=> Create sampling templates when creating sampling store

README.md
This adds the artifact hub badge for Jaeger, which will be official once the last PR is pushed from the helm chart repo.
https://github.com/jaegertracing/jaeger/issues/5363
Add new image on README.md
Tested on Github branch
- [NA] I have added unit tests for the new functionality
- [NA] I have run lint and test steps successfully
=> Adding artifacthub badge

cmd/agent/app/reporter/grpc/builder.go, cmd/agent/app/reporter/grpc/builder_test.go
- Part of #5330
- Use grpc.NewClient
- Remove irrelevant tests for connection status
- CI
=> [agent] Use grpc.NewClient

CHANGELOG.md, RELEASE.md
- This is the first jaeger release where Jaeger UI changes are included in the release notes and where we have version parity between the two repos.
=> Prepare releaes 1.57.0

plugin/storage/es/spanstore/writer.go, plugin/storage/es/spanstore/writer_test.go
- The cache was initialized with incorrect parameter, and when I looked around it wasn't even used anywhere
- delete indexCache and indexCacheTTL argument
```
$ go test ./plugin/storage/es/spanstore
ok      github.com/jaegertracing/jaeger/plugin/storage/es/spanstore     0.471s
```
=> [es] Remove unused indexCache

plugin/storage/cassandra/factory.go, plugin/storage/integration/cassandra_test.go
- https://github.com/jaegertracing/jaeger/pull/5398#discussion_r1589755830
- added purge for method for cassandra
- via integration tests
=> Add Purge method for cassandra

cmd/jaeger/internal/extension/remotesampling/README.md
- Previous PR did not include markup and the diagram is not rendering correctly
- Add markup
=> Add missing mermaid markup

.github/workflows/ci-cassandra.yml, .github/workflows/ci-unit-tests.yml
- Noticed the following logs, not sure how it worked (probably default matched the file name)
```
Unexpected input(s) 'file', valid inputs are ['files', 'flags']
```
- Change calls to this action to always specify `files` param
- CI
=> [bug] Fix syntax for invoking upload-codecov action

.codecov.yml, cmd/jaeger/internal/integration/e2e_integration.go
- Resolves #5421
- Instead of throwing binary logs to the parent's output, it now writes the logs to a temp file and only outputs the logs if the test fails. This behavior is similar to the current v1 tests that run `docker logs` if failed.
- Here's the outcome if the test fails.
```
=== NAME  TestGRPCStorage
e2e_integration.go:88: Jaeger-v2 logs:
2024/05/08 00:41:25 application version: git-commit=, git-version=, build-date=
2024-05-08T00:41:25.557+0700	info	service@v0.99.0/service.go:99	Setting up own telemetry...
2024-05-08T00:41:25.557+0700	info	service@v0.99.0/telemetry.go:103	Serving metrics	{"address": ":8888", "level": "Normal"}
2024-05-08T00:41:25.557+0700	info	exporter@v0.99.0/exporter.go:275	Development component. May change in the future.	{"kind": "exporter", "data_type": …
```
=> [v2] Change e2e jaeger-v2 binary log output to temp file

.github/workflows/ci-cassandra.yml, .github/workflows/ci-elasticsearch.yml, .github/workflows/ci-opensearch.yml, scripts/cassandra-integration-test.sh, scripts/es-integration-test.sh
- Helps debugging unstable e2e tests in #5418
- Add more visibility to CI workflows by dumping related storage docker logs if the tests failed.
- Made changes to Cassandra, Elasticsearch, and Opensearch.
- Not tested, unable to test locally.
=> [v2] Dump storage docker logs in Github CI if e2e test failed

cmd/jaeger/internal/integration/badger_test.go, cmd/jaeger/internal/integration/cassandra_test.go, cmd/jaeger/internal/integration/es_test.go, cmd/jaeger/internal/integration/grpc_test.go, cmd/jaeger/internal/integration/os_test.go, plugin/storage/integration/integration.go
- Resolves #5341
- PR #5322 temporarily added a SkipBinaryAttrs flag to avoid checking span's tags with a binary type since the OTEL Jaeger translator has a bug that converts binary tags into string tags. Since it has been fixed, we will delete this flag.
- Delete the SkipBinaryAttrs flag from StorageIntegration.
- Tested locally by running all the e2e storage tests. e.g. `STORAGE=grpc SPAN_STORAGE_TYPE=memory make jaeger-v2-storage-integration-test`
=> [v2] Remove temporary SkipBinaryAttrs flag from e2e tests 

.github/workflows/ci-elasticsearch.yml
- Part of #5439
- Stop running integration tests for Elasticsearch v5/v6
- CI
=> Stop running integration tests for Elasticsearch v5/v6

crossdock/jaeger-docker-compose.yml, docker-compose/kafka/docker-compose.yml, plugin/storage/factory.go, plugin/storage/factory_config.go, plugin/storage/grpc/factory.go, scripts/generate-help-output.sh
- Resolves #4647
- Add new storage type `grpc` and log warning if the old value `grpc-plugin` is used.
- CII
=> Replace grpc-plugin storage type name with just grpc

cmd/jaeger/internal/integration/span_reader.go
- gRPC Dial & DialContext is now deprecated and requires to be replaced with NewClient https://github.com/grpc/grpc-go/blob/master/Documentation/anti-patterns.md#the-wrong-way-grpcdial
- Replaces grpc.DialContext with NewClient at `cmd/jaeger/internal/integration/span_reader.go`
- Run `STORAGE=grpc SPAN_STORAGE_TYPE=memory make jaeger-v2-storage-integration-test` locally.
=> [v2] Replace e2e span_reader grpc.DialContext with NewClient

cmd/esmapping-generator/app/renderer/render_test.go, plugin/storage/es/dependencystore/storage_test.go, plugin/storage/integration/elasticsearch_test.go, plugin/storage/integration/es_index_rollover_test.go
- Part of  #5439 
- Removed instances of v5/v6 in the tests.
- 
=> Remove elasticsearch v5/v6 from tests

docker/Makefile, docker/base/Dockerfile, docker/debug/Dockerfile, scripts/check-go-version.sh
fixes: #5450
- changed alpine image tag from 3.16 to 3.19.0
- 
=> Fix alpine image to 3.19.0

.github/workflows/ci-lint-checks.yaml, Makefile
Many of GH workflows are logging warnings like this:
```
Run make install-test-tools
fatal: No names found, cannot describe anything.
fatal: No names found, cannot describe anything.
fatal: No names found, cannot describe anything.
fatal: No names found, cannot describe anything.
fatal: No names found, cannot describe anything.
```
This is because we typically do a shallow checkout of the repo without tags.
- Check for shallow checkout and don't run `git describe`
- CI `lint`: no warnings logged when calling `make`
```
$ make echo-version
GIT_CLOSEST_TAG=0.0.0
```
=> Avoid git warnings on shallow checkout

cmd/jaeger/internal/integration/e2e_integration.go, cmd/jaeger/internal/integration/span_reader.go, cmd/jaeger/internal/integration/span_writer.go, plugin/storage/integration/integration.go
- Helps to debug unstable e2e tests in https://github.com/jaegertracing/jaeger/issues/5418
- Current logs are still hard to follow even it already dump storage's docker and OTEL col binary logs because we can't see which part of the test related to which storage docker/ OTEL col binary logs.
- Add more logging to e2e tests that capture the timestamp of each read/write run.
- Run `STORAGE=grpc SPAN_STORAGE_TYPE=memory make jaeger-v2-storage-integration-test`
=> [v2] Add logging to read/write spans in e2e tests

cmd/jaeger/internal/exporters/storageexporter/factory.go, cmd/jaeger/internal/integration/span_writer.go
- Retrying write spans doesn't solve the problem (even though it reduces the failure rates), CI tests are still failing.
- Instead of retrying the requests, we increase the timeout from 5s (default) to 30s
- Run `STORAGE=grpc SPAN_STORAGE_TYPE=memory make jaeger-v2-storage-integration-test` in local.
=> [v2] Remove retries and increase timeout for e2e tests

cmd/jaeger/internal/extension/jaegerquery/server_test.go, cmd/jaeger/internal/integration/e2e_integration.go, cmd/jaeger/internal/integration/span_reader.go, cmd/remote-storage/app/server.go, pkg/testutils/logger.go, plugin/storage/grpc/shared/grpc_handler.go, plugin/storage/integration/badgerstore_test.go, plugin/storage/integration/cassandra_test.go, plugin/storage/integration/elasticsearch_test.go, plugin/storage/integration/grpc_test.go, plugin/storage/integration/integration.go, plugin/storage/integration/kafka_test.go, plugin/storage/integration/remote_memory_storage.go, plugin/storage/integration/trace_compare.go, plugin/storage/integration/trace_compare_test.go
- Remote storage server is missing a gRPC health check, the current use case is for testing environment to check if the gRPC server is ready before run the tests.
- Add "google.golang.org/grpc/health/grpc_health_v1" to remote-storage gRPC server.
- Ping health check for remote storage server before proceeding with tests
- Add deduping of spans by ID when retrieved from storage (when storage is not idempotent)
- Make `testzap` loggers include source file
- Tested with https://github.com/jaegertracing/jaeger/pull/5459 PR.
=> [remote-storage] Add healthcheck to grpc server

cmd/agent/app/reporter/grpc/collector_proxy_test.go, plugin/storage/es/factory_test.go
- Part of #5083
- Added f.close() in TestArhiveEnabled based on https://github.com/jaegertracing/jaeger/issues/5083#issuecomment-1902790414
-  CI workflow
=> fix: Close factory in plugin/storage/es/ test

docker/debug/Dockerfile
- ppc64le was previously excluded because delve did not support it. It does now.
- remove ppc64le exclusion.
- CI
=> Enable debug builds for ppc64le

go.mod
- CVE-2024-24788
- Bump Go version
- CI
=> Bump Go to v1.22.3

.github/workflows/ci-elasticsearch.yml, .github/workflows/ci-opensearch.yml, scripts/es-integration-test.sh
- ES tests are often failing due to v2 tests instability
- One one test fails the other matrix jobs are also cancelled
- Separate v1 and v2 tests into different matrix steps
- Turn off fail-fast to prevent other jobs from being cancelled
- 
=> Split v1 and v2 ES/OS integration tests

docker/debug/Dockerfile
- `ppc64le` was added in #5482, but even though it has been implemented in delve (https://github.com/go-delve/delve/issues/2104), it has not yet been released as of delve@v1.22.1
- since our PR CI does not build all arch, it was not noticed until the CI on the main branch started failing
- Add `ppc64le` back to exclusion list
- only after merging
=> Revert #5482 - ppc64le is not yet supported by delve

plugin/storage/es/README.md
- Resolves #5439  
- Updated documentation to reflect current supported versions (v7 and v8).
- Verified that no references to Elasticsearch v5 and v6 remain in the codebase and documentation.
=> Remove support for Elasticsearch v5 and v6 #5439

plugin/sampling/strategystore/adaptive/processor_test.go
- Test failed with a race condition in an unrelated PR: https://github.com/jaegertracing/jaeger/actions/runs/9307158853/job/25617867008?pr=5496#step:8:196
- Grab the lock before reading fields
```
$ go test -race -count 10 ./plugin/sampling/strategystore/adaptive/
ok  	github.com/jaegertracing/jaeger/plugin/sampling/strategystore/adaptive	1.556s
```
=> [test] Use locks to avoid race condition

.golangci.yml, cmd/agent/app/processors/thrift_processor_test.go, cmd/agent/app/reporter/metrics_test.go, cmd/collector/app/span_processor_test.go, cmd/ingester/app/consumer/consumer.go, cmd/internal/flags/service_test.go, cmd/jaeger/internal/extension/jaegerstorage/extension.go, cmd/query/app/grpc_handler_test.go, cmd/query/app/internal/api_v3/traces.go
- revive is a pretty comprehensive linter that catches many issues
- incidentally, I wanted to have a linter for the change in #5377, but the `errorf` [rule in revive](https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#errorf) is only catching `errors.New(fmt.Sprintf())`, not `fmt.Errorf(just_string)` scenarios.
- add revive to the main list of linters
- disable some of its rules which are currently breaking for future clean-up
- clean-up a few places what had low number of breaks
- `make lint`
=> Enable revive linter

.golangci.yml, cmd/agent/app/reporter/grpc/reporter_test.go, cmd/jaeger/internal/extension/jaegerstorage/config.go, storage/spanstore/downsampling_writer_test.go
- It flags unused nolint directive comments
- Add linter and remove ineffective nolint directives
- `make lint`
=> Add nolintlint linter

.golangci.yml, cmd/collector/app/flags/flags_test.go, cmd/jaeger/internal/integration/e2e_integration.go, cmd/query/app/server_test.go
-  Partial Fix for #5506
- Enabled unexported-naming in revive linter. 
- Changed local variables to start with lowercase letters.
- `make lint` `make test`
=> Enable Lint Rule: unexported-naming

.github/dependabot.yml, .github/workflows/ci-cassandra.yml, docker-compose/cassandra/v3.yaml, docker-compose/cassandra/v4.yaml, scripts/cassandra-integration-test.sh
- https://github.com/jaegertracing/jaeger/issues/5485
- updated `cassaandra-integration-test.sh` to use docker compose 
- update dependabot
- `bash scripts/cassandra-integration-test.sh 3 v003 v1`    ` bash scripts/cassandra-integration-test.sh 3 v003 v2 ` bash `scripts/cassandra-integration-test.sh 4 v004 v1` `scripts/cassandra-integration-test.sh 4 v004 v2`
=> Use docker compose for cassandra integration tests

.github/workflows/ci-lint-checks.yaml, scripts/dco_check.py
- Several PRs are stuck with DCO check pending. Apparently there's an ongoing issue with the DCO app: https://github.com/dcoapp/app/issues/211
- Add an alternative DCO check into the lint workflow using https://github.com/christophebedard/dco-check
Ran the script manually:
```shell
$ python3 scripts/dco_check.py -b main
Detected: git (default)
Checking commits: 5863430fa0c22679ff843abdd717ac8cf8fb6828..7a5e58b97d16f3ea024cb5da23442e6833798429
All good!
```
With an unsigned commit:
```shell
$ gca -m bad
[manual-dco-check 7da95684] bad
1 file changed, 1 insertion(+)
$ python3 scripts/dco_check.py -b main
Detected: git (default)
Checking commits: 5863430fa0c22679ff843abdd717ac8cf8fb6828..7da95684408ebd3f32692e9444940bdf0e04348d
Missing sign-off(s):
7da95684408ebd3f32692e9444940bdf0e04348d
no …
```
=> Add manual DCO check using Python script dco-check

.golangci.yml, model/converter/thrift/zipkin/to_domain.go, pkg/config/tlscfg/options.go, plugin/storage/es/mappings/mapping.go
-  Partial Fix for #5506
- Enabled confusing-results & receiver-naming in revive linter
- Used named outputs when datatype of outputs are same
- Made changes to maintain the same receiver name 
- `make lint` `make test`
=> Enable Lint Rules: confusing-results & receiver-naming

.golangci.yml, pkg/config/tlscfg/options.go, plugin/storage/grpc/shared/grpc_client.go, plugin/storage/grpc/shared/grpc_client_test.go
-  Partial Fix for #5506
- Enabled struct-tag & unexported-return in revive linter
- Only use tags on exported fields
- Converted exported function to have an exported return type
- `make lint` `make test`
-
=> Enable Lint Rules: struct-tag & unexported-return

.github/workflows/ci-all-in-one-build.yml, .github/workflows/ci-docker-build.yml, .github/workflows/ci-release-testing.yml, Makefile, scripts/build-all-in-one-image.sh, scripts/build-upload-docker-images.sh
- Part of #5529. Right now there is no way to test the release workflow outside of actually doing a release.
- Refactor CI scripts for better control of "test runs"
- Add a new release testing workflow that does not attempt to publish artifacts
- CI
=> Add a new workflow for testing the release workflow

cmd/jaeger/internal/command.go, go.mod
Related to https://github.com/open-telemetry/opentelemetry-collector/issues/10290
Updates the `otelcol.CollectorSettings` passed to `otelcol.NewCommand` to include desired providers and converters instead of relying on `otelcol.NewCommand` to provide defaults.
These providers/converters as the exact same being set by defaults [here](https://github.com/open-telemetry/opentelemetry-collector/blob/6888f8f7a45fd6dff4dfc29a82802c95459f619c/otelcol/configprovider.go#L134), which will probably stop getting set in the future.
- unit tests
=> Set desired providers/converters instead of relying on defaults

.github/workflows/ci-elasticsearch.yml, .github/workflows/ci-opensearch.yml, scripts/cassandra-integration-test.sh, scripts/es-integration-test.sh
- https://github.com/jaegertracing/jaeger/issues/5485
- changing how major version is passed eg form 7.x -> 7 
- 
=> changing how major version is passed

.github/dependabot.yml, .github/workflows/validate-dependabot-config.yml
- Per title
- new workflow
- fix existing breaks in the config
- CI
=> Add workflow to validate dependabot config

CHANGELOG.md, RELEASE.md
Depends on https://github.com/jaegertracing/jaeger-ui/pull/2331 
- 
- 
- 
=> Prepare release v1.58.0

scripts/package-deploy.sh
- A bug was introduced in #5501 where the wrong binary path was used 
- Use the right path
- Allow overriding `tar` command since on MacOS the `--sort` option is not supported (so I had to use `gtar` to test)
These steps succeeded locally:
```
$ make build-all-platforms
$ TARCMD=gtar bash scripts/package-deploy.sh
```
=> Fix binary path in package-deploy.sh

.github/dependabot.yml
- The `/` path is invalid since there is no Dockerfile in the root dir. Unfortunately, dependabot fails the whole run on this error, instead of working through all the dirs
- Part of #5552
- Remove invalid path
- Only testable after merge
=> [dependabot config] Remove invalid path

.golangci.yml
- Resolves #5585
Fix new warnings from the `golangci-lint` linter upgrade.
The configuration has been verified with the command `golangci-lint config verify`.
---
These warnings came from: https://github.com/golangci/golangci-lint/blob/master/pkg/config/loader.go#L374
=> Fix new warnings from the linter upgrade

renovate.json
- It turns out by default the Renovate bot does not run `go mod tidy`, so it leaves unused entries in the go.mod/sum files.
- Enable both tidy and upgrading imports on major version changes
- CI
=> Require Renovate bot to run go mod tidy

renovate.json
Updates #5607 to also turn off patches for the e2e test dependencies
Adds "patch" to the matchUpdateTypes array so that Renovatebot will not automate PRs for patches on the e2e test dependencies
Tested in fork and verified it wouldn't apply patches for those specified docker-compose files.
- [ x] I have read https://github.com/jaegertracing/jaeger/blob/master/CONTRIBUTING_GUIDELINES.md
- [ n/a] I have added unit tests for the new functionality
- [ n/a] I have run lint and test steps successfully
=> Update Renovate bot to not apply patches to e2e test dependencies

renovate.json
- OTEL dependencies cannot be updated individually, and too many PRs anyway
- Add groups
=> Group Renovate bot updates

docker-compose/cassandra/v3/docker-compose.yaml, docker-compose/cassandra/v4/docker-compose.yaml, docker-compose/elasticsearch/v7/docker-compose.yml, docker-compose/elasticsearch/v8/docker-compose.yml, docker-compose/kafka-integration-test/docker-compose.yml, docker-compose/monitor/docker-compose.yml, docker-compose/opensearch/v1/docker-compose.yml, docker-compose/opensearch/v2/docker-compose.yml
- Hey, I noticed you have some docker-compose files that are using floating tags to reference images. Pinning images and actions to their commit hash ensures that the same version of the image or action is used every time the workflow runs. This is important for reproducibility and security and it is a [security practice recommended by GitHub](https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#using-third-party-actions).
- The following PR used [frizbee](https://github.com/stacklok/frizbee) CLI to update the docker-compose files and pin the container images referenced by tags to their commit hash.
- 
=> Use image digests for docker-compose files

plugin/metrics/prometheus/metricsstore/dbmodel/to_domain.go, plugin/metrics/prometheus/metricsstore/dbmodel/to_domain_test.go, plugin/metrics/prometheus/metricsstore/reader.go, plugin/metrics/prometheus/metricsstore/reader_test.go
- Resolves #5672
- Due to oversight, a bug was introduced in #5539 which changed the attribute name expected by the UI from `operation` to `span_name`
- Revert those changes
`(cd docker-compose/monitor/ && make build dev)`
=> Restore "operation" name in the metrics response

cmd/internal/flags/flags.go, cmd/internal/flags/service.go, pkg/es/config/config.go
- Part of #5290
- It's difficult to troubleshoot ES queries because logs are always written in JSON format, so the ES req/resp JSON is being escaped.
- Add `--log-encoding` option to allow changing logs to plain text (console).
- Fix logger initialization for ES to reuse the existing logger instead of creating a new one (new one was switching back to JSON)
```
$ SPAN_STORAGE_TYPE=elasticsearch go run -tags=ui ./cmd/all-in-one --es.log-level=debug --log-encoding=console
```
A query is logged like this:
```
2024-06-22T22:56:34.272-0400	info	elastic@v6.2.37+incompatible/client.go:835	GET /_msearch?rest_total_hits_as_int=true HTTP/1.1
Host: 127.0.0.1:9200
User-Agent: elastic/6.2.37 (darwin-arm64)
Content-Length: 310
Accept: application/json
Content-Type: application/json
Accept-Encoding: gzip …
```
=> Add better logging options

cmd/jaeger/config-badger.yaml, cmd/jaeger/config-cassandra.yaml, cmd/jaeger/config-elasticsearch.yaml, cmd/jaeger/config-opensearch.yaml, cmd/jaeger/config-remote-storage.yaml, cmd/jaeger/internal/all-in-one.yaml, cmd/jaeger/internal/exporters/storageexporter/exporter_test.go, cmd/jaeger/internal/extension/jaegerstorage/config.go, cmd/jaeger/internal/extension/jaegerstorage/config_test.go, cmd/jaeger/internal/extension/jaegerstorage/extension.go, cmd/jaeger/internal/extension/jaegerstorage/extension_test.go, pkg/cassandra/config/config.go, plugin/storage/badger/options.go, plugin/storage/cassandra/factory.go, plugin/storage/cassandra/factory_test.go, plugin/storage/cassandra/options.go, plugin/storage/es/factory.go, plugin/storage/es/options.go, plugin/storage/grpc/config.go, plugin/storage/grpc/config_test.go
- Many OTEL Collector components provide default configs such that users do not need to provide most settings.
- However, due to our organization of the storage extension config, there was no way to provide defaults
- 🛑 **breaking**  Change the main config inside out: instead of static separation by storage types followed by a map of custom names, move the map to the top level followed by static separation by storage type. E.g.
```yaml
memory:
some_storage:
max_traces: 100000
backends:
some_storage:
memory:
max_traces: 100000
```
- This required an introduction of an extra nesting via `backends`, which is a bit unfortunate, but the OTEL framework requires config to be a struct, it did not work with a map at the top level. Having a struct might actually be beneficial in the future if we …
=> Support default configs for storage backends

.github/workflows/ci-elasticsearch.yml, .github/workflows/ci-lint-shell-scripts.yml, .github/workflows/ci-opensearch.yml, cmd/jaeger/internal/integration/e2e_integration.go, cmd/jaeger/internal/integration/e2e_integration_test.go, scripts/es-integration-test.sh
- There is a typo in the test script that means v2 test was never executed: https://github.com/jaegertracing/jaeger/blob/7b7e5ccb8ecb3a66ea3a6b06ecca63bff97897e9/scripts/es-integration-test.sh#L102-L103
- Even with the typo fixed the way the configs are parsed in the e2e tests (in order to add a storage cleaner extension) did not match the recent config changes (which would've caught the issue if not for the typo above).
- Fix typo. Expand usage printout to illustrate expected argument values
- Fix config parsing to reflect the new structure.
- Added unit test for config parsing, made sure it's successful
- CI shows v2 test is being executed https://github.com/jaegertracing/jaeger/actions/runs/9830991980/job/27137813884?pr=5716#step:8:230
```
T23:12:04 make …
```
=> [bug] Use correct argument as jaeger-version

cmd/tracegen/main.go, go.mod, go.sum, scripts/adaptive-sampling-integration-test.sh
- Part of #5717
- Add a new flag to tracegen to allow it to use `jaegerremotesampling` contrib module with OTEL SDK
- It's not actually working at the moment, the backend does not recognize the spans without sampling tags
=> [tracegen] Allow use of adaptive sampling

CHANGELOG.md, RELEASE.md
Prepares Jaeger for the 1.59.0 release. Updates changelog, jaeger-ui and rotates release managers.
=> Prepare release v1.59.0

cmd/jaeger/internal/integration/storagecleaner/README.md, docker-compose/monitor/README.md, examples/hotrod/docker-compose.yml
- HotROD demo stopped working. Since v0.105 the OTEL Collector components default hostname to 'localhost. However, that does not work inside a Docker container (at least on MacOS & Docker Desktop).
- Make OTLP receivers listen on all IPs (0.0.0.0)
- Unrelated, but added a mermaid diagram for SPM, as I needed it for the slides for a presentation
- Go through HotROD demo workflow
=> [hotrod] Fix connectivity in docker compose

renovate.json
- Patch upgrades for GH actions are unnecessary noise
- Restrict updates to major/minor only
=> Block patch upgrades for GH actions

cmd/collector/app/flags/flags.go, cmd/collector/app/server/grpc_test.go, cmd/jaeger/internal/extension/jaegerquery/config.go, cmd/jaeger/internal/extension/jaegerquery/factory.go, cmd/jaeger/internal/extension/jaegerquery/server.go, cmd/jaeger/internal/extension/jaegerquery/server_test.go, cmd/query/app/handler_archive_test.go, cmd/query/app/handler_deps_test.go, cmd/query/app/http_handler_test.go, cmd/query/app/query_parser_test.go, cmd/query/app/server.go, cmd/query/app/server_test.go, cmd/remote-storage/app/server_test.go, examples/hotrod/docker-compose.yml, internal/grpctest/reflection.go, internal/grpctest/reflection_test.go
- Resolves #5737
- Revert #5734
- Default OTLP receiver endpoints to `:port` instead of relying on OTEL Collector defaults
- Clean up tests to use ephemeral ports when possible
- Tested similar to #5734 by using `COLLECTOR_OTLP_HTTP_HOST_PORT=:4318`
=> Make OTLP receiver listen on all IPs again

plugin/storage/factory.go, plugin/storage/factory_config.go
- Last part of #4647
- In accordance with our deprecation policy, this CLI value can be removed in v1.60 (next release)
- No longer accept `grpc-plugin` as a storage type. The valid value is `grpc`.
=> Completely remove "grpc-plugin" as storage type

cmd/query/app/server_test.go, ports/ports.go, ports/ports_test.go
- Remove function that is no longer needed
=> Remove not needed GetAddressFromCLIOptions

cmd/jaeger/internal/exporters/storageexporter/exporter_test.go, cmd/jaeger/internal/extension/jaegerquery/server_test.go, cmd/jaeger/internal/extension/jaegerstorage/extension_test.go, cmd/jaeger/internal/processors/adaptivesampling/processor_test.go
=> [cleanup] Use storagetest.NewStorageHost() from contrib

.github/workflows/ci-e2e-memory.yaml, cmd/jaeger/internal/integration/e2e_integration.go, cmd/jaeger/internal/integration/elasticsearch_test.go, cmd/jaeger/internal/integration/memory_test.go, cmd/jaeger/internal/integration/opensearch_test.go, cmd/jaeger/internal/integration/storagecleaner/extension.go, cmd/jaeger/internal/integration/storagecleaner/extension_test.go, plugin/storage/memory/factory.go, plugin/storage/memory/memory.go
- Even though we were using memory storage in v2-e2e-grpc test, we never had an e2e that would validate `cmd/jaeger/config.yaml` config, which uses memory storage in-process
- Add the new test workflow an e2e test
- Rename other test files for more readable file names / test names
- build cmd/jaeger binary
- `$ STORAGE=memory go test ./cmd/jaeger/internal/integration`
=> [v2] Add e2e test with memory store

scripts/spm-integration-test.sh
- Makes sure the SPM CI doesn't fail if the first value received is zero.
- The script now waits until the threshold (Currently set to 3) number of zero values are received before throwing an error
- Manually
=> Add a threshold for expected zero values in the SPM script

examples/hotrod/cmd/root.go
- Resolves #5759 
- Invoke mapping function (which takes logger) after the logger is initialized
- It is safe to do because none of the env vars control the logic for logger initialization
- `$ JAEGER_AGENT_PORT=xyz go run ./examples/hotrod  all`
- Before the change this command would cause a panic
=> [bug] [hotrod] Delay env var mapping until logger is initialized

scripts/hotrod-integration-test.sh
- Fixes a bug introduced in https://github.com/jaegertracing/jaeger/pull/5740/files#r1683565379
- Continue the script on successful test
- Publish the image at the end
- CI
=> Ensure hotrod image is published at the end of e2e test

.github/workflows/ci-docker-hotrod.yml, scripts/hotrod-integration-test.sh
- Resolves #5743 
- Similar to the functionality we have for all-in-one image I tried to achieve same build configuration supported by corresponding script file.
=> Skip building HotROD for all platforms for pull requests

CHANGELOG.md
- Reflect breaking change #5737 in the changelog
=> Update changelog with breaking change

pkg/discovery/grpcresolver/grpc_resolver_test.go
Previously there was no sleep when `testc.EmptyCall` returned an error, so it was easy to blow throw 3000 attempts with no sleep whatsoever.
Sleep at the beginning of call iterations (except the first one).
It no longer fails in our internal aarch64 CI with this patch.
=> Fix grpc tests sleep between connections

README.md, cmd/jaeger/README.md, examples/hotrod/README.md, examples/hotrod/docker-compose-v2.yml
* add reference to the blog post to the main README
* add reference to v2 instructions to HotROD README
* create `examples/hotrod/docker-compose-v2.yml` to run with v2
* add "Try it out" section to `cmd/jaeger/README.md`
=> Add references to Jaeger v2

.github/workflows/ci-lint-shell-scripts.yml, scripts/compute-tags.sh, scripts/compute-tags.test.sh
- To address #5721, add unit tests first
- Add unit tests and call them from scripts linting workflow
- Minor refactoring of `scripts/compute-tags.sh` to make it easier to read
```
$ GREP=ggrep SHUNIT2=/Users/ysh/dev/shunit2 bash scripts/compute-tags.test.sh
testRequireImageName
testRequireBranch
testRequireGithubSha
testRandomBranch
Actual: --tag docker.io/foo/bar --tag quay.io/foo/bar --tag docker.io/foo/bar:latest --tag quay.io/foo/bar:latest --tag docker.io/foo/bar-snapshot:sha --tag quay.io/foo/bar-snapshot:sha --tag docker.io/foo/bar-snapshot:latest --tag quay.io/foo/bar-snapshot:latest
checking foo/bar
checking foo/bar:latest
checking foo/bar-snapshot:sha
checking foo/bar-snapshot:latest
testMainBranch
Actual: --tag docker.io/foo/bar --tag quay.io/foo/bar --tag …
```
=> Add unit tests for scripts/compute-tags.sh

scripts/compute-tags.sh, scripts/compute-tags.test.sh
- Resolves #5721
- Stacked after #5780
- Do not add `latest` tag when on the `main` branch
- Do add `latest` when on a semver tag
- unit tests
=> Only attach :latest tag to versioned images from main

scripts/compute-tags.sh, scripts/compute-tags.test.sh
- Resolves #5721
- The previous PR #5781 didn't quite work because we were still applying tags like `--tag docker.io/foo/bar` (without a version), which evidently leads Docker to treat them as `:latest`, which is exactly what we are trying to avoid for `main` branch
- Remove usage of no-version tags `--tag docker.io/foo/bar`  completely
- Fix unit tests, make them stricter
- Unit tests
=> Do not use image tag without version

.github/workflows/ci-e2e-kafka.yml, cmd/jaeger/collector-with-kafka.yaml, cmd/jaeger/internal/integration/e2e_integration.go, cmd/jaeger/internal/integration/kafka_test.go, scripts/kafka-integration-test.sh
- Update v2 e2e integration tests scripts for kafka
- Update v2 gh workflows for kafka
=> Run v2 e2e integration tests for Kafka

.github/workflows/codeql.yml
- Renovate bot does not upgrade these because the main branch there is on v2
- Code scanning does not need to be locked down as strictly as reproducible builds
- Use v3 instead of exact commit or exact semver
- The logs still show the exact version used, e.g. `CODEQL_ACTION_VERSION: 3.25.15`
- CI
=> Unpin codeql actions

.github/workflows/ci-docker-all-in-one.yml, cmd/all-in-one/all_in_one_test.go, cmd/jaeger/Dockerfile, cmd/jaeger/internal/all-in-one.yaml, cmd/jaeger/internal/extension/remotesampling/extension.go, cmd/jaeger/internal/extension/remotesampling/factory.go, cmd/jaeger/sampling-strategies.json, scripts/build-all-in-one-image.sh
- Resolves #5531
- Enable remote sampling extension in v2 all-in-one configuration
- Fix Dockerfile to copy this into the image in the appropriate location
- Change the default ports for the extension to match OTEL & agent 5778/5779
- Re-enable sampling e2e tests for v2 all-in-one
- `make all-in-one-integration-test`
- CI
=> [v2] Enable remote sampling extension and include in e2e tests

CHANGELOG.md, RELEASE.md
Prepares Jaeger for the 1.60.0 release. Updates changelog, jaeger-ui and rotates release managers.
=> Prepare release v1.60.0

.codecov.yml
We are now running 19 different uploads of codecov
However, the current configuration was only waiting for 11, which resulted in false positives like this:
I.e. a comment about non-covered code which is actually covered, but its result uploads came after the 11 other results.
- Bump expected count to 19, the current number of distinct flags/uploads.
=> Update expected codecov flags count to 19

pkg/es/config/config_test.go
partially fixes: #5068 
- This commit adds tests for the `pkg/es/config` package.
- `make test`
=> Added unit tests in pkg/es/config

RELEASE.md
Just improving the docs a bit to make sure the release manager does the Jaeger UI before the rest of the directions.
=> Clarify release docs slightly

cmd/tracegen/docker-compose.yml, crossdock/docker-compose.yml, crossdock/jaeger-docker-compose.yml, docker-compose/cassandra/v3/docker-compose.yaml, docker-compose/cassandra/v4/docker-compose.yaml, docker-compose/elasticsearch/v6/docker-compose.yml, docker-compose/elasticsearch/v7/docker-compose.yml, docker-compose/elasticsearch/v8/docker-compose.yml, docker-compose/jaeger-docker-compose.yml, docker-compose/kafka-integration-test/docker-compose.yml, docker-compose/kafka/docker-compose.yml, docker-compose/monitor/docker-compose-v2.yml, docker-compose/monitor/docker-compose.yml, docker-compose/opensearch/v1/docker-compose.yml, docker-compose/opensearch/v2/docker-compose.yml, examples/grafana-integration/docker-compose.yaml, examples/hotrod/docker-compose-v2.yml, examples/hotrod/docker-compose.yml, examples/reverse-proxy/docker-compose.yml
- As the latest updates in docker compose has deprecated the 'version' tag.This Pr aims to cleanup the version tags in the various docker-compose files so as to cleanup the log currently displaying ```'version' is obselete ``` when we run a docker-compose file.
- [ :white_check_mark: ] I have read https://github.com/jaegertracing/jaeger/blob/master/CONTRIBUTING_GUIDELINES.md
- [ :white_check_mark:  ] I have signed all commits
- [ :x:] I have added unit tests for the new functionality
- [ :white_check_mark: ] I have run lint and test steps successfully
=> Clean up obselete 'version' tag from docker-compose files

scripts/check-go-version.sh
Resolves #5845 
- check for the manual patch in docker file and notifies
=> Require manual Go version updates for patch versions

.golangci.yml, cmd/agent/app/configmanager/grpc/manager_test.go, plugin/sampling/strategyprovider/static/provider.go
- Partial Fix for https://github.com/jaegertracing/jaeger/issues/5506
- Enabled redefines-builtin-id in revive linter. Replaced function name which redefinition of the built-in function 
- make lint make test
=> Enable Lint Rule: redefines-builtin-id

.github/workflows/ci-lint-checks.yaml, .github/workflows/ci-lint-dependabot-config.yml
fixed the pinned dependencies issue reported by [scorecard](https://scorecard.dev/viewer/?uri=github.com/jaegertracing/jaeger).
Part of  #5815 
- pinned the github actions by hash.
- 
=> Pin GitHub Actions dependencies

.github/workflows/ci-e2e-kafka.yml, scripts/kafka-integration-test.sh
- Add Kafka service logging before shutdown in Kafka integration test script
=> [fix] Print Kafka logs on test failure

.github/workflows/ci-lint-dependabot-config.yml
- Related to #5815
- Define contents permissions on "dependabot validate" workflow
- Was done with the help of https://app.stepsecurity.io/secureworkflow
- 
=> Define contents permissions on "dependabot validate" workflow

plugin/storage/grpc/config.go, plugin/storage/grpc/config_test.go, plugin/storage/grpc/factory.go, plugin/storage/grpc/factory_test.go, plugin/storage/grpc/options_test.go
- Config.go contained business logic that belongs to the factory
- move logic to factory
- add unit tests for 100% coverage
- CI
=> Clean up gRPC storage config

cmd/es-index-cleaner/README.md, plugin/storage/es/README.md
esCleaner.py no longer exists, but README.md still has the relevant content, so I've made some adjustments.
=> Remove the description of esCleaner.py from plugin/storage/es/README.md

.github/workflows/ci-docker-hotrod.yml, .github/workflows/ci-e2e-cassandra.yml, .github/workflows/ci-e2e-elasticsearch.yml, .github/workflows/ci-e2e-opensearch.yml, scripts/es-integration-test.sh, scripts/hotrod-integration-test.sh
Resolves #5912 
- Removed the log dumps in the CI workflow files and replace them with log dumps in the script files
- I ran the scripts locally and deliberately made them fail to ensure that the logs get printed. I also checked that the logs don't get printed when the scripts pass.
=> Fix Integration Test Log Dumping For Storage Backends

plugin/storage/memory/config.go, plugin/storage/memory/config_test.go
- Resolves #5923
- Implemented `Validate` method for `Configuration` struct for memory storage 
- Created [migration doc](https://docs.google.com/document/d/1w3z2hhxXAMLbuWsyyigUUMNSfflw4uayUERqHf45Dks/edit?usp=sharing) from v1 to v2 
- Added unit tests for the new method
=> [jaeger-v2] Add validation and comments to memory storage config (#5925)

.github/workflows/ci-build-binaries.yml, Makefile.BuildBinaries.mk, Makefile.Crossdock.mk, scripts/build-all-in-one-image.sh, scripts/build-upload-docker-images.sh, scripts/cassandra-integration-test.sh, scripts/es-integration-test.sh, scripts/kafka-integration-test.sh, scripts/package-deploy.sh, scripts/platforms-to-gh-matrix.sh
- Part of #5889
- `build-binaries-***` Makefile targets sometimes include os-arch, sometimes just os, sometimes just arch - it's a mess
- normalize all targets to be `build-binaries-$os-$arch`
- change `ci-build-binaries.yml` workflow to use `make echo-platforms` for the jobs matrix
- ci
=> Normalize build-binaries targets

plugin/storage/badger/dependencystore/storage_test.go, plugin/storage/badger/factory.go, plugin/storage/badger/options.go, plugin/storage/badger/options_test.go, plugin/storage/badger/spanstore/read_write_test.go, plugin/storage/badger/stats_linux_test.go, plugin/storage/badger/stats_test.go
- NamespaceConfig had a private `namespace` field which is not necessary
- Part of #5926
- Remove the field, clean up the tests
- CI
=> Remove unused "namespace" field from Badger config

cmd/jaeger/internal/extension/jaegerstorage/config.go, cmd/jaeger/internal/extension/jaegerstorage/extension_test.go, plugin/storage/badger/config.go, plugin/storage/badger/config_test.go, plugin/storage/badger/dependencystore/storage_test.go, plugin/storage/badger/factory.go, plugin/storage/badger/factory_test.go, plugin/storage/badger/options.go, plugin/storage/badger/options_test.go, plugin/storage/badger/spanstore/read_write_test.go, plugin/storage/badger/stats_linux.go, plugin/storage/badger/stats_linux_test.go, plugin/storage/badger/stats_test.go, plugin/storage/integration/badgerstore_test.go
- Part of #5926
- Removed the `Options` struct and renamed `NamespaceConfig` to `Namespace` for Badger Storage 
- Moved v2-related configuration items to `config.go` while leaving v1 cli flags in `options.go`
- CI
=> [jaeger-v2] Consolidate Options And NamespaceConfig For Badger Storage

cmd/jaeger/internal/processors/adaptivesampling/processor.go, plugin/sampling/strategyprovider/adaptive/aggregator.go, plugin/sampling/strategyprovider/adaptive/aggregator_test.go
- The function was a duplicate of another public method
- Remove the function and redirect callsites to invoke HandleRootSpan instead
- CI
=> [adaptive processor] Remove redundant function

plugin/sampling/strategyprovider/adaptive/aggregator.go, plugin/sampling/strategyprovider/adaptive/post_aggregator.go, plugin/sampling/strategyprovider/adaptive/post_aggregator_test.go, plugin/sampling/strategyprovider/adaptive/provider.go, plugin/sampling/strategyprovider/adaptive/provider_test.go
- Previous refactoring left the code in a mixed up state
- move provider / aggregator / post-aggregator into separate files named accordingly
- do the same for tests
- no actual code changes, just moving code around
- CI
=> [adaptive sampling] Clean-up after previous refactoring

.golangci.yml, cmd/collector/app/handler/grpc_handler_test.go, cmd/query/app/handler_archive_test.go
- Resolves #5972 
- Changed the loopvar linter to copyloopvar.
- 
=> Replace loopvar linter

.github/workflows/ci-docker-all-in-one.yml, .github/workflows/ci-release.yml, scripts/build-all-in-one-image.sh, scripts/build-hotrod-image.sh, scripts/build-upload-a-docker-image.sh, scripts/build-upload-docker-images.sh, scripts/compute-tags.sh, scripts/compute-tags.test.sh, scripts/compute-version.sh
- Part of #5889
- simplify all-in-one publishing by minimizing number of parameters passed from workflow (v1/v2 only instead of binary name and healthcheck flag - those are now set inside the script)
- implement overwrite `-o` flag in docker scripts to avoid accidental overriding of numbered releases
- simplify flags management in docker scripts via FLAGS array instead of individual variables
- fix base image building to respect selected platforms (by default it was building all)
- allow `scripts/compute-version.sh` to accept semver with `-rcN` suffix
- CI
- ran publish-release workflow manually https://github.com/jaegertracing/jaeger/actions/runs/10865002272/job/30150937690
=> Enable publishing of versioned jaeger-v2 artifacts

scripts/build-upload-a-docker-image.sh
- Release attempt did not publish v2 image 
```
[[ v2.0.0-rc1 =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]
+ echo 'skipping docker images upload, because not on tagged release or main branch'
```
- Fix the regex to include -rc suffix
- CI
=> Fix regex for publishing v2 image

cmd/jaeger/internal/all-in-one.yaml, cmd/jaeger/internal/components.go, cmd/jaeger/internal/extension/expvar/README.md, cmd/jaeger/internal/extension/expvar/config.go, cmd/jaeger/internal/extension/expvar/config_test.go, cmd/jaeger/internal/extension/expvar/extension.go, cmd/jaeger/internal/extension/expvar/extension_test.go, cmd/jaeger/internal/extension/expvar/factory.go, cmd/jaeger/internal/extension/expvar/factory_test.go, cmd/jaeger/internal/extension/expvar/package_test.go
- Some internal components expose their state via expvar, but OTEL collector does not expose expvar handler
- Create a temporary extension until [upstream ticket](https://github.com/open-telemetry/opentelemetry-collector/issues/11081) is resolved.
```
$ go run ./cmd/jaeger
$ curl http://localhost:27777/
{
"badger_compaction_current_num_lsm": 0,
"badger_get_num_lsm": {},
"badger_get_num_memtable": 0,
"badger_get_num_user": 0,
...
```
=> [v2] Add temporary expvar extension

.golangci.yml, cmd/agent/app/configmanager/grpc/manager_test.go, cmd/agent/app/reporter/grpc/collector_proxy_test.go, cmd/agent/app/servers/thriftudp/transport_test.go, cmd/agent/app/testutils/mock_grpc_collector.go, cmd/anonymizer/app/query/query_test.go, cmd/collector/app/handler/grpc_handler_test.go, cmd/query/app/apiv3/grpc_handler_test.go, cmd/query/app/grpc_handler_test.go, internal/grpctest/reflection_test.go, pkg/es/client/index_client_test.go, pkg/es/config/config_test.go, pkg/hostname/hostname_test.go, plugin/metrics/prometheus/metricsstore/reader_test.go, plugin/storage/es/factory_test.go
- Apply go-require rule of testifylint
-  More appropriate testify API with clearer failure message.
- CI 
=> testifylint: enable go-require

cmd/jaeger/internal/extension/jaegerquery/config.go, cmd/jaeger/internal/extension/jaegerquery/factory.go, cmd/jaeger/internal/extension/jaegerquery/server.go, cmd/query/app/additional_headers_handler.go, cmd/query/app/additional_headers_test.go, cmd/query/app/flags.go, cmd/query/app/flags_test.go, cmd/query/app/server.go, cmd/query/app/server_test.go, cmd/query/app/static_handler_test.go, cmd/query/app/token_propagation_test.go, pkg/config/tlscfg/options.go, pkg/config/tlscfg/options_test.go
- Part of #5996
- Removed the custom TLS and HTTP server configurations and replaced them with OTEL's configurations
- 🛑 Breaking change: the hot-reload of certificates will not happen at `reload_interval`s rather than immediately on file changes. This makes Jaeger's behavior similar to OTEL Collector's behavior.
- Unit tests / CI
=> [query] Change HTTP and TLS server configurations to use OTEL configurations

cmd/jaeger/config-kafka-collector.yaml, cmd/jaeger/config-kafka-ingester.yaml, cmd/jaeger/internal/integration/e2e_integration.go, cmd/jaeger/internal/integration/kafka_test.go
- Resolves #6027 
- Leverages the functionality added in https://github.com/open-telemetry/opentelemetry-collector/issues/5228 to remove the logic for rewriting the config and simply setting an environment variable for the Kafka integration tests.
- The change is to an integration test so the CI passing is a good test for this change
=> [jaeger-v2] Use environment variables in Kafka config

cmd/jaeger/internal/extension/jaegerstorage/config.go, cmd/jaeger/internal/extension/jaegerstorage/extension_test.go, plugin/storage/grpc/config.go, plugin/storage/grpc/config_test.go, plugin/storage/grpc/factory.go, plugin/storage/grpc/factory_test.go, plugin/storage/grpc/options.go, plugin/storage/grpc/options_test.go
- Resolves #6041
- We were currently maintaining two entirely separate configurations for v1 and v2 for the GRPC Storage Component and were initializing v1 configurations and then translating them to the v2 configurations which were the ones actually being used. This caused an issue where one configuration field was left out of the translation method (see https://github.com/jaegertracing/jaeger/pull/6030 for more details). 
- In this PR, we consolidate the v1 and v2 configurations into a single config type that is directly initialized to avoid having configurations that diverge or running into issues like the one described above.
- Unit tests were updated
- Integration tests were not touched but should still pass since this was just an internal change and the interface was not touched
- …
=> [jaeger-v2] Consolidate v1 and v2 Configurations for GRPC Storage

cmd/jaeger/internal/components.go, go.mod, go.sum
- Part of #6040
- Added the [attributesprocessor](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/processor/attributesprocessor/README.md) to the Jaeger V2 binary to replace `--collector.tags`. See the [migration guide](https://docs.google.com/document/d/18B1yTMewRft2N0nW9K-ecVRTt5VaNgnrPTW1eL236t4/edit?usp=sharing) for more details. 
- 
=> [jaeger-v2] Add Attributes Processor to Binary

plugin/storage/cassandra/factory.go, plugin/storage/cassandra/savetracetest/main.go, plugin/storage/cassandra/spanstore/operation_names.go, plugin/storage/cassandra/spanstore/operation_names_test.go, plugin/storage/cassandra/spanstore/reader.go, plugin/storage/cassandra/spanstore/reader_test.go, plugin/storage/cassandra/spanstore/writer.go, plugin/storage/cassandra/spanstore/writer_test.go
- Resolves #432 
- https://github.com/jaegertracing/jaeger/issues/432#issuecomment-2259968427
The current [operation names table check logic](https://github.com/jaegertracing/jaeger/blob/main/plugin/storage/cassandra/spanstore/operation_names.go#L97-L99) creates `OperationNamesStorage` instance pointing to old schema table in case of issues with Cassandra.  
- Check for the existence of old schema table before fallback
- Make `OperationNamesStorage`  constructor `NewOperationsStorage` to return `error` if both old and new tables doesn't exist or both of their existence cannot be checked. Since there was no `error` returned from `NewOperationsStorage` earlier had to update the dependencies and handle the `error` accordingly.
- Ran all tests
- Ran all-in-one and checked if traces are …
=> [cassandra] Prevent fallback to old schema for operation names table in case of db issues

cmd/jaeger/internal/exporters/storageexporter/config.go, cmd/jaeger/internal/exporters/storageexporter/factory.go
- Towards #6040
- Added the `sending_queue` configuration to `jaeger_storage_exporter`  from`exporterhelper` which will allow for enabling a queue when writing spans to any backend store.
- This will allow for achieving parity in jaeger-v2 with the v1 collector's `--collector.queue-size` flag as `sending_queue` has a configuration for `queue_size`.
- [Migration guide](https://docs.google.com/document/d/18B1yTMewRft2N0nW9K-ecVRTt5VaNgnrPTW1eL236t4/edit?usp=sharing) updated for the mapping between v1 and v2
- 
=> [jaeger-v2] Enable queueing configuration in storage exporter

scripts/rebuild-ui.sh
- Resolves #6097
- run `git fetch --unshallow` only on shallow repos
- 
=> Fix rebuild-ui.sh script

pkg/es/config/config.go
- Part of #6059
- Added some remaining documentation to the ElasticSearch configuration that was left over from #6090
- CI
=> [chore][docs] Add documentation to ElasticSearch configuration

GOVERNANCE.md
- The existing process requires the use of the mailing list for nominations, but we don't use that list very much
- It also requires disclosing the email address
- Allow using GitHub issue as alternative to the mailing list
- Do not require disclosure of the email address
=> Update maintainer nomination process

pkg/es/config/config.go
=> [v2] Add ES config comments

cmd/query/app/server.go
- Towards #6026 
- Fixes an issue from https://github.com/jaegertracing/jaeger/pull/6055 where the condition for routing to the legacy implementation was accidentally flipped. 
- CI
=> [fix][query] Correct query server legacy condition

scripts/build-upload-a-docker-image.sh, scripts/upload-docker-readme.sh, scripts/upload-docker-readme.test.sh
Fixes: #3842 
- Added a shell script that publishes README.md files along with docker images to docker hub
- Locally as well as on fork
=> feat: automatically publish readme to docker hub

cmd/jaeger/internal/integration/grpc_test.go, plugin/storage/grpc/factory.go, plugin/storage/grpc/factory_test.go, plugin/storage/grpc/shared/grpc_client.go, plugin/storage/grpc/shared/grpc_client_test.go
- Fixes #5971 
- Towards #6113 and #5859
- This PR fixes an issue where the GRPC remote storage client was provided a tracer which was resulting in an infinite loop of trace generation. This infinite loop would happen when we would try to write a trace to storage which would generate a new trace that needed to be written and so on. This PR provides a fix for this by using a noop tracer for the writer clients so that we do not generate traces on the write paths but still do so when reading. 
- This is likely just a temporary fix and we'll want to monitor https://github.com/open-telemetry/opentelemetry-collector/issues/10663 for a better long-term fix.
- Added the healthcheck endpoint which was previously failing in #6113.
- for `jaeger-ui`: `yarn lint` and …
=> [fix][grpc] Disable tracing in grpc storage writer clients

cmd/query/app/apiv3/gateway_test.go, cmd/query/app/apiv3/http_gateway.go, cmd/query/app/apiv3/http_gateway_test.go, cmd/query/app/http_handler.go, cmd/query/app/http_handler_test.go, cmd/query/app/server.go
- Prequel for #6121
- Consolidate business logic handlers into a single function `initRouter`
- Move tenancy handling to the same function, remove it from API and APIv3 handlers
- `go test ./cmd/query/app/...`
=> Move all query service HTTP handlers into one function

cmd/query/app/http_handler_test.go, cmd/query/app/querysvc/adjusters.go
- Resolves #6001 (again).  If ClockSkew adjuster is run before DedupeBySpanHash, it will add warnings to spans with duplicate span IDs, which affect the hash code, which means that you "dedupe" to two copies of each span, not one.
- Change the order of Adjusters so that DedupeBySpanHash runs before ClockSkew
- In production, lightly
- Also unit tested
=> Fix span deduplication via correct ordering of adjusters 

plugin/sampling/strategyprovider/static/factory.go
fix function name in comment
fix function name in comment
- 
=> chore: fix function name in comment

cmd/query/app/server.go, plugin/metrics/prometheus/metricsstore/reader.go, plugin/storage/grpc/factory.go, plugin/storage/grpc/shared/archive.go, plugin/storage/grpc/shared/grpc_client.go, plugin/storage/grpc/shared/grpc_client_test.go
=> Use GRPC interceptors instead of explicit context wrappers

.github/workflows/ci-docker-hotrod.yml, examples/hotrod/docker-compose-v2.yml, scripts/build-hotrod-image.sh
- Resolves #6137 
- Currently in `.github/workflows/ci-docker-hotrod.yml`, we are only testing internally via `.scripts/build-hotrod-image.sh` for `examples/hotrod/docker-compose.yml` while `examples/hotrod/docker-compose-v2.yml` isnt getting covered
- For this, in `.github/workflows/ci-docker-hotrod.yml` we are passing `-b` flag to specify the jaeger binary (`all-in-one` or `jaeger`)
- For the flags and normal bash scirpt code i tested it manually in seperate bash file so that atleast ensures the basic code test
=> [jaeger-v2] Add HotROD integration test for jaeger-v2

cmd/query/app/server.go
- Resolves #6026 
- This PR removes the bifurcation in the creation of the GRPC query server. This bifurcation was initially added to handle the case where users were leveraging the same port for starting both the GRPC and HTTP query servers. However, that part is handled by `initListener` and not at the time of creating the server, so we can simply use OTEL's helper to create the server while leaving our logic to start the listeners using cmux if the ports are the same. 
- CI
=> [fix][query] Remove bifurcation for grpc query server

cmd/query/app/http_handler.go, cmd/query/app/server.go, cmd/query/app/trace_response_handler.go, cmd/query/app/trace_response_handler_test.go
- Resolves #6141
- Move the trace response handler to the server level so that it is applied to the whole server rather than just within the API handler. 
- Unit test
=> [query] Move trace handler to server level

docker-compose/monitor/README.md, docker-compose/monitor/docker-compose-v2.yml, docker-compose/monitor/docker-compose.yml
- Grafana server was not necessary for demonstrating SPM behavior or debugging
- Remove grafana service
- Update readme
- Manually (incidentally ran into an odd issue #6150)
=> [spm] Remove Grafana from examples

scripts/spm-integration-test.sh
- Part of #5608 
- The changes include requesting metric with `groupByOperation` to get labels along with `operation`. This is then compared with the expected label set = `"operation service_name"`
- jaeger/scripts/spm-integration-test.sh
=> Added Label Validation in SPM Integration Test

crossdock/docker-compose.yml, crossdock/main.go, crossdock/services/agent.go, crossdock/services/agent_test.go, crossdock/services/tracehandler.go
- Resolve #6083 
- 
- make test 
=> Crossdock sampling redirection to collector 

.github/workflows/ci-e2e-elasticsearch.yml, cmd/jaeger/config-badger.yaml, cmd/jaeger/config-cassandra.yaml, cmd/jaeger/config-elasticsearch.yaml, cmd/jaeger/config-kafka-collector.yaml, cmd/jaeger/config-kafka-ingester.yaml, cmd/jaeger/config-opensearch.yaml, cmd/jaeger/config-remote-storage.yaml, cmd/jaeger/config-tail-sampling-always-sample.yaml, cmd/jaeger/config-tail-sampling-service-name-policy.yaml, cmd/jaeger/config.yaml, cmd/jaeger/internal/all-in-one.yaml, plugin/storage/es/spanstore/reader.go, plugin/storage/es/spanstore/reader_test.go, plugin/storage/es/spanstore/writer.go, plugin/storage/es/spanstore/writer_test.go, plugin/storage/integration/integration.go, scripts/spm-integration-test.sh
- ES v8.0/v2 integration tests often fail ([exampe](https://github.com/jaegertracing/jaeger/actions/runs/11622432732/job/32429220258)), but looks like maybe only during certain hours of the day. E.g. yesterday I rerun the workflow 4 times at night and it repeatedly failed, then in the morning it succeeded.
- Log time settings in the runner to verify whether it's a time-zone related issue with locating the indices
- Add debug logging to ES to indicate which indices are being used for reading / writing (did not notice any issues with that in the failed run above)
- Add debug logging to v2 binary configs
- Fix a bug in `integration.go` where `require.NoError` was using inside lambda functions passed to `waitForCondition` - it was causing tests to fail on transient error with Elastic. Change …
=> Log time settings in CI

.golangci.yml, cmd/anonymizer/app/uiconv/reader.go, cmd/collector/app/handler/http_thrift_handler_test.go, cmd/collector/app/span_processor_test.go, cmd/es-index-cleaner/main.go, cmd/es-rollover/app/init/action.go, cmd/jaeger/internal/extension/jaegerquery/server_test.go, cmd/jaeger/internal/extension/jaegerstorage/config.go, cmd/jaeger/internal/extension/jaegerstorage/extension_test.go, cmd/jaeger/internal/integration/storagecleaner/extension_test.go, cmd/query/app/apiv3/grpc_handler_test.go, cmd/query/app/flags.go, cmd/query/app/grpc_handler_test.go, cmd/query/app/http_handler_test.go, cmd/query/app/static_handler_test.go, crossdock/services/tracehandler.go, internal/tracegen/config.go, model/ids.go, pkg/bearertoken/grpc.go, pkg/config/tlscfg/options.go, pkg/config/tlscfg/options_test.go, pkg/es/config/config.go, pkg/es/errors_test.go, plugin/storage/es/factory.go, plugin/storage/es/samplingstore/storage.go, plugin/storage/es/spanstore/dbmodel/to_domain_test.go, plugin/storage/factory_test.go, plugin/storage/grpc/factory.go, plugin/storage/grpc/shared/grpc_handler_test.go, plugin/storage/grpc/shared/streaming_writer.go
- Covers #5377
- enable `err-error` and `errorf` rules from [perfsprint](https://golangci-lint.run/usage/linters/#perfsprint) linter
- Uses `errors.New` instead of `fmt.Errorf` when there is only one argument
- CI
=> chore: enable err-error and errorf rules from perfsprint linter

cmd/agent/app/agent_test.go, internal/metrics/prometheus/factory_test.go, pkg/gogocodec/codec_test.go, plugin/storage/integration/elasticsearch_test.go
- Replaces `t.Fatal` calls with `"github.com/stretchr/testify/require"` use
- CI
=> chore: use testify instead of t.Fatal

.golangci.yml, cmd/agent/app/reporter/flags.go, cmd/collector/app/server/http_test.go, cmd/ingester/app/consumer/consumer_test.go, cmd/internal/status/command.go, cmd/jaeger/internal/sanitizer/utf8_test.go, crossdock/services/common.go, crossdock/services/tracehandler_test.go, examples/hotrod/pkg/log/spanlogger.go, model/span_test.go, pkg/es/client/client.go, pkg/es/client/ilm_client.go, pkg/es/client/index_client.go, pkg/fswatcher/fswatcher.go, pkg/testutils/logger_test.go, plugin/sampling/leaderelection/leader_election_test.go, plugin/storage/badger/factory_test.go, plugin/storage/badger/spanstore/read_write_test.go, plugin/storage/es/spanstore/reader.go, plugin/storage/es/spanstore/service_operation.go, plugin/storage/integration/es_index_cleaner_test.go
- enable all rules of [perfsprint](https://github.com/catenacyber/perfsprint) linter
- CI
=> chore: enable all rules of perfsprint linter

scripts/draft-release.py
- The script expects changelog header with digits only, but last release was with `v` prefix (as it was shown in the header template).
- Relax regex in the script to allow `v` prefix as well
- `make draft-release` was run to create 2.0.0 release
=> Relax regex in draft-release.py

ADOPTERS.md
=> Add Alauda to adopters list

pkg/jtracer/jtracer.go
Resolves #6122 
- The changes include using the `otlptracegrpc.WithInsecure()` based on `OTEL_EXPORTER_OTLP_ENDPOINT` and `OTEL_EXPORTER_OTLP_INSECURE` env variables.
=> Respect environment variables when creating internal tracer

cmd/agent/app/builder_test.go, cmd/agent/app/reporter/grpc/builder_test.go
- Part of #6111 
- Added t.parallel to tests where it made significant improvement 
- 
=> Parallelize the unit tests

cmd/jaeger/README.md, examples/hotrod/docker-compose-v2.yml, scripts/build-hotrod-image.sh
- README was referring to 1.59 version as example
- Update to refer to 2.0.0
- Clean-up
- CI
=> [v2] Update versions in README

docker-compose/monitor/README.md, scripts/spm-integration-test.sh
- The SPM integration test in the CI has been failing consistently. It looks like the default endpoint for prometheus has changed from `localhost:9090/graph` to `localhost:9090/query`. This PR fixes that in the integration test and in the README. 
- Integration test passes
- Ran the `docker-compose/monitor/docker-compose-v2.yml` example and verified that the prometheus UI displays the metrics at the new endpoint. 
=> [fix][ci] Change the prometheus healthcheck endpoint 

docker-compose/cassandra/v4/docker-compose.yaml, docker-compose/cassandra/v5/docker-compose.yaml, scripts/cassandra-integration-test.sh
- Resolves #6215 
- Added the username and password values for health check cmd
- Added `healthcheck_cassandra` point to make sure the container is healthy as per the cmd.
- bash scripts/cassandra-integration-test.sh 4 v004 v1 
- bash scripts/cassandra-integration-test.sh 4 v004 v2
=> Pass username/password to Cassandra docker-compose health check

storage_v2/factoryadapter/factory.go, storage_v2/factoryadapter/factory_test.go, storage_v2/factoryadapter/reader.go, storage_v2/factoryadapter/reader_test.go
- Towards #5079 
- This PR implements the v2 `spanstore.Reader` interface in the factory adapter through the `TraceReader`, which is currently just a wrapper around the v1 `spanstore.Reader`. The `TraceReader` provides a function `GetV1Reader` that exposes the underlying v1 reader which will be used in https://github.com/jaegertracing/jaeger/pull/6170. 
- Added unit tests for new functions
=> [storage][v2] Add reader adapter that just exposes the underlying v1 reader

cmd/jaeger/internal/all-in-one.yaml, examples/hotrod/docker-compose-v2.yml
- Part of #6209
- The example should be working without these overrides
- Remove overrides
- Add explicit 0.0.0.0 host to all-in-one config
- CI
=> Remove 0.0.0.0 overrides in HotROD CI

cmd/query/app/server_test.go
- Resolves #6230 
- We had a bug report come in #6230 which wasn't caught by our unit tests. The reason here was because the test was not checking the status code of the response received from the server but rather just the error returned from doing `Client.Do`. 
- - This PR also cleans up the tests to remove the manual dial call and an unnecessary filter in the test body. 
- This test passes on main because of the patch that was landed in https://github.com/jaegertracing/jaeger/pull/6239. 
- To verify that this test would have caught the bug, I ran this test on the v1.63.0 release. Running this test caused failures in the following tests, all of which were returning `400` instead of `200`.
```
TestServerHTTPTLS/should_pass_with_TLS_client_to_trusted_TLS_server_with_correct_hostname …
```
=> [fix][test] Fix query server unit tests to check for status code

Makefile.Protobuf.mk
People can use different container manager in protobuf makefile
```
make DOCKER=podman PWD=${PWD} <makefile-target>
```
- 
- unix test
=> Allow using different container runtime

cmd/jaeger/internal/exporters/storageexporter/exporter_test.go, cmd/jaeger/internal/extension/jaegerstorage/config.go, cmd/jaeger/internal/extension/jaegerstorage/config_test.go, cmd/jaeger/internal/extension/jaegerstorage/extension.go, cmd/jaeger/internal/extension/jaegerstorage/extension_test.go, cmd/jaeger/internal/extension/remotesampling/extension_test.go, cmd/jaeger/internal/processors/adaptivesampling/processor_test.go
- Make config struct naming more consistent
- Backends -> TraceBackends
- Backend -> TraceBackend
- MetricBackends -> MetricBackend
- CI
=> [refactor] Normalize jaegerstorage names

cmd/jaeger/internal/command.go
We were passing the whole VersionInfo to OTEL's BuildInfo, which resulted in the metrics being labeled with a very long string: `service_version="git-commit=600d82c5815289ba13197ce80b742c0f4411df78, git-version=v2.0.0, build-date=2024-11-26T15:15:15Z"`
Only pass the actual version. The metrics become much more readable: `jaeger_query_responses_count{operation="get_services",service_instance_id="06f22e3e-3ad7-4067-8b0f-15d35b329712",service_name="jaeger",service_version="v2.0.0"}`
`$ curl -s http://localhost:8888/metrics | grep -v '^#' | grep 'get_services'`
=> [v2] Use only version number for BuildInfo

cmd/jaeger/internal/extension/remotesampling/extension.go, plugin/sampling/strategyprovider/adaptive/factory.go
- Some components were still using `metrics.NullFactory`
- Create real factory from OTEL MetricsProvider
- CI
=> Use real metrics factory instead of NullFactory

pkg/prometheus/config/config.go, plugin/metrics/prometheus/metricsstore/reader.go, plugin/metrics/prometheus/metricsstore/reader_test.go, plugin/metrics/prometheus/options.go
=> [prometheus] Use OTEL helper instead of tlscfg package

pkg/es/config/config.go, plugin/storage/es/spanstore/writer.go, storage/spanstore/spanstoremetrics/write_metrics.go, storage/spanstore/spanstoremetrics/write_metrics_test.go
- Towards #6219 
- In https://github.com/jaegertracing/jaeger/pull/6255, `NewMetricsWriter` was renamed to `NewWriterDecorator`. However, `MetricWriter` is not a decorator and simply a helper so this PR changes the function to be called `spanstoremetrics.NewWriter`. 
- CI
=> [chore][fix] Rename `NewWriteDecorator` to `NewWriter`

CHANGELOG.md, cmd/all-in-one/main.go, cmd/jaeger/config-badger.yaml, cmd/jaeger/config-cassandra.yaml, cmd/jaeger/config-elasticsearch.yaml, cmd/jaeger/config-opensearch.yaml, cmd/jaeger/config-remote-storage.yaml, cmd/jaeger/config-tail-sampling-always-sample.yaml, cmd/jaeger/config-tail-sampling-service-name-policy.yaml, cmd/jaeger/config.yaml, cmd/jaeger/internal/all-in-one.yaml, cmd/jaeger/internal/extension/jaegerquery/server.go, cmd/jaeger/internal/extension/jaegerstorage/extension.go, cmd/query/app/server.go, cmd/query/app/server_test.go, cmd/query/app/token_propagation_test.go, cmd/query/main.go, cmd/remote-storage/app/server.go, cmd/remote-storage/app/server_test.go, cmd/remote-storage/main.go, pkg/telemetry/settings.go, pkg/telemetry/settings_test.go, plugin/storage/grpc/factory.go, plugin/storage/grpc/factory_test.go, plugin/storage/integration/remote_memory_storage.go
Per title
* rename folder first pkg/telemetery->pkg/telemetry
* then run this command
```
grep -rl telemetery . | xargs gsed -i 's/telemetery/telemetry/g'
```
=> [refactor] Fix package misspelling: telemetery->telemetry

cmd/ingester/app/flags_test.go, cmd/ingester/main.go, pkg/kafka/auth/config.go, pkg/kafka/auth/config_test.go, pkg/kafka/auth/tls.go, pkg/kafka/auth/tls_test.go, plugin/storage/kafka/factory.go, plugin/storage/kafka/options_test.go
=> [kafka] OTEL helper instead of tlscfg package

pkg/kafka/auth/options_test.go
- Test for options.go
- Add test for options.go file.
- 
=> test: Add test for kafka/auth/options.go file

plugin/storage/integration/integration.go
Signed-off-by: vaidikcode <vaidikbhardwaj00@gmail.com>
- 
#4466 
- 
added new testGetLargeSpanWithDuplicateIds with a method to generate duplicate span ids and also fixed testGetLargeSpan to generate unique ids
- 
=> [test] Explicitly test writing traces with duplicate span ids

plugin/storage/integration/cassandra_test.go
Minor fix in cassandra initialization for integration test
- Changed environment variable used for initialization
=> Fix password in integration test

cmd/jaeger/internal/exporters/storageexporter/exporter.go, cmd/jaeger/internal/extension/jaegerstorage/extension.go, storage_v2/factoryadapter/factory.go, storage_v2/factoryadapter/reader.go, storage_v2/factoryadapter/reader_test.go, storage_v2/factoryadapter/writer.go, storage_v2/tracestore/empty_test.go, storage_v2/tracestore/factory.go, storage_v2/tracestore/reader.go, storage_v2/tracestore/writer.go
- Towards #5079 and #6170 
- Renames `storage_v2/spanstore` to `storage_v2/tracestore` to address https://github.com/jaegertracing/jaeger/pull/6170#pullrequestreview-2471293046
- CI
=> [chore] Rename `spanstore` to `tracestore` for v2 storage

cmd/all-in-one/main.go, cmd/collector/main.go, cmd/ingester/main.go, cmd/internal/flags/service.go, cmd/query/main.go
- Part of #6321
- Print EOL notice from core v1 binaries
```
$ go run ./cmd/all-in-one
2024/12/07 13:02:54 maxprocs: Leaving GOMAXPROCS=12: CPU quota undefined
*******************************************************************************
🛑  WARNING: End-of-life Notice for Jaeger v1
You are currently running a v1 version of Jaeger, which is deprecated and will
reach end-of-life on December 31st, 2025. This means there will be no further
development, bug fixes, or security patches for v1 after this date.
We strongly recommend migrating to Jaeger v2 for continued support and access
to new features.
For detailed migration instructions, please refer to the official Jaeger
documentation:  https://www.jaegertracing.io/docs/latest/migration/
Tracking issue: …
```
=> Pring EOL notice from v1 binaries

GOVERNANCE.md, MAINTAINERS.md, README.md, RELEASE.md
- Resolves #6264
- Add new maintainer
- Clean-up README
=> Add mahadzaryab1 to maintainers

cmd/query/app/grpc_handler.go, cmd/query/app/grpc_handler_test.go
- This PR fixes a bug in the query GRPC handler which currently passes `startTime` to `GetDependencies` instead of `endTime`
- Fixed unit test expectations
=> [fix] Fix call to `GetDependencies` in grpc handler

storage_v2/factoryadapter/reader.go, storage_v2/factoryadapter/reader_test.go
- Towards #5079 
- This PR implements `GetServices` and `GetOperations` in the v2 `factoryadapter`
=> [v2][storage] Implement `GetServices` and `GetOperations` in v2 factory adapter

model/ids.go, model/ids_test.go, storage_v2/factoryadapter/reader.go, storage_v2/factoryadapter/reader_test.go
- Towards #5079
- This PR implements `FindTraceIDs` in the v2 factory adapter
=> [storage][v2] Implement `FindTraceIDs` in v2 factory adapter

storage_v2/factoryadapter/reader.go, storage_v2/factoryadapter/reader_test.go, storage_v2/tracestore/reader.go, storage_v2/tracestore/reader_test.go
- Towards #5079
- This PR implements `FindTraces` in the v2 factory adapter
=> [storage][v2] Implement `FindTraces` in v2 factory adapter

cmd/ingester/app/flags_test.go, pkg/config/tlscfg/options.go, pkg/config/tlscfg/options_test.go, pkg/kafka/auth/config_test.go, plugin/storage/kafka/options_test.go
- Resolves #6334
- Restore pre-OTEL behavior of using system cert pool if no CAFile is specified.
- unit tests
=> [fix] Fallback to system CA certs pool

cmd/query/app/querysvc/adjuster/adjuster.go, cmd/query/app/querysvc/adjuster/adjuster_test.go, cmd/query/app/querysvc/adjuster/package_test.go
- This PR adds an interface for `Adjuster` to operate on the OTLP model format so that it can be used by the v2 query service. The v1 interface/implementation can be found in `model/adjuster`. 
- In the following PRs, we'll implement all the standard adjusters in `model/adjuster` to implement the new interface. 
- Unit tests
=> [v2][query] Add interface for adjuster to operate on OTLP data format

plugin/storage/integration/badgerstore_test.go, plugin/storage/integration/grpc_test.go, plugin/storage/integration/memstore_test.go
Fixes a part of #5006 
- Added go leak check for badgerstore, grpc and Memstore
- Integration Tests
=> Add Go Leak Check for Badgerstore, gRPC and Memstore e2e Tests

cmd/query/app/querysvc/adjuster/adjuster.go, cmd/query/app/querysvc/adjuster/ipattribute.go, cmd/query/app/querysvc/adjuster/ipattribute_test.go
- Towards https://github.com/jaegertracing/jaeger/issues/6344
- This PR implements the `IPTag` adjuster to operate on the OTLP data model. In the OTLP model, tags are dubbed as attributes so the adjuster was renamed to `IPAttribute`.
=> [v2][adjuster] Implement ip attribute adjuster to operate on otlp data model

cmd/query/app/apiv3/grpc_handler.go, cmd/query/app/apiv3/grpc_handler_test.go, cmd/query/app/apiv3/http_gateway.go, cmd/query/app/apiv3/http_gateway_test.go, cmd/query/app/apiv3/otlp_translator.go
- Noticed by accident that apiv3 handler was ignoring stream send error
- Handle error propertly
- Add tests
- Remove impossible error handling from pdata converter
- CI
=> Respond correctly to stream send error

cmd/query/app/querysvc/query_service_test.go, pkg/iter/iter.go, pkg/iter/iter_test.go, pkg/iter/package_test.go, storage_v2/factoryadapter/reader.go, storage_v2/factoryadapter/reader_test.go, storage_v2/tracestore/mocks/Reader.go, storage_v2/tracestore/reader.go
- v1 storage API was fully synchronous that required buffering add span data in memory, even though our gRPC Remote Storage API supported streaming.
- Change `tracestore.Reader` interface to use function iterators in the style of Go 1.23 `iter` package
- Add a sort of a backport of `iter` package until we can upgrade to Go 1.23
- CI
=> Change Storage v2 API to use streaming

storage_v2/factoryadapter/reader.go, storage_v2/factoryadapter/reader_test.go, storage_v2/tracestore/mocks/Reader.go, storage_v2/tracestore/reader.go, storage_v2/tracestore/reader_test.go
- GetTrace returns a single trace. The use case for FindTraceIDs specifically exists for loading traces in batches, but there's really no capability in Jaeger to do that: if you loaded 10K IDs you need to make 10K RPCs to load 10K traces. 
- Part of #5079
- Change it to `GetTraces(...TraceID)`
- Also add start/end times (per #4150)
- CI, unit tests
=> Change storage_v2 GetTrace to GetTraces plural

cmd/query/app/querysvc/adjuster/adjuster.go, cmd/query/app/querysvc/adjuster/adjuster_test.go, cmd/query/app/querysvc/adjuster/ipattribute.go, cmd/query/app/querysvc/adjuster/ipattribute_test.go, cmd/query/app/querysvc/adjuster/resourceattributes.go, cmd/query/app/querysvc/adjuster/resourceattributes_test.go, cmd/query/app/querysvc/adjuster/spaniduniquifier.go, cmd/query/app/querysvc/adjuster/spaniduniquifier_test.go, cmd/query/app/querysvc/adjuster/spanlinks.go, cmd/query/app/querysvc/adjuster/spanlinks_test.go
- This PR removes the `error` return value from the v2 adjuster interface as none of the adjusters return any errors and errors instead recorded on the spans as warnings. 
- CI
=> [v2][adjuster] Remove error return from adjuster interface

pkg/prometheus/config/config.go, plugin/metricstore/prometheus/metricstore/reader.go, plugin/metricstore/prometheus/metricstore/reader_test.go, plugin/metricstore/prometheus/options.go
- Resolves #4221 
- Wrapped the client in `promClient` to decorate url with additional parameters
- `TestCreatePromClientWithAdditionalParameters`
=> Support extra custom query parameters in requests to Prometheus backend

cmd/query/app/querysvc/adjuster/sort.go, cmd/query/app/querysvc/adjuster/sort_test.go
- Implemented an adjuster to sort attributes and events that operates natively on the OTLP data format. This is analogous to the `SortTagsAndLogFields` adjuster in v1.
- Added a unit test
=> [v2][adjuster] Implement adjuster for sorting attributes and events

cmd/query/app/handler_archive_test.go, cmd/query/app/http_handler.go, cmd/query/app/http_handler_test.go
Resolves #4150
- add optional time window when fetching trace by id
- unittest
=> Add optional time window for GetTrace & SearchTrace of http_handler

cmd/query/app/querysvc/adjuster/clockskew.go, cmd/query/app/querysvc/adjuster/clockskew_test.go, pkg/otelsemconv/semconv.go
- Implemented an adjuster to correct timestamps for clockskew. 
=> [v2][adjuster] Implement adjuster for correct timestamps for clockskew

.golangci.yml, cmd/collector/app/handler/otlp_receiver.go, cmd/jaeger/internal/processors/adaptivesampling/processor.go, cmd/query/app/otlp_translator.go, internal/jptrace/translator.go, internal/jptrace/translator_test.go, model/ids.go, model/ids_test.go, storage_v2/v1adapter/writer.go
- Implemented a translator in `jptrace` with a function `ProtoFromTraces`  that is a wrapper of the upstream `ProtoFromTraces` in opentelemetry-collector-contrib jaeger translator. This function appends the warnings in `jaeger.internal.warnings` to the corresponding warnings field in the proto model. 
=> [v2][adjuster] Implement otlp to model translator with post processing

cmd/query/app/querysvc/adjuster/clockskew.go, cmd/query/app/querysvc/adjuster/clockskew_test.go, cmd/query/app/querysvc/adjuster/hash.go, cmd/query/app/querysvc/adjuster/hash_test.go, cmd/query/app/querysvc/adjuster/ipattribute.go, cmd/query/app/querysvc/adjuster/ipattribute_test.go, cmd/query/app/querysvc/adjuster/libraryattributes.go, cmd/query/app/querysvc/adjuster/libraryattributes_test.go, cmd/query/app/querysvc/adjuster/sort.go, cmd/query/app/querysvc/adjuster/sort_test.go, cmd/query/app/querysvc/adjuster/spaniduniquifier.go, cmd/query/app/querysvc/adjuster/spaniduniquifier_test.go, cmd/query/app/querysvc/adjuster/spanlinks.go, cmd/query/app/querysvc/adjuster/spanlinks_test.go, cmd/query/app/querysvc/adjuster/standard.go, cmd/query/app/querysvc/adjuster/standard_test.go
- Towards #6344 
- Implemented a function `StandardAdjusters` that returns a list of adjusters to be applied on ptrace.Traces
- This will be used by the v2 query service in https://github.com/jaegertracing/jaeger/pull/6343
=> [v2][adjuster] Implement function to get standard adjusters to operate on otlp format

.golangci.yml, cmd/jaeger/internal/integration/span_writer.go, cmd/query/app/apiv3/otlp_translator.go, cmd/query/app/querysvc/adjuster/clockskew.go, cmd/query/app/querysvc/adjuster/hash.go, cmd/query/app/querysvc/adjuster/libraryattributes.go, cmd/query/app/querysvc/adjuster/spaniduniquifier.go, cmd/query/app/querysvc/adjuster/spanlinks.go, internal/jptrace/translator.go, internal/jptrace/translator_test.go, internal/jptrace/warning.go, internal/jptrace/warning_test.go, storage_v2/v1adapter/reader.go
- Implemented a translator in `jptrace` with a function `ProtoToTraces`  that is a wrapper of the upstream `ProtoToTraces` in opentelemetry-collector-contrib jaeger translator. This function appends the warnings in model.Span to the `jaeger.internal.warnings` attribute in the corresponding span in ptrace.Traces.
=> [v2][adjuster] Implement model to otlp translator with post processing

cmd/query/app/querysvc/query_service_v2_test.go, internal/jptrace/aggregator.go, internal/jptrace/aggregator_test.go, storage_v2/tracestore/reader.go
- Towards #6337 
- This PR implements a helper `AggregateTraces` in the `jptrace` package to aggregate a sequence of `[]ptrace.Traces` to `ptrace.Traces`. This was done by combining contiguous trace chunks together based on the traceID. 
=> [v2][query] Implement helper to buffer sequence of traces 

.golangci.yml, internal/jptrace/aggregator.go
- https://github.com/jaegertracing/jaeger/pull/6401 was accidentally using the official `iter` package instead of the internal one. This PR fixes that usage.
- Added a linter rule so we don't accidentally use the official package again until we upgrade to Go 1.23
- CI
=> [fix] Fix incorrect usage of iter package in aggregator

internal/jptrace/translator_test.go
- The output of `ProtoToTraces` is not guaranteed to be in order which was causing flaky test failures in `translator_test.go`. This PR changes the test expectations to not depend on the return order of `ProtoToTraces`. 
- CI
=> [fix] Fix test expectations for translator to avoid depending on order

cmd/jaeger/internal/all-in-one.yaml
- Recently there was a thread in `#jaeger` slack room with a user who is still using legacy SDKs that emit traces via UDP. The all-in-one configuration in Jaeger v2 currently has them disabled, which breaks backwards compatibility.
- Enable UDP ports
- Ran `go run ./cmd/jaeger` to ensure configuration is accepted. The user on slack also confirmed that it worked for them.
- Unfortunately, we do not have e2e tests for this.
=> Enable UDP ports in all-in-one

.golangci.yml, cmd/collector/app/handler/otlp_receiver.go, cmd/jaeger/internal/integration/span_writer.go, cmd/jaeger/internal/processors/adaptivesampling/processor.go, cmd/query/app/apiv3/otlp_translator.go, cmd/query/app/otlp_translator.go, internal/jptrace/warning.go, storage_v2/v1adapter/reader.go, storage_v2/v1adapter/translator.go, storage_v2/v1adapter/translator_test.go, storage_v2/v1adapter/writer.go
- Move model<->otlp translation from `jptrace` to `v1adapter` to keep `jptrace` specific to helper around the `ptrace` domain objects.
- CI
=> [refactor] Move model<->otlp translation from `jptrace` to `v1adapter`

cmd/query/app/http_handler.go, cmd/query/app/http_handler_test.go, cmd/query/app/querysvc/query_service.go, cmd/query/app/querysvc/query_service_test.go, model/adjuster/adjuster.go, model/adjuster/adjuster_test.go, model/adjuster/bad_span_references.go, model/adjuster/bad_span_references_test.go, model/adjuster/clockskew.go, model/adjuster/clockskew_test.go, model/adjuster/ip_tag.go, model/adjuster/ip_tag_test.go, model/adjuster/otel_tag.go, model/adjuster/otel_tag_test.go, model/adjuster/parent_reference.go, model/adjuster/parent_reference_test.go, model/adjuster/sort_tags_and_log_fields.go, model/adjuster/sort_tags_and_log_fields_test.go, model/adjuster/span_hash_deduper.go, model/adjuster/span_hash_deduper_test.go, model/adjuster/zipkin_span_id_uniquify.go, model/adjuster/zipkin_span_id_uniquify_test.go, plugin/storage/memory/memory.go
- Towards #6417
- The v1 adjuster interface returns an error even though none of the adjusters ever return an error. This was leading to handling errors that would never be thrown. This PR simplifies the interface by removing the error return. 
- The v1 adjuster interface was also returning the trace that it modified. However, all the adjusters currently just take the trace in as a pointer and modify it in place so this return was not necessary. 
- CI
=> [v1][adjuster] Change v1 adjuster interface to not return error and modify trace in place

cmd/query/app/apiv3/grpc_handler.go, cmd/query/app/apiv3/http_gateway.go, cmd/query/app/apiv3/http_gateway_test.go, cmd/query/app/grpc_handler.go, cmd/query/app/http_handler.go, cmd/query/app/http_handler_test.go, cmd/query/app/query_parser.go, cmd/query/app/query_parser_test.go, cmd/query/app/querysvc/query_service.go, cmd/query/app/querysvc/query_service_test.go
- Towards #6417
- This PR defines `GetTraceParamaters` and `TraceQueryParameters` inside `package querysvc` that are currently just wrappers around their `package spanstore` counterparts.
- This is done so that additional parameters can be passed into the query service, like the `RawTraces` flag, without having to extend the parameters that are passed into the storage implementations. 
- CI
=> [refactor][query] Propagate `RawTraces` flag to  query service

cmd/jaeger/internal/all-in-one.yaml, cmd/jaeger/internal/extension/remotesampling/config.go, cmd/jaeger/internal/extension/remotesampling/config_test.go, cmd/jaeger/internal/extension/remotesampling/extension.go, plugin/sampling/strategyprovider/static/provider.go
- Accidentally stumbled upon this when looking at #6431
- Turns out v2 config did not support all the options from v1
- Add support for reload interval
`go run ./cmd/jaeger`
```
$ curl "http://localhost:5778/?service=x"
{"strategyType":0,"probabilisticSampling":{"samplingRate":1}}%
```
Edit cmd/jaeger/sampling-strategies.json to change default to 0.1.
Observe server logs showing new values.
```
$ curl "http://localhost:5778/?service=x"
{"strategyType":0,"probabilisticSampling":{"samplingRate":0.1}}%
```
=> Support sampling file reload interval

cmd/jaeger/internal/all-in-one.yaml, cmd/jaeger/internal/extension/remotesampling/config.go, cmd/jaeger/internal/extension/remotesampling/extension.go, go.mod, plugin/sampling/strategyprovider/static/options.go
- Part 2 of #5270
- 🛑 Make the new behavior to inherit from default strategy to be ON by default.
- In v1 it can still be disabled via a flag, which will be deprecated in the future.
- In v2 it can be disabled via a feature gate `jaeger.sampling.includeDefaultOpStrategies`
- CI
=> [sampling] Inherit default per-operation strategies

cmd/query/app/querysvc/v2/querysvc/service.go, cmd/query/app/querysvc/v2/querysvc/service_test.go
- Towards #6337
- The query service was currently performing aggregation when the `raw_traces` flag is set. This PR fixes that by removing aggregation when the flag is set.
- Adding unit tests
=> [v2][query] Fix query service to not perform aggregation for raw traces

cmd/all-in-one/main.go, cmd/jaeger/internal/extension/jaegerquery/server.go, cmd/jaeger/internal/extension/jaegerquery/server_test.go, cmd/query/app/apiv3/grpc_handler.go, cmd/query/app/apiv3/grpc_handler_test.go, cmd/query/app/flags.go, cmd/query/app/flags_test.go, cmd/query/app/server.go, cmd/query/app/server_test.go, cmd/query/app/token_propagation_test.go, cmd/query/main.go, storage_v2/v1adapter/archive.go, storage_v2/v1adapter/archive_test.go, storage_v2/v1adapter/writer.go
- Towards #6337
- This PR migrates the v3_api GRPC handler to use the new v2 query service.
- CI
=> [api_v3][query] Change api_v3 grpc handler to use query service v2 

cmd/query/app/apiv3/gateway_test.go, cmd/query/app/apiv3/grpc_handler_test.go
- Towards #6460
- The unit tests for the `api_v3` grpc handler were still using `package spanstore` wrapped in a v1 adapter. Now that the API has been migrated to use the v2 query service, the tests were changed to pass in the native reader instead.
- CI
=> [test] Change api_v3 unit tests to use `tracestore` natively

examples/hotrod/README.md
If you curl metrics on port 8083 you get a message "endpoint moved to the frontend service". Since the frontend port is 8080, I changed the metrics port to 8080, too. Now the examples are working again.
=> chore: fixed port for metrics

cmd/query/app/querysvc/query_service.go, cmd/query/app/querysvc/query_service_test.go, storage_v2/v1adapter/reader.go, storage_v2/v1adapter/reader_test.go
- Towards #6480
- This PR changes the v1 query service to check for the v1 adapter at construction rather than at method invocation. 
- Currently, the constructor will panic if its provided a native v2 storage implementation. This will be remedied in a follow-up PR that will implement a reverse adapter to go from v2->v1. 
- CI and added a unit test
=> [query] Update v1 query service to check for adapter at construction

cmd/collector/app/span_processor.go, pkg/queue/bounded_queue.go, pkg/queue/bounded_queue_test.go
- Continuation of #6474
- In order to allow the queue to carry both v1 and v2 data model, let's first make the queue strongly typed by using generics
- unit tests, CI
=> Change collector's queue to use generics

cmd/collector/app/collector.go, cmd/collector/app/span_handler_builder.go, cmd/collector/app/span_handler_builder_test.go, cmd/collector/app/span_processor.go, cmd/collector/app/span_processor_test.go
- Part of #6487
- Creation of exporterhelper may result in an error, so extend the processor construction signature to return the error.
- CI
=> Return errors from span processor creation

cmd/collector/app/span_processor.go, internal/jptrace/attributes.go, internal/jptrace/warning.go, internal/jptrace/warning_test.go
- Resolves #6522 
- Replaced the names of non-standard tags with standard tags
- make test returned pass for all the test cases
- for `jaeger`: `make test`
=> Add standard tags for internal warnings and span format

CONTRIBUTING_GUIDELINES.md
#6528 
changed some git commands' format from 'code' to 'bash script' 
now you can just click and copy shell commands
=> Use bash script markdown in CONTRIBUTING.md 

cmd/jaeger/internal/all-in-one.yaml, cmd/jaeger/internal/extension/remotesampling/config.go, cmd/jaeger/internal/extension/remotesampling/config_test.go, cmd/jaeger/internal/extension/remotesampling/extension.go, cmd/jaeger/internal/extension/remotesampling/extension_test.go, cmd/jaeger/internal/extension/remotesampling/factory.go, plugin/sampling/strategyprovider/static/constants.go, plugin/sampling/strategyprovider/static/options.go, plugin/sampling/strategyprovider/static/provider.go, plugin/sampling/strategyprovider/static/provider_test.go
- fix #6338 
-  Removed the hardcoded path in the default configuration (all-in-one.yaml).
- updated tests accordingly
- Since some of the tests are using hardcoded services in ```sampling-strategies.json``` (the service "foo").
https://github.com/jaegertracing/jaeger/blob/b02900cd99b38a79f70d9ba14f631307ded84764/cmd/jaeger/internal/extension/remotesampling/extension_test.go#L83
the ```sampling-strategies.json``` file could not be removed
- Also, right now there are some tests, namely:
1.) TestServerHTTP_TracesRequest,
2.) all 3 tests in cmd/query/app
which are not passing even on the main branch itself (according to me, otherwise I have made some mistake), and hence these same tests are not passing after I made my changes (my changes should not affect them anyway). 
- for `jaeger`: `make …
=> Make all-in-one.yaml file independant of sampling-strategies.json file 

cmd/collector/app/collector_test.go, cmd/collector/app/handler/grpc_handler.go, cmd/collector/app/handler/grpc_handler_test.go, cmd/collector/app/handler/http_thrift_handler.go, cmd/collector/app/handler/http_thrift_handler_test.go, cmd/collector/app/handler/thrift_span_handler.go, cmd/collector/app/handler/thrift_span_handler_test.go, cmd/collector/app/processor/processor.go, cmd/collector/app/server/test.go, cmd/collector/app/span_processor.go, cmd/collector/app/span_processor_test.go
- Context is lost in the process, see https://github.com/jaegertracing/jaeger/pull/6491#discussion_r1912529658
- Add Context argument to handler and span processor methods
- CI
=> Pass Context through span processors

cmd/collector/app/server/grpc.go, cmd/jaeger/internal/extension/remotesampling/extension.go, internal/sampling/grpc/grpc_handler.go, internal/sampling/grpc/grpc_handler_test.go
- Towards #6411 
- Move sampling grpc handler from cmd/collector/app/sampling to internal/sampling/grpc
- Covered by existing
=> [refactor] Move sampling grpc handler to internal/sampling/grpc

.github/workflows/ci-lint-checks.yaml
- Fix for one issue caused in #6527 
- cache_output not being set after a cache hit using restore key
- Instead check for cache-matched-key != ''" 
- 
=> [ci] Fix binary-size-check workflow

Makefile.Protobuf.mk
- Part of #6494
- Bump jaeger-idl submodule
- Adjust code gen to account for different custom types due to https://github.com/jaegertracing/jaeger-idl/pull/118
- CI
=> Bump jaeger-idl

model/flags.go, model/flags_test.go, model/ids.go, model/ids_proto_test.go, model/ids_test.go, model/otelids.go, model/otelids_test.go, model/span.go, model/span_test.go
- Part of https://github.com/jaegertracing/jaeger/issues/6571
- Follow-up to https://github.com/jaegertracing/jaeger-idl/pull/118
- Separate model files into more independent pieces that are easier to move to jaeger-idl
- CI
=> Separate model parts into more independent pieces

cmd/collector/app/collector.go, cmd/collector/app/collector_test.go, cmd/jaeger/internal/processors/adaptivesampling/processor.go, cmd/jaeger/internal/processors/adaptivesampling/processor_test.go, internal/sampling/samplingstrategy/adaptive/aggregator.go, internal/sampling/samplingstrategy/adaptive/aggregator_test.go, internal/sampling/samplingstrategy/aggregator.go
- https://github.com/jaegertracing/jaeger/issues/6584
- edit `HandleRootSpan` and it's mocks to use `aggregator` parameter logger
- `make lint test`
=> Remove Logger parameter in adaptive/aggregator.go

cmd/query/app/apiv3/grpc_handler.go, cmd/query/app/apiv3/http_gateway.go, model/otelids.go, model/otelids_test.go, plugin/storage/integration/integration.go, storage_v2/v1adapter/spanreader.go, storage_v2/v1adapter/tracereader.go, storage_v2/v1adapter/translator.go, storage_v2/v1adapter/translator_test.go
- Part of #6494
- If we move TraceID/SpanID types to jaeger-idl we will not be able to define methods on them, so change to plain functions.
- CI
=> Change model.ToOTELxxxID() to accept ID argument

Makefile
- Part of #6494
- Since `jaeger-idl` repo now includes Go code, as soon as we update the submodule here it's treated as a real source of Go code, including by tools like `go fmt`, etc.
- Exclude `idl/` from ALL_SOURCES, so that `make fmt` does not apply to it
- Bump `idl` submodule to latest
- CI
=> Exclude idl/ as a source of Go code

cmd/esmapping-generator/generator/esmapping_generator.go, cmd/esmapping-generator/generator/esmapping_generator_test.go, cmd/esmapping-generator/main.go, cmd/jaeger/main.go, internal/storage/elasticsearch/mapping/command.go, internal/storage/elasticsearch/mapping/command_test.go
- part of #6283  
- Decoupled the Esmapping generation logic from cmd/esmappnig-generator/main.go and kept it into reusable renderer package and then reimplemented the subcommand in the plugin/storage/es/esmapping-generator.go file and then registered in jaeger/main.go. 
- go test ./... -count=1
=> feat: Add esmapping-generator into jaeger binary

plugin/storage/cassandra/schema/create.sh
- Fixes https://github.com/jaegertracing/jaeger/issues/6597
-  This issue arises when I was trying to release the operator, for some reason (may be the cassandra version) the returned version contains spaces. This result in trying to fallback to /`cassandra-schema/v004-go-tmpl.cql.tmpl` which is a golang template. This produced the following error
This migh be happen only with 3.x and I know we dropped support for it. but it could also happens with others. 
```
Using template file /cassandra-schema/v004-go-tmpl.cql.tmpl with parameters:
mode = test
datacenter = datacenter3
keyspace = jaeger_v1_datacenter3
replication = {'class': 'SimpleStrategy', 'replication_factor': '1'}
trace_ttl = 172800
dependencies_ttl = 0
compaction_window_size = 96
compaction_window_unit = MINUTES …
```
=> Sanitize Cassandra version before use it

cmd/jaeger/config-elasticsearch.yaml, cmd/jaeger/config-opensearch.yaml
- Example configs do not show how to configure server addresses
- https://github.com/orgs/jaegertracing/discussions/6548#discussioncomment-11925175
- Add server address
- CI
=> Add example of ES/OS server_urls to configs

.github/workflows/ci-lint-checks.yaml, plugin/storage/cassandra/schema/create.test.sh, scripts/utils/run-tests.sh
- Subpart of the #6582 
- created unit tests for the create.sh file , to test for various cases such as presence of Mode parameter , output for specific parameters
- 
=> Add unit tests for the cassandra/schema/create.sh script

docker-compose/monitor/Makefile, docker-compose/monitor/README.md, docker-compose/monitor/docker-compose-v1.yml, docker-compose/monitor/docker-compose.yml, docker-compose/tail-sampling/Makefile, docker-compose/tail-sampling/docker-compose.yml
=> Replace JAEGER_IMAGE_TAG with JAEGER_VERSION

examples/hotrod/Dockerfile
- resolves #6626
- includes CA Certificates to the HOTRod image
- Tested with secured endpoint of upstream collector
=> fix(hotrod): include CA certificates for HOTRod Dockerfile

cmd/jaeger/internal/integration/badger_test.go, cmd/jaeger/internal/integration/cassandra_test.go, cmd/jaeger/internal/integration/kafka_test.go, cmd/jaeger/internal/integration/memory_test.go, plugin/storage/integration/badgerstore_test.go, plugin/storage/integration/cassandra_test.go, plugin/storage/integration/elasticsearch_test.go, plugin/storage/integration/grpc_test.go, plugin/storage/integration/integration.go, plugin/storage/integration/kafka_test.go, plugin/storage/integration/memstore_test.go
- Towards #6065
- This PR cleans up the integration test suite for jaeger-v1 by removing the archive related fields for all tests since they were being skipped anyway, with the exception of elasticsearch.
- Since the only storage that has a difference between primary and archive storage is ElasticSearch, this PR moves the archive trace test to `elasticsearch_test.go`.
- CI
=> [chore][tests] Clean up integration tests to remove archive reader / writer

cmd/jaeger/config.yaml, cmd/jaeger/internal/extension/jaegerquery/server.go, cmd/query/app/flags.go, cmd/query/app/flags_test.go, cmd/query/app/querysvc/query_service.go, cmd/query/app/querysvc/v2/querysvc/service.go, cmd/query/app/querysvc/v2/querysvc/service_test.go
Apply the `max_clock_skew_adjust` setting to the query service during initialization.
The maximum clock skew adjustment setting for the query component is properly read during initialization, but not applied in the v2 server in the end. This causes it to always default to 1 second, regardless of the configuration value.
- Resolves #6565 
- Initialize and set the `Adjuster` on both the v1 and v2 query options.
- The config defaults to `0` so applying this unconditionally would now disable the clock skew adjustment instead of defaulting to `1s`? However, the same _seems to be done_ in the older services from v1.
- Having a default of `1s` instead of `0` (which disables adjustments completely) might have been an accident?
- Not testing so far.
- for …
=> [v2][query] Apply "Max Clock Skew Adjust" setting

model/converter/json/sampling_test.go, model/converter/thrift/jaeger/sampling_from_domain.go, model/converter/thrift/jaeger/sampling_from_domain_test.go, model/converter/thrift/jaeger/sampling_to_domain.go, model/converter/thrift/jaeger/sampling_to_domain_test.go
- https://github.com/jaegertracing/jaeger/issues/6617#issuecomment-2624759289
- replace use of jaeger-idl/thrift-gen/sampling imports
- `make test lint'
=> Update import paths for jaeger thrift files to use jaeger-idl

cmd/all-in-one/main.go, cmd/collector/main.go, cmd/ingester/main.go, cmd/internal/env/command.go, cmd/query/app/flags.go, cmd/query/app/flags_test.go, cmd/query/main.go, cmd/remote-storage/main.go, internal/storage/integration/remote_memory_storage.go, internal/storage/v1/factory/config.go, internal/storage/v1/factory/config_test.go, internal/storage/v1/factory/factory.go, internal/storage/v1/factory/factory_test.go, internal/storage/v1/factory/package_test.go
- Towards #6637
- This PR moves the meta factory from `plugin/storage` to `internal/storage/v1/factory`
- CI
=> [refactor] Move `plugin/storage` to `internal/storage/v1/factory`

internal/storage/v1/elasticsearch/README.md
- This PR is to update the link about ElasticSearch shards optimization as the existing link cannot be accessed.
- update the link about ElasticSearch shards optimization.
- confirm the updated link can be accessed.
- [x ] I have read https://github.com/jaegertracing/jaeger/blob/master/CONTRIBUTING_GUIDELINES.md
- [x ] I have signed all commits
~~- [ ] I have added unit tests for the new functionality~~
~~- [ ] I have run lint and test steps successfully~~
~~ - for `jaeger`: `make lint test`~~
~~  - for `jaeger-ui`: `npm run lint` and `npm run test`~~
=> Update ElasticSearch article Link

cmd/jaeger/internal/exporters/storageexporter/exporter_test.go, cmd/jaeger/internal/extension/jaegerstorage/extension.go, cmd/jaeger/internal/extension/jaegerstorage/extension_test.go
- Resolves #6564
- Removes the final usage of `GetStorageFactory` from `extension_test.go` by replacing it with `GetTraceStoreFactory`
- CI
=> [refactor] Change `extension_test.go` to use `GetTraceStoreFactory` instead of `GetStorageFactory`

internal/storage/v2/v1adapter/tracereader.go, internal/storage/v2/v1adapter/tracereader_test.go
- Towards #6697
- This is a prequel to https://github.com/jaegertracing/jaeger/pull/6699. This PR refactors the `TraceReader` to conditionally propagate the implementations of `storage.Purger` and `storage.SamplingStoreFactory`. Without this change, the implementation of the aforementioned interfaces get lost when we wrap a v1 `SpanReader`. 
=> [refactor] Conditionally implement interfaces in `v1adapter`

internal/storage/v2/v1adapter/tracereader.go, internal/storage/v2/v1adapter/tracereader_test.go
- This PR reverts the changes to #6701 since v1 implements the `Purger` and `SamplingStoreFactory` on `storage.Factory` instead of on `spanstore.Reader`.
- CI
=> [fix] Revert changes to tracereader adapter 

cmd/all-in-one/main.go, cmd/query/main.go, internal/storage/v2/v1adapter/factory.go, internal/storage/v2/v1adapter/factory_test.go
- Towards #6697
- This is a prequel to https://github.com/jaegertracing/jaeger/pull/6699. This PR refactors `v1adapter.Factory` to conditionally propagate the implementations of `storage.Purger` and `storage.SamplingStoreFactory`. Without this change, the implementation of the aforementioned interfaces get lost when we wrap a v1 `storage.Factory` into the adapter.. 
=> [refactor] Conditionally implement interfaces in v1adapter factory

docker/debug/Dockerfile
script set it to 1.24.6 which doesn't exist
=> Fix go alpine version to 1.24.0

.github/workflows/label-check.yml
- https://github.com/jaegertracing/jaeger/issues/6712#issuecomment-2657267408
- Do not run label check step from merge queue, let workflow succeed
- CI
=> Do not run label check from merge queue

.github/workflows/ci-lint-checks.yaml
It fails in merge queue
```
Detected: GitHub CI
Unknown workflow event: merge_group
Error: Process completed with exit code 1.
```
- Skip this check in merge queue
- CI
=> Do not run dco-check from merge queue

cmd/es-rollover/app/init/action.go, cmd/es-rollover/app/init/action_test.go, internal/storage/integration/es_index_rollover_test.go, pkg/es/client/index_client.go, pkg/es/client/index_client_test.go, pkg/es/client/interfaces.go, pkg/es/client/mocks/IndexAPI.go
Fixes: #6203 
- Currently `es-rollover` checks for index existence through errors, it is mainly expecting the error:
```
{"error":{"root_cause":[{"type":"resource_already_exists_exception","reason":"]"}],"type":"resource_already_exists_exception","reason":"request [/jaeger-*] contains unrecognized parameter: [help]"},"status":400}
```
But it can lead to inconsistent results as found in the issue, where init was failing due to the error:
```
Error: failed to create index: jaeger-span-000001, request failed, status code: 400, body: {"error":{"root_cause":[{"type":"invalid_index_name_exception","reason":"Invalid index name [jaeger-span-000001], already exists as alias","index_uuid":"_na_","index":"jaeger-span-000001"}],"type":"invalid_index_name_exception","reason":"Invalid index name …
```
=> [bug][storage] Make ES-Rollover idempotent by checking if the index or alias already exist

cmd/query/app/http_handler.go, cmd/query/app/http_handler_test.go
- Follow up to #6608
- Resolves #6607
- Remove intermediate `data:` element from the response
- Match response to what the UI expects
- Fix unit test that wasn't testing the output
- unit tests
- manual test with https://github.com/jaegertracing/jaeger-ui/pull/2641
=> Fix /qualitymetrics to return data in expected format

.github/workflows/ci-lint-checks.yaml, Makefile, scripts/lint/check-jaeger-idl-version.sh
- Resolves #6743 
- Create a bash script for getting semantic versions of go.mod dependency and git submodule
- Update CI
- 
=> [test]: Check for jaeger-idl version mismatch

cmd/jaeger/internal/integration/trace_reader.go, cmd/query/app/apiv3/grpc_handler.go, cmd/query/app/apiv3/http_gateway.go, cmd/query/app/apiv3/http_gateway_test.go, internal/jptrace/attributes.go, internal/jptrace/attributes_test.go, internal/storage/integration/fixtures/queries.json, internal/storage/integration/integration.go, internal/storage/v2/api/tracestore/reader.go, internal/storage/v2/api/tracestore/reader_test.go, internal/storage/v2/v1adapter/spanreader.go, internal/storage/v2/v1adapter/spanreader_test.go, internal/storage/v2/v1adapter/tracereader_test.go
- Towards #6765
- Updates `TraceQueryParams` to change the `Attributes` field from a `map[string]string` to `pcommon.Map` to accept typed attributes to match the Remote Storage API v2 being developed as part of https://github.com/jaegertracing/jaeger/issues/6629
- CI
=> [refactor] Change `TraceQueryParams` to accept typed attributes

examples/hotrod/cmd/customer.go, examples/hotrod/cmd/driver.go, examples/hotrod/cmd/flags.go, examples/hotrod/cmd/frontend.go, examples/hotrod/cmd/root.go, examples/hotrod/cmd/route.go
Resolves #6774 
We want to allow users to configure the hostnames of the Hotrod services. This would allow users of the example app to run the services as separate containers.
The main change is to add hostname flags for each service. We pass these in as part of the `command` when running the containers. 
Example docker-compose usage:
```
hotrod-frontend:
container_name: hotrod-frontend
image: hotrod:0.1.0-alpha.2
ports:
- '8080:8080'
command: ["frontend", "--customer-service-hostname", "hotrod-customer", "-c", "8081", "--driver-service-hostname", "hotrod-driver", "-d", "8082", "--route-service-hostname", "hotrod-route", "-r", "8083"]
hotrod-customer:
container_name: hotrod-customer
image: ...
```
=> feat: Enable configuration of hostnames for hotrod services

cmd/jaeger/internal/integration/trace_reader.go, cmd/query/app/apiv3/grpc_handler.go, cmd/query/app/apiv3/http_gateway.go, cmd/query/app/apiv3/http_gateway_test.go, cmd/query/app/querysvc/v2/querysvc/service_test.go, internal/storage/integration/integration.go, internal/storage/v2/api/tracestore/reader.go, internal/storage/v2/api/tracestore/reader_test.go, internal/storage/v2/v1adapter/spanreader.go, internal/storage/v2/v1adapter/tracereader_test.go
- Towards #6629 and #6765
- This PR makes the following changes to converge the v2 storage API with the v2 remote storage API
- `NumTraces` -> `SearchDepth`
- Update documentation for `TraceQueryParams`
- CI
=> [refactor] Converge v2 API with v2 remote storage API

internal/jptrace/attributes_test.go
- This PR fixes a flaky test that was being caused because a map is not iterated in order and hence the insertion order of elements in a `pcommon.Map` is not guaranteed
- CI
=> [fix] Fix flaky unit test in `attributes_test.go`

cmd/jaeger/internal/integration/trace_reader.go, cmd/query/app/apiv3/grpc_handler.go, internal/jptrace/attributes.go, internal/jptrace/attributes_test.go, internal/storage/v2/api/tracestore/reader.go, internal/storage/v2/v1adapter/spanreader.go
- Addresses the leftover comments from https://github.com/jaegertracing/jaeger/pull/6785
- CI
=> [refactor] Refactor `jptrace/attributes_tests.go` for readability

internal/storage/v2/grpc/tracereader.go, internal/storage/v2/grpc/tracereader_test.go
- Towards #6789
- This PR implements the `GetOperations` call in the gRPC tracereader
- Added a unit test
=> [grpc][v2] Implement `GetOperations` Call in gRPC reader for remote storage api v2

renovate.json
- In light of https://semgrep.dev/blog/2025/popular-github-action-tj-actionschanged-files-is-compromised/, make sure all actions are pinned
- Turns out Renovate has this as a feature https://docs.renovatebot.com/modules/manager/github-actions/#digest-pinning-and-updating
- CI
=> Instruct Renovate to pin GitHub Action hashes

internal/sampling/http/handler.go
- Towards #4739
- This was the only dependency on cmd/agent from other packages. Once the next release of OTEL Contrib lands we can remove cmd/agent.
- Copy the interface into internal/sampling/http/handler.go
- CI
=> [refactor] Move interface to remove cmd/agent dependency

.github/workflows/ci-docker-all-in-one.yml
- Resolves #6880: Optimizes the all-in-one CI workflow by preventing unnecessary multi-architecture builds in the merge queue, reducing build times.
- Updated `.github/workflows/ci-docker-all-in-one.yml` to exclude multi-arch builds for merge queue events, similar to PR handling.
- This prevents sequential multi-arch builds, significantly improving CI efficiency.
=> [all-in-one] Avoid multi-arch builds in merge queue (#6880)

cmd/jaeger/internal/extension/remotesampling/config.go, cmd/jaeger/internal/extension/remotesampling/extension.go, internal/sampling/samplingstrategy/file/options.go, internal/sampling/samplingstrategy/file/provider.go, internal/sampling/samplingstrategy/file/provider_test.go
- Resolves #5270
- Remove v1 flag `--sampling.strategies.bugfix-5270`
- Make `jaeger.sampling.includeDefaultOpStrategies` feature stable, meaning it cannot be changed from `true` anymore
- Remove deprecated code
- CI
=> Remove sampling.strategies.bugfix-5270 flag and mark feature Stable

internal/storage/v2/grpc/tracewriter.go, internal/storage/v2/grpc/tracewriter_test.go
- Towards #6789 
- This PR implements the v2 gRPC trace writer using OTEL's gRPC exporter client. 
=> [grpc][v2] Implement v2 gRPC trace writer 

internal/storage/v2/grpc/depreader.go, internal/storage/v2/grpc/depreader_test.go, internal/storage/v2/grpc/tracereader_test.go
- Towards #6789 
- This PR implements the v2 gRPC dependency reader
=> [grpc][v2] Implement v2 gRPC dependency reader 

internal/storage/v2/grpc/tracereader.go, internal/storage/v2/grpc/tracereader_test.go
- Towards #6789
- This PR implements the `FindTraces` call in the gRPC v2 API client
=> [grpc][v2] Implement `FindTraces` Call in gRPC reader for remote storage api v2 

internal/storage/v2/grpc/config.go, internal/storage/v2/grpc/config_test.go, internal/storage/v2/grpc/factory.go, internal/storage/v2/grpc/factory_test.go
- Towards #6965
- This PR implements the following factories for gRPC storage
- `io.Closer`
- `tracestore.Factory`
- `depstore.Factory`
=> [grpc][v2] Implement gRPC v2 factory

scripts/release/start.sh
- Discovered some small issues while running the `scripts/release/start.sh` script.
- Able to successfully create the checklist from a cold start with these fixes in place: https://github.com/jaegertracing/jaeger/issues/6975
=> Minor fixes to release checklist generator

internal/storage/v2/grpc/handler.go, internal/storage/v2/grpc/handler_test.go
- Implement the `GetOperations` call in the gRPC v2 handler
=> [grpc][v2] Implement `GetServices` in grpc v2 handler

internal/storage/v2/grpc/handler.go, internal/storage/v2/grpc/handler_test.go
- Implement the `Traces` call in the gRPC v2 handler
=> [grpc][v2] Implement `GetTraces` in gRPC v2 handler

cmd/tracegen/README.md
Remove outdated info related to jaeger exporter from the tracegen readme
jaeger exporter is no longer supported, see https://github.com/jaegertracing/jaeger/pull/4717
=> Remove outdated info related to jaeger exporter

scripts/makefiles/BuildInfo.mk
I noticed that you have changed the version module path so we have to update the path in the ldflags too: https://github.com/jaegertracing/jaeger/blob/06840acda4e6ea5cec5afaa19356125595904231/CHANGELOG.md?plain=1#L86
=> [bug] Fix the version module path in ldflags

scripts/e2e/spm.sh
- part of https://github.com/jaegertracing/jaeger/issues/5608
- Add smoke test for /metrics/errors
- validate correct service name
- validate correct labels (case groupByOperation=true)
- run `scripts/e2e/spm.sh` locally
=> #5608 Improve SPM e2e test with test for error rate

internal/storage/v2/grpc/handler.go, internal/storage/v2/grpc/handler_test.go
- Implement the `FindTraces` call in the gRPC v2 handler
=> [grpc][v2] Implement `FindTraces` in gRPC v2 handler

internal/storage/integration/es_index_cleaner_test.go
RESOLVE #7002
**issue:** - The test `runIndexCleanerTest` was flaky because it included unrelated system indices (e.g., `top_queries-2025.04.08-51429`).
- Added `strings` import to use `strings.HasPrefix`.
- Filtered indices to only include those starting with `prefixWithSeparator + "jaeger-"`.
- Updated the assertion to use `filteredIndices` instead of raw `indices`.
**Impact:** Ensures the test only checks relevant Jaeger indices, improving reliability.
- [✓]I have read https://github.com/jaegertracing/jaeger/blob/master/CONTRIBUTING_GUIDELINES.md
- [✓] I have signed all commits
- [  ] I have added unit tests for the new functionality
- [✓]I have run lint and test steps successfully
=> Fix flakiness in runIndexCleanerTest by filtering Jaeger indices

internal/storage/v2/grpc/handler.go, internal/storage/v2/grpc/handler_test.go
- Implement the `FindTraceIDs` call in the gRPC v2 handler
=> [grpc][v2] Implement FindTraceIDs in gRPC v2 handler 

internal/storage/v2/elasticsearch/tracestore/fixtures/es_01_string_tags.json, internal/storage/v2/elasticsearch/tracestore/from_dbmodel.go, internal/storage/v2/elasticsearch/tracestore/from_dbmodel_test.go, internal/storage/v2/elasticsearch/tracestore/to_dbmodel.go, internal/storage/v2/elasticsearch/tracestore/to_dbmodel_test.go
Fixes a part of: #6458 
- As discussed in #6946 we need to change the value which was saved as string in v1 to a raw value in v2
- Unit Tests
=> [ES][v2] Change the DB Tag value from `string` to `any` type

internal/storage/v2/grpc/handler.go, internal/storage/v2/grpc/handler_test.go
- Implement the `Export` (from OTEL's Exporter API) call in the gRPC v2 handler
=> [grpc][v2] Implement OTLP exporter API in gRPC v2 handler

cmd/jaeger/internal/extension/jaegerquery/server.go, cmd/jaeger/internal/extension/jaegerquery/server_test.go, cmd/query/app/querysvc/query_service.go, internal/storage/v2/v1adapter/spanreader.go, internal/storage/v2/v1adapter/spanreader_test.go, internal/storage/v2/v1adapter/tracereader.go, internal/storage/v2/v1adapter/tracereader_test.go
- This PR consolidates the v1/v2 reader adapter functionality by combining `GetV1Reader` with `NewSpanReader`
- CI
=> [refactor] Consolidate v1/v2 reader factory adapter functionality 

cmd/collector/app/span_processor.go, cmd/jaeger/internal/extension/jaegerquery/server.go, cmd/jaeger/internal/extension/jaegerquery/server_test.go, internal/storage/v2/v1adapter/spanwriter.go, internal/storage/v2/v1adapter/spanwriter_test.go, internal/storage/v2/v1adapter/tracewriter.go, internal/storage/v2/v1adapter/tracewriter_test.go
- This PR consolidates the v1/v2 writer adapter functionality by combining `GetV1Writer` with `NewSpanWriter`
- CI
=> [refactor] Consolidate v1/v2 writer factory adapter functionality

internal/storage/v2/elasticsearch/tracestore/reader.go, internal/storage/v2/elasticsearch/tracestore/reader_test.go
-  Fixes a part of: #6458 
- Implement `GetOperations` and `GetServices` for v2 for ES/OS
- Unit Tests
=> [ES][v2] Implement `GetOperations` and `GetServices` for v2

cmd/remote-storage/app/server.go, cmd/remote-storage/app/server_test.go, internal/storage/v2/grpc/handler.go
- Registers the v2 gRPC handler in the remote-storage server
- CI 
=> [grpc][v2] Register gRPC v2 handler in remote-storage server

cmd/anonymizer/app/query/query_test.go
- Test failed sporadically https://github.com/jaegertracing/jaeger/actions/runs/14538973210/job/40793017264#step:8:16
- Block until test server starts
```
$ go test ./cmd/anonymizer/app/query
ok  	github.com/jaegertracing/jaeger/cmd/anonymizer/app/query	0.409s
```
=> [test] Block until server starts

.mockery.yaml, internal/storage/cassandra/mocks/Iterator.go, internal/storage/cassandra/mocks/Query.go, internal/storage/cassandra/mocks/Session.go, internal/storage/v1/cassandra/samplingstore/storage_test.go, internal/storage/v1/cassandra/spanstore/matchers_test.go, internal/storage/v1/cassandra/spanstore/reader_test.go, internal/storage/v1/cassandra/spanstore/service_names_test.go, internal/storage/v1/cassandra/spanstore/writer_test.go
- Final cleanup to accompany #7046
- Remove `with-expecter=true` for Cassandra and fix the tests
- CI
=> Remove last mockery/with-expecter=false

internal/storage/v2/memory/fixtures/db_traces_01.json, internal/storage/v2/memory/fixtures/db_traces_02.json, internal/storage/v2/memory/fixtures/otel_traces_01.json, internal/storage/v2/memory/memory.go, internal/storage/v2/memory/memory_test.go
- Fixes a part of: #7052 
- Implement GetOperations and GetServices for memory backend
- Unit tests
=> [v2] Implement `GetOperations` and `GetServices` for memory backend

cmd/jaeger/config-remote-storage-backend.yaml, cmd/jaeger/internal/integration/e2e_integration.go, cmd/jaeger/internal/integration/e2e_integration_test.go, cmd/jaeger/internal/integration/grpc_test.go, cmd/jaeger/internal/integration/query_test.go
- Resolves #7058
- The `jaeger_query` extension was previously added to `config-remote-storage-backend.yaml` solely to satisfy a requirement in the storage cleaner setup, even though it was otherwise unnecessary.
- This PR removes that dependency by relaxing the logic that creates the storage cleaner configuration. Instead of requiring `jaeger_query`, the code now first attempts to read the storage from the `jaeger_query` extension if available, and falls back to the `remote_storage` extension if it is not.
- CI
=> [refactor] Remove `jaeger_query` extension from remote storage backend config

internal/storage/elasticsearch/config/config.go, internal/storage/v1/elasticsearch/options.go, internal/storage/v1/elasticsearch/options_test.go
Currently, Jaeger sends its traces to ElasticSearch as uncompressed text. Since text is can be compressed quite well, enabling Gzip compression can significantly reduce Jaeger's network traffic. ElasticSearch has accepted compressed requests since version 5.0 and since the same version it has already sent compressed responses by default (cf. https://github.com/elastic/elasticsearch/commit/0a6f40c7f5f3af4e04a8875216e059025e1bbdf3).
* 🛑 (breaking change) **Enable by default** the compression for requests to ElasticSearch
* Add a new flag `--es.http-compression=true|false` that can be used to opt-out of compression . The setting is already supported by both client libraries that are used.
I tested the change running a local ElasticSearch instance and `SPAN_STORAGE_TYPE=elasticsearch …
=> feat(elasticsearch): add flag to enable gzip compression

internal/storage/v2/elasticsearch/depstore/storagev2.go, internal/storage/v2/elasticsearch/depstore/storagev2_test.go
- Fixes a part of: #7034 
- Upgrade DependencyStore for ES
- Unit Tests
=> [ES][v2] Implement `GetDependenies` and `WriteDependencies`

Makefile, scripts/makefiles/BuildBinaries.mk
- Resolves #7090
- Add validation to the build step that the version number is correctly embedded in the binary
- When reverting the fix done in #6990 the build fails:
```
$ make build-jaeger
echo "building binary for $(go env GOOS)-$(go env GOARCH)"; CGO_ENABLED=0 installsuffix=cgo go build -trimpath   -o ./cmd/jaeger/jaeger-darwin-arm64   -ldflags "-X   github.com/jaegertracing/jaeger/pkg/version.commitSHA=687207be86edb688436f8ef6c4383968a0ec1855 -X   github.com/jaegertracing/jaeger/pkg/version.latestVersion=v2.5.0 -X   github.com/jaegertracing/jaeger/pkg/version.date=2025-05-02T18:47:48Z" ./cmd/jaeger
building binary for darwin-arm64
❌ ERROR: version mismatch: want=v2.5.0, have=
make: *** [build-jaeger] Error 1
```
=> Check that version number is corectly embedded in the binary

.github/workflows/ci-lint-checks.yaml, cmd/jaeger/internal/components.go, go.mod, go.sum
- Resolves #6930
- Import `filterprocessor` as a counterpart to `attributeprocessor`
- Increases the binary size by 2.18%, more than our "accidental" threshold, but acceptable
```
Previous binary size: 100223599 bytes
New binary size:      102409625 bytes
❌ binary size increased by more than 2% (2.18%)
```
=> Add filterprocessor

.github/workflows/ci-lint-checks.yaml
- When previous PR #7094 was force-merged with binary size check failing (there's no way to override that check to succeed), the same check [failed](https://github.com/jaegertracing/jaeger/actions/runs/14816241094/job/41597074760) on `main` AND the steps to update the binary size cache did not run
- Change the check for size to not run when on the main branch
- The check is expected to still fail for this PR and will have to be force-merged
- But then the same check on main should succeed and update the cached value
=> Do not run binary size check on push to main

cmd/jaeger/config-remote-storage.yaml
- This PR allows the remote storage endpoint in `config-remote-storage.yml` to be set via an environment variable. The instructions for setting this PR will be added to https://github.com/jaegertracing/jaeger/pull/7097
- CI
=> [grpc] Allow remote storage endpoint to be set via environment variable

cmd/jaeger/config-remote-storage-backend.yaml, cmd/jaeger/config-remote-storage.yaml, cmd/jaeger/internal/integration/grpc_test.go, internal/storage/v2/grpc/README.md
- Removes the archive storage from the gRPC config as it is not being used in the integration test setup
- CI
=> [refactor] Remove archive storage from gRPC config

cmd/jaeger/internal/integration/README.md
- The original Mermaid diagram for the gRPC integration test setup only showed two binaries, but there are actually three involved. This PR updates the diagram to accurately reflect all three.
=> [fix] Fix mermaid diagram for gRPC integration test setup

cmd/jaeger/internal/exporters/storageexporter/README.md, cmd/jaeger/internal/exporters/storageexporter/config.go, cmd/jaeger/internal/exporters/storageexporter/factory.go, cmd/jaeger/internal/exporters/storageexporter/factory_test.go
- Resolves #7110
- Added retry configuration with all available parameters
- Updated documentation to reflect all configurable retry parameters
- Added tests in `storageexporter` package.
=> Add retry configuration to storage exporter

cmd/jaeger/config-spm-elasticsearch.yaml, docker-compose/monitor/docker-compose-elasticsearch.yml
- Partly solve jaegertracing/jaeger/issues/7142
- Add docker-compose/monitor/docker-compose-spm-elasticsearch.yaml as an easier way to start jaeger & SPM with elasticsearch storage.
- Add example configurations: cmd/jaeger/config-spm-elasticsearch.yaml and cmd/jaeger/config-spm-opensearch.yaml
- System test
=> Add docker-compose-elasticsearch.yml and its sample configuration

.github/workflows/ci-e2e-spm.yml, docker-compose/monitor/Makefile, scripts/e2e/spm.sh
- Partly solve https://github.com/jaegertracing/jaeger/issues/7142
- Add e2e test to exercise docker-compose-elasticsearch.yml file
- Through system test
=> Add e2e test for docker-compose-elasticsearch.yml file

docker-compose/monitor/README.md
- Part of https://github.com/jaegertracing/jaeger/issues/7142
- Add description for docker-compose-elasticsearch.yml in docker-compose/monitor/README.md
- make lint test
=> Add description for docker-compose-elasticsearch.yml

cmd/jaeger/internal/extension/jaegerstorage/extension.go, internal/storage/v1/elasticsearch/factory_v1.go, internal/storage/v1/elasticsearch/factoryv1_test.go
- Fixes a part of: #7034 
- Upgrade jaeger to use v2 APIs for ES/OS storage
- Unit and e2e
=> [feat] Use v2 ES/OS storage in Jaeger-v2

internal/storage/v2/clickhouse/tracestore/dbmodel/dbmodel.go, internal/storage/v2/clickhouse/tracestore/reader.go, internal/storage/v2/clickhouse/tracestore/reader_test.go
- Towards #7134
- Implemented a function to get operations from ClickHouse storage. 
- 
=> [clickhouse] Implement GetOperations for trace reader in ClickHouse storage

internal/storage/v1/elasticsearch/factory_test.go, internal/storage/v1/elasticsearch/spanstore/writer.go
- Resolves #7168 
- Sent different spans to both functions to stop data race
=> Fix data race in ESv1 WriteSpan by using distinct inputs

cmd/jaeger/internal/extension/jaegerstorage/extension.go, cmd/jaeger/internal/extension/jaegerstorage/extension_test.go, internal/storage/elasticsearch/config/config.go, internal/storage/elasticsearch/config/config_test.go, internal/storage/metricstore/elasticsearch/factory.go, internal/storage/metricstore/elasticsearch/factory_test.go, internal/storage/metricstore/elasticsearch/reader.go, internal/storage/metricstore/elasticsearch/reader_test.go, internal/storage/v1/elasticsearch/factory.go, internal/storage/v1/elasticsearch/factory_test.go, internal/storage/v1/elasticsearch/helper.go
- Partly solve https://github.com/jaegertracing/jaeger/issues/7208
- Add es.client to metricstore/elasticsearch/reader.go
- Use mockServer for factory_test and reader_test and refactor it
- make lint test
=> [spm] And esclient to es/reader.go and refactor test

internal/storage/v2/clickhouse/schema/schema.sql, internal/storage/v2/clickhouse/tracestore/dbmodel/dbmodel.go, internal/storage/v2/clickhouse/tracestore/dbmodel/from_dbmodel.go, internal/storage/v2/clickhouse/tracestore/dbmodel/from_dbmodel_test.go, internal/storage/v2/clickhouse/tracestore/reader.go, internal/storage/v2/clickhouse/tracestore/reader_test.go, internal/storage/v2/clickhouse/tracestore/testdata/assert.go, internal/storage/v2/clickhouse/tracestore/testdata/package_test.go, internal/storage/v2/clickhouse/tracestore/testdata/spans.go
- Towards #7134
- This PR implements the `GetTraces` function for ClickHouse storage. 
- This PR also introduces a schema that will later be used to auto-create the required tables upon instantiation of the ClickHouse factory. 
Started the ClickHouse server on my local machine using 
```
./clickhouse server
```
Initialized the tables using
```
/Users/mzaryab/clickhouse client --multiquery < schema.sql
```
Seeded the database using [test.sql](https://gist.github.com/mahadzaryab1/9b7243f637804e10b972647f82374bef#file-test-sql)
```
/Users/mzaryab/clickhouse client --multiquery < test.sql
```
Wrote a [Go unit test](https://gist.github.com/mahadzaryab1/9b7243f637804e10b972647f82374bef#file-reader_test-go) to run `GetTraces` and got the following output
```
Span: POST /api/order, Start: …
```
=> [clickhouse] Implement GetTraces for ClickHouse Storage

cmd/jaeger/internal/exporters/storageexporter/exporter_test.go, internal/jptrace/sanitizer/emptyservicename.go, internal/jptrace/sanitizer/negative_duration_santizer.go, internal/jptrace/sanitizer/readonly_test.go, internal/jptrace/sanitizer/utf8.go
- Resolves #7221 
Implement copy-on-write approach for all sanitizers:
- Check if modifications are needed before attempting changes
- Return original traces if no sanitization required
- Test mutability and create a copy if data is read-only
- Apply modifications to the working copy instead of original data
- Tests each sanitizer with read-only traces that need modification
- Tests each sanitizer with read-only traces that don't need modification
- Added test in storage exporter that reproduces the original panic scenario
=> [Fix] Prevent panic when sanitizing read-only traces with multiple exporters

cmd/jaeger/internal/extension/jaegerstorage/extension.go, internal/storage/integration/cassandra_test.go, internal/storage/v1/cassandra/factory.go, internal/storage/v1/cassandra/factory_test.go, internal/storage/v1/cassandra/helper.go, internal/storage/v2/cassandra/factory.go, internal/storage/v2/cassandra/factory_test.go, internal/storage/v2/cassandra/package_test.go
- Towards: #7050
- The responsibility of converting the v1 factory to v2 factory is now given to storage backend for cassandra
- Unit Tests
=> [cassandra] Give responsibility of creating v2 factory to storage backend

.github/workflows/ci-docker-all-in-one.yml
Added custom timeout for `all-in-one` job of the `Build all-in-one` workflow based on historical data that could lead to resource savings and faster CI for the project.
Over the last 2643 successful runs, the `all-in-one` job has a maximum runtime of 18 minutes (mean=6, std=4) across all matrix combinations.
However, there are failed runs that fail after reaching the threshold of 6 hours that GitHub imposes. In other words, these jobs seem to get stuck, possibly for external or random reasons. 
One such example is [this](https://github.com/jaegertracing/jaeger/actions/runs/13909902215/job/38921630813) job run, that failed after 6 hours. More stuck jobs have been observed over the last months, the first one on 21-Sep-2024 and the last one one on 17-Mar-2025, while more recent occurences …
=> Added custom timeout to docker-all-in-one CI job

examples/oci/README.md, examples/oci/deploy-all.sh, examples/oci/monitoring-values.yaml, examples/oci/prometheus-deploy.yaml, examples/oci/prometheus.yml
- Added Deployment script to deploy the whole setup with bash command (Jaeger demos + Monitoring stack + load-generator )
- Added helm chart deployment for prometheus + grafana + alert manager 
- All of the setup configured directly from their respective values.yaml 
Screentshots ( forced dark mode enabled due to chrome extension) : 
250708_122947.png…]()
- [ *] I have read https://github.com/jaegertracing/jaeger/blob/master/CONTRIBUTING_GUIDELINES.md
- [ *] I have signed all commits
- [ *] I have added unit tests for the new functionality
- [ *] I have run lint and test steps successfully
=> Add Jaeger Demo Monitoring Setup with Deployment Script

internal/storage/metricstore/elasticsearch/processor.go, internal/storage/metricstore/elasticsearch/processor_test.go, internal/storage/metricstore/elasticsearch/reader_test.go, internal/storage/metricstore/elasticsearch/testdata/output_call_rate_operation.json
- Fix 2 bugs of the current implementation in https://github.com/jaegertracing/jaeger/issues/7147
Bug 1: The current `calcCallRate` overvalue the call rate when after a long period of having no data, this is caused by setting 
`if math.IsNaN(firstValue) { firstValue = 0 }`
**Reference images:** 
When compares to the working solution: 
Some other timestamp & service:
**Solution**: Use 	`lastNonNaNMap := make(map[string]float64)` that tracks the lastNonNaN value associates with different labels key. When I rerun with this changes, the problem is now fixed: 
When compares to the working solution: 
Bug 2: Add 0 data point for service that don't return any data point for errorRate. This changes is made with `zeroValue`
- Add `lastNonNaNmap` to fix bug 1
- Add `zeroValue` to fix bug 2
- CI
- …
=> [spm] Bug fix for metricstore/elasticsearch/processor.go

examples/oci/README.md, examples/oci/ingress.yaml
- Setup Ingress service for external usage of jaeger deployment on k8s 
- The ingress service needs to be deployed once per cluster 
- Also made changes to README.md 
- [* ] I have read https://github.com/jaegertracing/jaeger/blob/master/CONTRIBUTING_GUIDELINES.md
- [ *] I have signed all commits
- [* ] I have added unit tests for the new functionality
- [ *] I have run lint and test steps successfully
=> Ingress service for Jaeger demo deployment 

.github/workflows/ci-e2e-spm.yml, cmd/jaeger/config-spm-opensearch.yaml, cmd/jaeger/internal/extension/jaegerstorage/config.go, cmd/jaeger/internal/extension/jaegerstorage/config_test.go, cmd/jaeger/internal/extension/jaegerstorage/extension.go, cmd/jaeger/internal/extension/jaegerstorage/extension_test.go, docker-compose/monitor/Makefile, docker-compose/monitor/docker-compose-opensearch.yml, scripts/e2e/spm.sh
- Resolves part of https://github.com/jaegertracing/jaeger/issues/7232
- Add option for OpenSearch inside config.go and extension.go
- Add e2e test for OpenSearch spm
- CI
- Manual testing
=> [spm] Add opensearch option

internal/storage/v1/elasticsearch/mappings/mapping.go
- Addresses part of #7274 by ensuring proper index template selection for Elasticsearch v9.
- Modified mapping logic to treat Elasticsearch v9 the same as v8 for template selection.
- This avoids the need for a separate v9 template file and prevents runtime errors due to missing mappings.
- Verified by running `jaeger-query` and `jaeger-collector` using Elasticsearch v9 as the storage backend.
- Confirmed that the services start successfully and ingest/query traces without template-related errors.
=> Reuse v8 index templates for Elasticsearch v9

examples/oci/ingress.yaml, examples/oci/jaeger-values.yaml, examples/oci/monitoring-values.yaml
- Solve the issue of base path for hotrod ui and grafana ui 
- Changed ingress , helm values of jaeger and monitoring stack
=> Serve Hotrod UI and Grafana from Separate Basepaths in Jaeger Demo

CONTRIBUTING.md
Update documentation to highlight the need for GNU sed when running `make test`, especially on macOS systems where BSD sed is the default. This helps avoid test failures due to sed incompatibilities.
Resolves #7329
Changes are in the docs.
=> docs: Add prerequisites for running make test

internal/storage/v2/elasticsearch/tracestore/to_dbmodel.go, internal/storage/v2/elasticsearch/tracestore/to_dbmodel_test.go
- Resolves #7346 
- Problem:
- when traces contained array valued tags like `[value1, value2]`, the ui showed `invalid string type` error
- this happened because collection type attributes were not properly handled during elasticsearch storage
- Root Cause:
- In `internal/storage/v2/elasticsearch/tracestore/to_dbmodel.go`, the `attributeToDbTag` function only handled `ValueTypeMap` for JSON serialization
- `ValueTypeSlice` (arrays) were falling through to the default case, this causing the type mismatching
- solution:
- added `pcommon.ValueTypeSlice` to the existing case that handles JSON serialization
- Created a test scenario in HotRod that generates array-valued tags `(blockers: ["7510-2"])`
- added unit tests to prevent regression
Screenshot:
- for …
=> Fixed invalid string type issue for array-valued tags

examples/oci/jaeger-values.yaml, examples/oci/monitoring-values.yaml
- Add probe path for deployment 
- Removed http_port from grafana configuration 
=> Add readiness and liveness probe paths to Demo deployment for improved health checks

examples/oci/deploy-all.sh, examples/oci/jaeger-values.yaml, examples/oci/prometheus-svc.yaml
- Fix the issue where hotrod redirected to jaeger-ui to localhost 
- Deleted unused YAML in one of the previous PRs but that was indeed needed to help jaeger access the prometheus database when created with helm . 
- add --force flag to ensure upgrade are not done inplace but by recreating the pods 
- locally on a kind cluster 
=> Multiple minor changes in Jaeger demo deployment in OKE 

examples/oci/README.md, examples/oci/config.yaml, examples/oci/deploy-all.sh, examples/oci/ingress.yaml, examples/oci/jaeger-values.yaml
- Part of #7115
- Changed base path for jaeger deployment 
- Changed redirect path on jaeger hotrod 
- add a dummy ingress to redirect 
- made changes to deployment script 
- locally on kind cluster 
=> Redirect to demo documentation in Jaeger demo deployment 

.golangci.yml, cmd/anonymizer/main.go, internal/storage/v1/grpc/shared/grpc_client.go, internal/storage/v2/clickhouse/tracestore/dbmodel/to_dbmodel.go
- enable rangeValCopy from go-critic
- 
- 
=> chore: enable rangeValCopy from go-critic

.github/workflows/ci-comment.yml, .github/workflows/ci-e2e-all.yml, internal/storage/v1/api/spanstore/spanstoremetrics/read_metrics.go, scripts/e2e/metrics_summary.py
- Continues on https://github.com/jaegertracing/jaeger/pull/7376
- Resolves part of https://github.com/jaegertracing/jaeger/issues/6278
- Add post pr comment workflow
- 
=> [CI] Add new post comment workflow

.github/workflows/ci-comment.yml, .github/workflows/ci-e2e-all.yml
- Resolves part of https://github.com/jaegertracing/jaeger/issues/6278
- Supports https://github.com/jaegertracing/jaeger/pull/7414
- Add upload pr_number artifacts action
- The ci-comment.yml workflow can now detect pr number by downloading the artifact
- from my repostory pull request: https://github.com/pipiland2612/jaeger/pull/2
- log from the action https://github.com/pipiland2612/jaeger/actions/runs/16997159461/job/48190513998: 
```
Successfully extracted metrics_snapshot_elasticsearch_8.x_v2
Processing artifact: diff_metrics_snapshot_elasticsearch_8.x_v2 (ID: 3776313824)
Extracting to /home/runner/work/jaeger/jaeger/.metrics/diff_metrics_snapshot_elasticsearch_8.x_v2
Successfully extracted diff_metrics_snapshot_elasticsearch_8.x_v2
Starting PR number detection...
Workflow run …
```
=> [CI] Add upload pr_number artifacts action to ci-e2e-all.yml

cmd/tracegen/docker-compose.yml
- Fix #7480 
- Use jaeger v2 instead of v1
Running docker compose I was able to see tracegen service
=> chore(jaeger-tracegen): upgrade tracegen docker compose to jaeger-v2

CHANGELOG.md, RELEASE.md
Part of https://github.com/jaegertracing/jaeger/issues/7496
=> Prepare release 1.73/2.10

CHANGELOG.md, RELEASE.md
=> Prepare release 1.74.0 / 2.11.0
