model/adjuster/ip_tag.go, model/adjuster/ip_tag_test.go
=> Add IP tag adjuster

cmd/builder/builder_options.go, cmd/collector/app/builder/span_handler_builder.go, cmd/collector/app/builder/span_handler_builder_test.go, cmd/flags/flags.go, cmd/query/app/builder/memory.go, cmd/query/app/builder/memory_test.go, cmd/query/app/builder/storage.go, cmd/query/app/builder/storage_test.go, cmd/standalone/main.go, storage/spanstore/memory/memory.go, storage/spanstore/memory/memory_test.go
=> Create standalone jaeger main with a backing in memory store.

Makefile, cmd/query/app/adjusters.go, cmd/query/main.go, model/adjuster/sort_log_fields.go, model/adjuster/sort_log_fields_test.go
- Add StandardAdjusters for query service
- Migrate SortLogFields
=> Migrate SortLogFields model adjuster; add StandardAdjusters for query service

plugin/storage/cassandra/cassandra3v001-schema.sh
Fixes https://github.com/uber/jaeger/issues/82
=> Add CQL schema generation script

plugin/storage/cassandra/spanstore/reader.go
Fixes https://github.com/uber/jaeger/issues/83
=> Introduce limit multiple

.travis.yml, travis/install-ui-deps.sh
Changing travis to only install necessary dependencies for the given matrix env
=> Improve travis build times

.travis.yml, crossdock/Dockerfile, crossdock/main.go, crossdock/rules.mk, travis/build-all-in-one-image.sh, travis/build-crossdock.sh, travis/upload-to-docker.sh
- Uploading the crossdock test-driver to docker hub so that other clients can use it for testing.
- Refactoring docker upload script
- Using gliderlabs/alpine image for test-driver (smallest image possible with shell 7MB)
=> Upload test driver

Makefile, cmd/query/app/handler.go, cmd/query/app/handler_options.go, cmd/query/app/handler_test.go, cmd/query/main.go
Fixed https://github.com/uber/jaeger-ui/issues/8
=> Use standard adjusters from all-in-one

docs/getting_started.md
Fixes https://github.com/uber/jaeger-client-node/issues/121
=> [docs] Expose all ports in Docker command

Makefile, travis/build-docker-images.sh
Fixes the image tagging, currently failing on Travis: 
https://travis-ci.org/uber/jaeger/jobs/236245547#L1096
=> Specify the docker tag during the build

cmd/standalone/Dockerfile, docs/getting_started.md
Todo: integration tests for http endpoints
=> Update standalone dockerfile and docs

crossdock/services/tracehandler.go, crossdock/services/tracehandler_test.go
Moving the code over from internal repo and adding tests
=> Add adaptive sampling crossdock tests

cmd/flags/flags.go
=> Remove unused flags

cmd/query/app/static_handler.go, cmd/query/app/static_handler_test.go, cmd/query/main.go, cmd/standalone/main.go, crossdock/main.go
* Fixes #144
* Adds trailing `/` to the path if it's missing
=> Append trailing slash to static asset root

travis/build-docker-images.sh, travis/upload-to-docker.sh
* Allow Docker Hub push if there is a release tag in the `v#.#.#` format
* Add alias tags `major` and `major.minor`
=> Push to Docker Hub on release tags

plugin/storage/es/spanstore/reader.go, plugin/storage/es/spanstore/reader_test.go, plugin/storage/es/spanstore/service_operation.go, plugin/storage/es/spanstore/service_operation_test.go
forgot to move the reader fns to the `service_operation.go` file
=> Move ES Service/Operation Reader to other file

cmd/agent/app/builder.go, cmd/agent/app/flags.go, cmd/agent/app/flags_test.go, cmd/agent/main.go, cmd/standalone/main.go, crossdock/docker-compose.yml, crossdock/main.go, pkg/metrics/builder.go, pkg/metrics/builder_test.go
This is part of #235 but applied only for agent.
cc @yurishkuro
=> Configuration viper/cobra - agent only

plugin/storage/es/esCleaner.py, plugin/storage/es/es_indices_clean.sh, scripts/esCleaner.py
=> Add ES Curator script

cmd/collector/app/builder/builder_flags.go, cmd/collector/app/http_handler.go, cmd/collector/app/http_handler_test.go, cmd/collector/app/zipkin/http_handler.go, cmd/collector/app/zipkin/http_handler_test.go, cmd/collector/main.go, cmd/standalone/main.go, docs/getting_started.md
=> Zipkin api/v1/spans endpoint

cmd/query/app/handler.go, cmd/query/app/handler_test.go
=> Do not fail multi-trace search if some traces are not found

cmd/query/app/builder/cassandra.go
Related to https://github.com/uber/jaeger/pull/316
=> C* Remove default proto version from query command

cmd/flags/cassandra/options.go, pkg/cassandra/config/config.go
=> Add basic authenticator to configs for Cassandra

cmd/collector/app/builder/span_handler_builder.go, cmd/collector/app/sanitizer/zipkin/span_sanitizer.go, cmd/collector/app/sanitizer/zipkin/span_sanitizer_test.go
=> Zipkin error tag sanitizer

cmd/flags/cassandra/options.go, cmd/flags/es/options.go
=> TODO about default values in storage options

cmd/builder/builder_options.go, cmd/builder/builder_options_test.go, cmd/collector/app/builder/span_handler_builder.go, cmd/collector/app/builder/span_handler_builder_test.go, cmd/collector/main.go, cmd/query/app/builder/cassandra.go, cmd/query/app/builder/cassandra_test.go, cmd/query/app/builder/elastic_search.go, cmd/query/app/builder/elastic_search_test.go, cmd/query/app/builder/memory.go, cmd/query/app/builder/memory_test.go, cmd/query/app/builder/storage.go, cmd/query/app/builder/storage_test.go, cmd/query/main.go, cmd/standalone/main.go, pkg/es/config/config.go
=> Refactor storage configuration

cmd/collector/app/builder/span_handler_builder.go, cmd/collector/app/sanitizer/zipkin/span_sanitizer.go, cmd/collector/app/sanitizer/zipkin/span_sanitizer_test.go, cmd/collector/app/span_handler_test.go, cmd/collector/app/span_processor_test.go
I could not find where these loggers are used
=> Remove loggers from zipkin sanitizers

ADOPTERS.md, README.md
=> Add adopters list

docs/getting_started.md
=> Doc improve migration from zipkin

pkg/distributedlock/interface.go, pkg/distributedlock/mocks/Lock.go, plugin/pkg/distributedlock/cassandra/lock.go, plugin/pkg/distributedlock/cassandra/lock_test.go
Implement forfeit method for `distributedlock` interface and plugin.
=> Implement forfeit lock.

model/converter/thrift/zipkin/fixtures/jaeger_01.json, model/converter/thrift/zipkin/fixtures/zipkin_01.json, model/converter/thrift/zipkin/to_domain.go
=> Update Zipkin toDomain to handle 128bit traceId and ipv6

pkg/discovery/peerlistmgr/peer_list_mgr.go
Additional log messages will help in diagnosing connection issues between the agent and the collector, as seen in #261.
=> log error message when unable to connect to jaeger-collector

travis/build-docker-images.sh
https://github.com/uber/jaeger/issues/283
=> Docker images update :latest tag per commit in master

Makefile
=> Makefile use  GNU sed and force thrift to use the same user

CODEOWNERS
=> Add Pavol Loffay to CODEOWNERS

docs/deployment.md
=> Documented how to run the agent via Docker with a remote collector

crossdock/docker-compose.yml, crossdock/main.go, model/converter/thrift/zipkin/to_domain.go, model/converter/thrift/zipkin/to_domain_test.go
Fixes #181 #337. 
It uses https://hub.docker.com/r/pavolloffay/xdock-zipkin-brave/ with https://github.com/pavolloffay/xdock-zipkin-brave/pull/1/files. Once this is approved I will move it to jaegertracing.
=> Zipkin json and thrift xdock tests

ADOPTERS.md
@Dieterbe @tanner-bruce please review
=> Add GrafanaLabs and FarmersEdge to Adopters

.travis.yml, Makefile, crossdock/docker-compose.yml, crossdock/rules.mk, travis/build-all-in-one-image.sh, travis/build-crossdock.sh, travis/build-docker-images.sh, travis/upload-to-docker.sh
related to #283 
It also fixes all-in-one image, latest is published per commit and added release tags.
=> Docker images do not push SHA and travis build number tags

ADOPTERS.md
We're expanding our production deployment of jaeger at UA!
=> Adding Under Armour to adopters

README.md
This is required of CNCF projects.
=> Mention CNCF in README

.travis.yml, crossdock/services/tracehandler.go, model/converter/thrift/zipkin/to_domain.go, plugin/storage/es/dependencystore/storage.go, plugin/storage/es/spanstore/reader_test.go, plugin/storage/es/spanstore/writer.go
per https://github.com/uber/jaeger/issues/409
=> Define import path in preparation of repository move to jaegertracing

docs/deployment.md
=> Docs spark job

README.md
Signed-off-by: Chris Aniszczyk <caniszczyk@gmail.com>
=> Add FOSSA license scanning badge

README.md
=> Add Building From Source section

CONTRIBUTING.md, scripts/updateLicense.py
=> Rename future copyright headers to The Jaeger Authors

CHANGELOG.md
=> Preparing release 0.9.0

ADOPTERS.md
=> Add Kausal to adopters.md

README.md
=> Added CII Best Practices badge

docs/getting_started.md
Signed-off-by: Kara de la Marck <karadelamarck@gmail.com>
=> Change Running Instructions

docs/deployment.md
Add information on UI configuration to the deployment docs.
=> Add info on UI configuration to docs

README.md
=> Added weekly meeting details to README

GOVERNANCE.md
=> Change maintainer nominations to public

docs/getting_started.md, docs/index.md
=> Docs: mention golang version

docs/getting_started.md
=> Docs: update migration from zipkin

cmd/collector/app/zipkin/annotation.go, cmd/collector/app/zipkin/annotation_test.go, model/converter/thrift/jaeger/fixtures/model_01.json, model/converter/thrift/jaeger/fixtures/model_03.json, model/converter/thrift/jaeger/fixtures/thrift_batch_01.json
Fixes https://github.com/jaegertracing/jaeger/issues/553
=> Remove HAProxy zipkin check

crossdock/docker-compose.yml, crossdock/main.go
Related to https://github.com/jaegertracing/jaeger/issues/547#issuecomment-347459583
=> test-driver increase wait time in healthcheck

RELEASE.md
=> Describe release process

cmd/agent/app/servers/tbuffered_server.go
discussion here: https://gitter.im/jaegertracing/Lobby?at=5a31aea1c65707ba2b4bfe1d
=> Fix SIGSEGV in tbuffered_server

cmd/collector/app/zipkin/fixtures/zipkin_02.json, cmd/collector/app/zipkin/jsonv2.go, cmd/collector/app/zipkin/jsonv2_test.go
=> Zipin add lc to keep service name

cmd/collector/app/zipkin/fixtures/zipkin_01.json, cmd/collector/app/zipkin/jsonv2.go, cmd/collector/app/zipkin/jsonv2_test.go
https://github.com/jaegertracing/jaeger/pull/566 with added test cc @moolex and thanks
=> Parse zipkin v2 high trace id

cmd/query/app/query_parser.go, cmd/query/app/query_parser_test.go
=> Extend query API to allow passing tags as JSON string

plugin/storage/cassandra/spanstore/dbmodel/tag_filter.go, plugin/storage/cassandra/spanstore/dbmodel/tag_filter_test.go
=> Add ChainedTagFilter

Makefile
Since original bug is fixed in glide 0.13
Resolves #629
=> Simplify install-glide command

cmd/collector/main.go, cmd/query/main.go, pkg/healthcheck/handler.go, pkg/healthcheck/handler_test.go, pkg/healthcheck/internal_test.go
=> Refactor healthcheck pkg, fix race condition in tests

CHANGELOG.md
=> Preparing release 1.1.0

docs/deployment.md, docs/index.md
=> Clarify supported storage backends and versions

cmd/flags/flags.go
=> Fix variable name in the help line

README.md, examples/hotrod/.gitignore
=> Add Features section to the readme

ADOPTERS.md
Signed-off-by: Ed Kelley <ekelleyv@gmail.com>
=> Add SeatGeek to ADOPTERS.md

examples/hotrod/cmd/customer.go, examples/hotrod/cmd/driver.go, examples/hotrod/cmd/frontend.go, examples/hotrod/cmd/root.go, examples/hotrod/cmd/route.go, examples/hotrod/pkg/tracing/init.go, examples/hotrod/services/customer/server.go, examples/hotrod/services/driver/redis.go, examples/hotrod/services/driver/server.go
=> Make agent host port configurable in hotrod

plugin/storage/integration/domain_trace_compare_test.go, plugin/storage/integration/elasticsearch_test.go, plugin/storage/integration/integration_test.go, plugin/storage/integration/memstore_test.go, scripts/travis/es-integration-test.sh
=> Extend integration tests to memory storage

CHANGELOG.md
=> Preparing release 1.2.0

glide.lock, glide.yaml, plugin/storage/factory_test.go
See https://github.com/jaegertracing/jaeger/pull/702#issuecomment-367381845
=> Pin testify version to 1.2.1

pkg/healthcheck/handler.go
fix typos in healthcheck handler
Signed-off-by: Eundoo Song <eundoo.song@gmail.com>
=> fix typos in healthcheck handler

cmd/query/app/handler.go, cmd/query/app/static_handler.go, cmd/query/app/static_handler_test.go, cmd/query/main.go, cmd/standalone/main.go
the code was duplicated in standalone/query mains.
Signed-off-by: Yuri Shkuro ys@uber.com
=> Move static handler registration into a shared function

pkg/metrics/builder.go
=> Fixes #697 - Disable compression on Prom Handler

pkg/metrics/builder.go, pkg/metrics/builder_test.go
=> Apply namespace when creating Prometheus metrics factory (fix for #732)

scripts/travis/hotrod-integration-test.sh
Fixes: https://travis-ci.org/jaegertracing/jaeger/jobs/356860777#L785
=> Publis hotrod only when TRAVIS_SECURE_ENV_VARS is true

Makefile
=> Revert 7a9ca55

.github/ISSUE_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE.md
As of https://github.com/jaegertracing/jaeger/issues/785
Signed-off-by: B0go <victorbogo@icloud.com>
=> Add Issue template and pull request template

ADOPTERS.md
refs https://github.com/jaegertracing/jaeger/issues/207#issuecomment-386604451
=> Add ContaAzul to the adopters list

model/adjuster/ip_tag.go, model/adjuster/ip_tag_test.go
Signed-off-by: cem turker <cemturker92@gmail.com>
Resolves #821
- Process IP problem/inconsistency #821
-  Added support to process float 64 type entered ip addresses.
=> Process IP problem/inconsistency (#821)

.travis.yml, plugin/storage/integration/kafka_test.go, scripts/travis/kafka-integration-test.sh
- Kafka writer did not have an integration test
=> Add Kafka Integration Test

model/span.go
- Some things just deserve to be public
-
=> Expose span flags

ADOPTERS.md
None -- Adding SpotHero as a user
Adds SpotHero as a user of Jaeger
=> Add SpotHero to adopters

pkg/cassandra/config/config.go
=> Fix cassandra DisableAutodiscovery config variable name

CHANGELOG.md
=> Prepare release 1.6.0

.travis.yml
=> Fix deploy step

cmd/collector/app/builder/span_handler_builder_test.go, cmd/collector/app/grpc_handler.go
PR to @yurishkuro's branch for him to include or redo on the grpc branch.
=> Simple fixes

plugin/storage/es/spanstore/reader.go
Clone of #969 just trying to build rebased PR
=> Fix hard-coded ES spanType

cmd/ingester/app/consumer/offset/manager.go, cmd/ingester/app/consumer/offset/manager_test.go, cmd/ingester/app/consumer/processor_factory_test.go
Only mark offsets if there is a change in offsets
=> Cache offset commits

pkg/recoveryhandler/zap.go, pkg/recoveryhandler/zap_test.go, plugin/storage/cassandra/samplingstore/storage_test.go
Signed-off-by: Isaac Hier <isaachier@gmail.com>
- Fixes #1039.
- Use casting to suppress error.
=> Fix Go 1.11 incompatibilities

Makefile
=> Fix gosec 107 - request with variable URL

Makefile, cmd/collector/app/sanitizer/cache/auto_refresh_cache.go, cmd/collector/app/sanitizer/cache/auto_refresh_cache_test.go, cmd/collector/app/span_processor.go, cmd/collector/app/span_processor_test.go, cmd/collector/main.go, cmd/ingester/main.go, cmd/query/main.go, cmd/standalone/main.go, model/converter/json/from_domain_test.go, model/converter/thrift/zipkin/to_domain.go, pkg/es/config/config.go, pkg/testutils/logger_test.go, plugin/storage/es/spanstore/reader.go
- Resolves #1045.
- Add gosimple to lint task. Apply existing suggestions to code.
=> Add gosimple

.travis.yml
=> Fix deploy process not being run

plugin/storage/integration/kafka_test.go
=> Fix failing kafka integration test

cmd/collector/app/builder/builder_flags.go
- 
typo error, the CollectorZipkinHTTPort should be CollectorZipkinHTTPPort
-
=> change CollectorZipkinHTTPort to CollectorZipkinHTTPPort

Makefile
=> Fix golit link

scripts/travis/es-integration-test.sh
=> Bump ES docker version

plugin/storage/integration/integration_test.go
=> Use UTC time in integration tests

ADOPTERS.md
Signed-off-by: Zachary DiCesare <zachary.v.dicesare@gmail.com>
=> Add Vistar to ADOPTERS.md

plugin/storage/integration/elasticsearch_test.go
=> Fix flaky elasticsearch integration test

ADOPTERS.md
@bboreham - ok with you?  Based on https://youtu.be/qg0ENOdP1Lo
=> Add Weaveworks to adopters

CHANGELOG.md, cmd/agent/app/reporter/tchannel/flags.go, cmd/agent/app/reporter/tchannel/flags_test.go, docker-compose/jaeger-docker-compose.yml
Resolves https://github.com/jaegertracing/jaeger/issues/927#issuecomment-437959791
=> Remove collector from tchannel reporter flag

crossdock/services/query.go
To address https://github.com/jaegertracing/jaeger/issues/1191#issuecomment-441072859
=> Fix misleading log line

CHANGELOG.md
=> Add changelog for 1.8.1

CHANGELOG.md
=> Add changelog for 1.8.1 (#1209)

CHANGELOG.md
=> Add changelog for 1.8.2

CHANGELOG.md
=> Backport from 1.8.2 to master

cmd/query/app/ui/actual/statik/.nocover
=> Exclude query/statik package from coverage

scripts/travis/build-all-in-one-image.sh, scripts/travis/install-ui-deps.sh
=> Bump UI to 1.0.0

scripts/travis/build-docker-images.sh
Resolves https://travis-ci.org/jaegertracing/jaeger/jobs/482303968#L750
=> Use node 8 when building docker images

CHANGELOG.md
=> Add date to changelog to 1.9 release

RELEASE.md
=> Add documentation step into release guide

plugin/storage/es/factory.go
=> Pass primary ES client to the main span writer

Gopkg.toml
- Resolves #1335 
Update Sarama to latest version that includes a related fix as per: https://github.com/Shopify/sarama/releases
=> Update Sarama to 1.20.1

.travis.yml, Makefile, plugin/storage/cassandra/schema/docker.sh, plugin/storage/integration/cassandra_test.go, scripts/travis/cassandra-integration-test.sh
Testing https://github.com/jaegertracing/jaeger/pull/1328 is a pain in the ass without integration tests.
This will increase travis build times unfortunately.
=> Add cassandra integration tests

plugin/storage/es/esCleaner.py, plugin/storage/es/esRollover.py
=> Support certificates in elasticsearch scripts

ADOPTERS.md, README.md
- Fix http link to https link for secure. 
- Modify http to https in the links of project. Have some http links does not redirect into https.
=> Change http to https for security links

CHANGELOG.md
=> Preparing release 1.10.0

.travis.yml
Related to https://github.com/jaegertracing/jaeger/issues/1321#issuecomment-464113535
=> Skip deploy in non deploy jobs

CHANGELOG.md, model/json/model.go
This commit aims to remove some duplicated words in this project
Co-Authored-By: Nguyen Phuong An <AnNP@vn.fujitsu.com>
Signed-off-by: Kim Bao Long <longkb@vn.fujitsu.com>
- 
- Remove duplicated words
=> Remove the duplicated words

CHANGELOG.md
=> Preparing release 1.10.1

model/hash.go
"calcualtes" to "calculates" in line 29.
=> Fix typo in comment

pkg/testutils/logger_test.go
"occurences" to "occurrences".
=> Fix some misspells in logger_test.go

cmd/query/app/ui/actual/doc.go
- Small fix on top of Pavol's commit 9c18cfc7f60b54f05f7ecc3c1f84e8cad9f33784.
-`dep ensure` will complain about malformed code from cmd/query/app/ui/actual folder. We need to add an empty file to get around it.
=> [fix] Allow importing code as library via dep

CHANGELOG.md
=> Add missing items to changelog for 1.11

.github/PULL_REQUEST_TEMPLATE.md, CONTRIBUTING_GUIDELINES.md
Resolves #1413 
This change replaces the incorrect links in the .MD files with the correct ones.
=> Replacing the wrong link with the correct.

cmd/agent/app/builder.go, cmd/agent/main.go, cmd/all-in-one/main.go, cmd/collector/main.go, cmd/ingester/main.go, cmd/query/main.go
=> Ensure grpclog is only set once

.codecov.yml
=> Lower coverage threshold

plugin/storage/es/Dockerfile, plugin/storage/es/Dockerfile.rollover
=> Pin urllib3 version to unblock image build

cmd/query/app/grpc_handler_test.go
Signed-off-by: stefan vassilev <stefanvassilev1@gmail.com>
- Resolves #1483
- Remove boilerplate code
- Merge creation of grp server with options with creation of grp server without specifying options.
=> Simplify grpc_hanlder_test.go

plugin/storage/grpc/README.md
#1518, create a README for developing grpc storage plugins
Added a README detailing how to develop a grpc storage plugin
=> Create README for developing grpc storage plugins #1518

CHANGELOG.md
=> Prepare release 1.12.0

Makefile
Fixes 
> make: Circular changelog <- changelog dependency dropped.
=> Fix chagelog target in make

examples/hotrod/README.md, examples/hotrod/docker-compose.yml
=> Add docker-compose for HotROD example

plugin/storage/grpc/README.md
Signed-off-by: Charles Dixon <chvckd@gmail.com>
The gRPC storage plugin README is slightly incorrect.
Update the README to reflect what is actually correct with regards to logging.
=> Update storage gRPC plugin README

CHANGELOG.md
Address https://github.com/jaegertracing/jaeger/pull/1442#issuecomment-500558296
=> Add missing breaking change to the changelog

plugin/storage/es/mappings/gen_assets.go, plugin/storage/es/mappings/jaeger-span.json
Supersedes #1383 
Resolves #1382
=> Define logs as nested data type

CONTRIBUTING.md
- nil
- update on contribution guide
=> Minor update on contribution guide

CHANGELOG.md
- Updates https://github.com/jaegertracing/jaeger/issues/1592
- Update breaking changes for new `sampler_type` tag for traces metrics
=> Update changelog to include breaking change trace metric tag sampler_type

CHANGELOG.md
Resolves #1592 
Blocked by https://github.com/jaegertracing/jaeger/pull/1589
=> Preparing release 1.13.0

plugin/storage/es/dependencystore/storage.go, plugin/storage/es/dependencystore/storage_test.go
Related to https://github.com/jaegertracing/jaeger/pull/1620
=> Remove deprecated index prefix from dependency store

CHANGELOG.md
=> Preparing release 1.13.1

storage/spanstore/downsampling_writer.go, storage/spanstore/downsampling_writer_benchmark_test.go, storage/spanstore/downsampling_writer_test.go
- https://github.com/jaegertracing/jaeger/issues/1661
- Capitalize `shouldDownsample` so external components could use it.
=> Minor refactor to make ShouldDownsample publicly accessible

storage/spanstore/downsampling_writer.go
- #1661 
- Minor change to return pointer instead
=> Minor change to return Sampler as pointer

plugin/storage/es/esCleaner.py
Resolves https://github.com/jaegertracing/jaeger/pull/1689#discussion_r307765086
=> Use find by regex for archive index in index cleaner

examples/hotrod/cmd/root.go
Signed-off-by: Guangming Wang <guangming.wang@daocloud.io>
- correct the flag message, make it more understandable.
- just words correction.
=> cleanup: fix word in flag help message

cmd/collector/app/metrics.go, cmd/collector/app/service_name_normalizer.go, pkg/cassandra/gocql/testutils/udt.go, pkg/discovery/grpcresolver/grpc_resolver.go, pkg/queue/bounded_queue.go
Signed-off-by: Guangming Wang <guangming.wang@daocloud.io>
- cleanup code base by fix typo
- just fix comment in code
=> Cleanup: fix some typos in code comment

model/span.go, model/span_test.go, plugin/storage/cassandra/spanstore/writer.go, plugin/storage/cassandra/spanstore/writer_test.go
Part of #1731 
- Add firehose flag to skip indexing
=> Add firehose flag to bypass indexing

cmd/agent/Dockerfile
Resolves #1760, similar to #598.
@jpkrohling @pavolloffay please review
=> Add CA certificates to agent image

CHANGELOG.md
=> Preparing release 1.14.0

examples/hotrod/services/customer/database.go, examples/hotrod/services/frontend/web_assets/index.html
No sand, more pom pom purin
- A typo
- Fixing a typo
=> We want Japanese Desserts not Deserts

plugin/storage/badger/dependencystore/storage_test.go, plugin/storage/badger/spanstore/read_write_test.go, plugin/storage/grpc/README.md
Signed-off-by: yuxiaobo <yuxiaobogo@163.com>
- Grammatical correction.
- Delete extra words.
=> Grammatical correction

cmd/query/app/http_handler.go, cmd/query/app/server.go, examples/hotrod/services/driver/interface.go, plugin/storage/badger/factory.go
Signed-off-by: yuxiaobo <yuxiaobogo@163.com>
- 
- Modify word spelling errors.
=> Modify word spelling errors

model/adjuster/clockskew_test.go, model/converter/thrift/zipkin/to_domain.go, pkg/discovery/grpcresolver/grpc_resolver.go
Signed-off-by: yuxiaobo <yuxiaobogo@163.com>
- 
- Perfect documentation.
=> Improve the quality of the documents

cmd/ingester/app/consumer/processor_factory.go
- Allows for configuring RetryOptions when calling NewProcessorFactory
=> [refactor] Add RetryOptions to ProcessorFactoryParams

plugin/storage/es/README.md
Signed-off-by: Jonah Back <jonah@jonahback.com>
- Removes incorrect documentation
- Removes a limitation that was addressed in #292
=> Remove incorrect elasticsearch limitation in README

CONTRIBUTING.md
=> Update CONTRIBUTING.md fix #1834

plugin/storage/es/mappings/gen_assets.go, plugin/storage/es/spanstore/reader_test.go
=> Fix flaky ES span reader test due to date differences

README.md
Shows fuzzing status with build status.
Proposing to show fuzzing status in the readme. Thank you for considering.
Meant to include this in the fuzzing integration #1787.
=> Add Fuzzit badge

Makefile, cmd/all-in-one/all_in_one_test.go, scripts/travis/build-all-in-one-image.sh, scripts/travis/install-ui-deps.sh
Not clear why build failing in https://github.com/jaegertracing/jaeger/pull/1854#issuecomment-541224934, https://travis-ci.org/jaegertracing/jaeger/jobs/596790829
=> Enable logs from all-in-one integration test

README.md
verbage might need a little tuning
- 
-
=> Mention badger in the main Readme

CHANGELOG.md, RELEASE.md
Signed-off-by: Jun Guo <guo0693@gmail.com>
- 
-
=> Preparing release 1.15.0

examples/hotrod/services/config/config.go, examples/hotrod/services/customer/client.go, examples/hotrod/services/route/client.go, examples/memstore-plugin/main.go
- Corrected malformed code
- Use gofmt to correct malformed code.
=> [hotrod]: Apply go fmt

plugin/storage/cassandra/spanstore/reader.go
=> Remove ineffectual context assignment

cmd/agent/app/processors/thrift_processor.go
Although it is spelling mistakes, it might make an affects while reading.
Signed-off-by: Kim Bao Long <longkb@vn.fujitsu.com>
- None
- Remove the duplicated words
=> Fix some typo in comment

Gopkg.lock, Gopkg.toml, pkg/discovery/grpcresolver/grpc_resolver.go, pkg/discovery/grpcresolver/grpc_resolver_test.go
=> Upgrade gRPC to ^1.26

CHANGELOG.md
Signed-off-by: Albert Teoh <albteo@uber.com>
- 
-
=> Preparing release 1.17.0

Makefile
- Remove TODO comment since proto generation inside docker container is merged.
=> Remove TODO comment in makefile

CHANGELOG.md
=> Bump UI to 1.8 and changelog for 1.17.1

.gitignore
Signed-off-by: ZouYu <zouy.fnst@cn.fujitsu.com>
-  NONE
-  Ignore vscode settings file
=> Ignore vscode settings file

.travis.yml, cmd/opentelemetry-collector/app/defaults/default_config.go, cmd/opentelemetry-collector/app/defaults/default_config_test.go, cmd/opentelemetry-collector/main.go, crossdock/docker-compose.yml, crossdock/jaeger-opentelemetry-docker-compose.yml, crossdock/otel-agent-config.yml, crossdock/rules.mk, plugin/sampling/strategystore/static/strategy_store.go
=> Test OTEL collector in xdock

cmd/opentelemetry-collector/app/defaults/merge_test.go, cmd/opentelemetry-collector/app/defaults/testdata/addprocessor-override.yaml, cmd/opentelemetry-collector/app/defaults/testdata/multiplecomponents-override.yaml, cmd/opentelemetry-collector/cmd/agent/main.go, cmd/opentelemetry-collector/cmd/collector/main.go, cmd/opentelemetry-collector/go.mod, cmd/opentelemetry-collector/go.sum, crossdock/otel-agent-config.yml
=> Bump to OTEL version that supports loading empty config

cmd/opentelemetry-collector/app/defaults/default_config_test.go, cmd/opentelemetry-collector/app/exporter/cassandra/factory_test.go, cmd/opentelemetry-collector/app/exporter/elasticsearch/factory_test.go, cmd/opentelemetry-collector/app/exporter/grpcplugin/factory_test.go, cmd/opentelemetry-collector/app/exporter/kafka/factory_test.go, cmd/opentelemetry-collector/app/exporter/span_writer_exporter_test.go, cmd/opentelemetry-collector/app/receiver/kafka/factory_test.go
=> Use assert.contains in error testing

CHANGELOG.md
=> Preparing release v1.18.0

pkg/netutils/port_test.go
Signed-off-by: ZouYu <zouy.fnst@cn.fujitsu.com>
- NONE
- Add unit test case
=> Add unit test case for pkg/netutils/port_test.go

cmd/opentelemetry-collector/app/exporter/memoryexporter/factory_test.go
=> Change approach to test cleanup to maintain go 1.13 compatibility

cmd/opentelemetry-collector/app/exporter/cassandraexporter/exporter.go, cmd/opentelemetry-collector/app/exporter/cassandraexporter/factory.go, cmd/opentelemetry-collector/app/exporter/elasticsearchexporter/exporter.go, cmd/opentelemetry-collector/app/exporter/elasticsearchexporter/factory.go, cmd/opentelemetry-collector/app/exporter/kafkaexporter/exporter.go, cmd/opentelemetry-collector/app/exporter/kafkaexporter/factory.go
Hiding unnecessary exposed APIs.
=> Make some APIs private in OTEL components

cmd/opentelemetry-collector/app/exporter/badgerexporter/doc.go, cmd/opentelemetry-collector/app/exporter/grpcpluginexporter/doc.go, cmd/opentelemetry-collector/app/exporter/kafkaexporter/doc.go, cmd/opentelemetry-collector/app/exporter/memoryexporter/doc.go, cmd/opentelemetry-collector/app/receiver/kafkareceiver/doc.go
=> Add godoc for OTEL component packages

Makefile
Got a feeling these should be `.PHONY`?
=> Typofix (.PHONE to .PHONY)

cmd/opentelemetry/go.mod, go.mod, go.sum
=> Bump go to 1.14 in go.mod and run tidy

.travis.yml
- system version updates for installing new version docker
-
=> updates to ubuntu:bionic in travis

plugin/storage/badger/spanstore/read_write_test.go
=> cleanup tempfiles for read_write_test

examples/hotrod/services/driver/client.go, examples/hotrod/services/driver/server.go
- 
- 
I found that [ALL_SRC](https://github.com/jaegertracing/jaeger/blob/master/Makefile#L6-L21) does not include some folders in the Makefile, which results in the format of some files that cannot be detected by make fmt. Not sure if this is acceptable.
=> Apply go fmt

CHANGELOG.md
Revert UI back to 1.9 due to a bug https://github.com/jaegertracing/jaeger-ui/issues/628
=> Prepare release 1.19.1

cmd/opentelemetry/app/internal/esclient/client.go
=> fix misspell

cmd/opentelemetry/app/internal/reader/es/esspanreader/span_reader_test.go
- fix ineffectual assignment to err
- add err verification for span_reader_test
=> [test] Add err verification to span_reader_test

cmd/opentelemetry/app/receiver/jaegerreceiver/jaeger_receiver.go
I forgot to push this change https://github.com/jaegertracing/jaeger/pull/2438#discussion_r480169442
@joe-elliott could you please review?
=> Trivial: simplify if statement

go.mod, go.sum
There are a bunch of bug fixes and improvements: https://github.com/uber-go/zap/releases/tag/v1.16.0
=> Upgrade zap to v1.16

cmd/query/app/flags.go
=> Log deprecation warning only when deprecated flags are set

cmd/opentelemetry/app/exporter/elasticsearchexporter/esmodeltranslator/modeltranslator.go, cmd/opentelemetry/app/exporter/elasticsearchexporter/esmodeltranslator/modeltranslator_test.go, cmd/opentelemetry/app/exporter/elasticsearchexporter/storagefactory_test.go
=> Rename container to spanData

plugin/storage/grpc/README.md
Signed-off-by: Andrew Putilov <to.merge@gmail.com>
- Readme for issue #2299 and pr #2317
- Updated `plugin/storage/grpc/README.md` according to new grpc archive storage api change.
=> Grpc plugin archive storage readme

CHANGELOG.md
=> Preparing release 1.20.0

cmd/opentelemetry/cmd/all-in-one/main.go
Signed-off-by: Toufik Zarouali <zerouali.t@gmail.com>
- This fixes #2581 
- Handle error returned by `cmd.ParseFlags(os.Args)`.
=> Exit properly after displayed help

cmd/all-in-one/main.go, cmd/collector/app/collector.go
- Add more idiomatic go in `cmd/collector/main.go` 
- Delete nested code, Add error blank identifiers, and use `Fprint*` to display err.
=> Clean-up error handling and logging

Makefile, cmd/anonymizer/Dockerfile, scripts/travis/upload-all-docker-images.sh
I realised in v1.21.0 we didn't had the anonymizer binary and docker image due to missing Makefile targets. This PR adds those.
- Update Makefile for anonymizer specific targets.
- Add Dockerfile for anonymizer.
=> [anonymizer] Update Makefile and Dockerfile

ADOPTERS.md
None
Just add our company name and link to the ADOPTERS, as suggested by @jpkrohling . Thanks to the Jaeger team.
=> Add PalFish to ADOPTERS

.github/workflows/unit-tests.yml
This PR is the first step in moving from travis to github action.
We run the unit tests and coverage job in github action. 
Sample Run: https://github.com/Ashmita152/jaeger/actions/runs/383055239
=> Add github action for unit test and coverage

plugin/storage/badger/dependencystore/storage_test.go, plugin/storage/badger/factory.go, plugin/storage/badger/spanstore/read_write_test.go, plugin/storage/badger/spanstore/rw_internal_test.go, plugin/storage/badger/spanstore/writer.go
Remove inverted dependency of Badger SpanWriter on Badger Storage Factory.
Fixes #2642.
=> Clean-up Badger factory Close() behavior

plugin/storage/badger/factory_test.go, plugin/storage/badger/stats_linux_test.go, plugin/storage/badger/stats_test.go
Signed-off-by: Li Zhijian <lizhijian@cn.fujitsu.com>
- 
-
=> [tests]: call Close() to cleanup temporary directory

.github/workflows/codeql.yml, .github/workflows/fossa.yml
per https://github.com/jaegertracing/jaeger/issues/2645#issuecomment-734935515
=> Clean-up GH action names

.github/workflows/memory-badger-integration-tests.yml, plugin/storage/integration/badgerstore_test.go
Closes https://github.com/jaegertracing/jaeger/issues/2659
Update the integration test based on the cleanup done in badger factory close() function.
=> Fix for failures in badger integration tests

scripts/travis/upload-to-docker.sh
Remove any travis related variable
Fix for https://github.com/jaegertracing/jaeger/pull/2668#issuecomment-735534880
/cc @yurishkuro
=> Fix issue with all-in-one build

examples/hotrod/README.md
- Fix typo in hotrod README.md
=> Fix typo in hotrod README.md

cmd/env/command_test.go
- 
- Replace deprecated function in command_test.go
=> Replace deprecated function in command_test.go

CHANGELOG.md
Signed-off-by: rjs211 <srivatsa211@gmail.com>
- Add changelog entry for Query server TLS support
- Adding changelog entry for changes done in #2337
=> Add changelog entry for Query server TLS support

examples/grafana-integration/README.md, examples/grafana-integration/docker-compose.yaml
- Grafana integration example don't run correctly
- Fix Docker compose file to mount correctly the dashboard volume
- Fix minimal typos and fix the example Loki query in README file
=> Fix Grafana example

RELEASE.md
- Ensure announcement of release is always last.
- Explicit instructions on how to verify the various releases.
- Provide troubleshooting tips.
- Links for where announcements should be made.
=> Improve release notes

plugin/storage/cassandra/factory_test.go, plugin/storage/cassandra/options.go, plugin/storage/es/factory_test.go, plugin/storage/es/options.go
=> Remove unused NewOptionsFromConfig

cmd/anonymizer/main.go, cmd/query/main.go, docker-compose/jaeger-docker-compose.yml
- Code specification：change variable name replacing golang's keyword "error"
- "error" is golang's keyword. It's better not to make it as a variable.
=> Change variable name from error to err

CONTRIBUTING.md, README.md
- Fixes #2113
- Sets in stone the agreed upon proposed protocol for handling CLI flag deprecation and removal.
- README.md updated for the benefit of users who want to understand the stability guarantees.
- CONTRIBUTING.md updated to provide instructions to contributors introducing and removing deprecated CLI flags.
=> Add deprecation notes in documentation

model/proto/metrics/README.md, model/proto/metrics/otelmetric.proto, model/proto/metrics/otelspankind.proto
- Address review comments from https://github.com/jaegertracing/jaeger/pull/2946#pullrequestreview-650211822 
- Fix the copied OTEL proto to a tagged version.
- docker -> container
=> Fix proto version

cmd/collector/app/options.go
=> Fix comment.

CHANGELOG.md
=> Preparing release v1.23.0

plugin/sampling/strategystore/adaptive/aggregator.go, plugin/sampling/strategystore/adaptive/aggregator_test.go, plugin/sampling/strategystore/adaptive/root_span_handler.go, plugin/sampling/strategystore/adaptive/root_span_handler_test.go, plugin/sampling/strategystore/adaptive/span.go, plugin/sampling/strategystore/adaptive/span_test.go
Replace #3063 to run from non-master branch (because on master other tests fail)
Closes #3063
=> Add adaptive sampling files

CHANGELOG.md
=> Preparing release 1.24.0

scripts/package-deploy.sh
Clean up extra spaces, although these errors are not important, they affect the code specification.
- 
-
=> Clean up extra spaces

.github/workflows/ci-elasticsearch.yml
=> Upgrade ES images in integration tests

RELEASE.md
Removed past releases and added future releases keeping the order from the removed releases.
=> Update the release schedule with 1.30/1.31

monitoring/jaeger-mixin/README.md, monitoring/jaeger-mixin/monitoring-setup.example.jsonnet
This PR synchronizes the monitoring mixin examples from the readme and from the jsonnet files. It also adds a missing plus on the final summary.
=> Fix monitoring mixin examples

plugin/storage/memory/sampling.go
Signed-off-by: Hu Shuai <hus.fnst@fujitsu.com>
- Fix golint issue
- Fix a golint issue caused by typo: SamplingStroe --> SamplingStore
=> Fix golint issue

CHANGELOG.md, RELEASE.md
=> Prepare release v1.29.0

.github/workflows/ci-all-in-one-build.yml, .github/workflows/ci-build-binaries.yml, .github/workflows/ci-cassandra.yml, .github/workflows/ci-crossdock.yml, .github/workflows/ci-docker-build.yml, .github/workflows/ci-elasticsearch.yml, .github/workflows/ci-grpc-badger.yml, .github/workflows/ci-hotrod.yml, .github/workflows/ci-kafka.yml, .github/workflows/ci-protogen-tests.yml, .github/workflows/ci-unit-tests.yml, .github/workflows/codeql.yml, .github/workflows/fossa.yml, scripts/build-crossdock.sh, scripts/build-upload-a-docker-image.sh
=> Remove master from CI config/scripts

CHANGELOG.md, RELEASE.md
=> Prepare release 1.30.0

cmd/ingester/app/consumer/consumer_test.go, go.mod, go.sum
=> Bump github.com/Shopify/sarama from 1.30.1 to 1.31.0

scripts/es-integration-test.sh
Signed-off-by: Ashmita Bohara <ashmita.bohara@logz.io>
- Resolves https://github.com/jaegertracing/jaeger/issues/3411
- We are waiting for elasticsearch/opensearch to be ready before running the integration tests
- Bumping opensearch container version to 1.2.0.
=> Wait for elasticsearch/opensearch to be ready before running the integration tests

README.md, cmd/collector/app/span_processor_test.go, plugin/storage/integration/cassandra_test.go
Re-apply fixes to comments and tests from stale PRs.
Closes #3098, #2919, #3073.
=> Apply comments/tests fixes from stale PRs

.golangci.yml, plugin/storage/grpc/shared/grpc_server.go
- Enable misspell linter
- Fixes one misspell
=> Enable misspell linter

.golangci.yml
=> enable contextcheck linter

.gitignore, Makefile, cmd/remote-storage/Dockerfile, scripts/build-upload-docker-images.sh
=> Build remote-storage

CHANGELOG.md
=> Prepare release v1.38.0

go.mod, go.sum
=> Bump golang.org/x/net to 2022-09-26

plugin/storage/es/mappings/.nocover
The package already has 100% test coverage
Signed-off-by: Yuri Shkuro <yurishkuro@users.noreply.github.com>
=> Delete unnecessary .nocover

docker-compose/monitor/README.md
Signed-off-by: Albert Teoh <see.kwang.teoh@gmail.com>
=> Fix example python script name

CHANGELOG.md, RELEASE.md
Updated changelog.md, release.md and jaeger-ui submodule for 1.40.0.
=> Prepare release 1.40.0

.github/workflows/ci-release.yml
Signed-off-by: Joe Elliott <number101010@gmail.com>
- 
-
=> correct crazy max

.github/workflows/ci-kafka.yml, plugin/storage/integration/integration.go
Temporary workaround for #4420
=> Pin Kafka to 3.1.0 to avoid CI job failure

RELEASE.md
Adding @jkowall as release manager for July and bumping the other folks +1 month. Going to give it a go!
Thanks.
=> Adding myself as release manger for July

CHANGELOG.md, README.md, _To_People_of_Russia.md
https://github.com/vshymanskyy/StandWithUkraine/issues/4
=> Raise awareness of current Russia-Ukraine situation, targeting Russian 🇷🇺 readers

examples/hotrod/README.md, examples/hotrod/pkg/log/factory.go, examples/hotrod/pkg/tracing/baggage.go, examples/hotrod/pkg/tracing/init.go, examples/hotrod/services/customer/database.go
- Part of https://github.com/jaegertracing/jaeger/issues/3380
=> [hotrod] Remove most references to OpenTracing

cmd/tracegen/main.go, examples/hotrod/pkg/tracing/init.go, examples/hotrod/pkg/tracing/rpcmetrics/observer.go, examples/hotrod/pkg/tracing/rpcmetrics/observer_test.go, plugin/storage/cassandra/spanstore/reader.go
Make usage consistent across the codebase
=> Bump otel/semconv usage to v1.20

README.md, go.mod, go.sum, pkg/jtracer/jtracer.go
* This PR removes `opentracing pkg` from jtracer pkg and go.mod file
- Removes `opentracing pkg` from `jaeger module` and modifies README file to rmv OT support.
=> Removes `opentracing pkg` from `jaeger module`

.github/workflows/ci-all-in-one-build.yml
=> [fix] Use pr-only mode for PRs only

cmd/collector/app/metrics.go, cmd/collector/app/metrics_test.go, model/span.go, model/span_pkg_test.go
- Minor clean-up after #4681
- Add tests for `model.SamplerType.String()`
- Refactor `cmd/collector/app/metrics.go` to use `model.SamplerType` more directly
- Unit tests
=> [chore] Add tests and remove unnecessary constants

examples/hotrod/services/driver/server.go
- UI has the ability to display JSON tag value nicely rendered, but HotROD did not produce any spans with JSON tag values
- Log driver locations as a JSON string
Expand `driver.DriverService/FindNearest` span and look for the last log entry:
collapsed
expanded
=> [hotrod] Log driver locations as JSON to demo respective UI capability

scripts/release-notes.py
- Per discussion in https://github.com/jaegertracing/jaeger-ui/pull/1844/files#r1345598291, we'd like to reference the release notes in this repo from the jaeger-ui repo.
- This PR makes some modifications needed for https://github.com/jaegertracing/jaeger-ui/pull/1844.
- Used to generate the changelog in https://github.com/jaegertracing/jaeger-ui/pull/1844.
=> Ensure each changelog entry is capitalized

plugin/storage/cassandra/schema/docker.sh, plugin/storage/integration/cassandra_test.go
- Cassandra tests started failing frequently, once more tests were enabled (in #4776)
- Skip `Multiple Traces` test
- CI
=> Skip Multiple_traces integration test for Cassandra

plugin/storage/es/factory_test.go
- Resolves #4743 (third time a charm?)
- Do not rely on span write to synchronously reach the fake server
- Keep track of all passwords seen by the server
- Assert that the 2nd password shows up
- unit test
=> test: Keep track of both passwords

Makefile
- Remove copy-paste redundant code
- Parameterize binary building
- CI
=> Simplify binary building in Makefile

SECURITY-INSIGHTS.yml, SECURITY.md, SELF-ASSESMENT.md, THREAT-MODEL.md
Adding security policy to SECURITY.md 
Adding a couple of sections to the SECURITY-INSIGHTS.yml to fix missing items.
Next step is to check the CLOMonitor for other gaps - Need to build a threat model too.
Only text changes in this PR.
- [Not needed] I have added unit tests for the new functionality
- [Not needed] I have run lint and test steps successfully
=> fix dependency policy and add to SECURITY-INSIGHTS.yml

.github/workflows/ci-all-in-one-build.yml
=> ci: Build jaeger v2 image on main branch runs

SECURITY-INSIGHTS.yml
Fixing a typo in the yaml
Added a tab
Not needed
- [Not needed] I have added unit tests for the new functionality
- [Not needed] I have run lint and test steps successfully
=> Fix typo in SECURITY-INSIGHTS.yml

crossdock/services/agent_test.go, crossdock/services/pakcage_test.go, crossdock/services/query_test.go, examples/hotrod/pkg/tracing/rpcmetrics/observer_test.go, examples/hotrod/pkg/tracing/rpcmetrics/package_test.go, internal/metrics/expvar/cache_test.go, internal/metrics/expvar/package_test.go, internal/metrics/fork/fork_test.go
- part of #5006
- fix goroutine leaks and add goleak check 
- go test
=> Fix goroutine leaks in some packages

README.md
Fixes for #5071
Fixed CNCF  Graduated image badge was not loading properly
=> Fixed CNCF  Graduated image badge loading

CHANGELOG.md
Depends on https://github.com/jaegertracing/jaeger-ui/pull/2097
=> Prepare release v1.53.0

RELEASE.md
Change the Tentative release date for version 1.57.0 to 1 May 2024
- 
=> Fix future release date

RELEASE.md
Suggested update to the release instructions to clarify that the jaeger-ui submodule only should be checked for updates.
=> Release notes update

plugin/metrics/prometheus/metricsstore/reader_test.go
- Solves part of https://github.com/jaegertracing/jaeger/issues/5006
- Enables testutils.VerifyGoLeaks and fixes the one violation.
- `make test lint`
=> Fix goroutine leaks in prometheus/metricsstore tests

MAINTAINERS.md
Fixed typo, thanks for the catch @yurishkuro 
re: https://github.com/jaegertracing/jaeger/issues/5363
=> Fixing capitalization

README.md
Fix to help with security and visibility per https://github.com/jaegertracing/jaeger/issues/5363
Adding a new badge we already have
- [NA] I have added unit tests for the new functionality
=> Adding best practices badge to README.md

plugin/storage/integration/badgerstore_test.go, plugin/storage/integration/cassandra_test.go, plugin/storage/integration/elasticsearch_test.go, plugin/storage/integration/es_index_cleaner_test.go, plugin/storage/integration/grpc_test.go, plugin/storage/integration/kafka_test.go
- Minimize cross-function dependencies
=> [tests] Simplify integration tests

cmd/jaeger/internal/extension/remotesampling/README.md, cmd/jaeger/internal/integration/README.md
- These diagrams were sprinkled in the tickets, can easily get lost
- Add them to READMEs
=> [v2] Add diagrams to the docs

cmd/agent/app/agent.go
- Spurious failure of tests in main due to a data race https://github.com/jaegertracing/jaeger/actions/runs/9312817206/job/25634207633#step:8:15
- Most likely because the agent logs "http server exiting" from the server goroutine, which may happen after Close returned and the test finished, this causing a log to be written to finished testing.T
- use WaitGroup and block Close until goroutine is done
```
$ go test -race -count 10 ./cmd/agent/app
ok  	github.com/jaegertracing/jaeger/cmd/agent/app	11.416s
```
but this is not really conclusive since it does not always reproduce the data race
=> [agent/test] Wait for goroutine to exit

.github/dependabot.yml
- #5552
- try different config
- CI
=> Attempt another fix to dependabot config

.github/dependabot.yml
- Config is currently broken, but the change in #5560 removed one of the errors
- Apply similar change to the other entries
- Fix image name for opensearch
- cannot test it until merged
=> Fix .github/dependabot.yml

docker-compose/opensearch/v2/docker-compose.yml
- Resolves #5624
- added password env flag 
- 
=> Update opensearchproject/opensearch to v2.14.0

CHANGELOG.md, scripts/release-notes.py
- Merging changelog update from `patch-1.58.1` branch
- Small fix to release notes to allow overriding branch name for pulling changes (was tested when creating release notes for `1.58.1`)
=> Update changelog with patch release 1.58.1

scripts/check-goleak-files.sh, scripts/check-test-files.sh
Print messages on success too.
=> Clearer output from lint scripts

cmd/agent/app/customtransport/buffered_read_transport.go, cmd/agent/app/reporter/grpc/flags.go, cmd/agent/app/servers/thriftudp/socket_buffer.go, cmd/collector/app/collector.go, cmd/collector/app/flags/flags.go, cmd/collector/app/span_handler_builder.go, cmd/collector/app/span_processor.go, model/converter/thrift/jaeger/to_domain.go, model/converter/thrift/zipkin/to_domain.go, model/time.go, pkg/es/config/config.go, plugin/storage/badger/spanstore/cache.go, plugin/storage/badger/spanstore/writer.go, plugin/storage/cassandra/dependencystore/storage.go, plugin/storage/cassandra/spanstore/dbmodel/converter.go, plugin/storage/cassandra/spanstore/writer.go, plugin/storage/es/options.go, plugin/storage/integration/integration.go
fixes #5974 
- fixing the problem created during upgrade of the linter
- 
=> coverage while upgrading linter

cmd/agent/README.md
=> [agent] Add deprecation notice to the readme

pkg/cassandra/config/config.go
Address https://github.com/jaegertracing/jaeger/issues/5797#issuecomment-2509176512
=> [cassandra] Change compaction window default to 2hrs

cmd/collector/app/sanitizer/service_name_sanitizer.go, pkg/es/client/index_client.go, storage_v2/tracestore/writer.go
- 
fix some struct names in comment
resubmit for https://github.com/jaegertracing/jaeger/pull/6253 and  https://github.com/jaegertracing/jaeger/pull/6509
- 
=> chore: fix some struct names in comment

.github/workflows/ci-lint-checks.yaml, scripts/lint/check-jaeger-idl-version.sh
- The test in #6753 was still failing, even with the submodule update
- Try to fetch tags
- CI
=> [idl check] Fetch tags

CHANGELOG.md, RELEASE.md
=> Prepare release v1.67.0/v2.4.0

scripts/lint/dco_check.py
=> Make dco check email case-insensitive

cmd/agent/app/servers/server.go
- Simplify code, in preparation to migrating to OTEL #6704
- Remove unnecessary Server interface, just alias it to concrete struct.
- CI
=> [agent] Remove unnecessary Server interface

.golangci.yml, internal/fswatcher/fswatcher_test.go, internal/jaegerclientenv2otel/envvars_test.go, internal/sampling/samplingstrategy/file/provider_test.go, internal/storage/metricstore/prometheus/metricstore/reader_test.go, internal/storage/v1/elasticsearch/mappings/command_test.go
- Resolves #6892 
- Added `usetesting` linter.
- Fixed lint issues.
- By running following command from project's root directory:
```shell
make
```
=> Add usetesting linter and fix lint issues (#6892)

scripts/release/notes.py
- Fast follow to this comment: https://github.com/jaegertracing/jaeger/pull/6976#pullrequestreview-2744257236
=> Add changelog:refactoring

CHANGELOG.md, RELEASE.md, scripts/release/notes.py
Part of https://github.com/jaegertracing/jaeger/issues/6975
=> Prepare release v1.68.0/v2.5.0

internal/storage/v2/grpc/handler.go, internal/storage/v2/grpc/handler_test.go
- Implement the `GetDependencies` call in the gRPC v2 handler
=> [grpc][v2] Implement `GetDependencies` in gRPC v2 Server

internal/storage/v2/elasticsearch/tracestore/reader.go, internal/storage/v2/elasticsearch/tracestore/reader_test.go
- Fixes a part of: #7034 
- Implement `GetTraces` for ES/OS
- Unit Tests
=> [ES][v2] Implement `GetTraces` for ES/OS

examples/reverse-proxy/docker-compose.yml
=> Upgrade reverse-proxy example to jaeger-v2

cmd/jaeger/internal/extension/remotestorage/README.md, cmd/jaeger/internal/integration/README.md
=> [docs] Add documentation for new remote storage backend extension

cmd/jaeger/internal/integration/README.md
=> Remove unnecessary heading

CHANGELOG.md, RELEASE.md
- 
Depends on https://github.com/jaegertracing/jaeger-ui/pull/2762 
Updates: https://github.com/jaegertracing/jaeger/issues/7106
- 
- 
=> Prepare release 1.69.0

internal/storage/integration/integration.go
- 
There is a [new function](https://pkg.go.dev/slices@go1.21.0#Contains) added in the go1.21 standard library, which can make the code more concise and easy to read.
- 
=> [refactor]: use slices.Contains to simplify code

internal/storage/v2/grpc/README.md
- Adds a mermaid diagram for the gRPC storage integration test setup
=> [docs] Add mermaid diagram for gRPC storage integration test setup

CHANGELOG.md, internal/storage/v1/grpc/README.md, internal/storage/v2/grpc/README.md
TSIA
Part of https://github.com/jaegertracing/jaeger/issues/7089
=> Minor cleanup of grpc storage docs

internal/storage/v2/memory/memory.go, internal/storage/v2/memory/memory_test.go, internal/storage/v2/memory/tenant.go
- Fixes a part of: #7052 
- Implement FindTraceIds for memoty backend
- Unit Tests
=> [v2] Implement `FindTraceIDs` for memory backend

MAINTAINERS.md
=> Update company name for jkowall

internal/storage/metricstore/elasticsearch/reader.go, internal/storage/metricstore/elasticsearch/reader_test.go, internal/storage/metricstore/elasticsearch/testdata/output_call_rate.json, internal/storage/metricstore/elasticsearch/testdata/output_call_rate_operation.json, internal/storage/metricstore/elasticsearch/to_domain.go, internal/storage/metricstore/elasticsearch/to_domain_test.go
- Resolves part of https://github.com/jaegertracing/jaeger/issues/7147
- Refactor reader.go
- make lint test
=> Refactor metricstore/elasticsearch/reader.go

internal/storage/metricstore/elasticsearch/query_builder.go, internal/storage/metricstore/elasticsearch/query_builder_test.go, internal/storage/metricstore/elasticsearch/reader.go, internal/storage/metricstore/elasticsearch/to_domain.go
- Resolves part of https://github.com/jaegertracing/jaeger/issues/7147
- Refactor suggestion: https://github.com/jaegertracing/jaeger/pull/7290#pullrequestreview-2991498055
- Introduce QueryBuilder
- Add comment for struct for better clarity
- make lint test
=> Refactor metricstore/es/reader.go by introducing queryBuilder

internal/storage/metricstore/elasticsearch/README.md, internal/storage/metricstore/elasticsearch/processor.go, internal/storage/metricstore/elasticsearch/processor_test.go, internal/storage/metricstore/elasticsearch/query_builder.go, internal/storage/metricstore/elasticsearch/reader.go, internal/storage/metricstore/elasticsearch/reader_test.go, internal/storage/metricstore/elasticsearch/testdata/output_call_rate_operation.json, internal/storage/metricstore/elasticsearch/testdata/output_errors_rate.json, internal/storage/metricstore/elasticsearch/testdata/output_errors_rate_operation.json
- Resolves part of https://github.com/jaegertracing/jaeger/issues/7147
- Implement GetErrorRate Implementation
- Add corresponding unit test
- Refactor reader.go (by introduce processor.go), reader_test.go 
- CI
- may be there is a bug with getErrorRate chart inside jaeger-ui, it's turning math.NaN into 0
=> [spm] GetErrorRates implementation

docker-compose/monitor/README.md
- Resolves https://github.com/jaegertracing/jaeger/issues/7305
- Update command in monitor/readme.md
- Comment https://github.com/jaegertracing/jaeger/issues/7305#issuecomment-3062704109
- CI
=> Correct command in docker-compose/monitor/readme.md

cmd/jaeger/config-badger.yaml
Keep getting this question so why not include it in the sample config
=> Add TTL to Badger sample config

.github/workflows/stale.yml
=> Enable stale bot

internal/metrics/otelmetrics/factory_test.go
- Towards https://github.com/jaegertracing/jaeger/pull/7377#issuecomment-3128226363
- 
- 
=> Help update OTEL collector packages

examples/oci/README.md, examples/oci/ingress.yaml, examples/oci/tls-cert/issuer.yaml
- Added the configuration for issuer 
- Added TLS/SSL support on ingress controller 
- Deployed the changes on the OKE cluster 
=> Added TLS/SSL certification and automation for Jaeger Demo Deployment

CHANGELOG.md, RELEASE.md
Prepare Release v1.72.0 / v2.9.0
=> Prepare Release v1.72.0 / v2.9.0

go.mod
It was previously pinned in #7109 to a pre-release version to work around an issue with darwin builds in #7107.
=> Unpin github.com/ebitengine/purego

scripts/e2e/metrics_summary.py
- Improves on https://github.com/jaegertracing/jaeger/pull/7414
- Resolves part of https://github.com/jaegertracing/jaeger/issues/6278
- Improve  CI comment
- My own forked pr comment: https://github.com/pipiland2612/jaeger/pull/3#issuecomment-3193800268
=> [CI] Improve summary comment

cmd/jaeger/internal/extension/expvar/extension.go
- Improves Code coverage of `cmd/jaeger/internal/extension/expvar/extension.go`
- removes nested if which will reduce amount of untested code.
- 
=> [chore]: Improve test coverage of expvar extension
