jaegertracing/jaeger

- cmd/query/app/handler.go
- cmd/query/app/handler_test.go
- glide.lock
- glide.yaml
> Trace query service routes

- cmd/agent/app/config.go
For localhost to hit agent processor endpoints in the docker world, we need to use 0.0.0.0 as the host for the agent.
> Make agent hostPort more docker friendly

- cmd/standalone/Dockerfile
707MB -> 31MB using an empty docker image. Had to swap from ENTRYPOINT to CMD because ENTRYPOINT requires bash and the scratch container doesn't even have that.
> Reduce size of all in one image

- .gitignore
- Makefile
- cmd/standalone/main.go
- cmd/standalone/standalone_test.go
- glide.lock
- travis/build-all-in-one-image.sh
Adding a test for the standalone docker image that creates a trace with via the query service and then retrieves it.
> Add standalone test

- cmd/query/app/handler.go
- cmd/query/app/handler_archive_test.go
Per agreement in https://github.com/uber/jaeger-ui/issues/7
> Change archive storage to be a fallback for /api/traces/ route

- cmd/flags/cassandra/options.go
- cmd/flags/cassandra/options_test.go
- crossdock/main.go
If the user doesn't pass in the flag cassandra.connections-per-host when initializing collector or query services, the initialization will fail. Adding a default to prevent this.
The actual default is up for debate.
> Add default for cassandra.connections-per-host

- travis/build-all-in-one-image.sh
- travis/build-crossdock.sh
When a good samaritan creates a PR from a forked version of jaeger, we run into a problem when running the following:
`if [ "$BRANCH" == "master" ]; then echo 'upload to Docker Hub'; else echo 'skip docker upload for PR'; exit 0; fi`
because the branch is "master". Travis will attempt to upload the docker image to docker hub but the encrypted environment variables (docker hub username and password) are not available for forked repos. This results in the travis build being stuck for 10 minutes before timing out.
Given that travis doesn't provide a way to check if the current build is from a fork, I'm using `"$TRAVIS_SECURE_ENV_VARS" == "true"` to determine if the encrypted environment variables are available which signals that the build is a non-forked version.
> Skip upload to docker hub from forked repo PRs

- cmd/agent/app/config.go
- cmd/agent/app/processors/thrift_processor_test.go
- cmd/agent/app/reporter/tchannel_reporter.go
- cmd/agent/app/reporter/tchannel_reporter_test.go
- cmd/agent/app/sampling/collector_proxy.go
- cmd/agent/app/sampling/collector_proxy_test.go
Fixed discoverer with static hosts have made the client options obsolete.
> Remove TChannel thrift client options

- README.md
- docs/getting_started.md
* Add links to all jaeger related repositories to root readme
* add section about kubernetes and OC to docs
> Docs add link to oc, k8s templates and links to all repositories

- cmd/collector/app/sanitizer/zipkin/span_sanitizer.go
- cmd/collector/app/sanitizer/zipkin/span_sanitizer_test.go
This data is already stored in the span, and can be queried via tag search or duration search.
> Remove zipkin span sanitizer logs

- model/converter/json/fixtures/ui_01.json
- model/json/fixture.json
- model/json/model.go
- model/json/model_test.go
Fixes https://github.com/uber/jaeger-ui/issues/33
Cf. https://stackoverflow.com/questions/1969993/is-it-better-to-return-null-or-empty-collection/
> Do not omit empty arrays in JSON

- pkg/testutils/logger.go
- pkg/testutils/logger_test.go
You can't both write and read from testutils.logger buffer concurrently given buffer is not threadsafe. Overwriting some functions with locks to fix.
> Fix race condition in testutils.logger

- cmd/collector/app/http_handler.go
- cmd/collector/app/http_handler_test.go
- glide.lock
- Also add a test using jaeger-client (depends on https://github.com/uber/jaeger-client-go/pull/161 and new release of the client)
> Accept jaeger.Batch Thrift type in HTTP handler

- cmd/collector/app/http_handler_test.go
Test both jaeger and zipkin thrift in one function
> Test posting Thrift to HTTP endpoint via Jaeger client 

- plugin/storage/integration/es_integration_test.go
- travis/es-integration-test.sh
the writer cache attached in previous commit was interfering with the integration tests because each test wasn't initialized/cleaned up properly
> Fix ES Storage integration test

- cmd/agent/app/agent_test.go
- cmd/agent/app/builder.go
- cmd/agent/app/builder_test.go
- cmd/agent/app/flags.go
- cmd/agent/main.go
- cmd/standalone/main.go
- glide.lock
- glide.yaml
- pkg/metrics/builder.go
- pkg/metrics/builder_test.go
- pkg/metrics/package.go
Defaults to expvar. Prometheus metrics currently don't work because
it does not allow dots in the names (https://github.com/uber/jaeger-lib/issues/20)
and requires pre-declaring all tag keys, which is not supported by
the Jaeger's metrics API.
Re: https://github.com/uber/jaeger/issues/273
> Support configurable metrics backend in the agent

- cmd/collector/app/builder/span_handler_builder.go
- pkg/es/config/config.go
- plugin/storage/es/spanstore/schema.go
- plugin/storage/es/spanstore/writer.go
- plugin/storage/es/spanstore/writer_test.go
- plugin/storage/integration/es_integration_test.go
> Make ES number of shards and replicas configurable

- cmd/agent/main.go
- cmd/collector/app/builder/builder_flags.go
- cmd/collector/app/builder/span_handler_builder.go
- cmd/collector/app/builder/span_handler_builder_test.go
- cmd/collector/main.go
- cmd/flags/cassandra/options.go
- cmd/flags/cassandra/options_test.go
- cmd/flags/flags.go
- cmd/query/app/builder/builder_flags_test.go
- cmd/query/app/builder/cassandra.go
- cmd/query/app/builder/cassandra_test.go
- cmd/query/app/builder/storage.go
- cmd/query/app/builder/storage_test.go
- cmd/query/main.go
- cmd/standalone/main.go
- crossdock/main.go
- docs/deployment.md
- pkg/cassandra/config/config.go
- pkg/config/config.go
- pkg/es/config/config.go
@yurishkuro I have opened this as a final version of #235 . Let's keep it simple stick to the current behavior and do refactoring in separate PRs. After this is merged I will submit PRs to address: 
* #296 
* `span_handler_builder` init functions to not return func, but immediately create a connection to C*/elastic
> Cobra viper configuration keep it simple

- pkg/cassandra/config/config.go
We currently hard code the version to 4; this doesn't seem necessary given default protoVersion is set on the primary namespace and gocql also discovers the best protoVersion for the current session if protoVersion is not set.
As a side note we run cassandra 2 internally for "reasons" and this prevents it.
> Remove default cassandra ProtoVersion

- cmd/flags/es/options.go
- cmd/flags/es/options_test.go
- plugin/storage/es/spanstore/writer.go
- plugin/storage/es/spanstore/writer_test.go
the default value of replicas is 1, not 2; passing in 1 as the number of replicas means 1 primary + 1 replica, so 2 in total.
https://www.elastic.co/guide/en/elasticsearch/guide/current/replica-shards.html
> Change ElasticSearch replicas default value

- cmd/collector/app/builder/builder_flags.go
- cmd/collector/main.go
- cmd/query/app/builder/builder_flags.go
- cmd/query/main.go
- pkg/healthcheck/handler.go
- pkg/healthcheck/handler_test.go
The idea of this PR is to create a first version of the readiness and liveness checks. It can be improved in the future to expose the metrics from `expvar`, so that an orchestration service can auto scale based on the data reported by this.
Similarly, this would allow the server to keep booted even if the underlying data store is offline: while the main HTTP port might still accept incoming requests and put on a buffer, the health check endpoint might return a `degraded` state, so that admins could get notified if something is wrong.
Sample output for "ready and alive":
```
curl -v http://localhost:17686/
*   Trying ::1...
* TCP_NODELAY set
* Connected to localhost (::1) port 17686 (#0)
> GET / HTTP/1.1
> Host: localhost:17686
> User-Agent: curl/7.53.1
> Accept: */*
> 
< HTTP/1.1 204 No …
```
> Added liveness and readiness checks to collector and query

- cmd/collector/app/builder/span_handler_builder.go
- cmd/collector/app/sanitizer/zipkin/span_sanitizer.go
- cmd/collector/app/sanitizer/zipkin/span_sanitizer_test.go
- cmd/collector/app/span_handler.go
Similar to: https://github.com/openzipkin/zipkin/blob/master/zipkin/src/main/java/zipkin/internal/ApplyTimestampAndDuration.java
This is required for follow-up PR with zipkin JSON encoding.
> Zipkin span start time and duration sanitizer

- docs/client_libraries.md
Address concerns in https://github.com/uber/jaeger-client-node/issues/124
> Mention UDP buffer size restrictions

- pkg/healthcheck/handler.go
log field name `http-port` for new HTTP status is misleading, change to `http-status`
> use `http-status` as log field name when set new HTTP status for the health check

- CODE_OF_CONDUCT.md
All CNCF projects should have code of conduct.
Signed-off-by: Chris Aniszczyk <caniszczyk@gmail.com>
> Add CNCF Code of Conduct

- docs/index.md
Provide links to how Jaeger can be used with Istio and Envoy. When/if the documentation is restructured we could have a think about best way to describe such use cases.
> Add Jaeger related istio and envoy links

- cmd/query/main.go
The standalone query server already has tracing enabled. This is a
trivial parity patch.
> Trace the dedicated query server

- cmd/agent/main.go
- cmd/collector/main.go
- cmd/flags/flags.go
- cmd/query/main.go
- cmd/standalone/main.go
Support configuration files. This allows us to configure Jaeger with kubernetes config maps. 
By default configuration files are disabled. Lists are currently not handled because we parse them manually. For instance `cassandra.servers` requires a string with comma separated values. 
Follows some examples. Note that flags with dots can be written as nested objects.
```json
{
"query": {
"prefix": "prefix",
"static-files": "static"
},
"cassandra": {
"keyspace": "from_file",
"password": "pas_from_file",
"servers": "localhost,localhost2",
"archive": {
"keyspace": "archive_keyspace"
}
},
"es.archive.max-span-age": "75h0m0s"
}
```
```yml
query:
prefix: prefix
static-files: static
cassandra:
keyspace: from_file
password: pas_from_file
servers: localhost,localhost2
archive:
keyspace: …
```
> Support configuration files

- plugin/storage/cassandra/schema/create.sh
if cassandra fails because of using invalid character the user will now
know why, thus can make changes to KEYSPACE parameter
fixes: #445
Signed-off-by: Deepika Upadhyay <deepikaupadhyay01@gmail.com>
>  passes error message if KEYSPACE does not have valid character

- docs/index.md
PR changes text for "Using Jaeger with Istio" link in "Related links" section. It adds the missing "t".
> Correct typo: Isio -> Istio

- cmd/collector/app/zipkin/http_handler_test.go
- cmd/collector/app/zipkin/json.go
> Handle ports > 32k in Zipkin JSON

- cmd/collector/app/span_handler.go
- model/converter/thrift/zipkin/to_domain.go
- model/converter/thrift/zipkin/to_domain_test.go
Fixes #451 
Zipkin logic is here: 
Collector: https://github.com/openzipkin/zipkin/blob/5c8a17620674ada895acf05038bfdb209924a47d/zipkin/src/main/java/zipkin/collector/Collector.java#L143
v1 to v2 model: https://github.com/openzipkin/zipkin/blob/eeeeb3c02b0e0c578eb36c08d80cf2bf400067fc/zipkin/src/main/java/zipkin/internal/V2SpanConverter.java#L46
> Split zipkin span which contains server and client annotations

- cmd/collector/app/zipkin/http_handler.go
- cmd/collector/app/zipkin/json.go
- cmd/collector/app/zipkin/json_test.go
Fix deserialization of zipkin binary annotations values of number type. cc @golonzovsky 
The following json fails to deserialize with this error `Unable to process request body: json: cannot unmarshal number into Go value of type string`
```json
[
{
"traceId": "7d3277b087a7c05a",
"name": "/",
"id": "3c1813d224db60fe",
"parentId": "a50ac2ce7f3bf056",
"timestamp": 1508924339988597,
"duration": 1781,
"annotations": [],
"binaryAnnotations": [
{
"key": "http.status_code",
"value": 200,
"type": "I64"
}
]
}
]
```
> Zipkin json binAnnotation value number

- cmd/collector/app/zipkin/http_handler_test.go
- cmd/collector/app/zipkin/json.go
- cmd/collector/app/zipkin/json_test.go
> Zipkin use net.parseIP and model functions for IDs

- plugin/storage/cassandra/schema/create.sh
in our prod environment, we use simplestrategy with >1 replication factor.
seems like `test` and `prod` are a bit tied to uber's environments, but we can do what we want with this PR by using "test" (actually prod) and a custom replication factor.
> allow overriding replication factor for 'test'

- crossdock/docker-compose.yml
A minor improvement. `test-driver` should depend on jaeger services and not xdock.
> Xdock compose, test driver links jaeger services

- crossdock/docker-compose.yml
- docker-compose/jaeger-docker-compose.yml
> Remove unnecessary links to xdock test_driver

- README.md
- docs/client_libraries.md
- docs/index.md
Hi, 
with the new [C++ client](https://github.com/jaegertracing/cpp-client) merged, maybe it would be nice to expose it into the document materials of Jaeger.
Let me know if you find this useful or maybe premature.
I also wanted to update [this image](https://github.com/jaegertracing/jaeger/blob/master/docs/images/architecture.png) by adding C++ but I could not find the source.
Thanks !
> Update README and docs with new C++ client lib.

- thrift-gen/baggage/tchan-baggage.go
- thrift-gen/jaeger/tchan-jaeger.go
- thrift-gen/sampling/tchan-sampling.go
- thrift-gen/zipkincore/constants.go
- thrift-gen/zipkincore/tchan-zipkincore.go
* updated idl to master/head
* run `make thrift`
> Bump idl with zipkin swagger and messaging annos

- cmd/agent/main.go
- cmd/collector/main.go
- cmd/flags/flags.go
- cmd/query/main.go
- cmd/standalone/main.go
Logging struct was defined in flag package but not used. I have also removed unused code from there.
> Introduce logging level configuration

- examples/hotrod/README.md
[minor] following the `README` you hit the following error:
```
 ~/go/src/github.com/uber/jaeger/examples/hotrod   master  go run ./main.go all
main.go:8:2: cannot find package "github.com/jaegertracing/jaeger/examples/hotrod/cmd" in any of:
/Users/me/go/src/github.com/uber/jaeger/vendor/github.com/jaegertracing/jaeger/examples/hotrod/cmd (vendor tree)
/usr/local/Cellar/go/1.9.2/libexec/src/github.com/jaegertracing/jaeger/examples/hotrod/cmd (from $GOROOT)
/Users/me/go/src/github.com/jaegertracing/jaeger/examples/hotrod/cmd (from $GOPATH)
```
> docs(example): fix go get url

- CONTRIBUTING.md
- README.md
- doc.go
- docs/deployment.md
- docs/getting_started.md
- docs/index.md
- docs/news.md
- docs/roadmap.md
- glide.yaml
After #528 many instructions still incorrectly refer to `uber`
> Finish replacing uber/jaeger with jaegertracing/jaeger

- plugin/storage/es/spanstore/reader.go
- plugin/storage/es/spanstore/reader_test.go
- plugin/storage/es/spanstore/service_operation.go
- plugin/storage/es/spanstore/service_operation_test.go
> ES fix aggregation errors when index is empty

- cmd/flags/cassandra/options.go
- docs/deployment.md
- pkg/cassandra/config/config.go
I'm not entirely sure how to test this in the context of Jaeger's test suite; it does work for me...
> Enable TLS client connections to Cassandra

- plugin/storage/es/dependencystore/storage_test.go
I changed test `TestGetIndices` to use UTC timezone instead of local
Fixes #557
> use utc time zone in es storage getIndices test

- docs/deployment.md
- plugin/storage/cassandra/schema/docker.sh
We can configure most of cqlsh externally, but we do need to pass --ssl in to enable the SSL support. Here's a trivial patch to do that plus docs to make it easy for others.
> Configure cqlsh for TLS for schema setup.

- cmd/agent/app/builder.go
- cmd/agent/app/builder_test.go
- cmd/agent/app/httpserver/server.go
- cmd/agent/app/httpserver/server_test.go
- cmd/collector/app/builder/span_handler_builder.go
- cmd/collector/app/zipkin/json.go
- cmd/collector/main.go
- cmd/query/main.go
- cmd/standalone/main.go
- examples/hotrod/cmd/root.go
- examples/hotrod/services/route/server.go
- glide.lock
- glide.yaml
- pkg/metrics/builder.go
- pkg/metrics/builder_test.go
Depends in https://github.com/jaegertracing/jaeger-lib/pull/29
Resolves #360, partially #273 .
> Support Prometheus metrics as default mode

- plugin/storage/es/spanstore/reader_test.go
This test fails when the local timezone is IST.
> Use UTC time zone in es storage findIndices test

- cmd/agent/app/builder.go
- When overriding the collector service name using the agent app builder's embedded
`WithCollectorServiceName`, the service name is stored in the embedded struct and
not in the outer struct.
- When constructing an agent using `createAgent`, `GetHttpServer` reads the outer
struct leading to different behavior when reading configuration from a file, as
opposed to using the builder.
- This change uses go-yaml's `inline` keyword to deserialize embedded structs.
> Fix jaeger agent embedded reporter builder bug

- plugin/storage/cassandra/spanstore/writer.go
Use the span hash as the source of variation for bucket choice instead of an atomic counter so that the inserts are idempotent.
Signed-off-by: Kevin Wojcik <kwojcik@uber.com>
> make cassandra service_name_index inserts idempotent

- examples/hotrod/services/driver/redis.go
Signed-off-by: Isaac Hier <ihier@uber.com>
> Add log to avoid warning for ineffectual assignment

- plugin/storage/cassandra/spanstore/writer.go
Span hash is used for cassandra buckets, but since it's signed it can produce negative numbers.
Related to #587, replaces #595
Resolves https://github.com/jaegertracing/spark-dependencies/issues/23
> Ensure Cassandra bucket number is not negative

- plugin/storage/es/spanstore/reader.go
- plugin/storage/es/spanstore/reader_test.go
Focus on the flowing multiread function code snippet
```golang
var traces []*model.Trace
for _, result := range results.Responses {
if result.Hits == nil {
return nil, errNilHits
}
spans, err := s.collectSpans(result.Hits.Hits)
if err != nil {
return nil, err
}
traces = append(traces, &model.Trace{Spans: spans})
}
return traces, nil
```
when trace id is invalid or not in the es store, we got response json as follows:
```json
{
"responses":[
{
"took":2,
"timed_out":false,
"_shards":{
"total":15,
"successful":15,
"failed":0
},
"hits":{
"total":0,
"max_score":null,
"hits":[]
},
"status":200
}
]
}
```
and then the response json is unmarshalled to the `elastic.MultiSearchResult` struct, you will notice that the snippet
```json
"hits":{
"total":0,
"max_score":null,
"hits":[]
},
```
will not get …
> skip nil and zero length hits, fix #556

- cmd/collector/Dockerfile
- cmd/query/Dockerfile
Resolves #485 
When connecting query/collector to storage backends that use TLS with certificates signed by public root CAs, it's useful to have those CA certificates in the Docker image.
On the other hand, the certificates can always be mounted from the host filesystem, which is necessary anyway when connecting to servers using self-signed certificates.
I think this is a nice to have so that people don't have to do extra work. For collector it increases the image size from 24.6MB to 25.3MB.
> Add CA certificates to collector/query images

- cmd/query/app/adjusters.go
- model/adjuster/bad_span_references.go
- model/adjuster/bad_span_references_test.go
> Add adjuster that removes bad span references

- cmd/query/app/handler.go
- cmd/query/app/handler_test.go
- model/adjuster/bad_span_references.go
> Add support for retrieving unadjusted/raw spans

- plugin/storage/cassandra/spanstore/operation_names.go
Signed-off-by: jukylin <742161455@qq.com>
> Init operationNames's cache capacity

- cmd/agent/app/agent.go
- cmd/agent/app/agent_test.go
- pkg/testutils/logger.go
- pkg/testutils/logger_test.go
1. The test was using default HTTP port instead of ephemeral port, which lead to unexpected failures if you happen to run some other jaeger components locally
1. The coverage was unstable because there was no waiting for the http server to shutdown and execute the error handler
> Make agent tests more robust

- cmd/env/command.go
- cmd/standalone/main.go
- docs/deployment.md
- plugin/storage/factory_config.go
- plugin/storage/factory_config_test.go
Resolves #642 
```
$ go run ./cmd/query/main.go env
All command line options can be provided via environment variables by converting
their names to upper case and replacing punctuation with underscores. For example,
command line option                 environment variable
------------------------------------------------------------------
--cassandra.connections-per-host    CASSANDRA_CONNECTIONS_PER_HOST
--metrics-backend                   METRICS_BACKEND
The following configuration options are only available via environment variables:
SPAN_STORAGE_TYPE string         The type of backend (cassandra, elasticsearch, memory) used for trace storage. (default "cassandra")
DEPENDENCY_STORAGE_TYPE string   The type of backend used for service dependencies storage. (default "${SPAN_STORAGE}")
``` …
> Rename SPAN_STORAGE to SPAN_STORAGE_TYPE to be backwards compatible

- plugin/storage/es/spanstore/writer.go
- plugin/storage/es/spanstore/writer_test.go
> Fix elasticsearch create index race condition error

- plugin/storage/es/spanstore/writer.go
> Use UTC timezone for ES indices

- plugin/storage/factory_test.go
```
=== RUN   TestNewFactory
--- FAIL: TestNewFactory (0.00s)
Error Trace:	factory_test.go:66
Error:      	Not equal: 
expected: "Unknown storage type x."
actual: "Unknown storage type y."
```
> Fix flaky test

- cmd/standalone/main.go
> Add signal handling to standalone

- cmd/agent/main.go
- cmd/standalone/main.go
- examples/hotrod/main.go
From Go 1.5, the default setting of `GOMAXPROCS` is the number of
CPUs available. we might as well remove this so people can set
GOMAXPROCS to a custom value using environment variables.
> https://golang.org/doc/go1.5#runtime
Signed-off-by: kun <oiooj@qq.com>
> Remove the override of GOMAXPROCS

- plugin/storage/cassandra/spanstore/writer.go
- plugin/storage/cassandra/spanstore/writer_options.go
- plugin/storage/cassandra/spanstore/writer_options_test.go
- plugin/storage/cassandra/spanstore/writer_test.go
- Add `StoreIndexesOnly` and `StoreWithoutIndexing` options to the cassandra
storage which controls whether indexes are written along with spans.
- This allows us to deploy, scale, and prioritize  writers independently for
indexing and storage workloads.
> Add options to Cassandra to control indexing

- pkg/es/config/config.go
- plugin/storage/es/factory.go
- plugin/storage/es/factory_test.go
Related to #662 
This is not sending bulk stats https://github.com/olivere/elastic/wiki/BulkProcessor#stats to our metrics but just emitting additional duration metrics. Bulk stats does not provide this duration metrics.
> Collect metrics from ES bulk service

- cmd/agent/app/builder.go
- cmd/agent/app/builder_test.go
- cmd/agent/app/flags.go
The `ProcessorConfiguration` can be exported, but the custom type `model` and `protocol` can not, so it's hard to new a `ProcessorConfiguration` outside the package.
Signed-off-by: kun <oiooj@qq.com>
> export model and protocol type

- plugin/storage/cassandra/options.go
- plugin/storage/cassandra/options_test.go
Resolves #699
```
$ go run ./cmd/collector/main.go -h | grep consistency
--cassandra-archive.consistency string                 The Cassandra consistency level, e.g. ANY, ONE, TWO, THREE, QUORUM, ALL, LOCAL_QUORUM, EACH_QUORUM, LOCAL_ONE (default LOCAL_ONE)
--cassandra.consistency string                         The Cassandra consistency level, e.g. ANY, ONE, TWO, THREE, QUORUM, ALL, LOCAL_QUORUM, EACH_QUORUM, LOCAL_ONE (default LOCAL_ONE)
```
cc @LarsMilland
> Add a flag to control Cassandra consistency level

- pkg/discovery/peerlistmgr/peer_list_mgr.go
The calls to Add should execute before the statement creating the
goroutine or other event to be waited for.
Signed-off-by: kun <oiooj@qq.com>
> Wait group should add before the goroutine creating

- model/time.go
- model/time_test.go
- standardize on UTC for time representation
- the wire format for everything is microseconds since epoch, so this change does not effect data transfer over rpcs. 
> Use UTC for model timezone

- model/converter/json/process_hashtable_test.go
The UI converter dedups Process objects using the hash code that is currently independent of the tags order (provided NewProcess ctor is used). Whether relying on NewProcess to sort the tags is the right or wrong thing, this PR simply enhances the tests to demonstrate the existing dependency.
> Test that processes with identical tags are deduped

- examples/hotrod/pkg/tracing/init.go
I ran into a case where trace had spans with the same IDs. The RNG is seeded with time.Now().UnixNano(), which potentially can give identical values over several calls (since the clock precision is not actually nanos).
This is a quick (hacky) workaround. A proper fix needs to be in the Jaeger client.
> Make sure different tracers in HotROD process use different RNG seeds

- cmd/agent/app/agent_test.go
- cmd/agent/app/builder.go
This will fix #738 
I'm looking at adding a test to ensure the functionality will stay over time. I'll update the PR
> Use the default metricsFactory if not provided

- cmd/query/app/fixture/index.html
- cmd/query/app/fixture/static/asset.txt
- cmd/query/app/flags.go
- cmd/query/app/flags_test.go
- cmd/query/app/handler.go
- cmd/query/app/handler_options.go
- cmd/query/app/handler_test.go
- cmd/query/app/static_handler.go
- cmd/query/app/static_handler_test.go
- cmd/query/main.go
- cmd/standalone/main.go
Resolves #745 **Provide a means to define a path-prefix for the UI**
Resolves #746 **Remove --query.prefix option**
> Allow overriding base path for UI/API routes; rm --query.prefix

- cmd/query/app/handler.go
- cmd/query/app/handler_test.go
- cmd/query/main.go
> Configure Gorilla router to allow slash in path params

- examples/hotrod/cmd/all.go
- examples/hotrod/cmd/customer.go
- examples/hotrod/cmd/driver.go
- examples/hotrod/cmd/frontend.go
- examples/hotrod/cmd/root.go
- examples/hotrod/cmd/route.go
> Log errors from HotROD servers

- CONTRIBUTING.md
For some reason we were pointing to a different blog post from what I thought.
> Use different "good commit message" reference and inline it

- plugin/storage/cassandra/spanstore/dbmodel/log_fields_filter.go
- plugin/storage/cassandra/spanstore/dbmodel/log_fields_filter_test.go
- plugin/storage/cassandra/spanstore/dbmodel/tag_filter.go
- plugin/storage/cassandra/spanstore/dbmodel/tag_filter_test.go
- plugin/storage/cassandra/spanstore/dbmodel/unique_tags.go
Because sometimes the filtering decision depends not only on the tags, but on the span itself, e.g. debug bit, or the service name.
> Change dbmodel.TagFilter to take span as argument

- .travis.yml
- Makefile
- scripts/travis/build-windows.sh
- scripts/travis/package-deploy.sh
This is for #765. It will build executables for windows and in the travis job it will publish the windows and linux binaries with the GitHub release when the build is tagged. Out of the box the standalone binary and the query binary won't work as they need the UI files location specified.
Also, before this is merged someone with access to the repo will have to add a secure key to the travis deploy so the files can be sent along to GitHub.
> add make and travis options for building for windows

- plugin/storage/cassandra/schema/v001.cql.tmpl
This prevents schema upgrades or re-executions from erroring.
Closes jaegertracing/jaeger-openshift#79
> Tune create on custom index to not be created if it already exists.

- Makefile
Builds failing with what looks like https://github.com/golang/lint/issues/397
> Fix for installing golint

- Makefile
- plugin/storage/integration/domain_trace_compare_test.go
Use pretty.Diff(expected, actual) instead of reflect.DeepEqual(expected, actual) to check for equality between given and received trace. Also, if there is a difference, set the test to fail instead of only logging the failed trace.
And prettify the storage-integration-test output
> Fail test if the expected and actual traces differ (#777)

- .travis.yml
- cmd/env/command.go
- remove redundant newline in Fprintln arg list to fix build
> Upgrade to  go 1.10

- cmd/collector/app/sanitizer/utf8_sanitizer_test.go
- model/adjuster/clockskew.go
- model/adjuster/ip_tag.go
- model/adjuster/ip_tag_test.go
- model/converter/json/from_domain_test.go
- model/converter/json/to_domain_test.go
- model/converter/thrift/jaeger/from_domain.go
- model/converter/thrift/zipkin/to_domain_test.go
- model/keyvalues_test.go
- model/process.go
- model/span.go
Addresses first two issues in https://github.com/jaegertracing/jaeger/issues/773#issuecomment-386932926
* Do not use `KeyValue` fields like `VNum` directly
* Use `KeyValues` as decorator only
> Do not use KeyValue fields directly and use KeyValues as decorator only

- plugin/storage/cassandra/dependencystore/storage.go
- plugin/storage/cassandra/dependencystore/storage_test.go
-  Reducing complexity by removing an unused function
-  Remove `timeIntervalToPoints`
> Remove unused function

- plugin/sampling/strategystore/static/fixtures/operation_strategies.json
- plugin/sampling/strategystore/static/strategy.go
- plugin/sampling/strategystore/static/strategy_store.go
- plugin/sampling/strategystore/static/strategy_store_test.go
- scripts/import-order-cleanup.py
- ability to adjust sampling probabilities per operation rather than just per service
- resolves #814 
-
> Add ability to adjust static sampling probabilities per operation

- Makefile
`gas` linter logs a lot of unnecessary debug information
> Make gas run quiet

- cmd/agent/app/builder.go
- cmd/collector/app/metrics.go
- cmd/collector/app/metrics_test.go
- cmd/collector/app/span_processor.go
- cmd/collector/app/span_processor_test.go
- cmd/collector/main.go
- cmd/query/main.go
- cmd/standalone/main.go
- glide.lock
- glide.yaml
- pkg/cassandra/metrics/table.go
- pkg/cassandra/metrics/table_test.go
- pkg/es/config/config.go
- pkg/metrics/builder_test.go
- plugin/storage/cassandra/dependencystore/storage.go
- plugin/storage/cassandra/samplingstore/storage.go
- plugin/storage/cassandra/spanstore/operation_names.go
- plugin/storage/cassandra/spanstore/operation_names_test.go
- plugin/storage/cassandra/spanstore/reader.go
- plugin/storage/cassandra/spanstore/service_names.go
- plugin/storage/cassandra/spanstore/service_names_test.go
- plugin/storage/cassandra/spanstore/writer.go
- plugin/storage/es/spanstore/writer.go
- storage/spanstore/metrics/decorator.go
- storage/spanstore/metrics/decorator_test.go
> Change metrics naming scheme

- cmd/collector/app/metrics.go
- cmd/collector/app/metrics_test.go
- cmd/collector/app/span_processor_test.go
Currently, we support metrics for the total number of debug spans but another useful metric to have is the debug traces (services that initiate the debug trace). Since debug traces aren't downsampled (this isn't technically true here in OSS...) having metrics to observe which service is creating more debug traces than necessary is useful.
> Add metric for debug traces

- pkg/memory/config/config.go
- plugin/storage/memory/factory.go
- plugin/storage/memory/factory_test.go
- plugin/storage/memory/memory.go
- plugin/storage/memory/memory_test.go
- plugin/storage/memory/options.go
- plugin/storage/memory/options_test.go
Resolves #842
- See #842 for background information
- This PR adds a simple FIFO eviction mechanism
This is WIP as it's missing:
If the approach from this PR is acceptable, I'll proceed with the doc/flag changes.
> Add bounds to memory storage

- CHANGELOG.md
-  Release 1.5.0
- User-visible changes from 1.4.1 to 1.5.0 added to the changelog
> Preparing release 1.5.0

- plugin/storage/memory/factory.go
- plugin/storage/memory/factory_test.go
- With #845, there's now a configuration option to set the maximum number of traces to store in memory, but there's no positive feedback about the actual value of this configuration option during runtime. This PR adds a log statement with the configuration option, like:
```
$ MEMORY_MAX_TRACES=100 go run cmd/standalone/main.go
{"level":"info","ts":1527668119.7661645,"caller":"memory/factory.go:55","msg":"Memory storage configuration","configuration":{"MaxTraces":100}}
```
- Added log statement with the contents of the configuration object
> Log configuration options for memory storage

- model/converter/thrift/jaeger/fixtures/model_02.json
- model/converter/thrift/jaeger/fixtures/thrift_batch_02.json
- model/converter/thrift/jaeger/to_domain.go
- model/spanref.go
Fixes a bug introduced in #831. Resolves #859.
Issue: some Jaeger clients specify parent span via both `parentSpanId` field and a span reference. The new method `model.MaybeAddParentSpanID(traceID, parentSpanID, refs)` was checking for duplicate reference, but only of child-of type, which was incorrect, since there should be no situations when the same parent span is linked via two reference types.
> Do not create duplicate child-of reference from parentSpanId

- cmd/query/app/handler_archive_test.go
- cmd/query/app/handler_test.go
- cmd/query/app/query_parser_test.go
- model/adjuster/bad_span_references_test.go
- model/adjuster/clockskew_test.go
- model/adjuster/span_id_deduper.go
- model/adjuster/span_id_deduper_test.go
- model/converter/json/to_domain.go
- model/converter/thrift/jaeger/to_domain.go
- model/converter/thrift/zipkin/to_domain.go
- model/ids.go
- model/span.go
- model/span_test.go
- model/spanref_test.go
- model/trace_test.go
- plugin/storage/cassandra/savetracetest/main.go
- plugin/storage/cassandra/spanstore/dbmodel/converter.go
- plugin/storage/cassandra/spanstore/dbmodel/converter_test.go
- plugin/storage/cassandra/spanstore/dbmodel/cql_udt_test.go
- plugin/storage/cassandra/spanstore/dbmodel/model.go
- plugin/storage/cassandra/spanstore/dbmodel/model_test.go
- plugin/storage/cassandra/spanstore/dbmodel/unique_ids_test.go
- plugin/storage/cassandra/spanstore/reader_test.go
- plugin/storage/cassandra/spanstore/writer_test.go
- plugin/storage/es/spanstore/reader_test.go
- plugin/storage/es/spanstore/writer_test.go
- plugin/storage/memory/memory_test.go
#856 may change the SpanID type alias from uint64 to `[8]byte`. It would make the change smaller if we didn't assume that int values can be converted directly to SpanID, so this change replaces instantiations with a call to `NewSpanID()` function. It decouples the usage from the actual implementation of SpanID type.
Similar change for TraceID.
> Use NewSpanID()/NewTraceID() instead of type-specific intializations

- CONTRIBUTING_GUIDELINES.md
Signed-off-by: Prakriti <prakritibansal98@gmail.com>
- Adding general contribution guidelines for uniformity across all repos. 
- refs jaegertracing/jaeger#771
-  Adding general contribution guidelines.
> Adding CONTRIBUTING_GUIDELINES.md

- glide.lock
- glide.yaml
- In the previous PR (https://github.com/jaegertracing/jaeger/pull/862), we had to pin a repo because the builds were failing. We were unable to ascertain why it was failing. However, now that I've removed it, the builds are passing. 🤷‍♂️
> Remove golang.org/x/sys pin

- plugin/storage/kafka/factory.go
- plugin/storage/kafka/factory_test.go
- plugin/storage/kafka/marshaller.go
- plugin/storage/kafka/marshaller_test.go
- plugin/storage/kafka/options.go
- plugin/storage/kafka/options_test.go
https://github.com/jaegertracing/jaeger/pull/862#discussion_r195198455
- Standard JSON encoding is not optimal for sending spans
- Thrift model doesn't have the process in the definition, therefore encoding causes loss of data when writing
- JSON Marshaller now uses protobuf to encode spans
- Thrift Marshaller has been replaced by a ProtobufMarshaller
> Use protobuf marshaller

- plugin/storage/cassandra/spanstore/dbmodel/index_filter.go
- plugin/storage/cassandra/spanstore/dbmodel/index_filter_test.go
- plugin/storage/cassandra/spanstore/writer.go
- plugin/storage/cassandra/spanstore/writer_options.go
- plugin/storage/cassandra/spanstore/writer_options_test.go
- plugin/storage/cassandra/spanstore/writer_test.go
- There are certain times when you want to skip indexing a certain span. ie for debug spans, the most common use case is that the user will use the traceid directly to find the trace, there's no need to index it by duration, etc.
- Add a new IndexFilter which checks the span and determines whether it should be indexed or not. Defaults to indexing everything
> Add cassandra index filter

- README.md
Signed-off-by: Eundoo Song <eundoo.song@gmail.com>
- Jaeger switched to codecov.io from coveralls from https://github.com/jaegertracing/jaeger/pull/857, but badges are not changed.
- Replace coveralls badge with codecov badge
> Replace coveralls badge with codecov badge

- cmd/agent/app/builder.go
- cmd/agent/app/processors/thrift_processor.go
- cmd/agent/app/processors/thrift_processor_test.go
- cmd/agent/app/reporter/tchannel/reporter.go
- cmd/collector/app/span_handler.go
- cmd/collector/app/span_processor.go
- Resolves #867
- Added a few `logger.Debug()` statements on the path from the agent's incoming span processor down to the collector's span writer. The logger had to be passed down in some places, whereas others had a logger instance by default.
When running the `standalone` with the `--log-level debug`  set, this is seen upon visiting the Jaeger's Query UI for the first time:
```
{"level":"debug","ts":1529666719.3805306,"caller":"processors/thrift_processor.go:113","msg":"Span(s) received by the agent"}
{"level":"debug","ts":1529666719.3815565,"caller":"app/span_handler.go:90","msg":"Span batch processed by the collector.","ok":true}
{"level":"debug","ts":1529666719.3816545,"caller":"app/span_processor.go:104","msg":"Span wrote …
```
> Log debug message when span reported

- plugin/storage/cassandra/spanstore/dbmodel/converter.go
- plugin/storage/cassandra/spanstore/dbmodel/converter_test.go
- The recent PR that changed the domain model to use proto added this change: https://github.com/jaegertracing/jaeger/pull/856/files#diff-96d29428fedf19815cb3671bba06767eL33. The issue is that previously we were storing "child-of" instead of "CHILD_OF" and doing a simple strings.Upper() isn't going to help.
With this fix, cassandra dbmodel will use it's own version of RefTypes so it's not affected by any outside changes.
-
> Make new proto RefType backwards compatible in cassandra

- cmd/collector/app/metrics.go
- cmd/collector/app/metrics_test.go
- cmd/collector/app/span_processor_test.go
- I just realized that the "service" tag is pretty common, internally we deployed the newest version of jaeger with the new tag based metrics and the "service" metric tag was overwriting the actual service tag (jaeger-collector) so we were emitting metrics for every other service at Uber except jaeger-collector (oops). I changed the tag to the shorthand "svc" but I'm open to suggestions.  
- service -> svc
> Change metric tag from "service" to "svc"

- model/converter/json/to_domain.go
- model/converter/json/to_domain_test.go
- model/keyvalue.go
- model/keyvalue_test.go
- model/spanref.go
- model/spanref_test.go
- plugin/storage/cassandra/spanstore/dbmodel/converter.go
- plugin/storage/cassandra/spanstore/dbmodel/converter_test.go
- plugin/storage/cassandra/spanstore/dbmodel/model.go
- plugin/storage/cassandra/spanstore/reader_test.go
> Decouple DB and JSON conversions from protobuf strings

- cmd/agent/app/processors/thrift_processor.go
- Follow-up PR from #879. As [commented](https://github.com/jaegertracing/jaeger/pull/879/files#r197501562) by @yurishkuro, it's possible to have a race condition when logging the buffer size, as it has been released already by the previous statement.
- Log the buffer size before the buffer is released
> Avoid race condition on logging the buffer size

- cmd/collector/app/sanitizer/zipkin/span_sanitizer.go
- cmd/collector/app/sanitizer/zipkin/span_sanitizer_test.go
Currently a Zipkin error tag of type string shows up in
Jaeger UI as an error.message tag with the value "False"
instead of the string value. The sanitizer is missing
annotationType on the new tag that holds error.message
Resolves #890 
Signed-off-by: Hananiel Sarella <hananiel@gmail.com>
> Fix missing Zipkin error messages

- pkg/es/config/config.go
Plz, review it as I am not golang native ;)
- #896 
- for more debug info, number of failed and total requests in bulk in case of error
> ES storage: logging number of total and failed requests

- .codecov.yml
Our codecov.io status no longer blocks PRs with less than 100% code coverage. Trying to fix that.
> Require 100% coverage

- cmd/agent/app/builder.go
- cmd/agent/app/flags.go
- cmd/agent/app/reporter/tchannel/builder.go
Adds a option to set connCheckTimeout. Now the value is hardcoded at 250ms. 
Added a flag to accept a new timeout for connCheckTimeout (--discovery.conn-check-timeout) that receives a duration. Defaults to 250ms.
> connCheckTimeout as flag

- cmd/collector/app/http_handler.go
- cmd/collector/app/http_handler_test.go
Since Zipkin HTTP endpoint has been moved to another port, the only format that Collector HTTP handler recognizes is Thrift, which makes the `?format=` URL parameter redundant since the payload type can be inferred from the `Content-Type` header.
This change removes the `format` URL parameter and only looks at the `Content-Type`.
> Detect HTTP payload format from Content-Type

- examples/hotrod/cmd/root.go
- examples/hotrod/pkg/tracing/init.go
- examples/hotrod/services/config/config.go
- examples/hotrod/services/customer/database.go
* Allow controlling optimizations from cmd line
* Suppress logging of stack traces unless fatal
* Add `hotrod` namespace to all metrics
* Support HTTP or UDP senders
On the topic of senders, the Go client, unfortunately, does not support JAEGER_ENDPOINT env variable like Java client does, and the current CLI argument is called `--jaeger-agent.host-port`, even though it now accepts HTTP endpoint name.
> Improve HotROD demo

- plugin/storage/es/spanstore/writer.go
Resolves #665
Add `resource_already_exists_exception` used by ES 6.x. It has been renamed from `index_already_exists_exception` https://github.com/elastic/elasticsearch/blob/7d7ead95b2a3b967f788f1fa56f118ee77d857fe/server/src/main/java/org/elasticsearch/ElasticsearchException.java#L978
> Fix ES 6.x index already exists race condition

- pkg/cassandra/config/config.go
- plugin/storage/cassandra/options.go
- plugin/storage/cassandra/options_test.go
- Resolves #767 
- Adds support for configuring gocql's `ReconnectInterval` setting. This will make gocql attempt to reconnect to downed Cassandra nodes every interval.
> Cassandra reconnect interval

- Makefile
- GoASTScanner/gas was renamed to gosec in securego/gosec#216 causing our
builds to break. 
- Resolves #945 be renaming `gas` to `gosec`
> Rename gas to gosec

- examples/hotrod/README.md
- The HotROD Docker example is missing the `all` command
- Added the `all` command
- Split the command into more readable lines
- Fixed versions to 1.6
- Changed the Jaeger command to run in the foreground
> Fix HotROD Docker command

- cmd/agent/app/processors/thrift_processor_test.go
- cmd/agent/app/reporter/tchannel/reporter.go
- cmd/agent/app/reporter/tchannel/reporter_test.go
Signed-off-by: Eundoo Song <eundoo.song@gmail.com>
- Change  path-based metrics to new format in agent.
- Resolves: #850 
- jaeger and zipkin are pulled into format tag.
- Gist : https://gist.github.com/eundoosong/8d3e06a259b60ce0ff346799dd3f7f22
```
jaeger_agent_tc_reporter_batch_size{format="jaeger"} 0
jaeger_agent_tc_reporter_batch_size{format="zipkin"} 0
jaeger_agent_tc_reporter_batches_failures{format="jaeger"} 0
jaeger_agent_tc_reporter_batches_failures{format="zipkin"} 0
jaeger_agent_tc_reporter_batches_submitted{format="jaeger"} 0
jaeger_agent_tc_reporter_batches_submitted{format="zipkin"} 0
jaeger_agent_tc_reporter_spans_failures{format="jaeger"} 0
jaeger_agent_tc_reporter_spans_failures{format="zipkin"} 0
jaeger_agent_tc_reporter_spans_submitted{format="jaeger"} 0 …
```
> Use tags in agent metrics

- cmd/query/app/handler.go
- cmd/query/app/handler_test.go
Internal server errors are not being logged. For example ES might crash and on the jaeger server side this info is completelly missing. Just the client get:
```
{"data":null,"total":0,"limit":0,"offset":0,"errors":[{"code":500,"msg":"Search service failed: elastic: Error 400 (Bad Request): all shards failed [type=search_phase_execution_exception]"}]}
```
An example of server log
```
SPAN_STORAGE_TYPE=elasticsearch  go run -tags ui cmd/query/main.go   --log-level=debug                              5:48 
{"level":"info","ts":1532620123.9571958,"caller":"healthcheck/handler.go:99","msg":"Health Check server started","http-port":16687,"status":"unavailable"}
{"level":"info","ts":1532620123.960481,"caller":"query/main.go:180","msg":"Archive storage not created","reason":"Archive storage not …
```
> Log internal server errors in http handler

- cmd/collector/app/http_handler.go
- cmd/collector/app/http_handler_test.go
- cmd/collector/app/zipkin/http_handler.go
- cmd/collector/app/zipkin/http_handler_test.go
- Resolves #963 , in which `Content-Type` extraction was using the raw value of the `Content-Type` header, rather than extracting it from the containing Media Type.
- Imports the `mime` module into the HTTP Thrift endpoint as well as the Zipkin endpoints and resolves the `Content-Type` using the `mime` package's [`ParseMediaType`](https://golang.org/pkg/mime/#ParseMediaType) method.
> Parse media types in the Content-Type header correctly

- cmd/standalone/Dockerfile
- gRPC Prototype has all-in-one-support, but the dockerfile doesn't expose the port yet 
- add the port to the all-in-one Dockerfile
> adds the gRPC port to the docker-all-in-one Dockerfile (#773)

- cmd/ingester/app/builder/builder.go
- cmd/ingester/app/flags.go
- cmd/ingester/app/flags_test.go
- cmd/ingester/main.go
- #929 
- Add options.go to configure ingester using viper
- Add main.go to initialize and start Ingester
> Ingester Main

- plugin/storage/integration/kafka_test.go
- #929 
- Use Ingester in the Kafka integration test
> Ingester integration test

- pkg/es/config/config.go
It's important to check every bulk response because
root error can be nil even when some response failed.
> Add error logging for individual ES bulk reposes

- plugin/storage/es/spanstore/schema.go
Fixes indentation in ES schema. The file contained spaces and tags. Now the indentation is done only with tags.
> Remove spances from ES schema

- cmd/ingester/app/consumer/offset/manager.go
- cmd/ingester/app/consumer/offset/manager_test.go
fix duplicate metrics collector registration attempted panic
use different names for counter and gauge metrics collector.
> fix panic: duplicate metrics collector registration attempted

- glide.lock
- glide.yaml
- model/model.pb.go
Undo some upgrades introduced in #940. A short term fix to #985.
> Pin proto / gogo versions for repeatable builds

- plugin/storage/integration/domain_trace_compare_test.go
- plugin/storage/integration/elasticsearch_test.go
- plugin/storage/integration/integration_test.go
- plugin/storage/integration/kafka_test.go
- plugin/storage/integration/memstore_test.go
Pulling these changes out of #984.
> Fix logging in the integration tests

- cmd/agent/app/testutils/mock_collector_test.go
- cmd/agent/app/testutils/thriftudp_client_test.go
-  Resolves #1002.
- Use `256` to overflow IP address.
> Use reliable bad address to guarantee failure

- scripts/travis/kafka-integration-test.sh
- Fixes #1004 (hopefully). 
- Use netcat to wait until Kafka is up before beginning integration test.
> Use netcat to detect when Kafka is up

- pkg/es/config/config.go
- plugin/storage/es/dependencystore/storage.go
- plugin/storage/es/dependencystore/storage_test.go
- plugin/storage/es/esCleaner.py
- plugin/storage/es/factory.go
- plugin/storage/es/options.go
- plugin/storage/es/spanstore/reader.go
- plugin/storage/es/spanstore/reader_test.go
- plugin/storage/es/spanstore/writer.go
- plugin/storage/es/spanstore/writer_test.go
- plugin/storage/integration/elasticsearch_test.go
Resolves #799 
Dependency job PR:  https://github.com/jaegertracing/spark-dependencies/pull/38
> Make ES index name configurable

- cmd/ingester/app/consumer/consumer.go
- cmd/ingester/app/consumer/consumer_test.go
Shutdown all partitions before shutting down the sarama consumer. This sidesteps   https://github.com/bsm/sarama-cluster/issues/255 and ensures that the shutdown completes in a reasonable timeframe. 
A given host could be reassigned the same partition quickly. In this case, we wait for proper shutdown and draining of the messages queue to prevent committing offsets for more recent messages before processing older ones. 
While this solution works on one host, it doesn't scale to multiple hosts because `sarama-cluster` does not provide an API to complete actions after a rebalance is triggered, but before subscriptions are released. This is being addressed as part of https://github.com/Shopify/sarama/pull/1099. 
> Shutdown sarama consumer cleanly

- Makefile
We do not pin a specific version of tools. It's better to update them because on travis they are not cached and always used the new ones.
> Update tools when installing

- plugin/storage/integration/kafka_test.go
Reverts jaegertracing/jaeger#1068
See https://github.com/jaegertracing/jaeger/issues/1011#issuecomment-423275998
> Revert "Fix failing kafka integration test"

- .gitignore
- Makefile
- cmd/ingester/Dockerfile
- scripts/travis/build-docker-images.sh
- scripts/travis/package-deploy.sh
Resolves https://github.com/jaegertracing/jaeger/issues/1031 
This supersede https://github.com/jaegertracing/jaeger/pull/1033
> Ingester binaries & Docker

- CHANGELOG.md
- storage/spanstore/metrics/decorator.go
- storage/spanstore/metrics/decorator_test.go
Currently jaeger-query produces a set of metrics for the following operations: find traces, get operations, get services and get trace.
The set of metrics are (only showing one bucket for histograms):
```
jaeger_find_traces_attempts 1
jaeger_find_traces_errLatency_bucket{le="0.005"} 0
jaeger_find_traces_errors 0
jaeger_find_traces_okLatency_bucket{le="0.005"} 0
jaeger_find_traces_responses_bucket{le="0.005"} 1
jaeger_find_traces_successes 1
```
Errors and successes for latency and counters are separated out (including a further counter representing the total counts).
This PR consolidates the metrics to use common name with a `result` tag representing ok or err states.
Have a single counter `find_traces_requests` with tag result (ok, err) to …
> Consolidate query metrics and include result tag

- CHANGELOG.md
- storage/spanstore/metrics/decorator.go
- storage/spanstore/metrics/decorator_test.go
Addresses https://github.com/jaegertracing/jaeger/pull/1075#discussion_r221322279
Only issue is that the metric field needs a name, empty string does not work, so have called the overall counter(success/error) 'calls'. If another word is preferred let me know.
Revert to using the annotation approach for defining metrics.
> Specify metric name/tags via annotation

- cmd/agent/app/processors/thrift_processor.go
ReadBuf byte slice can be overriden before processing in processor is finished.
```
{"level":"error","ts":1538663826.591028,"caller":"processors/thrift_processor.go:117","msg":"Processor failed","error":"*jaeger.Batch error reading struct: *jaeger.Span error reading struct: *jaeger.Tag error reading struct: *jaeger.Tag field 7 read error: don't know what type: %!s(thrift.tCompactType=14)","stacktrace":"github.com/jaegertracing/jaeger/cmd/agent/app/processors.(*ThriftProcessor).processBuffer\n\t/home/ploffay/projects/golang/src/github.com/jaegertracing/jaeger/cmd/agent/app/processors/thrift_processor.go:117"}
{"level":"error","ts":1538663827.887695,"caller":"processors/thrift_processor.go:117","msg":"Processor failed","error":"*jaeger.Batch error reading struct: *jaeger.Span error reading …
```
> Fix processor overriding ReadBuf data

- .travis.yml
- crossdock/services/tracehandler_test.go
- plugin/storage/cassandra/dependencystore/storage.go
- plugin/storage/cassandra/spanstore/writer_test.go
Reproposing this now that https://github.com/golang/go/issues/27778 has been fixed.
> Use Go 1.11 in Travis

- examples/hotrod/README.md
- examples/hotrod/cmd/customer.go
- examples/hotrod/cmd/driver.go
- examples/hotrod/cmd/frontend.go
- examples/hotrod/cmd/root.go
- examples/hotrod/cmd/route.go
- examples/hotrod/pkg/tracing/init.go
- examples/hotrod/services/customer/server.go
- examples/hotrod/services/driver/redis.go
- examples/hotrod/services/driver/server.go
- glide.lock
- glide.yaml
- Support tracer env based initialization in hotrod
- Resolves: #920 
- Remove jAgentHostPort(jaeger-agent.host-port) flag.
- Replace config.Configuration() by config.FromEnv()
- Move metricsFactory.Namespace inside Init()
> Support tracer env based initialization in hotrod

- plugin/storage/cassandra/spanstore/reader.go
- PR fixes childSpan context in the cassandra query tracer. 
- Child-spans should be created with context, which was missing earlier.
> [Storage] Fix childspan context while tracing cassandra queries

- cmd/collector/main.go
Signed-off-by: Mindaugas Rukas <momomg@gmail.com>
Related to #1071
* Log jaeger-collector tchannel port
* Update jaeger-collector HTTP server log message
> Log jaeger-collector tchannel port

- cmd/agent/app/agent_test.go
- cmd/agent/app/builder.go
- cmd/agent/app/builder_test.go
- cmd/agent/app/flags.go
- cmd/agent/app/reporter/tchannel/builder_test.go
- cmd/agent/app/reporter/tchannel/collector_proxy.go
- cmd/agent/app/reporter/tchannel/collector_proxy_test.go
- cmd/agent/app/reporter/tchannel/flags.go
- cmd/agent/app/reporter/tchannel/flags_test.go
- cmd/agent/app/reporter/tchannel/reporter.go
- cmd/agent/main.go
- cmd/all-in-one/main.go
- docker-compose/jaeger-docker-compose.yml
Resolves: #927 
* agent tchannel flags moved to `reporter.tchannel.*`
* agent reporters have to be specified explicitly `b.WithReporters` - if none added create fails
* agent client configuration manager have to be specified explicitly `b.WithClientConfigManager` - if none added create fails
> Refactor agent configuration

- cmd/ingester/app/consumer/consumer.go
- cmd/ingester/app/consumer/consumer_metrics.go
- cmd/ingester/app/consumer/consumer_test.go
> Add a metric for number of partitions held

- cmd/ingester/app/flags.go
- cmd/ingester/app/flags_test.go
- cmd/ingester/main.go
- plugin/storage/integration/kafka_test.go
Resolves https://github.com/jaegertracing/jaeger/issues/1014
Resolves https://github.com/jaegertracing/jaeger/issues/1013
Resolves https://github.com/jaegertracing/jaeger/issues/1093
- Add default healthcheck port (14270)
- Add a configurable metrics HTTP handler (default port is 14271)
- Make Kafka flags the same as in the Collector (prefix is `kafka` instead of `ingester`)
I wasn't sure if I should have refactor the following:
- Move the various Kafka flags under `/pkg`
- I left it as is mainly because there's a mix of consumer vs producer flags and because the producer flags are under `plugins`
Also, should the `Parallelism` be under Kafka prefix? I felt it was more a `ingester` flags than a `kafka` one, but I don't have any strong opinion about it
> [ingester] Add metrics& healthcheck, rename Kafka cli flags

- plugin/storage/es/spanstore/reader.go
- plugin/storage/es/spanstore/reader_test.go
First draft, aims to fix #1043 
- Context is passed, but spans are not emitted for the ES backend.
- Create spans in calls to ES backend.
> [Storage] Emit spans for elastic storage backend

- cmd/agent/app/reporter/grpc/collector_proxy.go
- cmd/agent/app/reporter/grpc/collector_proxy_test.go
- cmd/agent/app/reporter/grpc/flags.go
- cmd/agent/main.go
- cmd/all-in-one/main.go
`initFromViper` was adding an empty address if no address was provided. all-in-one main added another address causing failed to connect logs.
I think the current patch is better because it exists the agent if no grpc address was provided - before it was reconnecting on empty address.
```bash
go run -tags ui ./cmd/all-in-one/main.go   --reporter.type=grpc                                         2:33 
{"level":"info","ts":1542115995.914291,"caller":"healthcheck/handler.go:99","msg":"Health Check server started","http-port":14269,"status":"unavailable"}
{"level":"info","ts":1542115995.9144924,"caller":"memory/factory.go:55","msg":"Memory storage configuration","configuration":{"MaxTraces":0}}
{"level":"info","ts":1542115995.9145684,"caller":"static/strategy_store.go:77","msg":"No sampling …
```
> Fix empty grpc address

- README.md
It would be helpful to be able to jump from this readme to the OpenTracing specification.
Signed-off-by: Bert Roos <bert@famroos.nu>
- Quickly get to the OpenTracing specification
- Added a link to the OpenTracing specification
> Add hyperlink to OpenTracing specification

- cmd/agent/app/agent.go
- cmd/agent/app/agent_test.go
- cmd/agent/app/builder.go
- cmd/agent/app/builder_test.go
- cmd/agent/app/flags.go
- cmd/agent/main.go
Resolves #1177 
I have removed metrics registration from agent. now following the same approach as in query, collector and allinone.
> Fix metrics handler registration in agent

- CHANGELOG.md
- cmd/agent/app/httpserver/server.go
- cmd/agent/app/httpserver/server_test.go
Related to https://github.com/jaegertracing/jaeger/issues/773#issuecomment-436602664
This is not something required but it seems wrong to have tag `tcollector-proxy` when the proxy can use any protocol.
> Rename tcollector proxy metric in agent

- cmd/all-in-one/main.go
> Add archive traces to all-in-one

- cmd/agent/app/processors/thrift_processor_test.go
- cmd/agent/app/reporter/tchannel/builder.go
- cmd/agent/app/reporter/tchannel/flags.go
- cmd/agent/app/reporter/tchannel/flags_test.go
- cmd/agent/app/reporter/tchannel/reporter.go
- cmd/agent/app/reporter/tchannel/reporter_test.go
So, this is less a fix for #1026 but more to kick off the discussion around: https://github.com/jaegertracing/jaeger/issues/927
While the original proposal has:
```
reporters:
- kind: tchannel
collector:
hostPort: ...
discovery:
minPeers: 10
- kind: grps
```
I kind of like:
```
tchannel:
grpc:
```
I took a stab at implementing my version and turns out it's super straight forward and is very little changed code. But if the preference is to have the originally proposed format, I'll make the changes. But now I'm curious, can we 2 different `tchannel` reporters?
Note: This will be a breaking change.
> [agent] Make timeout for reporting configurable

- cmd/agent/app/reporter/tchannel/reporter.go
Unused leftovers from https://github.com/jaegertracing/jaeger/pull/1180
> Remove unused code

- RELEASE.md
> Add naming convention for maintenance branches

- CONTRIBUTING.md
- CONTRIBUTING_GUIDELINES.md
> Document branches in contributing guidelines

- Gopkg.toml
- Pinning dependencies prevents causes the dep solver from trying other versions when solving. This is problematic when jaeger is imported alongside other projects.
- Because only specific dependencies in `Gopkg.toml` are updated when `dep ensure -update <dependency>` is executed, these pins are unnecessary. Unrelated version bumps cannot happen (as they used to with `glide`)
- Unpin dependencies
> Unpin dependencies in Gopkg.toml

- cmd/collector/app/zipkin/http_handler.go
- cmd/collector/app/zipkin/http_handler_test.go
- cmd/ingester/app/builder/builder.go
- cmd/ingester/app/flags.go
- cmd/ingester/app/flags_test.go
- model/converter/thrift/zipkin/deserialize.go
- model/converter/thrift/zipkin/deserialize_test.go
- plugin/storage/kafka/factory.go
- plugin/storage/kafka/marshalling_test.go
- plugin/storage/kafka/options.go
- plugin/storage/kafka/unmarshaller.go
- Ingesting Zipkin thrift span from Kafka: This is useful for a seamless migration from Zipkin. It is mentioned in #171
- Add an unmarshaller to process spans in zipkin thrift using what was used for collector zipkin API
> Add Zipkin Thrift as kafka ingestion format

- Gopkg.lock
- Gopkg.toml
- Makefile
Signed-off-by: Isaac Hier <isaachier@gmail.com>
- Resolves #1258.
- Use [required](https://golang.github.io/dep/docs/Gopkg.toml.html#required) list to maintain tool dependencies.
> Fix tools pruned by dep

- plugin/storage/es/spanstore/dbmodel/to_domain.go
- plugin/storage/es/spanstore/dbmodel/to_domain_test.go
> Fix dot replacement for int

- Gopkg.lock
- Gopkg.toml
The current version of CQL causes failures in spark-dependencies https://github.com/jaegertracing/spark-dependencies/pull/51#issuecomment-454820619. The tests with Jaeger 1.8.1 passes without problems See the build https://github.com/jaegertracing/spark-dependencies/pull/53
``
19/01/16 14:54:09 INFO CassandraDependenciesJobTest: STDERR: {"level":"error","ts":1547650449.1140292,"caller":"metrics/table.go:48","msg":"Failed to exec query","query":"[query statement=\"\\n\\t\\tINSERT\\n\\t\\tINTO service_name_index(service_name, bucket, start_time, trace_id)\\n\\t\\tVALUES (?, ?, ?, ?)\" values=[10fae286a78f4f64a04619e13b2d3e8f 0 1547650448754000 96591cdbaf960a86] consistency=LOCAL_ONE]","error":"read tcp 172.18.0.3:48606->172.18.0.2:9042: i/o …
> Pin cql version to a versin used before migraiton to dep

- pkg/es/config/config.go
- plugin/storage/es/factory.go
- plugin/storage/es/options.go
- plugin/storage/es/spanstore/reader.go
Signed-off-by: Annanay <annanay.a@media.net>
- Follow up PR for #1202 
- Added a CLI configurable option to limit the number of spans fetched in a single query to the ES backend.
> Add CLI configurable MaxNumSpans while retrieving spans from ES.

- plugin/storage/es/esCleaner.py
- plugin/storage/es/options.go
- plugin/storage/es/spanstore/reader.go
- plugin/storage/es/spanstore/reader_test.go
- plugin/storage/es/spanstore/writer.go
- plugin/storage/es/spanstore/writer_test.go
Resolves #1238 
Spark dependencies: https://github.com/jaegertracing/spark-dependencies/pull/52
The readers will still read from indices containing prefix "prefix:"
to keep backward compability.
> Change index prefix from : to -

- cmd/ingester/Dockerfile
> Update exposed ports in ingester dockerfile

- CHANGELOG.md
> Preparing release 1.9.0

- Makefile
- pkg/es/config/config.go
- plugin/storage/es/Dockerfile.rollover
- plugin/storage/es/esCleaner.py
- plugin/storage/es/esRollover.py
- plugin/storage/es/factory.go
- plugin/storage/es/factory_test.go
- plugin/storage/es/options.go
- plugin/storage/es/spanstore/index_utils.go
- plugin/storage/es/spanstore/reader.go
- plugin/storage/es/spanstore/reader_test.go
- plugin/storage/es/spanstore/writer.go
- plugin/storage/es/spanstore/writer_test.go
- scripts/travis/build-docker-images.sh
Resolves https://github.com/jaegertracing/jaeger/issues/818
Related to https://github.com/jaegertracing/jaeger/issues/1242
This adds the implementation of archive storage for ES. There are two possible configurations how to use this feature:
* the default - it will store and read archived traces from `jaeger-archive-span` index.
* using rollover API - it writers spans to an alias `jaeger-span-archive-write` and reads from an alias `jaeger-span-archive-read`. This deployment requires an external component that performs index managent: creating index, creating alias, callig rollover API and managing `max-span-age` by removing indices from read alias. This component is `esRollover.py` available as `jaeger-es-rollover` docker image.
As the default index name does not collide with aliases used …
> Support archive traces for ES storage

- plugin/storage/es/options.go
- plugin/storage/es/options_test.go
- plugin/storage/kafka/options.go
- plugin/storage/kafka/options_test.go
- Addresses the issue #1302 
- A stripWhiteSpace function is added for both ES and kafka 
- An additional whitespace is added to the strings used for testing
> Added whitespace tolerance for value for ES servers and kafka brokers

- plugin/storage/es/README.md
- plugin/storage/es/esCleaner.py
Resolves https://github.com/jaegertracing/jaeger/issues/1317
Add optional ES_USERNAME and ES_PASSWORD environment variables in order that esCleaner.py can authenticate against elasticsearch clusters.
> Make it possible for esCleaner.py to use a username/password

- README.md
> Added link to the maintainer's GitHub profile pages

- pkg/es/config/config.go
- plugin/storage/es/factory.go
- plugin/storage/es/factory_test.go
- plugin/storage/es/options.go
- plugin/storage/es/options_test.go
In k8s the auth token (serviceaccount) is injected to pod. 
> Load elasticsearch auth token from file

- Gopkg.lock
- Gopkg.toml
This includes the fix for https://github.com/grpc/grpc-go/issues/1928 (https://github.com/grpc/grpc-go/pull/2045), which makes jaeger-collector usable behind nginx (and probably other grpc/http2 implementations) as load balancers for its grpc endpoint.
More info: https://trac.nginx.org/nginx/ticket/1538
Require grpc-go >=1.13 instead of >=1.11
> Require a slightly newer version of grpc-go

- Gopkg.lock
- Gopkg.toml
Needed because of breaking change in sarama-cluster 2.1.15 (#1325)
> Pin sarama-cluster to 2.1.13

- pkg/es/config/config.go
- plugin/storage/es/factory.go
- plugin/storage/es/factory_test.go
- plugin/storage/es/options.go
Related to https://github.com/jaegertracing/jaeger/issues/1321#issuecomment-462753759
> Make Elasticsearch archive storage optional

- model/converter/thrift/zipkin/to_domain.go
- model/converter/thrift/zipkin/to_domain_test.go
When the span.Timestamp is 0, jaeger write the span with the timestamp to zero even when we have more informations in the annotations.
If the timestamp is zero, we determine if the span is a client or a server and extract timestamp and information from there
> Use Zipkin annotations if the timestamp is zero

- CHANGELOG.md
- model/dependencies.go
- model/dependencies_test.go
- pkg/cassandra/config/config.go
- plugin/storage/cassandra/dependencystore/model.go
- plugin/storage/cassandra/dependencystore/model_test.go
- plugin/storage/cassandra/dependencystore/storage.go
- plugin/storage/cassandra/dependencystore/storage_test.go
- plugin/storage/cassandra/factory.go
- plugin/storage/cassandra/factory_test.go
- plugin/storage/cassandra/options.go
- plugin/storage/cassandra/options_test.go
- plugin/storage/cassandra/schema/migration/v001tov002part1.sh
- plugin/storage/cassandra/schema/migration/v001tov002part2.sh
- plugin/storage/cassandra/schema/v002.cql.tmpl
- plugin/storage/integration/cassandra_test.go
- scripts/travis/cassandra-integration-test.sh
A lot of Copy Pasta from #793. Resolves #790.
Migration Path:
1) Run `v001tov002part1.sh` which will copy dependencies into a csv, update the `dependency UDT`, create a new `dependenciesv2` table, and write dependencies from the csv into the `dependenciesv2` table.
2) Run the collector and query services with the cassandra flag `dependency-sasi-disabled=true` which will update jaeger to read from the new `dependenciesv2` table.
3) Update [spark job](https://github.com/jaegertracing/spark-dependencies) to write to the new `dependenciesv2` table (this is a TODO).
4) Run `v001tov002part2.sh` which will delete the old dependency table and the SASI index.
Users who wish to continue to use the SASI indices don't have to do anything as the cassandra …
> Remove SASI indices

- plugin/storage/cassandra/schema/create.sh
- plugin/storage/cassandra/schema/docker.sh
This commit aims to add `/usr/bin/env bash` as a shebang line
to indicates scripts use bash shell for interpreting.
Signed-off-by: Nguyen Hai Truong <truongnh@vn.fujitsu.com>
- 
-
> Adding `/usr/bin/env bash`

- cmd/agent/app/reporter/grpc/collector_proxy_test.go
- cmd/agent/app/reporter/tchannel/reporter_test.go
- plugin/storage/cassandra/samplingstore/storage_test.go
- plugin/storage/cassandra/spanstore/operation_names_test.go
- plugin/storage/cassandra/spanstore/reader_test.go
- plugin/storage/cassandra/spanstore/service_names_test.go
- plugin/storage/cassandra/spanstore/writer_test.go
- plugin/storage/es/spanstore/writer_test.go
- plugin/storage/integration/elasticsearch_test.go
- Imports should be sorted by Go coding convention
- Sort the imports
> Fix unsorted imports

- model/process.go
- plugin/storage/es/spanstore/dbmodel/model.go
Although it is spelling mistakes, it might make an affects
while reading.
Signed-off-by: Nguyen Hai Truong <truongnh@vn.fujitsu.com>
> Remove duplicated words in comments

- CHANGELOG.md
- plugin/storage/cassandra/dependencystore/bootstrap.go
- plugin/storage/cassandra/dependencystore/bootstrap_test.go
- plugin/storage/cassandra/factory.go
- plugin/storage/cassandra/factory_test.go
- plugin/storage/cassandra/options.go
> Discover dependencies table version automatically

- plugin/storage/cassandra/schema/docker.sh
- docker script doesn't use CQLSH_HOST variable for final call to cqlsh
I suppose, it makes impossible to use docker image on other host that is not part of cassandra cluster.
- add CQLSH_HOST variable in place of host argument
> Use CQLSH_HOST in final call to cqlsh as well

- model/spanref_test.go
Currently, the URL of converter between **base64** and **HEX** is out of date.
This commit intends to update this URL to the working one.
Co-Authored-By: Nguyen Phuong An <AnNP@vn.fujitsu.com>
Signed-off-by: Kim Bao Long <longkb@vn.fujitsu.com>
- Update the deprecated URL
- A minor change
> Update a deprecated link in test file

- plugin/storage/es/esCleaner.py
- plugin/storage/es/esRollover.py
- scripts/utils/ids-to-base64.py
Modules which are imported to python are sorted alphabetically are
quicker to read and searchable.
Co-Authored-By: Dao Cong Tien tiendc@vn.fujitsu.com
Signed-off-by: Nguyen Hai Truong <truongnh@vn.fujitsu.com>
- 
-
> Alphabetically sorted modules import

- plugin/storage/es/dependencystore/storage.go
- plugin/storage/es/dependencystore/storage_test.go
Related to https://github.com/jaegertracing/jaeger/issues/1238
> Deprecate colon in index prefix in ES dependency store

- pkg/es/config/config.go
- plugin/storage/es/options.go
> Allow to use TLS with ES basic auth

- Gopkg.lock
- cmd/agent/app/flags_test.go
- cmd/agent/app/reporter/flags_test.go
- cmd/agent/app/reporter/grpc/collector_proxy.go
- cmd/agent/app/reporter/grpc/collector_proxy_test.go
- cmd/agent/app/reporter/grpc/flags.go
- cmd/agent/app/reporter/grpc/flags_test.go
- cmd/agent/app/reporter/tchannel/flags_test.go
- cmd/collector/app/builder/builder_flags.go
- cmd/collector/main.go
- pkg/testutils/logger_test.go
Extends PR #1311 (which was in ghouscht:master, hard to add to directly)
> Support secure gRPC channel between agent and collector

- cmd/agent/app/builder.go
- cmd/agent/app/builder_test.go
- cmd/agent/app/reporter/metrics_test.go
- cmd/agent/app/reporter/tchannel/flags.go
- cmd/agent/main.go
- cmd/all-in-one/main.go
> Allow thrift reporter even if grpc hosts are not provided

- plugin/storage/es/esRollover.py
> Make rollover idempotent

- CHANGELOG.md
> Preparing release 1.11

- plugin/storage/es/esRollover.py
Related to #1407 
If the init was run after rollover action it would add indices to read and more importantly write alias. The write alias can contain only one index. 
```
python3  esRollover.py init http://localhost:9200
CONDITIONS='{"max_age": "1s"}' python3  esRollover.py rollover http://localhost:9200
python3  esRollover.py init http://localhost:9200
```
> Do not add indices to not empty alias

- crossdock/jaeger-docker-compose.yml
Related to https://github.com/jaegertracing/jaeger/commit/d8ab6948c24ddd8d9b27a9bb6459fe40be1fe432#r32679636
> Increase grpc retry to 1000 in xdock

- cmd/collector/app/sanitizer/zipkin/span_sanitizer.go
- cmd/collector/app/span_processor_test.go
- cmd/collector/app/zipkin/http_handler.go
- cmd/ingester/app/builder/builder.go
- examples/hotrod/cmd/root.go
- model/ids.go
- model/sort.go
- plugin/storage/es/spanstore/dbmodel/to_domain.go
This commit rewrites some if-else-if-else chains as a switch.
Based on Go style guide:
https://golang.org/doc/effective_go.html#switch
Signed-off-by: Kirill Motkov <motkov.kirill@gmail.com>
> Rewrite if-else to switch statements

- plugin/storage/cassandra/spanstore/writer.go
Optimizes a bit "isJSON" check for tag value.
RawMessage replaces `map[string]interface{}` as a target for json.Unmarshal.
Unmarshalling checks JSON validity even when unmarshal to RawMessage.
> use RawMessage in check of value for being json

- CHANGELOG.md
- cmd/ingester/app/flags.go
- cmd/ingester/app/flags_test.go
- plugin/storage/integration/kafka_test.go
- plugin/storage/kafka/factory_test.go
- plugin/storage/kafka/options.go
- plugin/storage/kafka/options_test.go
They are deprecated in favor of `kafka.producer` and `kafka.consumer` flags
- Closes #1190
- Follow up of #1360
- Address this comment to remove whitespace: https://github.com/jaegertracing/jaeger/pull/1360#discussion_r259557341
- The flags were still defined twice, so the crash described in #1190 still exists. Now it does not:
```
$ SPAN_STORAGE_TYPE=kafka go run cmd/ingester/main.go -h
Jaeger ingester consumes spans from a particular Kafka topic and writes them to all configured storage types.
Usage:
(experimental) jaeger-ingester [flags]
(experimental) [command]
Available Commands:
env         Help about environment variables
help        Help about any command
version     Print the version
Flags:
--config-file string                   Configuration file in JSON, TOML, YAML, HCL, or …
```
> Remove deprecated kafka flags

- proto-gen/api_v2/api_v2.pb.gw.go
- proto-gen/openapi/api_v2.swagger.json
The grpc-gateway files are out of sync with its current version in the Gopkg. We're not actually using them, but this is needed before fixing #1431.
> Regenerate grpc-gateway code

- .travis.yml
- Makefile
- proto-gen/api_v2/api_v2.pb.gw.go
> Verify that proto-generated files are up-to-date

- plugin/storage/es/options.go
Additionally, replaced `ElasticSearch` by `Elasticsearch`
> Fixed typo in the ES 'flush-interval' option.

- crossdock/main.go
- crossdock/services/tracehandler.go
- the crossdock tests in the clients do not need to run independent Jaeger components with separate storage, they can use all-in-one. But the testdriver has hardcoded host names for the components that it checks.
- Introduce env variables to optionally override agent/collector/query addresses
> Parameterize crossdock test_driver

- .travis.yml
- scripts/import-order-cleanup.sh
Signed-off-by: Annanay <annanay.a@media.net>
- Travis complains about unformatted proto generated files
- Add list of proto generated files to ignored files in import-order-cleanup.
> Ignore autogenerated files from import-order-cleanup

- CONTRIBUTING.md
- cmd/agent/app/builder.go
- cmd/agent/app/flags.go
- cmd/agent/app/reporter/tchannel/flags.go
- cmd/agent/main.go
- cmd/all-in-one/main.go
- cmd/builder/builder_options.go
- cmd/collector/app/builder/builder_flags.go
- cmd/collector/main.go
- cmd/flags/admin.go
- cmd/flags/flags.go
- cmd/flags/service.go
- cmd/ingester/app/flags.go
- cmd/ingester/app/flags_test.go
- cmd/ingester/main.go
- cmd/query/app/flags.go
- cmd/query/main.go
- examples/hotrod/services/frontend/gen_assets.go
- pkg/healthcheck/handler.go
- pkg/healthcheck/handler_test.go
- pkg/healthcheck/internal_test.go
- plugin/storage/cassandra/options.go
- plugin/storage/es/mappings/gen_assets.go
- plugin/storage/memory/factory.go
- ports/empty_test.go
- ports/ports.go
Health checks, metrics, and other housekeeping data should not be exposed on the ports that also serve public APIs
* Partially supersedes #1375.
* Resolves #1428
* Resolves #1332
* combines health check and metrics handlers on a single admin port. There are **breaking changes**:
* agent metrics move from /sampling config port to the new admin port 14271
* query metrics move from /api port to the former health check port 16687
* collector metrics move from HTTP API port to the former health check port 14269
* ingestor metrics move from standalone port 14271 to the health check port 14270
* groups all numeric port numbers in a single file `ports/ports.go` for easier reference
* consolidates common boilerplate code in all binaries into a Service type
* flag `health-check-http-port` is …
> Add Admin port and group all ports in one file

- cmd/flags/service.go
- Resolves #160. Sets the default config behavior to no sampling for zap
- Changes the default sampling config for the zap logger to nil
> Set default zap sampling config to nil

- pkg/es/config/config.go
Add nil pointer check in elasticsearch bulkprocessor's
after callback, defined inside pkg/es/config/config.go.
In some rare cases, elasticsearch request will return
error with nil response, and then nil response will
be passed into after callback, and using of nil pointer
will cause process crash.
Signed-off-by: YEXINGZHE54 <429567185@qq.com>
- Resolves #1440 
- Add nil pointer check inside es after callback
> Avoid process crash when elasticsearch response is nil

- crossdock/main.go
- pkg/healthcheck/handler.go
- pkg/healthcheck/internal_test.go
- Return 200 OK for status `ready`
- Return Json containing time `startedAt` and `upTime` statistics
Resolves #1450
> Return info msg for `/health` endpoint

- Gopkg.lock
- Gopkg.toml
- Makefile
- cmd/collector/app/builder/builder_flags.go
- cmd/collector/main.go
Signed-off-by: Jonas Verhofsté <25819942+JonasVerhofste@users.noreply.github.com>
- Handling of CORS on the Zipkin collector service, issue #703 
- Add and call the CORS handler
- Add variables for allowed origins and headers
> Add CORS handling for Zipkin collector service, fixes #703

- pkg/es/config/config.go
- plugin/storage/es/options.go
- plugin/storage/es/options_test.go
- Resolves #1471
- Add `SkipHostVerify` field to `TLSConfig` struct, exposed by `.tls.skip-host-verify`CLI flag
> Expose tls.InsecureSkipVerify to es.tls.* CLI flags

- cmd/query/app/query_parser.go
- cmd/query/app/query_parser_test.go
The check only applies to Cassandra backend, which already has the same check enabled.
Resolves #1047.
Signed-off-by: Ivan Babrou <ibobrik@gmail.com>
> Remove check for tags + duration in query parser

- cmd/ingester/app/consumer/consumer.go
- cmd/ingester/app/consumer/consumer_metrics.go
- cmd/ingester/app/consumer/consumer_test.go
Counters cannot be decremented in Prometheus:
```
panic: counter cannot decrease in value
goroutine 895 [running]:
github.com/jaegertracing/jaeger/vendor/github.com/prometheus/client_golang/prometheus.(*counter).Add(0xc000790600, 0xbff0000000000000)
/home/travis/gopath/src/github.com/jaegertracing/jaeger/vendor/github.com/prometheus/client_golang/prometheus/counter.go:71 +0xa3
github.com/jaegertracing/jaeger/vendor/github.com/uber/jaeger-lib/metrics/prometheus.(*counter).Inc(0xc0006b42a0, 0xffffffffffffffff)
/home/travis/gopath/src/github.com/jaegertracing/jaeger/vendor/github.com/uber/jaeger-lib/metrics/prometheus/factory.go:183 +0x46
github.com/jaegertracing/jaeger/cmd/ingester/app/consumer.(*Consumer).handleMessages(0xc0004c4300, 0xf08c60, 0xc00054e630) …
```
> Switch from counter to a gauge for partitions held

- Gopkg.lock
- Gopkg.toml
- cmd/agent/app/reporter/grpc/builder.go
-  #1491 
- Upgrade grpc to 1.20.1
> upgrade grpc to 1.20.1

- cmd/collector/app/span_processor.go
- model/converter/thrift/jaeger/to_domain.go
Signed-off-by: jung <jung@uber.com>
-  Resolves #1490 
- include span format tag for every processed span in the collector
> Add span format tag for jaeger-collector

- Gopkg.lock
- Gopkg.toml
- Makefile
> Install gosec from vendor and pin to 1.3.0

- cmd/ingester/app/builder/builder.go
- cmd/ingester/app/flags.go
- cmd/ingester/app/flags_test.go
- pkg/kafka/consumer/config.go
- plugin/storage/integration/kafka_test.go
#1506 
supports customized kafka client id in ingester
> supports customized kafka client id

- Makefile
- scripts/travis/build-crossdock.sh
In #1461  the crossdock step fail repeatedly when trying to build an image with elasticcurator
https://travis-ci.org/jaegertracing/jaeger/jobs/527861990#L620
Elastic is not needed for crossdock.
> Remove ES dependency from crossdock

- cmd/env/command.go
- plugin/storage/factory.go
> Add all storages to env command

- cmd/agent/app/reporter/grpc/collector_proxy.go
- cmd/agent/app/reporter/grpc/collector_proxy_test.go
- #1539 
- Expose grpc conn for agent so it could register grpc client with it
we should revert the change after baggage and throttler are fully migrated to oss
> temporarily expose grpc conn

- cmd/all-in-one/Dockerfile
…sticsearch backend. (#1545)
Signed-off-by: chandresh-pancholi <chandreshpancholi007@gmail.com>
- all-in-one image misses ca-certs - can not connect to cloud-based elasticsearch backend 
- NA
> Add CA certs to all-in-one image

- examples/hotrod/README.md
The version in the `examples/hotrod/README.md` is quite old (~10 months I believe) and contains bugs that have been fixed. It seems to me that the example docs should use `latest`. If we don't want to use a dynamic version, this could be a more recent static version (`1.12` in particular).
> Update version in hotrod example

- Makefile
- RELEASE.md
I have written https://github.com/pavolloffay/github-changelog, I could not find anything good and customizable. Now it generates only non categorized changes. I will extend it to create categories based on labels on PRs.
```
* Use latest all-in-one image in hotrod ([#1555](https://github.com/jaegertracing/jaeger/pull/1555), [@everett980](https://github.com/everett980))
* Add CA certs to all-in-one image ([#1554](https://github.com/jaegertracing/jaeger/pull/1554), [@chandresh-pancholi](https://github.com/chandresh-pancholi))
* temporarily expose grpc conn ([#1547](https://github.com/jaegertracing/jaeger/pull/1547), [@guanw](https://github.com/guanw))
* Add all storages to env command ([#1541](https://github.com/jaegertracing/jaeger/pull/1541), …
```
> Add changelog target to make

- cmd/all-in-one/Dockerfile
- scripts/travis/build-all-in-one-image.sh
Signed-off-by: wxdao <waxiadao@gmail.com>
Before this PR building of all-in-one image uses the whole project directory as docker build context, while the artifacts needed for the image are all stored under cmd/all-in-one/. Since the former could take up as large as 1Gi after `make build`, most of the building time is consumed on `Sending build context to Docker daemon`.
This PR tweaks Dockerfile in cmd/all-in-one and the build script in scripts/travis to limit docker build context to be cmd/all-in-one, where all the needed artifacts are stored after `make build-all-in-one-linux`.
> Speed up building of all-in-one image by enclosing docker build context

- Gopkg.lock
- cmd/agent/main.go
- cmd/all-in-one/main.go
- cmd/collector/main.go
- cmd/ingester/main.go
- cmd/query/main.go
-  Fixes Issue https://github.com/jaegertracing/jaeger-operator/issues/396
- This PR set the GOMXPROCS to an automatic valid depending of the containers limits.
Does we need to make this configurable? I mean enable/disable using flags? @pavolloffay @objectiser
> Automatically set GOMAXPROCS

- plugin/storage/es/esCleaner.py
Resolves #1468 
The original stacktrace
```
Traceback (most recent call last):
File "plugin/storage/es/esCleaner.py", line 89, in <module>
main()
File "plugin/storage/es/esCleaner.py", line 49, in main
filter_main_indices(ilo, prefix)
File "plugin/storage/es/esCleaner.py", line 65, in filter_main_indices
ilo.filter_by_age(source='name', direction='older', timestring='%Y-%m-%d', unit='days', unit_count=int(sys.argv[1]))
File "/usr/local/lib/python3.6/site-packages/curator/indexlist.py", line 495, in filter_by_age
stats_result=stats_result
File "/usr/local/lib/python3.6/site-packages/curator/indexlist.py", line 356, in _calculate_ages
self._get_name_based_ages(timestring)
File "/usr/local/lib/python3.6/site-packages/curator/indexlist.py", line 279, in _get_name_based_ages …
```
> Do not fail es-cleaner if there are no jaeger indices

- cmd/all-in-one/Dockerfile
Fixes issue #1543, badger does not start without mounting tmpfs.
Adds /tmp volume to the container. This allows the badger storage to work with a simple command:
``docker run -e SPAN_STORAGE_TYPE=badger``
Which uses tmpfs in the container in this case. It does not prevent customization to the tmpfs, so user can still issue mount parameters for the tmpfs (such as limiting memory size) by overriding the /tmp mount.
> Add tmp-volume to all-in-one image, fixes #1543

- .gitignore
- Gopkg.lock
- Gopkg.toml
- cmd/agent/main.go
- cmd/all-in-one/main.go
- cmd/collector/main.go
- cmd/docs/command.go
- cmd/docs/command_test.go
- cmd/ingester/main.go
- cmd/query/main.go
Resolves #1537 
docs PR: https://github.com/jaegertracing/documentation/pull/257
> Add docs generation command

- cmd/all-in-one/main.go
- cmd/env/command.go
- cmd/ingester/main.go
- pkg/version/command.go
> Refactor commands descriptions

- Gopkg.lock
- cmd/flags/service.go
Resolves #1602, supersedes #1330.
Sample output:
```
{"level":"info","ts":1560530693.131958,"caller":"grpc/clientconn.go:242","msg":"parsed scheme: \"\"","system":"grpc","grpc_log":true}
{"level":"info","ts":1560530693.1319869,"caller":"grpc/clientconn.go:248","msg":"scheme \"\" not registered, fallback to default scheme","system":"grpc","grpc_log":true}
{"level":"info","ts":1560530693.132017,"caller":"grpc/resolver_conn_wrapper.go:113","msg":"ccResolverWrapper: sending update to cc: {[{127.0.0.1:14250 0  <nil>}] }","system":"grpc","grpc_log":true}
{"level":"info","ts":1560530693.132215,"caller":"base/balancer.go:76","msg":"base.baseBalancer: got new resolver state: {[{127.0.0.1:14250 0  <nil>}] }","system":"grpc","grpc_log":true} …
```
> Direct grpc logs to Zap logger

- cmd/flags/admin.go
- cmd/query/app/server.go
- cmd/query/app/server_test.go
Signed-off-by: Abhilash Gnan <abhilashgnan@gmail.com>
- Resolves #1542
- Query service servers return errors on SIGINT (when we call `Close()` on them). This PR handles such errors correctly and stops from logging
Previously merged PR: #1598 - I think, fixed the similar issue, but solving for SIGTERM. So it stopped from logging errors when i tested rebuilt query image inside a [all-in-one](https://github.com/jaegertracing/jaeger-kubernetes/blob/master/all-in-one/jaeger-all-in-one-template.yml) pod
> Query service: fix logging errors on SIGINT

- plugin/storage/es/spanstore/reader.go
- plugin/storage/es/spanstore/reader_test.go
In Jaeger 1.9.0 the index prefix separator was changed from ":" (not allowed in ES7) to "-". However query still reads from deprecated indices to keep backward compatibility. After half year old indices should be expired so safe to remove.
https://github.com/jaegertracing/jaeger/blob/master/CHANGELOG.md#190-2019-01-21
> Remove deprecated index prefix separator : from Elastic

- plugin/storage/es/spanstore/reader.go
- plugin/storage/integration/elasticsearch_test.go
> Fix archive storage not querying old spans older than maxSpanAge

- plugin/storage/es/spanstore/dbmodel/to_domain.go
- plugin/storage/es/spanstore/dbmodel/to_domain_test.go
- plugin/storage/es/spanstore/reader.go
> Use json number when unmarshalling data from ES

- cmd/agent/app/agent_test.go
- cmd/agent/app/processors/thrift_processor.go
We had a data race with Agent.Stop() failing if called immediately
after Agent.Run() returns.
The root cause of the race was that Stop() called WaitGroup.Wait()
before Run() called WaitGroup.Add() for the first time which is
prohibited: https://golang.org/pkg/sync/#WaitGroup.Add
This change moves WaitGroup.Add() to earlier stage which guarantees
that WaitGroup.Wait() will be called after that.
Github issue: https://github.com/jaegertracing/jaeger/issues/1624
Testing done:
Added an automated test which was failing before the bug was fixed
and does not fail any more after the fix.
Also verified that `make test` passes.
Signed-off-by: Tigran Najaryan <tigran@najaryan.net>
> Fix data race between Agent.Run() and Agent.Stop()

- plugin/storage/cassandra/schema/docker.sh
Currently the Cassandra schema builder job only works on open Cassandra installations. This PR fixes this by modifying the script so that two environmental variables, CASSANDRA_USER and CASSANDRA_PASSWORD, could be passed in to supply these credentials.
Signed-off-by: E.G. Hornbostel <eg.hornbostel@pricespider.com>
- Currently the Cassandra schema builder job only works on open Cassandra installations. This PR fixes this by modifying the script so that two environmental variables, CASSANDRA_USER and CASSANDRA_PASSWORD, could be passed in to supply these credentials.
- Modify docker.sh script to allow for credentials to be assed in to cqlsh
> Allow Cassandra schema builder to use credentials

- Gopkg.lock
- Gopkg.toml
- cmd/ingester/app/builder/builder.go
- cmd/ingester/app/flags.go
- pkg/kafka/auth/.nocover
- pkg/kafka/auth/config.go
- pkg/kafka/auth/kerberos.go
- pkg/kafka/auth/options.go
- pkg/kafka/consumer/config.go
- pkg/kafka/producer/config.go
- plugin/storage/kafka/options.go
- Add support for Kerberos authentication to ingester/collector
- Fixes #1188 
-  Now that sarama library has support for Kerberos authentication, this PR add support for it on the jaeger side using flags.
> Kafka kerberos authentication support for collector/ingester

- cmd/query/app/flags.go
- cmd/query/app/server.go
- cmd/query/app/server_test.go
- cmd/query/app/token_propagation_hander_test.go
- cmd/query/app/token_propagation_handler.go
- cmd/query/main.go
- pkg/es/config/config.go
- plugin/storage/es/options.go
- plugin/storage/es/spanstore/reader.go
- plugin/storage/es/spanstore/reader_test.go
- plugin/storage/es/spanstore/service_operation.go
- plugin/storage/es/spanstore/writer.go
- storage/spanstore/token_propagation.go
- storage/spanstore/token_propagation_test.go
- To provide fine grained visibility of tracing information stored in Elasticsearch, protected using tools like SearchGuard, it would be useful if the OAuth bearer token for the authenticated user could be passed through the Query service to the ES storage plugin and then propagated to the ES cluster.
To enable users to disable the propagation, this PR includes the possibility of enable/disable this behavior using a flag.
- I injected the token in the context, and used it on ES plugin, also included a flag, but not sure if the flag should be at the query level, I put it the query level because this behavior only makes sense there. (IMHO). Also I did some changes to disable health check on plugin because the token is provided on each request, so I cannot check health of ES cluster when …
> Passthrough OAuth bearer token supplied to Query service through to ES storage

- cmd/query/app/flags.go
To false for backwards compatibility
Fixes #1641
- 
-
> Change default for bearer-token-propagation

- pkg/cassandra/config/config.go
- plugin/storage/cassandra/options.go
Signed-off-by: Sagar Anand <sagar.anand015@gmail.com>
- Resolves #1472 
- Added connect-timeout as a flag in cassandra storage config which is then used by gocql for connecting to the Cassandra Servers
> Add connect-timeout for Cassandra

- plugin/storage/badger/factory.go
- plugin/storage/badger/options.go
Resolves #1652 (Windows default directories do not work), but also ensures that the directories are created successfully since badger only creates the last directory - not the missing parent directories. This is why default directory does not work unless ``data`` is created first.
Use os.pathSeparator instead of hardcoded ``/`` and create directories if possible.
> [badger] Make default dirs work in Windows

- plugin/storage/badger/spanstore/reader.go
- plugin/storage/badger/spanstore/rw_internal_test.go
Signed-off-by: Michael Burman <yak@iki.fi>
Resolves #1604, seeing multiple traces in the UI 
Changes to the badger storage backend reader part (no changes to write path):
Filtering duplicates from the index key results when those occur in the same index seek. Previously only cross-index-seeks had their duplicates removed. Also added a test to ensure this does not break anymore.
> [badger] Filter duplicate results from a single indexSeek [fixes #1604]

- plugin/storage/cassandra/schema/docker.sh
This follows #1635 in order to solve https://github.com/jaegertracing/jaeger-operator/issues/469
- The cassandra-schema-builder is not using the provided credentials when trying to connect to cassandra to know if it's up.
- The query describing the keyspaces (used to wait for cassandra) will use the credentials if any is provided.
> Use credentials when describing keyspaces in cassandra schema builder

- cmd/ingester/app/builder/builder.go
- cmd/ingester/app/flags.go
- cmd/ingester/app/flags_test.go
- pkg/kafka/consumer/config.go
Jaeger ingester silently doesn't consume messages, when kafka server doesn't support kafka protocol in version 0.0.9.
I added new `kafka.consumer.protocol-version` configuration option, that allows specify kafka protocol version to use. Default is "0.9.0.0" which was used by bsm/sarama-cluster as default version (for backwards compatibility).
> Configurable kafka protocol version for msg consuming by jaeger ingester

- storage/spanstore/downsampling_writer.go
- storage/spanstore/downsampling_writer_test.go
- #1664 
- It's potential for conversion from an uint64 traceid to float64 number to lose precision.
> Fix the threshold precision issue

- plugin/storage/es/spanstore/reader.go
- plugin/storage/es/spanstore/reader_test.go
Resolves #1279 
Rebased #1298 and added test 
cc) @Volcannozzz
> Fix duplicated spans when querying Elasticsearch

- cmd/query/app/token_propagation_hander_test.go
- cmd/query/app/token_propagation_handler.go
- openshift oauth-proxy  (and is possible that other proxies) does not put the authorization header in the form `Authorization: <type> <token> `, they put the token in the form `Authorization: <token>`  and assumed that the token there is a bearer token.
- Allow those kind of tokens to be propagated.
> Allow token propagation if token type is not specified

- Makefile
- plugin/storage/es/esCleaner.py
- plugin/storage/integration/elasticsearch_test.go
- plugin/storage/integration/es_index_cleaner_test.go
- scripts/travis/es-integration-test.sh
Resolves #1681 
Resolves #1682
> Support index cleaner for rollover indices and add integration tests

- pkg/cassandra/config/config.go
- plugin/storage/cassandra/options.go
Signed-off-by: Sagar  Anand <sagar.anand015@gmail.com>
- Resolves https://github.com/jaegertracing/jaeger/issues/1667 and https://github.com/jaegertracing/jaeger/issues/1105
- Added flag to drive the Cassandra Connection Compression from config. This will be use to use SnappyCompressor by default or opt out of using the SnappyCompressor
> Added flags for driving cassandra connection compression through config

- Makefile
- cmd/agent/app/reporter/flags_test.go
- cmd/collector/app/tchannel_handler_test.go
- cmd/docs/command_test.go
- cmd/query/app/grpc_handler_test.go
- cmd/query/app/handler_archive_test.go
- cmd/query/app/token_propagation_hander_test.go
- plugin/storage/badger/spanstore/cache_test.go
- plugin/storage/badger/spanstore/read_write_test.go
- plugin/storage/badger/spanstore/rw_internal_test.go
- plugin/storage/cassandra/spanstore/writer_test.go
- plugin/storage/es/dependencystore/storage_test.go
- plugin/storage/es/factory_test.go
- plugin/storage/es/spanstore/dbmodel/to_domain_test.go
- plugin/storage/es/spanstore/reader_test.go
- plugin/storage/es/spanstore/writer_test.go
- plugin/storage/integration/elasticsearch_test.go
- plugin/storage/integration/es_index_cleaner_test.go
- plugin/storage/integration/grpc_test.go
- storage/spanstore/token_propagation_test.go
For some reason we were excluding them.
> Run go fmt and lint on test files

- plugin/storage/es/spanstore/reader_test.go
- Fixes #1703 by changing the way assertions are done for items within arrays
> Fixed intermittent test

- plugin/pkg/distributedlock/cassandra/lock.go
- plugin/pkg/distributedlock/cassandra/lock_test.go
Discovered during internal testing while consolidating oss and internal adaptive sampling code.
Unfortunately, we don't have a good integration tests for this yet.
> [bug fix] Pass TTL as int, not as float64

- cmd/query/app/fixture/ui-config-hotreload.json
- cmd/query/app/static_handler.go
- cmd/query/app/static_handler_test.go
- As seen on jaegertracing/jaeger-operator#533, changing the UI configuration requires the Jaeger Query to be stopped and started again. As the file is sent as is inside the HTML that is requested by the browser, it's safe to simply watch the file for changes and replace the internal `indexHTML` property.
> Added support for hot reload of UI config

- cmd/collector/app/metrics.go
- cmd/collector/app/span_processor.go
- cmd/collector/app/span_processor_test.go
- Fixes #1722 by returning an error before attempting to write the span that has no process attached to it. For the metrics collection, the service name is set to `__unknown`. Previously, such problems were not apparent via metrics.
Before this PR, the collector would crash at different points (see #1722) depending on the storage being used. After this PR, the following message is shown in the logs:
```
{"level":"error","ts":1565269296.058833,"caller":"app/span_processor.go:114","msg":"Failed to save span","error":"process is empty for the span","stacktrace":"github.com/jaegertracing/jaeger/cmd/collector/app.(*spanProcessor).saveSpan\n\t/mnt/storage/jpkroehling/Projects/src/github.com/jaegertracing/jaeger/cmd/collector/app/span_processor.go:114\ngithub.com/jaegertracing/jaeger/cmd/collecto …
```
> Added null guards to 'Process' when processing an incoming span

- Makefile
- plugin/storage/integration/token_propagation_test.go
- scripts/travis/es-integration-test.sh
-  e2e tests for token propagation to ES
-  This is an integration test that make sure that the token reached ES storage.
> e2e test for elasticsearch token propagation

- scripts/travis/build-all-in-one-image.sh
- #1583 
- Add additional bash script to dump docker log if docker integration test panic&fail
> dump log if integration test fails

- plugin/sampling/strategystore/adaptive/cache.go
- plugin/sampling/strategystore/adaptive/cache_test.go
- plugin/sampling/strategystore/adaptive/floatutils.go
- plugin/sampling/strategystore/adaptive/floatutils_test.go
- plugin/sampling/strategystore/adaptive/processor.go
- plugin/sampling/strategystore/adaptive/processor_test.go
- plugin/sampling/strategystore/adaptive/weightvectorcache.go
- plugin/sampling/strategystore/adaptive/weightvectorcache_test.go
This makes it easier to reconcile our internal code with oss as part of the move (#365).
> Make some utils public to ease transition

- cmd/collector/app/builder/builder_flags.go
- cmd/collector/main.go
Signed-off-by: Jonas Verhofsté <25819942+JonasVerhofste@users.noreply.github.com>
When I implemented the CORS handling in f9702c4b03903601e752af784b50a66b49c6058f (#1463), I forgot that there can be more than one origin and one header. This adds the functionality of specifying multiple origins and headers as a comma separated list.
> Change Zipkin CORS origins and headers to comma separated list

- plugin/storage/badger/spanstore/read_write_test.go
- plugin/storage/badger/spanstore/reader.go
- plugin/storage/badger/spanstore/rw_internal_test.go
Resolves #1719, the index seeks were not correctly merged and filtered. 
Make the merge-join correctly update two indices when encountering equal items. Also, the input must be the output of previous merge. Also, changed ASC to DESC reversing to happen after the top query filtering - thus reducing unnecessary work.
> Fix badger merge-join algorithm to correctly filter indexes

- cmd/collector/app/zipkin/http_handler_test.go
- cmd/collector/app/zipkin/protov2.go
- cmd/collector/app/zipkin/protov2_test.go
- model/ids.go
- model/ids_test.go
- model/span_test.go
- Related to https://github.com/jaegertracing/jaeger/pull/1695#discussion_r314391550 (from previously merged PR)
- Improve `model/ids.go` to parse `[]byte` into SpanID/TraceID
- Use `model/ids.go` in `zipkin/protov2.go`
> Refactor zipkin/protov2.go

- Gopkg.lock
- cmd/query/app/grpc_handler_test.go
- cmd/query/app/server.go
- cmd/query/app/server_test.go
Resolves #1754
Includes the main commit by @32leaves from #1756
> Fix gRPC over cmux and add unit tests

- plugin/storage/es/esRollover.py
Related to https://github.com/jaegertracing/jaeger/pull/1753
> Add elasticsearch version configuration to rollover script

- cmd/agent/app/reporter/flags.go
- cmd/agent/app/reporter/flags_test.go
- Fixes #1776 by setting an empty value to the tag when an env var is being used without explicit default value.
> Set an empty value when a default env var value is missing

- plugin/storage/badger/spanstore/cache.go
- plugin/storage/badger/spanstore/cache_test.go
- plugin/storage/badger/spanstore/read_write_test.go
- plugin/storage/badger/spanstore/reader.go
- plugin/storage/badger/spanstore/rw_internal_test.go
- plugin/storage/badger/spanstore/writer.go
This is work from another unfinished PR ported as standalone. Adds benchmarks for profiling purposes and removes some unnecessary duplicate processing and memory pressure from the write-path mostly. 
Improves perf slightly:
```
benchmark                                           old ns/op      new ns/op      delta
BenchmarkWrites-8                                   8365954405     7515525425     -10.17%
BenchmarkServiceTagsRangeQueryLimitIndexFetch-8     61905754       59933936       -3.19%
BenchmarkServiceIndexLimitFetch-8                   41341527       39249518       -5.06%
```
But more interesting, reduces memory pressure towards GC when writing:
```
benchmark             old allocs     new allocs     delta
BenchmarkWrites-8     49572552       36456074       -26.46%
benchmark …
```
> Small memory optimizations in badger write-path

- pkg/healthcheck/handler.go
Signed-off-by: Annanay <annanay.a@media.net>
- Code refactoring
- Healthcheck handler is now served through the `Adminserver` mux - 
https://github.com/jaegertracing/jaeger/blob/b8d21ac1093282c7769e6d3c4378780cc59f0e1d/cmd/flags/admin.go#L107-L110
> Cleanup healthcheck struct, remove server

- Gopkg.lock
- Gopkg.toml
- cmd/collector/app/zipkin/http_handler_test.go
- cmd/env/command.go
@objectiser not sure why jaeger-client was pinned to specific commit in #1282 without a new release, but it seems like everything compiles with the latest release.
- fix a few errors found by newer version of staticcheck
> Unpin jaeger-client-go and refresh dependencies

- Gopkg.toml
- internal/tracegen/config.go
- internal/tracegen/worker.go
- add 'firehose' flag for tracegen
- upgrade jaeger-client-go version to 2.18.0
Signed-off-by: jung <jung@uber.com>
- Relates to #1731 
-
> Tracegen supports generating firehose spans

- cmd/agent/app/builder.go
- pkg/es/config/.nocover
- pkg/kafka/auth/config.go
- pkg/kafka/auth/options.go
- pkg/kafka/auth/tls.go
- pkg/kafka/consumer/config.go
- pkg/kafka/producer/config.go
- Resolves #1401 
- add TLSConfig to kafka configuration and use it in the factories
- add flags to enable and configure TLS CA/Cert/Key
> Support TLS for Kafka

- plugin/storage/badger/spanstore/read_write_test.go
- plugin/storage/badger/spanstore/reader.go
- plugin/storage/badger/spanstore/rw_internal_test.go
Bug #1808 ``indexSeeksToTraceIDs`` returns keys in wrong order after parsing the TraceID, while ``durationQueries`` returned them in correct order.
Add slice sorting after TraceID parsing to ensure the order is correct. Also add read-order test for this method.
> Fix ordering of indexScanKeys after TraceID parsing, closes #1808

- .travis.yml
- cmd/agent/app/agent_fuzz.go
- cmd/collector/app/zipkin/json_fuzz.go
- model/converter/thrift/zipkin/deserialize_fuzz.go
- scripts/travis/fuzzit.sh
Closes #1737.
Integrates with [Fuzzit](https://fuzzit.dev/) for automated fuzzing. Proposed in #1737.
Runs fuzz regression tests in CI every push and PR. Runs full length fuzzing on Fuzzit every push. Uses genetic fuzzer [go-fuzz](https://github.com/dvyukov/go-fuzz).
Fuzzing targets are:
* Zipkin deserialization.
* JSON deserialization.
* HTTP requests to an agent.
There's a successful test build here:
https://travis-ci.org/bookmoons/jaeger/builds/583020533
The PR build will fail due to missing an API key. If you'd like to [sign in](https://fuzzit.dev/) to create an account I can add you to the jaeger org. Then setup is like this:
* In Fuzzit settings grab an API key.
* In repo settings in [Travis](https://travis-ci.org/) paste it to envvar `FUZZIT_API_KEY`.
> Automated fuzzing

- plugin/storage/es/spanstore/reader.go
- plugin/storage/es/spanstore/reader_test.go
- The actual ES code uses background context on search methods, this prevent some features to work properly (in this case I detected that token propagation does not work correctly).
- Now it uses the context from which is called.
> Use correct context on ES search methods

- plugin/storage/badger/README.md
- Describe how the current data modeling is designed in the badger implementation. 
@objectiser
> Add documentation how the current badger storage is modeled

- Gopkg.lock
- Gopkg.toml
Updates gopkg.in/yaml.v2 dependency to be greater or equal to v2.2.4.
> Update gopkg.in/yaml.v2 dependency to v2.2.4

- CHANGELOG.md
- cmd/ingester/app/flags.go
- Resolves #1867 by changing the default value for the flag `ingester.deadlockInterval` to `0`
> Changed the default value for the flag 'ingester.deadlockInterval'

- scripts/travis/build-docker-images.sh
Fixes failing builds on the master branch:
https://travis-ci.org/jaegertracing/jaeger/jobs/599917635#L780
https://travis-ci.org/jaegertracing/jaeger/jobs/598603785#L780
@everett980 could you please review? I am not sure why UI repo is using node 8 https://github.com/jaegertracing/jaeger-ui/blob/master/.travis.yml#L3
> Use node 10 when building docker images

- crossdock/jaeger-docker-compose.yml
This has been discussed during bi-weekly call. The motivation is to get more reliable and faster xdock tests.  
> Use Elasticsearch 6 in xdock

- .travis.yml
- Makefile
- cmd/flags/flags.go
- plugin/storage/memory/memory.go
this little dependency pulls all storage implementations into custom builds, not worth it.
The Go bump is needed as staticcheck is failing on 1.12
> Decouple storage dependencies and bump Go to 1.13.x

- .travis.yml
- scripts/travis/build-docker-images.sh
- scripts/travis/upload-all-docker-images.sh
As described in #1906, the release process failed to build Windows binaries.
This change makes sure that the build process is executed as part of the CI for all PRs, to allows catching these problems sooner.
This will increase the length of CI because the process needs to build the UI, which takes long time (to be addressed in #1908).
> Build platform binaries as part of CI

- CONTRIBUTING.md
- RELEASE.md
Follow up on https://github.com/jaegertracing/jaeger/issues/1877#issuecomment-550019380
> Guideline for release milestones and merging PRs

- pkg/es/config/config.go
We use a custom `net/http` Transport for talking to Elastic Search that doesn't currently support `HTTP{,S}_PROXY` environment variables, but Elastic Search might be only accessible via a Proxy for some corporate enterprise reasons or because you're using something like Envoy as a proxy for egress for service discovery.
> Use proxy env vars if they're configured

- cmd/all-in-one/main.go
- cmd/query/main.go
- Resolves #747
- invoke FromEnv on the tracer configuration object before creating a tracer so that default configuration can be overwritten via environment variables.
Tested with all-in-one by running it on different port, re-pointing the tracer to the new port, and validating messages via tcpdump:
```
JAEGER_AGENT_PORT=7701 go run -tags=ui ./cmd/all-in-one \
--processor.jaeger-binary.server-host-port :7700 \
--processor.jaeger-compact.server-host-port :7701 \
--processor.zipkin-compact.server-host-port :7702 \
--http-server.host-port :7703
sudo tcpdump -i any -Z root "udp port 7701" -w out.cap
```
> Allow tracer config via env vars

- .gitignore
- Makefile
- pkg/es/config/config.go
- plugin/storage/es/esCleaner.py
- plugin/storage/es/esRollover.py
- scripts/travis/es-integration-test.sh
Related to https://github.com/jaegertracing/jaeger-operator/issues/471#issuecomment-552842278
> Support insecure TLS and only CA cert in Elasticsearch scripts

- pkg/discovery/grpcresolver/grpc_resolver.go
Fixes a typo in the license comments URL in one file.
Signed-off-by: Steve Winslow <swinslow@gmail.com>
> Fix typo in license URL

- model/span.go
- model/span_test.go
- storage/spanstore/interface.go
Signed-off-by: Jun Guo <guo0693@gmail.com>
- Relates to #1921
Per https://github.com/jaegertracing/jaeger/pull/1924#pullrequestreview-318041879, I am going to open a few small PRs to replace https://github.com/jaegertracing/jaeger/pull/1924
- Add new input/output type for get operatoins
- Add util function to read span kind tag
> #1921 1. Add new input/output type for get operations & util function to read span kind tag

- plugin/storage/es/Dockerfile.rollover
- plugin/storage/es/esRollover.py
Switch to pathlib2, which is an actively maintained version.
Pathlib is a very old python lib, which has a more actively maintained backward compatible version called pathlib2.
Install pathlib2 within the rollover Dockerfile, and update the import in the rollover script.
Has been tested locally by running the rollover init command.
> Update python pathlib to pathlib2

- CHANGELOG.md
- plugin/storage/cassandra/schema/migration/V002toV003.sh
- continue migration if number of rows changed during migration
- improve the sample command and remove unused TTL since it will be
copied from old table
Signed-off-by: Jun Guo <guo0693@gmail.com>
- Relates to #1921 
- continue migration if number of rows changed during migration since indexer will keep adding new rows which cause the actual ported rows > original number of rows at the beginning
- improve the sample command and remove unused TTL since it will be
copied from old table
> Improve migration script

- .travis.yml
Resolves #1952. We used to publish snapshots on all commits to master, but now seem to only publish on tags, likely after https://github.com/jaegertracing/jaeger/pull/1909/files#diff-aeee4566b9eb012ce98bd3578f7740a3L26.
There is a call to `./scripts/travis/upload-all-docker-images.sh` from `before_deploy`, but `deploy` is configured to only run on a tag, so `before_deploy` is probably also skipped on master. Moving this step back into `script`.
> Deploy to Docker from master even without a tag

- plugin/storage/cassandra/spanstore/operation_names.go
Signed-off-by: Jun Guo <guo0693@gmail.com>
- If we materialize the operation_names schema more than once, the original query template will be changed to something like 
`INSERT INTO operation_names_v2(service_name, span_kind, operation_name) VALUES (?, ?, ?)%!!(string=operation_names_v2)(EXTRA string=operation_names_v2)`
- Do not use pointer for schemas map. Always materialize the copied struct for the storage use
> Fix the bug that operation_name table can not be init more than once

- plugin/storage/grpc/config/config.go
- plugin/storage/grpc/factory_test.go
- plugin/storage/grpc/options.go
- plugin/storage/grpc/options_test.go
- Resolves [#1529](https://github.com/jaegertracing/jaeger/issues/1529)
- Add flag grpc-storage-plugin.log-level to set the level of the grpc plugin logger
> Add grpc log level

- plugin/storage/es/Dockerfile
- plugin/storage/es/Dockerfile.rollover
> Update python urllib3 version required by curator

- plugin/storage/es/esRollover.py
Resolves https://github.com/jaegertracing/jaeger-operator/issues/757
> Make rollover init step idempotent

- cmd/collector/app/http_handler.go
- cmd/collector/app/http_handler_test.go
Resolves #1967 where it is not possible to add new endpoints that call the same "SaveSpan" function. This is required for differentiating authenticated "external" endpoints from "internal" endpoints that do not require (and cannot provide) authentication.
Export the `saveSpan` function in `cmd/collector/app/http_handler.go` to `SaveSpan` which allows for embedding the `APIHandler` into a struct for extending.
> Export SaveSpan to enable multiplexing (#1967)

- CHANGELOG.md
- plugin/storage/es/esRollover.py
Change default rollover conditions from 7 days to 2 days.
Given that by default Jaeger uses daily indices and some organizations do not keep data longer than 7 days the default of 7 days seems unreasonable - it might result in a too big index and running curator would immediatelly remove the old index.
We should be more careful and change the default to 2 days - double the default daily indices. Is anybody from @jaegertracing/elasticsearch running rollover? Can anybody share the experience with this?
> Change default rollover conditions to 2 days

- cmd/agent/app/reporter/flags.go
- cmd/all-in-one/main.go
- cmd/collector/main.go
Deprecating tchannel so can be removed from future release.
Added deprecation notice to agent flag and collector/all-in-one handler.
> Deprecate tchannel

- .devbots/needs-triage.yml
- .github/stale.yml
- Adds the bots discussed during today's bi-weekly meeting
- Adds the configuration to both the stale bot and the "needs-triage" dev bot
> Added configuration for stale bot and needs-triage

- cmd/agent/app/reporter/tchannel/flags.go
Address comment https://github.com/jaegertracing/jaeger/pull/1975#issuecomment-566009815
> Deprecate tchannel reporter flags

- CHANGELOG.md
> Preparing release 1.16.0

- pkg/queue/bounded_queue.go
- pkg/queue/bounded_queue_test.go
- This PR is a prerequisite for #943
- This adds a new `Resize(int)` method to the `BoundedQueue`
> Added 'resize' operation to BoundedQueue

- pkg/queue/bounded_queue_test.go
- Fixes #1997
- Relaxed the expectations around consumed/dropped items when the queue is being drained. There might be cases where a few more items exist in the combined queues than the desired capacity, but this situation is more desirable than ensuring consistency at the cost of performance.
> Relaxed the requirements for the test TestResizeOldQueueIsDrained

- cmd/collector/app/span_processor_test.go
- pkg/queue/bounded_queue.go
- pkg/queue/bounded_queue_test.go
- Some comments were left on #1949 after it got merged. This PR addresses some of the comments, and backports the remaining changes from #1985.
- Changed existing tests to always set a queue size
- Use uber-go/atomic for non-pointer types
- Other smaller items based on the review comments from #1949
> Follow-up on review comments for the bounded queue

- Gopkg.lock
- cmd/agent/app/configmanager/grpc/manager_test.go
- cmd/agent/app/reporter/grpc/reporter_test.go
- pkg/discovery/grpcresolver/grpc_resolver.go
- pkg/discovery/grpcresolver/grpc_resolver_test.go
- gRPC deprecated some structs, causing CI breaks on other PRs (e.g. #2005 )
- `dep ensure --update`
- use recommended structs
> Upgrade dependencies `dep ensure --update`

- .travis.yml
- Makefile
- plugin/storage/badger/stats_linux.go
- scripts/cover.sh
- scripts/travis/package-deploy.sh
Signed-off-by: Prasanna Kelkar <Prasanna.Kelkar@ibm.com>
-  PR not intended to resolve specific issue but As Travis CI [officially supports](https://blog.travis-ci.com/2019-11-12-multi-cpu-architecture-ibm-power-ibm-z) s390x builds, adding support for same.
- Added s390x specific changes to skip usage of `RACE` flag as it is not supported on s390x architecture.
- Added type casting in `plugin/storage/badger/stats_linux.go` file to resolve `mismatched types int64 and uint32` issue on s390x platform.
> Build binaries for Linux on IBM Z / s390x architecture

- .gitignore
- Makefile
- cmd/tracegen/Dockerfile
- cmd/tracegen/main.go
- scripts/travis/upload-all-docker-images.sh
- I'm currently building an autoscaler for Jaeger in the Jaeger Operator. To test that, I could make use of a pod with the tracegen, and the first step is to get a container image built and published somewhere, addressed by this PR.
- Added a build step for the trace gen, as well as a Dockerfile
- Changed the docker targets (build/push) to add tracegen
- Allows the tracegen utility to be configured from env
> Publish tracegen

- cmd/agent/app/builder.go
- cmd/agent/app/builder_test.go
- cmd/agent/app/flags.go
Currently flags like `--processor.jaeger-binary.server-host-port 5001` result in a failure. I think we can be more flexible since in most cases the host is not required, just the port.
> Allow raw port numbers for UDP servers

- cmd/agent/app/reporter/client_metrics.go
- cmd/agent/app/reporter/client_metrics_test.go
In #2010, the counters are always incremented by the delta from current client stats and the previously recorded values. However, when previous values are zero, as could be the case when the client has been running for a while but agent was just restarted, the delta could be very large and not reflective of the incremental change since the previous batch (which the agent did not see), causing massive spikes in metrics and messing up the totals.
- Stats from the first batch are captured, but not applied as deltas to the counters.
> [agent] Do not increment data loss counters on the first client batch

- cmd/agent/app/reporter/client_metrics.go
- cmd/agent/app/reporter/client_metrics_test.go
- The data loss metrics introduced in #2010 cannot be compared with the existing `batches.submitted` metrics unless all connected clients are emitting the new stats.
- Emit a separate `client_stats.batches_received` counter that only counts batches from "conforming" clients (those that provide clientUUID and batchSeqNo). Then the difference between `client_stats.batches_sent` and `client_stats.batches_received` counters reflects the data loss due to UDP packet loss.
> Count received batches from conforming clients

- cmd/collector/app/builder/builder_flags.go
- cmd/collector/app/builder/span_handler_builder.go
- cmd/collector/app/metrics.go
- cmd/collector/app/options.go
- cmd/collector/app/options_test.go
- cmd/collector/app/span_processor.go
- cmd/collector/app/span_processor_test.go
- Closes #943
* Introduces the new flags: `collector.dyn-queue-size-warmup` and `collector.dyn-queue-size-memory`.
* When the warm-up flag is set, the span processor starts a new background process to recalculate the queue capacity at regular intervals.
* The span processor now keeps track of the number of spans it has seen, as well as the total bytes it processed. That information allows to derive the average spans size that the collector has processed. Along with the memory to allocate, we can come up with the ideal queue size.
* New metrics: `jaeger_collector_queue_capacity` and `jaeger_collector_spans_bytes`.
This commit shouldn't cause performance degradation for instances not using the new options, except for a small memory overhead due to the new span tracker (quantity/size) and …
> Added support for dynamic queue sizes

- CODEOWNERS
- Use group membership to determine CODEOWNERS instead of explicitly managing users
- This would allow us to use Github's code review [auto-assignment](https://help.github.com/en/github/setting-up-and-managing-organizations-and-teams/managing-code-review-assignment-for-your-team).
> Update codeowners to jaeger-maintainers team

- Gopkg.lock
- Gopkg.toml
- cmd/agent/app/reporter/grpc/flags.go
- cmd/collector/app/builder/builder_flags.go
- pkg/cassandra/config/config.go
- pkg/config/tlscfg/flags.go
- pkg/config/tlscfg/flags_test.go
- pkg/config/tlscfg/options.go
- pkg/es/config/config.go
- pkg/kafka/auth/config.go
- pkg/kafka/auth/options.go
- pkg/kafka/auth/tls.go
- plugin/storage/cassandra/options.go
- plugin/storage/cassandra/options_test.go
- plugin/storage/es/options.go
- plugin/storage/es/options_test.go
Signed-off-by: Jonah Back <jonah@jonahback.com>
Closes #1837 
-  Makes TLS configuration standard across various storage systems
- Moves TLS configurations into the tls package
- Refactors cassandra/kafka/elasticsearch backends to use the common configuration
> Add common TLS configuration

- cmd/collector/app/span_processor.go
- #2041
- Removed the warn log message. In a previous iteration of the PR that incorporated that change, the queue size in memory had to be set together with the warmup, which isn't the case anymore. The warmup assumes a default value, meaning that it might always be set, requiring only the queue-size-memory to be set to activate the feature.
> Supress the warn on queue-size-memory not being set

- pkg/queue/bounded_queue.go
Fixes #2042 
Adding to size before we put an item in the channel prevents `q.size.Sub(1)` hitting before the addition.  This prevents the uint from underflowing to max value.
This change fixed the issue described in #2042 in our environment.
cc @gouthamve
> Add before you push to the queue to prevent race condition on size

- pkg/kafka/producer/config.go
- plugin/storage/kafka/options.go
- plugin/storage/kafka/options_test.go
Resolves #2037
The default Samara Kafka client writes to Kafka broker for every single span received.
This is not efficient and caused high CPU utilization on the brokers as well as high network traffic.
Samara Kafka client has options to enable batching.  These options needed to be exposed
to the command for performance tuning. The option names matches official Kafka documentation and
not specific to Samara.
Signed-off-by: albert chung <alchung@us.ibm.com>
- See #2037
- Added 2 new command line parameters for Kafka producer
> Add CLI flags for Kafka batching params

- model/adjuster/clockskew.go
- model/adjuster/clockskew_test.go
Time adjustment is confusing to many people, as you can see in #961.
This change adds a warning if we do any time adjustments, so that it's at least clear that adjustments happened.
> Warn about time adjustment in tags

- cmd/collector/app/span_processor.go
- cmd/collector/app/span_processor_test.go
- One more place was using the warmup flag to activate the dynamic queue size. This PR changes that to use the `dynQueueSizeMemory` value instead, as it's the only one explicitly set by users.
> Use memory size flag to activate dyn queue size feature

- Makefile
Fixes #2063
Signed-off-by: Pablo Caderno <kaderno@gmail.com>
- Fixes #2063
- Added -trimpath option to go build commands
> Added -trimpath option to go build

- cmd/env/command.go
To address user questions like:
> Hi , I am exploring Jaeger with Kafka as an intermediate storage. I am unable to understand that why do we have Kafka producer as config for Jaeger query component. I believe that Jaeger query would always query the data from either Elastic or Cassandra? Can someone pls clarify? Thanks
> Clarify that "kafka" is not a real storage backend

- Gopkg.lock
- Gopkg.toml
* Pin grpc to <1.27 (as a companion to #2018), to protect against breaking changes (https://github.com/grpc/grpc-go/pull/3309) to the `balancer` pkg which is considered "experimental"
* Run `dep ensure --update`
NB: I am checking when our internal monorepo is going to upgrade grpc version so that we can remove the pin.
> Update dependencies, pin grpc<1.27

- Gopkg.lock
- Gopkg.toml
> Remove pkg/errors from dependencies

- cmd/tracegen/main.go
- internal/tracegen/config.go
Signed-off-by: Kevin Earls <kearls@redhat.com>
- This PR adds a command line option to tracegen for service name.  This will help support some more complex test scenarios.
- "-service" has been added as a command line flag
> Add service as a command line option

- cmd/collector/app/collector.go
- cmd/collector/app/handler/grpc_handler_test.go
- cmd/collector/app/handler/thrift_span_handler_test.go
- cmd/collector/app/processor/span.go
- cmd/collector/app/server/test.go
- cmd/collector/app/span_handler_builder.go
- cmd/collector/app/span_handler_builder_test.go
- cmd/collector/app/span_processor.go
- cmd/collector/app/span_processor_test.go
- The Collector parts of #2031 
- See https://github.com/jaegertracing/jaeger/pull/2031#pullrequestreview-359966317 for context
Resolves #295
> Improved graceful shutdown - Collector

- cmd/agent/app/reporter/client_metrics_test.go
- plugin/storage/cassandra/schema/docker.sh
- plugin/storage/cassandra/spanstore/writer.go
- plugin/storage/cassandra/spanstore/writer_test.go
- scripts/travis/cassandra-integration-test.sh
The transitive dep graphs view uses service & operation index to populate the dropdown. However, when traces are stored in the firehose mode, they are excluded from indexing (to reduce the load on storage), including the service/operation tables, which are actually very inexpensive to write because writes only happen once per 12hr period due to a cache in front of them.
Allow service/operation tables to be written even in firehose mode.
> Do not skip service/operation indexing for firehose spans + a couple fixes

- cmd/collector/app/collector.go
- cmd/collector/main.go
- Fixes #2094 
- Previously, the span writer was being closed twice when the all-in-one was being used: once from the all-in-one main, and one from the collector's `#Close`. This PR makes the party that creates the span writer responsible for closing it.
> Close the span writer on main

- cmd/agent/app/reporter/grpc/builder_test.go
- cmd/collector/Dockerfile
> Remove tchannel port from dockerfile and test

- cmd/all-in-one/main.go
- cmd/query/app/flags.go
- cmd/query/app/flags_test.go
- cmd/query/app/querysvc/adjusters.go
- cmd/query/app/querysvc/query_service.go
- cmd/query/app/util.go
- cmd/query/main.go
- model/adjuster/clockskew.go
- model/adjuster/clockskew_test.go
- Fixes #2053 
- Added duration parameter `query.max-clock-skew-adjust`
- Wiring to pass into adjusters.ClockSkew()
- Tests to confirm functionality
Note that I consolidated the creation of `QueryServiceOptions` in the `cmd/query/app` package.  I don't necessarily think this is a great place for it, but I struggled to find a better one.  If you have recommendations please let me know.
> Clock skew config

- cmd/query/app/grpc_handler.go
- cmd/query/app/grpc_handler_test.go
- go.mod
- When using HTTP query API, we get a clear 404 when trace is not found. But gRPC API always returns Unknown gRPC code.
- Return appropriate gRPC errors and codes.
> Return appropriate gRPC errors/codes to indicate request status

- go.mod
- go.sum
I'm looking into using Jaeger together with Amazon Managed Apache Cassandra Service (MCS) and the first issue I found is not recent enough gocql https://github.com/gocql/gocql/issues/1389#issuecomment-597200469
This bumps gocql to the latest master, which includes https://github.com/gocql/gocql/commit/cd4b606dd2fb8920e814a86b2901d062daf388a8
> Update gocql to support AWS MCS

- cmd/opentelemetry-collector/app/defaults/defaults.go
- cmd/opentelemetry-collector/app/defaults/defaults_test.go
- cmd/opentelemetry-collector/app/exporter/elasticsearch/config.go
- cmd/opentelemetry-collector/app/exporter/elasticsearch/config_test.go
- cmd/opentelemetry-collector/app/exporter/elasticsearch/doc.go
- cmd/opentelemetry-collector/app/exporter/elasticsearch/exporter.go
- cmd/opentelemetry-collector/app/exporter/elasticsearch/factory.go
- cmd/opentelemetry-collector/app/exporter/elasticsearch/factory_test.go
- cmd/opentelemetry-collector/app/exporter/elasticsearch/testdata/config.yaml
- cmd/opentelemetry-collector/app/exporter/elasticsearch/testdata/jaeger-config.yaml
- cmd/opentelemetry-collector/go.sum
- cmd/opentelemetry-collector/main.go
- pkg/es/config/config.go
- plugin/storage/es/factory.go
- plugin/storage/es/factory_test.go
- plugin/storage/es/options.go
https://github.com/jaegertracing/jaeger/pull/2139 should go in first and this should reuse storage factory helper.
> Add Elasticsearch OTEL exporter

- Makefile
- cmd/opentelemetry-collector/Dockerfile
- scripts/travis/upload-all-docker-images.sh
- scripts/travis/upload-to-docker.sh
The container name for OTEL collector is `jaegertracing/jaeger-opentelemetry-collector`.
> Add Dockerfile for OTEL collector and publish latest tag

- cmd/agent/app/reporter/client_metrics_test.go
Resolves #2108
Supersedes #2168
> Fix flaky client metrics test

- cmd/opentelemetry-collector/app/defaults/default_config.go
- cmd/opentelemetry-collector/app/defaults/default_config_test.go
- cmd/opentelemetry-collector/app/defaults/defaults.go
- cmd/opentelemetry-collector/app/exporter/cassandra/factory.go
- cmd/opentelemetry-collector/app/exporter/elasticsearch/factory.go
- cmd/opentelemetry-collector/app/exporter/kafka/factory.go
- cmd/opentelemetry-collector/main.go
Add Zipkin receiver to OTEL collector.
The Zipkin receiver is disabled by default and it can be enabled by flags:
```
--collector.zipkin.host-port string          The host:port (e.g. 127.0.0.1:5555 or :5555) of the collector's Zipkin server (default ":0")
--collector.zipkin.http-port int             (deprecated, will be removed after 2020-06-30 or in release v1.20.0, whichever is later) see --collector.zipkin.host-port
```
Other notable changes:
* All collector flags are added to OTEL collector. Most of them are be noop exept zipkin. We could support other flags (grpc endpoint, HTTP endpoint) also but it will require changes in OTEL jaeger receiver.
```
--collector.grpc-port int                    (deprecated, will be removed after 2020-06-30 or in release v1.20.0, whichever is later) see …
```
> Add zipkin receiver to OTEL collector

- crossdock/docker-compose.yml
> Remove agent's hostPort env var from go service in xdock

- plugin/sampling/strategystore/static/constants.go
- plugin/sampling/strategystore/static/options.go
- plugin/sampling/strategystore/static/strategy_store.go
- plugin/sampling/strategystore/static/strategy_store_test.go
PR for #2186 
Signed-off-by: defool <defool@foxmail.com>
- Add CLI option to refresh sampling strategies file.
- Add --strategies-reload-interval option for updating strategies periodically.
> [feat] Support periodic refresh of sampling strategies

- plugin/sampling/strategystore/static/strategy_store.go
- plugin/sampling/strategystore/static/strategy_store_test.go
Address remaining comments from #2188
> [refactor] Clean-up tests from #2188

- cmd/opentelemetry-collector/app/defaults/defaults.go
- cmd/opentelemetry-collector/app/receiver/jaegerreceiver/jaeger_receiver.go
- cmd/opentelemetry-collector/app/receiver/jaegerreceiver/jaeger_receiver_test.go
- cmd/opentelemetry-collector/app/receiver/jaegerreceiver/testdata/config.yaml
- cmd/opentelemetry-collector/go.mod
- cmd/opentelemetry-collector/go.sum
- cmd/opentelemetry-collector/main.go
- plugin/sampling/strategystore/static/options.go
Resolves #2154 
This patch showcases how upstream OTEL components can be extended to support additional means of configuration. In this case I have added `sampling.strategies-file` flag to Jaeger receiver. The configuration in OTEL config has higher precedence over the configuration in Viper (like we do for other jaeger flags).
* if the flag `sampling.strategies-file` is used and the sampling strategies in the OTEL config is missing it would enable it. e.g.: 
```
go run main.go --config=/home/ploffay/tmp/otel-config.yml  --sampling.strategies-file=/home/ploffay/tmp/sampling.json
receivers:
jaeger:
protocols:
grpc:  
```
Now let's talk about how this approach could work for other flags. Flags that don't have a default value can be supported easily. However flags with a default value e.g. …
> Support samling startegies file flag in OTEL collector

- cmd/opentelemetry-collector/app/defaults/default_config.go
- cmd/opentelemetry-collector/app/defaults/default_config_test.go
- cmd/opentelemetry-collector/app/defaults/defaults_test.go
- cmd/opentelemetry-collector/app/exporter/cassandra/exporter.go
- cmd/opentelemetry-collector/app/exporter/cassandra/factory.go
- cmd/opentelemetry-collector/app/exporter/cassandra/factory_test.go
- cmd/opentelemetry-collector/app/exporter/elasticsearch/exporter.go
- cmd/opentelemetry-collector/app/exporter/elasticsearch/factory.go
- cmd/opentelemetry-collector/app/exporter/elasticsearch/factory_test.go
- cmd/opentelemetry-collector/app/exporter/kafka/exporter.go
- cmd/opentelemetry-collector/app/exporter/kafka/factory.go
- cmd/opentelemetry-collector/app/exporter/kafka/factory_test.go
- cmd/opentelemetry-collector/app/exporter/span_writer_exporter.go
- cmd/opentelemetry-collector/app/exporter/span_writer_exporter_test.go
- cmd/opentelemetry-collector/app/receiver/jaegerreceiver/jaeger_receiver.go
- cmd/opentelemetry-collector/app/receiver/jaegerreceiver/jaeger_receiver_test.go
- cmd/opentelemetry-collector/go.mod
- cmd/opentelemetry-collector/go.sum
- crossdock/docker-compose.yml
- crossdock/otel-agent-config.yml
~Currently blocked by https://github.com/open-telemetry/opentelemetry-collector/issues/872 as we need a new translator from `pdata.Traces` to Jaeger data model.~
> Update OTEL exporters to use new API

- plugin/storage/cassandra/schema/v001.cql.tmpl
- plugin/storage/cassandra/schema/v002.cql.tmpl
- plugin/storage/cassandra/schema/v003.cql.tmpl
- plugin/storage/cassandra/spanstore/dbmodel/model.go
Add comments that `bigint` fields for timestamps and durations are in microseconds.
> Document timestamp/duration precision in Cassandra schema

- cmd/agent/app/reporter/flags.go
- cmd/opentelemetry-collector/app/defaults/default_config.go
- cmd/opentelemetry-collector/app/defaults/default_config_test.go
- cmd/opentelemetry-collector/app/defaults/defaults.go
- cmd/opentelemetry-collector/app/defaults/defaults_test.go
- cmd/opentelemetry-collector/app/processor/resourceprocessor/resource_processor.go
- cmd/opentelemetry-collector/app/processor/resourceprocessor/resource_processor_test.go
- cmd/opentelemetry-collector/app/processor/resourceprocessor/testdata/config.yaml
- cmd/opentelemetry-collector/app/receiver/jaegerreceiver/jaeger_receiver_test.go
- cmd/opentelemetry-collector/cmd/agent/main.go
- cmd/opentelemetry-collector/cmd/collector/main.go
- cmd/opentelemetry-collector/go.mod
- cmd/opentelemetry-collector/go.sum
Resolves #2161
This PR makes configurable collector/agent tags via env variables(or any viper manged config).
Changes:
* process tags are injected via resource processor https://github.com/open-telemetry/opentelemetry-collector/tree/master/processor#resource-processor
* Agent and collector use the same flag name to configure the tags. At the moment it is `resource.tags`. This name aligns with OTEL naming conventions. 
This PR https://github.com/jaegertracing/jaeger/pull/1854#issuecomment-541753066 added `collector.tags`, `agent.tags` and deprecated `jaeger.tags`. It does not seem right to offer the same functionality via 2 different configuration properties. It creates confusion and additional (dedup) handling  in all-in-one.
> Support adding process tags in OTEL via env variable

- cmd/ingester/app/flags.go
- cmd/opentelemetry-collector/app/defaults/defaults.go
- cmd/opentelemetry-collector/app/defaults/defaults_test.go
- cmd/opentelemetry-collector/app/receiver/kafka/config.go
- cmd/opentelemetry-collector/app/receiver/kafka/config_test.go
- cmd/opentelemetry-collector/app/receiver/kafka/factory.go
- cmd/opentelemetry-collector/app/receiver/kafka/factory_test.go
- cmd/opentelemetry-collector/app/receiver/kafka/kafka_receiver.go
- cmd/opentelemetry-collector/app/receiver/kafka/testdata/config.yaml
- cmd/opentelemetry-collector/app/receiver/kafka/testdata/jaeger-config.yaml
- cmd/opentelemetry-collector/cmd/agent/main.go
- cmd/opentelemetry-collector/go.sum
- pkg/kafka/consumer/config.go
Related to https://github.com/jaegertracing/jaeger/issues/2205 
This PR adds Kafka OTEL receiver. This receiver will be used in OTEL ingester that will come in a follow-up PR.
PR for kafka exporter https://github.com/jaegertracing/jaeger/pull/2135
> Add Kafka OTEL receiver/ingester

- scripts/travis/upload-all-docker-images.sh
Signed-off-by: Ning Zhang <ning@autonomic.ai>
-  As Jaeger OTEL agent was recently introduced, its docker image is currently not uploaded to the jaegertracing docker hub, which may block the deployment of Jaeger OTEL agent.
- Given the Dockerfile of Jaeger OTEL has been made as well (https://github.com/jaegertracing/jaeger/blob/master/cmd/opentelemetry-collector/cmd/agent/Dockerfile), appending opentelemetry-agent to the exiting list of image upload should make jaeger-opentelemetry-agent available on docker hub
> Add Jaeger OTEL agent to docker image upload

- .gitignore
- Makefile
- cmd/opentelemetry-collector/app/defaults/default_config.go
- cmd/opentelemetry-collector/app/defaults/default_config_test.go
- cmd/opentelemetry-collector/app/receiver/kafka/factory.go
- cmd/opentelemetry-collector/app/util.go
- cmd/opentelemetry-collector/cmd/collector/main.go
- cmd/opentelemetry-collector/cmd/ingester/Dockerfile
- cmd/opentelemetry-collector/cmd/ingester/main.go
- scripts/travis/upload-all-docker-images.sh
- scripts/travis/upload-to-docker.sh
> Add OTEL ingester component

- cmd/opentelemetry-collector/app/util.go
- cmd/opentelemetry-collector/cmd/agent/main.go
- cmd/opentelemetry-collector/cmd/collector/main.go
- cmd/opentelemetry-collector/cmd/ingester/main.go
Explicit parsing of the flag is not needed. `GetConfigFile` is called after command run so it should be already intialized.
> Remove explicit parsing of OTEL config flag

- plugin/sampling/strategystore/static/fixtures/service_no_per_operation.json
- plugin/sampling/strategystore/static/strategy_store.go
- plugin/sampling/strategystore/static/strategy_store_test.go
Signed-off-by: defool <defool@foxmail.com>
-  Fix #2171
- Use `service`'s sampling param event though it has no per-operation strategies.
> Enable service default sampling param

- cmd/opentelemetry-collector/app/defaults/default_config_test.go
Fix for test failure during local build:
```
--- FAIL: TestDefaultCollectorConfig/cassandra,elasticsearch,grpc-plugin (0.10s)
default_config_test.go:159: 
Error Trace:	default_config_test.go:159
Error:      	Not equal: 
expected: configmodels.Pipelines{"traces":(*configmodels.Pipeline)(0xc0003312c0)}
actual  : configmodels.Pipelines{"traces":(*configmodels.Pipeline)(0xc0000c1f80)}
Diff:
--- Expected
+++ Actual
@@ -9,5 +9,5 @@
Exporters: ([]string) (len=3) {
+   (string) (len=18) "jaeger_grpc_plugin",
(string) (len=16) "jaeger_cassandra",
-   (string) (len=20) "jaeger_elasticsearch",
-   (string) (len=18) "jaeger_grpc_plugin"
+   (string) (len=20) "jaeger_elasticsearch"
}
Test:       	TestDefaultCollectorConfig/cassandra,elasticsearch,grpc-plugin …
```
> Sort exporters in default config test

- cmd/opentelemetry-collector/cmd/agent/main.go
- cmd/opentelemetry-collector/cmd/collector/main.go
- cmd/opentelemetry-collector/cmd/ingester/main.go
> Add build information to OTEL binaries

- plugin/storage/cassandra/spanstore/writer.go
- plugin/storage/cassandra/spanstore/writer_test.go
PR #2090 allowed recording of service and operations in the services/operations tables, but did not index traces by service & operation. This actually made UI even more confusing since the Operations dropdown shows a lot more operations, yet no traces can be found for them.
This change re-enables indexing of firehose traces by service and operation for real. It's a compromise, which brings 3x write amplification for each span (writes from PR #2090 are cached so don't happen often).  However, it significantly improves usability and is still much cheaper than indexing all of the span tags.
> Do not skip service/operation indexing for firehose spans

- cmd/collector/app/builder_flags.go
- cmd/opentelemetry-collector/app/defaults/defaults.go
- cmd/opentelemetry-collector/app/defaults/defaults_test.go
- cmd/opentelemetry-collector/app/flags.go
- cmd/opentelemetry-collector/app/receiver/jaegerreceiver/flags.go
- cmd/opentelemetry-collector/app/receiver/zipkinreceiver/flags.go
- cmd/opentelemetry-collector/app/receiver/zipkinreceiver/testdata/config.yaml
- cmd/opentelemetry-collector/app/receiver/zipkinreceiver/zipkin_receiver_test.go
- cmd/opentelemetry-collector/app/receiver/zipkinreceiver/zipkin_recevier.go
Related to https://github.com/jaegertracing/jaeger/pull/2241#discussion_r425272173
Zipkin receiver is configurable via Jaeger flag `collector.zipkin.host-port`, hence to follow the same approach as for Jaeger receiver we should provide a wrapper that configures the endpoint every time the receiver is used.
> Add Zipkin OTEL receiver

- cmd/opentelemetry-collector/app/receiver/kafka/flags.go
- cmd/opentelemetry-collector/cmd/ingester/main.go
> Add kafka receiver flags to ingester

- cmd/collector/app/builder_flags.go
- cmd/collector/app/builder_flags_test.go
- cmd/query/app/flags.go
- cmd/query/app/flags_test.go
- cmd/query/app/server.go
- cmd/query/app/server_test.go
- cmd/query/app/ui/placeholder/gen_assets.go
- ports/ports.go
- ports/ports_test.go
Signed-off-by: Jonas Reindl <j-reindl@live.at>
- Fixes #1447
- Normalize CLI flags to use host:port address format
- Add HostPort Flag to query app as it was left out
> Normalize CLI flags to use host:port addresses

- cmd/query/app/static_handler.go
Signed-off-by: Ruben <ruben.vargas@aluxoft.com>
-  Fixes https://github.com/jaegertracing/jaeger-operator/issues/934 (The issue was filed on jaeger-operator but I think the issue should be transferred to main jaeger project).
- The config file watcher now reacts to `CHMOD` and other events, and should only react when `CREATE` or `WRITE` events occurs. This prevents a lot of log noisy. Specially on kubernetes/openshift environments.
> Ignore chmod events on UI config watcher.

- examples/hotrod/cmd/root.go
- The log information in the previous example cannot truly show the file and line number of the printed log, which caused a certain degree of trouble for the learning of exmaple.
- Explicitly increase zap.AddCallerSkip(1), so that the logger can output the actual print log files and lines.
> Make the logger in example clearer

- CHANGELOG.md
- Makefile
- cmd/agent/Dockerfile
- cmd/all-in-one/Dockerfile
- cmd/collector/Dockerfile
- cmd/ingester/Dockerfile
- cmd/opentelemetry-collector/cmd/agent/Dockerfile
- cmd/opentelemetry-collector/cmd/collector/Dockerfile
- cmd/opentelemetry-collector/cmd/ingester/Dockerfile
- cmd/query/Dockerfile
- cmd/tracegen/Dockerfile
- examples/hotrod/Dockerfile
- scripts/travis/build-all-in-one-image.sh
- scripts/travis/es-integration-test.sh
- scripts/travis/package-deploy.sh
- Platform support for arm64.
Resolves #1656 
- This commit adds building support for binaries and a Dockerfile for all-in-one container image.
Signed-off-by: Henry Wang <Henry.Wang@arm.com>
> Add arm64 support for binaries and docker images

- cmd/opentelemetry-collector/app/defaults/default_config.go
- cmd/opentelemetry-collector/app/defaults/default_config_test.go
> Enable OTEL receiver by default

- plugin/storage/es/options.go
> Remove experimental flag from rollover

- pkg/es/config/config.go
- plugin/storage/es/options.go
- plugin/storage/es/options_test.go
Jaeger uses the default scheme set by the olivere client (which is http) when sniffing an Elasticsearch cluster without the option to change it.  This makes it impossible to use sniffing with a TLS Elasticsearch cluster.
The scheme can be set using the SetScheme client option
https://pkg.go.dev/github.com/olivere/elatic/v7\?tab\=doc\#SetScheme
This change exposes that client option as a boolean command line option: --es.sniffer-tls-enabled
Signed-off-by: nilsenj <jennynilsen@rentalcars.com>
In our use case, jaeger-collector needs to connect to Elasticsearch running in Kubernetes from outside the cluster.  By using sniffing, we can use the ingress for the initial node discovery and then send traffic directly to the elasticsearch nodes without it needing to go through the ingress.
In our …
> Expose option to enable TLS when sniffing an Elasticsearch Cluster

- .travis.yml
- Makefile
- scripts/travis/package-deploy.sh
Signed-off-by: Siddhesh Ghadi <Siddhesh.Ghadi@ibm.com>
- Resolves #2272
- Adds ppc64le support for binaries & runs unit test on ppc64le architecture on travis-ci
> Add ppc64le support

- pkg/cassandra/config/config.go
- pkg/es/config/config.go
Ensure that passwords are not accidentally written out as json.
Don't serialize the password fields as json.
> Mask passwords when written as json

- cmd/all-in-one/main.go
- cmd/opentelemetry/cmd/all-in-one/main.go
- cmd/query/app/flags.go
- cmd/query/app/server.go
- cmd/query/app/server_test.go
- cmd/query/main.go
- Add TLS for gRPC Query server
- Fixes #2248 
- Similar to collector TLS implementation. Made use of `pkg/config/tlscfg` and added new query options
~~- Add docs for `--query.grpc.tls.*` options~~ (will go in documentation repo)
> TLS support for gRPC Query server

- Makefile
Temporarily reverts https://github.com/jaegertracing/jaeger/pull/2312
PR https://github.com/jaegertracing/jaeger/pull/2311/files#diff-816674aac023894f13d8ee1ed31467a1R13 pinned Jaeger in OTEL module to 1.18.1. The pinned version (all versions) does not contain `assets.FS` for the UI, hence it's causing the build to fail. 
```
/home/travis/gopath/pkg/mod/github.com/jaegertracing/jaeger@v1.18.1/cmd/query/app/ui/actual.go:24:19: undefined: assets.FS
```
> Temporarily remove UI from OTEL all-in-one build

- Makefile
- cmd/agent/Dockerfile
- cmd/all-in-one/Dockerfile
- cmd/collector/Dockerfile
- cmd/ingester/Dockerfile
- cmd/opentelemetry/cmd/agent/Dockerfile
- cmd/opentelemetry/cmd/all-in-one/Dockerfile
- cmd/opentelemetry/cmd/collector/Dockerfile
- cmd/opentelemetry/cmd/ingester/Dockerfile
- cmd/query/Dockerfile
- cmd/tracegen/Dockerfile
- examples/hotrod/Dockerfile
- plugin/storage/es/mappings/gen_assets.go
- scripts/travis/build-all-in-one-image.sh
- first step to support #1091 
- `TARGETARCH` is the `ARG` need for `buildx` https://docs.docker.com/engine/reference/builder/#automatic-platform-args-in-the-global-scope
now could build local by
```bash
make build-ui
make build-query GOOS=linux GOARCH=arm64
make build-all-in-one GOOS=linux GOARCH=arm64
make build-query GOOS=linux GOARCH=amd64
make build-all-in-one GOOS=linux GOARCH=amd64
repo=jaegertracing/all-in-one # all change to custom repo
docker buildx build --platform=linux/amd64,linux/arm64 --push -f cmd/all-in-one/Dockerfile -t $repo:latest cmd/all-in-one
```
demo <https://hub.docker.com/r/querycap/jaegertracing-all-in-one/tags>
In travis, need to setup buildx with qemu <https://github.com/crazy-max/ghaction-docker-buildx>
> Rename ARCH to TARGETARCH for multi platform build by docker buildx

- .travis.yml
- Makefile
- cmd/opentelemetry/app/exporter/elasticsearchexporter/esclient/client.go
- cmd/opentelemetry/app/exporter/elasticsearchexporter/esclient/client_test.go
- cmd/opentelemetry/app/exporter/elasticsearchexporter/esclient/es6client.go
- cmd/opentelemetry/app/exporter/elasticsearchexporter/esclient/es6client_test.go
- cmd/opentelemetry/app/exporter/elasticsearchexporter/esclient/es7client.go
- cmd/opentelemetry/app/exporter/elasticsearchexporter/esclient/es7client_test.go
- cmd/opentelemetry/app/exporter/elasticsearchexporter/esclient/ping.go
- cmd/opentelemetry/app/exporter/elasticsearchexporter/esclient/ping_test.go
- cmd/opentelemetry/app/exporter/elasticsearchexporter/esmodeltranslator/modeltranslator.go
- cmd/opentelemetry/app/exporter/elasticsearchexporter/esmodeltranslator/modeltranslator_test.go
- cmd/opentelemetry/app/exporter/elasticsearchexporter/exporter.go
- cmd/opentelemetry/app/exporter/elasticsearchexporter/factory_test.go
- cmd/opentelemetry/app/exporter/elasticsearchexporter/integration_test.go
- cmd/opentelemetry/app/exporter/elasticsearchexporter/spanstore.go
- cmd/opentelemetry/go.mod
- cmd/opentelemetry/go.sum
- pkg/es/config/config.go
- plugin/storage/es/factory.go
- plugin/storage/es/factory_test.go
- plugin/storage/integration/badgerstore_test.go
- plugin/storage/integration/integration.go
- plugin/storage/integration/trace_compare.go
- scripts/travis/es-integration-test.sh
This PR reimplements OpenTelemetry Elasticsarch exporter. Only span exporter/writer is implemented the query still uses the current ES storage implementation.
Notable changes:
* new span writer implementation versioned in `exporter/jaegerelasticsearch`
* used ES client is https://github.com/elastic/go-elasticsearch
* OTEL data model is directly transformed to Jaeger ES model
* writer uses ES Bulk API
* batching and retries capabilities will be used as OTEL processors (batch, queued_retry)
* ES client is abstracted and specific implementation is created based on the supplied ES version or derived from ES ping API at startup. This allows us to easily add support for new ES versions
* added integration tests
Other changes to the codebase:
* storage integration test is more generic - it can …
> Add native OTEL ES exporter

- cmd/anonymizer/app/anonymizer/.nocover
- cmd/anonymizer/app/anonymizer/anonymizer.go
- cmd/anonymizer/app/writer/.nocover
- cmd/anonymizer/app/writer/writer.go
- cmd/anonymizer/main.go
The anonymizer is used to obfuscate production traces before sharing them with academics.
Moving code from Uber's internal repo. The binary does not do anything yet, it needs to be wired with a source of spans, e.g. the Uber version tails production Kafka stream until it sees N spans.
> Add trace anonymizer prorotype

- cmd/opentelemetry/app/exporter/elasticsearchexporter/esmodeltranslator/modeltranslator.go
- cmd/opentelemetry/app/exporter/elasticsearchexporter/esmodeltranslator/modeltranslator_test.go
fixes jaegertracing/jaeger-operator#1113
I'm not sure if other fields have the same issue.
> fix null pointer in jaeger-spark-dependencies

- cmd/opentelemetry/app/defaultconfig/default_config.go
- cmd/opentelemetry/app/defaultconfig/default_config_test.go
Related to https://github.com/jaegertracing/jaeger/issues/2152 and https://github.com/open-telemetry/opentelemetry-collector/issues/886
This PR enables by default `batch` and `queued_retry` OTEL processors. 
By default should be also enabled memory limiter, however it requires absolute settings which is not ideal solution for a single binary that is deployed in various environments. the memory limiter will support percentage settings in the future https://github.com/open-telemetry/opentelemetry-collector/issues/1078.
> Enable batch and queued retry processors by default

- cmd/agent/app/servers/tbuffered_server.go
- cmd/agent/app/servers/tbuffered_server_test.go
Resolves #2329.
I believe the issue was a race condition between starting the UDP server and sending the first packet to it. There's no reliable way to know when UDP server has started, which makes it difficult to test for the exact values of the metrics. Instead, the test is split into two parts:
* first part still does a real UDP send/receive, however it does it up to 1000 times with 10ms wait in between, which should be enough time to allow the server to start and receive at least one packet
* the part that tests metrics and queue overflow is moved into another test that uses a fake transport whose output we can control precisely.
> Fix flaky TestTBufferedServer test

- pkg/kafka/producer/config.go
- plugin/storage/kafka/options.go
- plugin/storage/kafka/options_test.go
Currently to control batch size when collector writes to kafka user can set `--kafka.producer.batch-max-messages` flag. This flag is used to configure kafka client library and set upper limit on the number of messages in a single batch, so the meaning of this flag is 'write up to N messages in a single batch'.
Current wording on `--kafka.producer.batch-max-messages` help text is 'Number of message to batch before sending records to Kafka.' which suggests that it's used to set minimal number of messages needed to send a batch to kafka.
For a user who wants to enforce a minimal batch size this means that there's currently no way of doing that, but at the same time there's a flag that is described as a way to do it, while actually doing something else.
This patch adds a …
> Add --kafka.producer.batch-min-messages collector flag

- model/converter/thrift/jaeger/sampling_from_domain.go
- Fixes #2356
- Removed extraneous `fmt.Println` from `sampling_from_domain`
> Jaeger agent logs "0" whenever sampling strategies are requested

- cmd/collector/app/collector.go
- cmd/collector/app/server/zipkin.go
…cit shutdown
Signed-off-by: Sreevani871 <sreevani@freshdesk.com>
- Solving https://github.com/jaegertracing/jaeger/issues/2395
- Handling explicit shutdown case to avoid collector exiting abruptly after Zipkin server close to allow shutdown process to complete.
> Fix panic in collector when Zipkin server is shutdown 

- cmd/agent/app/builder_test.go
- cmd/opentelemetry/app/exporter/elasticsearchexporter/dependencystore/dependency_store.go
- cmd/opentelemetry/app/exporter/elasticsearchexporter/dependencystore/dependency_store_test.go
- cmd/opentelemetry/app/exporter/elasticsearchexporter/esclient/client.go
- cmd/opentelemetry/app/exporter/elasticsearchexporter/esclient/client_test.go
- cmd/opentelemetry/app/exporter/elasticsearchexporter/esclient/es6client.go
- cmd/opentelemetry/app/exporter/elasticsearchexporter/esclient/es6client_test.go
- cmd/opentelemetry/app/exporter/elasticsearchexporter/esclient/es7client.go
- cmd/opentelemetry/app/exporter/elasticsearchexporter/esclient/es7client_test.go
- cmd/opentelemetry/app/exporter/elasticsearchexporter/esclient/search_body_encoder.go
- cmd/opentelemetry/app/exporter/elasticsearchexporter/esclient/search_body_encoder_test.go
- cmd/opentelemetry/app/exporter/elasticsearchexporter/esclient/utils.go
- cmd/opentelemetry/app/exporter/elasticsearchexporter/exporter.go
- cmd/opentelemetry/app/exporter/elasticsearchexporter/factory.go
- cmd/opentelemetry/app/exporter/elasticsearchexporter/integration_test.go
- cmd/opentelemetry/app/exporter/elasticsearchexporter/spanreader/index_name.go
- cmd/opentelemetry/app/exporter/elasticsearchexporter/spanreader/index_name_test.go
- cmd/opentelemetry/app/exporter/elasticsearchexporter/spanreader/query.go
- cmd/opentelemetry/app/exporter/elasticsearchexporter/spanreader/query_test.go
- cmd/opentelemetry/app/exporter/elasticsearchexporter/spanreader/span_reader.go
- cmd/opentelemetry/app/exporter/elasticsearchexporter/spanreader/span_reader_test.go
- cmd/opentelemetry/app/exporter/elasticsearchexporter/spanreader/validate_query.go
- cmd/opentelemetry/app/exporter/elasticsearchexporter/spanreader/validate_query_test.go
- cmd/opentelemetry/app/exporter/elasticsearchexporter/spanstore.go
This PR adds new Elasticsearch reader implementation that uses https://github.com/elastic/go-elasticsearch which is the client that ES OTEL exporter uses and we would like to use it for all interactions with ES. 
Notable changes:
* Uses https://github.com/elastic/go-elasticsearch client
* The client exposes low-level API and it does not expose any query/response objects.  The consumer code has to define all objects. 
* The query/response objects defined in this impl are not general-purpose and cover only use cases that our read API uses.
* This new implementation uses similar queries and logic as the current reader https://github.com/jaegertracing/jaeger/tree/master/plugin/storage/es/spanstore
> Add new Elasticsearch reader implementation

- crossdock/services/tracehandler_test.go
- pkg/normalizer/service_name.go
go vet reports 3 issues when using Go 1.15:
```
go vet ./...
crossdock/services/tracehandler_test.go:40:12: conversion from untyped int to TraceID (string) yields a string of one rune, not a string of digits (did you mean fmt.Sprint(x)?)
crossdock/services/tracehandler_test.go:252:90: conversion from untyped int to TraceID (string) yields a string of one rune, not a string of digits (did you mean fmt.Sprint(x)?)
pkg/normalizer/service_name.go:57:28: conversion from int to string yields a string of one rune, not a string of digits (did you mean fmt.Sprint(x)?)
```
Signed-off-by: Łukasz Mierzwa <l.mierzwa@gmail.com>
> Fix go vet warnings on Go 1.15

- cmd/opentelemetry/app/internal/esclient/client.go
- cmd/opentelemetry/app/internal/esclient/client_test.go
@joe-elliott could you please review?
> Check missing server URL in ES OTEL client

- pkg/multicloser/multicloser.go
- pkg/multicloser/multicloser_test.go
This was causing nil dereference as we are passing nil closer to the multicloser. 
E.g. some storage writers implement closer and sometimes not.
```
2020-08-25T16:32:03.079+0200	INFO	healthcheck/handler.go:128	Health Check state change	{"component_kind": "extension", "status": "unavailable"}
2020-08-25T16:32:03.079+0200	INFO	service/service.go:381	Stopping receivers...
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x168e5df]
goroutine 1 [running]:
github.com/jaegertracing/jaeger/pkg/multicloser.MultiCloser.Close(0xc000be1320, 0x3, 0x3, 0x394ab01, 0xc000100101)
/home/ploffay/projects/jaegertracing/jaeger/pkg/multicloser/multicloser.go:34 +0x7f
main.main() …
```
> Allow nil closer in multicloser

- cmd/opentelemetry/app/processor/resourceprocessor/resource_processor.go
- cmd/opentelemetry/app/processor/resourceprocessor/resource_processor_test.go
Fixes:
```
go run ./cmd/all-in-one/main.go --jaeger.tags=foo.val=kok                         1:22 
2020-08-25T13:22:43.651+0200	INFO	service/service.go:412	Starting Jaeger OpenTelemetry all-in-one...	{"Version": "", "GitHash": "", "NumCPU": 8}
2020-08-25T13:22:43.651+0200	INFO	service/service.go:256	Setting up own telemetry...
2020-08-25T13:22:43.651+0200	INFO	service/telemetry.go:102	Serving Prometheus metrics	{"address": "localhost:8888", "legacy_metrics": false, "new_metrics": true, "level": 3, "service.instance.id": "6fe8d94a-c107-4e26-8197-c9a2e605e694"}
2020-08-25T13:22:43.705+0200	INFO	service/service.go:293	Loading configuration...
panic: assignment to entry in nil map
goroutine 110 [running]: …
```
> Make sure tag map is always initialized

- scripts/travis/upload-to-docker.sh
- Hopefully, this is solving the failure to push images to Docker Hub.
- Added hostname to `docker login` command.
> Added host to docker login command

- cmd/opentelemetry/app/exporter/elasticsearchexporter/spanstore.go
- pkg/es/config/config.go
- plugin/storage/es/factory.go
- plugin/storage/es/factory_test.go
- plugin/storage/es/options.go
- plugin/storage/es/options_test.go
- Fixes #2295 by providing a way to specify ES tag keys directly through the CLI/config file
- Added a new parameter `es.tags-as-fields.include`.  "include" was chosen to leave space later for "exclude", but I'd be willing to change it to whatever.
- Dropped `LoadTagsFromFile` in favor of `TagKeysAsFields`.  `TagKeysAsFields` returns a slice of tags keys that combines both the new cli option and the file.
- Added appropriate tests
- Added missing `.Tags` fields to `ApplyDefaults`.  Unsure if these were left out for a reason.
> Allow configuration of ES tag keys directly through config/cli

- CHANGELOG.md
UI is bumped to commit `8279218` which includes the fixes we needed to release, but excludes all the new React refactoring, which seems to have broken the trace view (reported in https://github.com/jaegertracing/jaeger-ui/issues/628).
```
5b4ca26 - (HEAD -> master, tag: v1.10.0, upstream/master) Preparing release v1.10.0 (#627) (2 days ago) <Gary Brown>
6513b53 - Additional Test Coverage around TimelineViewingLayer (#617) (5 days ago) <Tim Klever>
60ee1fd - Add rubenvp8510 to code owners (8 days ago) <Yuri Shkuro>
0507ac8 - Add ArchiveNotifier tests (#619) (8 days ago) <Tim Klever>
6843b03 - Refactor SpanGraph.UNSAFE_componentWillReceiveProps  (#613) (9 days ago) <Tim Klever>
122a59e - Remove UNSAFE_componentWillMount lifecycle methods (#611) (12 days ago) <Tim Klever>
dac8c4a - Migrate …
```
> Prepare release 1.19.2

- pkg/config/tlscfg/cert_watcher_test.go
- Fixes #2428 
- The hypothesis on the cause of these flaky tests is that the `certWatcher` isn't detecting file changes and, hence, isn't logging these events causing the assertions to fail occasionally.
- Ensures calls to `ioutil.WriteFile` are replaced with a synchronous write to disk.
- The reason for doing this is because `ioutil.WriteFile` does not call `Sync()` nor opens the file with the `os.O_SYNC` flag and hence, potentially fails to flush write buffers to disk.
> Fix flaky tls test

- cmd/query/app/query_parser_test.go
Fixes a broken test introduced by an upgrade of go version to 1.15, caused by a [change in the time package](https://github.com/golang/go/commit/201cb046b745f8bb00e3d382290190c74ba7b7e1), specifically in [format.go:1437](https://github.com/golang/go/blob/18ea6f597c031d5f3c5160217db72d80cb62f689/src/time/format.go#L1437).
- Although the practice of asserting on error messages is debatable, the spirit of this PR is to respect the original intention of this test in making a strong assertion on the specific input value which causes the error. Further, the error message should be consistent between OSes, just not between go versions of course.
- Fixes the broken test, which does not expect a quoted value in the error message. Go 1.15 introduces a sensible change of quoting the values to more …
> Fix error equals

- cmd/opentelemetry/app/exporter/jaegerexporter/jaeger_exporter_test.go
- cmd/opentelemetry/app/receiver/jaegerreceiver/jaeger_receiver.go
- cmd/opentelemetry/app/receiver/jaegerreceiver/jaeger_receiver_test.go
The GRPC TLS settings were not applied when `--collector.grpc.host-port=`  was not provided. This was causing issues in the operator as it does not set the endpoint.
> Fix TLS flags settings in jaeger OTEL receiver

- README.md
Signed-off-by: Ihor Dvoretskyi <ihor@linux.com>
- Jaeger FOSSA scans are currently running under the CNCF organization, the updated badge URL is reflecting this.
Ref: https://github.com/jaegertracing/jaeger/issues/2432
> FOSSA badge link updated

- cmd/opentelemetry/app/exporter/badgerexporter/factory.go
- cmd/opentelemetry/app/exporter/memoryexporter/factory.go
> Fix mutex unlock in storage exporters

- cmd/opentelemetry/app/defaultconfig/default_config.go
- cmd/opentelemetry/app/defaultconfig/default_config_test.go
- cmd/opentelemetry/app/exporter/badgerexporter/config.go
- cmd/opentelemetry/app/exporter/badgerexporter/factory.go
- cmd/opentelemetry/app/exporter/badgerexporter/factory_test.go
- cmd/opentelemetry/app/exporter/cassandraexporter/config.go
- cmd/opentelemetry/app/exporter/cassandraexporter/exporter.go
- cmd/opentelemetry/app/exporter/cassandraexporter/factory.go
- cmd/opentelemetry/app/exporter/cassandraexporter/factory_test.go
- cmd/opentelemetry/app/exporter/elasticsearchexporter/config.go
- cmd/opentelemetry/app/exporter/elasticsearchexporter/exporter.go
- cmd/opentelemetry/app/exporter/elasticsearchexporter/factory.go
- cmd/opentelemetry/app/exporter/grpcpluginexporter/config.go
- cmd/opentelemetry/app/exporter/grpcpluginexporter/exporter.go
- cmd/opentelemetry/app/exporter/grpcpluginexporter/factory.go
- cmd/opentelemetry/app/exporter/grpcpluginexporter/factory_test.go
- cmd/opentelemetry/app/exporter/span_writer_exporter.go
This PR configures queue retry per exporter and removes the qretry form the default configuration. This is a prefered configuration since the global qretry would retry all exporters in the pipeline. See example ocnfig from OTEL https://github.com/open-telemetry/opentelemetry-collector/blob/master/exporter/otlpexporter/config.go#L26. 
Other notable changes:
* qretry is not defined for in-memory and kafka (we will swith to OTEL kafka impl soon)
> Use queue retry per exporter

- cmd/opentelemetry/app/exporter/elasticsearchexporter/exporter.go
- cmd/opentelemetry/app/exporter/elasticsearchexporter/integration_test.go
- cmd/opentelemetry/app/exporter/elasticsearchexporter/spanstore.go
- cmd/opentelemetry/app/exporter/elasticsearchexporter/spanstore_test.go
- cmd/opentelemetry/app/exporter/elasticsearchexporter/storagefactory.go
- cmd/opentelemetry/app/exporter/elasticsearchexporter/storagefactory_test.go
- cmd/opentelemetry/app/exporter/span_writer_exporter.go
- cmd/opentelemetry/app/exporter/span_writer_exporter_test.go
- cmd/opentelemetry/app/exporter/storagemetrics/metrics.go
- cmd/opentelemetry/app/exporter/storagemetrics/metrics_test.go
- cmd/opentelemetry/app/internal/esclient/client.go
- cmd/opentelemetry/app/telemetry.go
- cmd/opentelemetry/cmd/agent/main.go
- cmd/opentelemetry/cmd/all-in-one/main.go
- cmd/opentelemetry/cmd/collector/main.go
- cmd/opentelemetry/cmd/ingester/main.go
- cmd/opentelemetry/go.mod
- plugin/storage/integration/trace_compare.go
Resolves https://github.com/jaegertracing/jaeger/issues/2165#issuecomment-651179655
This PR adds storage metrics to OTEL distribution. The metrics show many spans were stored per service and exporter. There is a similar metric in the current jaeger distributions.
```
otelcol_spans_stored{service="jaeger-query",service_instance_id="23e9c69b-1383-4fbd-8614-638339329a8e",storage="in-memory"}
```
It is a similar metric to the core metric: 
```
otelcol_exporter_sent_spans{exporter="jaeger_memory",service_instance_id="23e9c69b-1383-4fbd-8614-638339329a8e"} 9
```
however it does not split the metric by reported service name.
> Add storage metrics to OTEL, metrics by span service name

- CHANGELOG.md
- cmd/opentelemetry/app/exporter/elasticsearchexporter/integration_test.go
- cmd/opentelemetry/app/exporter/elasticsearchexporter/storagefactory.go
- cmd/opentelemetry/app/internal/reader/es/esdependencyreader/dependency_store.go
- cmd/opentelemetry/app/internal/reader/es/esdependencyreader/dependency_store_test.go
- cmd/opentelemetry/app/internal/reader/es/esspanreader/query.go
- cmd/opentelemetry/app/internal/reader/es/esspanreader/query_test.go
- cmd/opentelemetry/app/internal/reader/es/esspanreader/span_reader.go
- pkg/es/config/config.go
- plugin/storage/es/dependencystore/storage.go
- plugin/storage/es/dependencystore/storage_test.go
- plugin/storage/es/factory.go
- plugin/storage/es/options.go
- plugin/storage/es/options_test.go
- plugin/storage/es/spanstore/reader.go
- plugin/storage/es/spanstore/reader_test.go
- plugin/storage/es/spanstore/service_operation.go
- plugin/storage/integration/elasticsearch_test.go
- Closes #2437
- Add deprecation note for `--es.max-num-spans`. (Will create another issue to decommission this flag for a future release).
- Add new flag `--es.max-doc-count`, that configures query (and aggregation) doc sizes, defaulting to `10_000`. Name based on existing `defaultDocCount` variable for consistency.
- Fix tests which were incorrectly checking for the document size at the query level. 
- Add test to assert on aggregation sizes applied.
> Configurable ES doc count

- plugin/storage/grpc/shared/grpc_client.go
- plugin/storage/grpc/shared/grpc_client_test.go
A previous attempt to fix this was made here:  https://github.com/jaegertracing/jaeger/pull/1814
Original issue: https://github.com/jaegertracing/jaeger/issues/1741
However, this is currently not working b/c on this line `ok` is set to true which skips the code that checks to see if the string equals "trace not found".
https://github.com/jaegertracing/jaeger/blob/412022065959c6a45e6250a733b081c387e9fdea/plugin/storage/grpc/shared/grpc_client.go#L80
Tracking it down:
**RecvMsg**
https://github.com/grpc/grpc-go/blob/8630cac324bf02ea0edfba758c2b2f3344af7bf7/stream.go#L749
**recvMsg**
https://github.com/grpc/grpc-go/blob/master/stream.go#L886
**toRPCErr**
https://github.com/grpc/grpc-go/blob/8630cac324bf02ea0edfba758c2b2f3344af7bf7/rpc_util.go#L775
`toRPCErr` calls `status.FromError` which …
> Propagate TraceNotFound error from grpc storage plugins

- .travis.yml
- Makefile
- plugin/storage/grpc/config/config.go
- plugin/storage/grpc/factory.go
- plugin/storage/grpc/factory_test.go
- plugin/storage/grpc/shared/interface.go
- plugin/storage/grpc/shared/plugin.go
- plugin/storage/integration/grpc_test.go
Partially address #1516 since the badger and grpc-plugin storage integration tests are not running in CI at all today.
* adds a new CI step to run grpc-plugin and badger integration tests
* minor clean-up of the plugin framework code
* reorder logic in .travis.yml to match the actual order of the matrix steps
> Enable CI for badger and grpc-plugin

- plugin/storage/badger/spanstore/read_write_test.go
- plugin/storage/badger/spanstore/reader.go
- plugin/storage/integration/integration.go
- storage/spanstore/interface.go
This is especially interesting when using go-plugin based storage, where the error has to be correctly passed through gRPC client.
The test revealed that Badger did not return NotFound when expected, so it's fixed here as well.
I added documentation to the span Reader API with expectations about not-found.
> Add integration test for ErrTraceNotFound

- plugin/storage/badger/spanstore/read_write_test.go
- plugin/storage/badger/spanstore/reader.go
> Clean-up Badger's trace-not-found check

- cmd/opentelemetry/app/exporter/elasticsearchexporter/esmodeltranslator/modeltranslator.go
- cmd/opentelemetry/app/exporter/elasticsearchexporter/esmodeltranslator/modeltranslator_test.go
- cmd/opentelemetry/app/exporter/elasticsearchexporter/exporter.go
- cmd/opentelemetry/app/exporter/elasticsearchexporter/factory.go
- cmd/opentelemetry/app/exporter/elasticsearchexporter/spanstore.go
- cmd/opentelemetry/app/exporter/elasticsearchexporter/spanstore_test.go
- cmd/opentelemetry/app/exporter/elasticsearchexporter/storagefactory.go
- cmd/opentelemetry/app/exporter/elasticsearchexporter/storagefactory_test.go
- cmd/opentelemetry/go.sum
The partial retry as the name suggests ensures that only spans that failed to be stored were retried. The returned error encapsulates `pdata.Traces` that is used by qretry on in the consecutive call to the exporter. The `pdata.Traces`  for retry is created from a struct that is created by ES model translator.
> Add partial retry capability to OTEL ES exporter.

- .travis.yml
- cmd/opentelemetry/app/exporter/elasticsearchexporter/esmodeltranslator/modeltranslator.go
- cmd/opentelemetry/app/exporter/elasticsearchexporter/esmodeltranslator/modeltranslator_test.go
> Translate OTEL instrumentation library to ES DB model

- cmd/query/app/ui/placeholder/gen_assets.go
- cmd/query/app/ui/placeholder/public/index.html
> Improve UI placeholder message

- plugin/storage/badger/spanstore/reader.go
> Fix unmarshalling in OTEL badger

- cmd/query/app/server.go
- cmd/query/app/server_test.go
- Master branch unit tests are failing on `TestServerInUseHostPort`, seemingly only for MacOS (okay for Linux builds).
- IIUC, the reason for the test is to have test coverage of error handling code when listening on GRPC and HTTP ports. To achieve this, the test first listens on those same ports, then attempts to bind to those same ports again via the QueryService `Start()`; and expecting an error to be returned.
- When running this test, no error is returned when binding to `127.0.0.1:8080` while `:8080` is bound, causing the assertion to fail. Interestingly, this behaviour differs between MacOS and Linux (at least on my Centos 8 VM).
- From this, it appears that the Linux OS libraries are stricter than MacOS; the former considering the …
> Fix failing ServerInUseHostPort test on MacOS

- .travis.yml
- Some CI jobs are flaky, working on second/third attempt. This PR adds a "travis_retry" in front of the jobs that are more likely to suffer from it.
- Added travis_retry in front of integration and crossdock tests
> Add travis_retry to some CI jobs

- cmd/opentelemetry/app/defaultconfig/default_config.go
- cmd/opentelemetry/app/defaultconfig/default_config_test.go
- cmd/opentelemetry/app/receiver/zipkinreceiver/zipkin_receiver.go
- cmd/opentelemetry/app/receiver/zipkinreceiver/zipkin_receiver_test.go
- cmd/opentelemetry/cmd/agent/main.go
- cmd/opentelemetry/cmd/all-in-one/main.go
- cmd/opentelemetry/cmd/collector/main.go
- cmd/opentelemetry/cmd/ingester/main.go
- Code refactoring
- Refactors repeated config factory code to use the same factory
- Moves zipkin host port configuration into the `zipkinreceiver CreateDefaultConfig()`. This mimics the way the jaegerreceiver works and removes the `ZipkinHostPort` field from `ComponentSettings`.
@pavolloffay I split out this refactoring from #2475 b/c I think it's valuable on its own.  Let me know what you think.
> OTel: Factored out Config Factory

- cmd/opentelemetry/app/exporter/elasticsearchexporter/esmodeltranslator/modeltranslator.go
- cmd/opentelemetry/app/exporter/elasticsearchexporter/esmodeltranslator/modeltranslator_test.go
> Fix ES OTEL status code

- SECURITY.md
Signed-off-by: lihaowei <haoweili35@gmail.com>
- One wrong word
- eiter-->either
> Chore: fix typo in security readme

- CHANGELOG.md
- cmd/query/app/flags.go
- Fixes #1459
- Changed the default value for the flag `query.max-clock-skew-adjustment` to `0s`.
> Disable clock-skew-adjustment by default.

- pkg/kafka/consumer/config.go
Fixes the following message. The description is in the code.
```
2020-09-21T09:00:55.075Z INFO service/service.go:396 Starting Jaeger OpenTelemetry Ingester... {"Version": "v1.19.2", "GitHash": "a2fb067f01551b47aef4f58bcc0e925ffeb32f5f", "NumCPU": 2}
2020-09-21T09:00:55.075Z INFO service/service.go:240 Setting up own telemetry...
2020-09-21T09:00:55.075Z INFO service/telemetry.go:107 Serving Prometheus metrics {"address": "localhost:8888", "legacy_metrics": false, "new_metrics": true, "level": 3, "service.instance.id": "6a816386-9c00-4531-90a7-819b4b0ff73e"}
2020-09-21T09:00:55.123Z INFO service/service.go:277 Loading configuration...
2020-09-21T09:00:55.138Z INFO service/service.go:288 Applying configuration...
2020-09-21T09:00:55.138Z …
```
> Fix OTEL kafka receiver/ingester panic

- cmd/opentelemetry/app/defaultcomponents/defaults_test.go
- cmd/opentelemetry/app/defaultconfig/default_config_test.go
- cmd/opentelemetry/app/defaultconfig/merge.go
- cmd/opentelemetry/app/defaultconfig/testdata/addqueuedprocessor.yaml
- Increasing coverage for #2514 
- Added the ability to test the factory returned by CreateDefaultConfig()
- Added the ability to test otelconfigs
- Refactored Merge() to remove an untested line
- Increased coverage on defaultscomponents/defaults
```
jaeger/cmd/opentelemetry/app/defaultconfig (master)$ go test -cover
PASS
coverage: 81.9% of statements
ok  	github.com/jaegertracing/jaeger/cmd/opentelemetry/app/defaultconfig	0.153s
jaeger/cmd/opentelemetry/app/defaultconfig (otel-coverage)$ go test -cover
PASS
coverage: 98.8% of statements
```
```
jaeger/cmd/opentelemetry/app/defaultcomponents (master)$ go test -cover
PASS
coverage: 84.6% of statements
jaeger/cmd/opentelemetry/app/defaultcomponents (otel-coverage)$ go test -cover
PASS
coverage: 100.0% of statements
```
> Increase coverage on otel/app/defaultconfig and otel/app/defaultcomponents

- cmd/opentelemetry/app/exporter/kafkaexporter/testdata/config.yaml
- cmd/opentelemetry/app/receiver/kafkareceiver/testdata/config.yaml
Created from https://github.com/jaegertracing/jaeger/pull/2494#discussion_r495984989
> Remove tabs from the OTEL test config files

- plugin/storage/es/options.go
- plugin/storage/es/options_test.go
- Closes #2526
- Replaces the hard-coded namespace with the provided namespaceConfig's.
- Write test to fail usage message assertions and pass after applying fixes to `options.go`.
> Fix max-num-spans flag's usage message

- README.md
The way this service works does not allow for investigation of the issues that it raises. Since most of those are just linters anyway, we'd be better off running the actual linters, e.g. #2503, #538.
> Remove Go report card

- plugin/storage/badger/spanstore/reader.go
- Reduce the amount of queries against the badger backend store if Tags are used as a query parameter. Also, if the Tags is the only query, then we also remove single merge-join phase.
- Tags' key already includes the ServiceName so it makes no sense to add the ServiceName index seek as we can filter it all in a single index seek.
> Remove unnecessary ServiceName index seek if tags query is available

- cmd/opentelemetry/go.mod
- cmd/opentelemetry/go.sum
> [otel] Update jaeger-lib to v2.4.0

- cmd/opentelemetry/app/exporter/cassandraexporter/factory.go
- cmd/opentelemetry/app/exporter/cassandraexporter/factory_test.go
- cmd/opentelemetry/app/exporter/elasticsearchexporter/factory.go
- cmd/opentelemetry/app/exporter/elasticsearchexporter/factory_test.go
While working on #2494 I discovered that the default otel config was pushing far less spans/second to my Scylla backend.  After some research it was discovered that it's b/c the default otel collector config only has 10 workers while the default jaeger collector config has 50.
This PR uses the default collector queue settings for both the cassandra and elasticsearch exporters' queue settings.  These are the two "production" exporters supported
This does bring up another concern that might make sense to discuss as part of this issue.  By default the ingester pulls from the Kafka queue and immediately pushes its spans into the configured backend, but a no-queue configuration of the otel collector does not seem possible at the moment.  The queue can technically be disabled but performance is …
> OTel Cassandra/Elasticsearch Exporter queue defaults

- README.md
Right now the README points to a deprecated repo which then redirects you the
operator project.
> README.md: Point to operator under deployment section

- CONTRIBUTING.md
Adding missing build instruction that allows jaeger binaries to be built.
> Adding missing build instruction #1887

- CONTRIBUTING.md
Following the instruction from the CONTRIBUTING.md file results in a "no such file or directory" error when trying to fetch static UI assets:
```
$ go run ./cmd/all-in-one/main.go --query.static-files jaeger-ui/packages
"Could not create static assets handler","error":"cannot load index.html: cannot open index.html: open jaeger-ui/build/index.html: no such file or directory"
```
The `Makefile` appears to copy the static UI assets into `jaeger-ui/packages/jaeger-ui/build` instead. See: https://github.com/jaegertracing/jaeger/blob/master/Makefile#L234
Changing the command to the correct path as specified in the `build-ui` `Makefile` target results in the all-in-one running successfully:
```
$ go run ./cmd/all-in-one/main.go …
```
> Update static UI assets path in contrib doc

- cmd/query/app/fixture/index.html
- cmd/query/app/static_handler.go
- cmd/query/app/static_handler_test.go
- cmd/query/app/ui/placeholder/gen_assets.go
- cmd/query/app/ui/placeholder/public/index.html
- pkg/version/build.go
Part of https://github.com/jaegertracing/jaeger-ui/issues/365
> Inject version info into index.html

- cmd/collector/app/builder_flags.go
- cmd/flags/admin.go
- cmd/query/app/flags.go
Align ports included in help messages with the jaeger default
ports specified in ports package.
Signed-off-by: Tobias Kohlbau <tobias@kohlbau.de>
- Resolves #2552 
- Aligning the ports shown in help messages with default ports defined in ports package.
> Align help message with default values

- Makefile
- cmd/collector/app/builder_flags.go
- cmd/collector/app/server/zipkin.go
- cmd/opentelemetry/app/defaultconfig/default_config.go
- cmd/opentelemetry/app/receiver/zipkinreceiver/zipkin_receiver_test.go
- ports/ports.go
- ports/ports_test.go
In the past Zipkin server would not be started if the port was not configured, but not it's always started.
* run OTEL tests as part of `test-ci` (without coverage)
* change CollectorZipkinHTTPHostPort default to ""
* add logging when Zipkin server is not started
* changed `ports.GetAddressFromCLIOptions()` to return empty string when `port=0 && hostPort=""` (previously it was returning `":"`, which didn't make sense, it's better to return default value for string when no parts of the address are specified)
With this change:
```
$ go run ./cmd/collector help | grep -i zipkin
--collector.zipkin.host-port string               The host:port (e.g. 127.0.0.1:9411 or :9411) of the collector's Zipkin server (disabled by default)
$ SPAN_STORAGE_TYPE=memory go run ./cmd/collector 2>&1 | grep -i …
```
> Disable Zipkin server if port/address is not configured

- .devbots/needs-triage.yml
- .github/labeler-needs-triage.yaml
- .github/workflows/labeler.yml
The bot that used to add the 'needs-triage' label to new issues stopped working and I can't figure out why. Looks like GitHub has a more official action that does something similar, so, this PR is replacing the 'devbots' with the issue-labeler.
See https://github.com/jaegertracing/jaeger-operator/pull/1251
> Replaced devbots with issue-labeler

- cmd/query/app/static_handler.go
- plugin/sampling/strategystore/static/options.go
- plugin/sampling/strategystore/static/strategy_store.go
- plugin/sampling/strategystore/static/strategy_store_test.go
- Resolve #2015 
- Added a URL option to support downloading a sampling strategies file from a url.
> Add URL option for sampling strategies file

- CONTRIBUTING.md
- Makefile
- Resolves #2572
- Remove `build-ui` step from CONTRIBUTING.md as it's automated by Makefile.
- Add UI asset files in `clean` target to enable rebuilding of UI assets.
- Reinstate the explanation of what `build-ui` does under the hood into the Makefile under its namesake, which was deleted in #2548.
- `build-ui` target dependency should _only_ be used for builds that use `-tags ui` (remove from `docker` and `build-all-in-one-linux` targets).
- Make `build-ui` target idempotent by explicitly checking for the UI assets files' existence. If all expected files exist, do nothing. Otherwise, regenerate UI asset files.
> Improve `build-ui` Makefile target and fix dependencies

- .travis.yml
- Makefile
- cmd/agent/Dockerfile
- cmd/all-in-one/Dockerfile
- cmd/collector/Dockerfile
- cmd/ingester/Dockerfile
- cmd/query/Dockerfile
- docker/Makefile
- docker/base/Dockerfile
- docker/debug/Dockerfile
- scripts/travis/build-all-in-one-image.sh
- scripts/travis/upload-all-docker-images.sh
Tackles https://github.com/jaegertracing/jaeger/issues/2493
As part of this PR, we are creating separate images for jaeger backend components.
> Create debug docker images for jaeger backends

- cmd/opentelemetry/app/exporter/badgerexporter/doc.go
- cmd/opentelemetry/app/exporter/kafkaexporter/flags.go
- cmd/opentelemetry/app/exporter/kafkaexporter/kafka_exporter.go
- cmd/opentelemetry/app/exporter/kafkaexporter/kafka_exporter_test.go
- cmd/opentelemetry/app/receiver/kafkareceiver/flags.go
- cmd/opentelemetry/app/receiver/kafkareceiver/kafka_receiver.go
- cmd/opentelemetry/app/receiver/kafkareceiver/kafka_receiver_test.go
> Support more encodings for Kafka in OTel Ingester

- cmd/agent/app/servers/tbuffered_server.go
TBufferedServer.Close() may close the data channel before
Serve detects it. Move chan close() to Serve to prevent
a panic caused by sending on a closed channel.
See also https://github.com/golang/go/issues/27769#issuecomment-423045727
=== RUN   TestTBufferedServer_SendReceive
==================
WARNING: DATA RACE
Write at 0x00c000074850 by goroutine 9:
runtime.closechan()
/home/travis/.gimme/versions/go1.15.2.linux.amd64/src/runtime/chan.go:352 +0x0
github.com/jaegertracing/jaeger/cmd/agent/app/servers.(*TBufferedServer).Stop()
...
Previous read at 0x00c000074850 by goroutine 10:
runtime.chansend()
/home/travis/.gimme/versions/go1.15.2.linux.amd64/src/runtime/chan.go:158 +0x0
github.com/jaegertracing/jaeger/cmd/agent/app/servers.(*TBufferedServer).Serve() …
> TBufferedServer: Avoid channel close/send race on Stop

- pkg/config/tlscfg/cert_watcher.go
- pkg/config/tlscfg/cert_watcher_test.go
There are a few file descriptor leaks in the unit tests, and on an error
condition in certwatcher.
This is an issue when checking for flaky tests with
`go test -test.count ..`. One leak is in an error condition in
certwatcher but it is unlikely to be a runtime issue because it happens
on initialization.
Related #2586
> Fix file descriptor leaks in tlscfg unit tests

- cmd/collector/app/zipkin/jsonv2.go
- cmd/collector/app/zipkin/jsonv2_test.go
Resolves #2595
For spans w/ span kind == "internal" and remoteEndpoint != nil, `spanV2ToThrift` would add a tag with empty name. This PR fixes the issue.
> fix: don't create tags w/ empty name for internal zipkin spans

- .travis.yml
- Makefile
- README.md
- cmd/agent/app/agent_test.go
- cmd/opentelemetry/go.sum
- empty_test.go
- go.mod
- go.sum
- pkg/testutils/logger.go
- pkg/testutils/logger_test.go
- tools.go
We have not used it actively, and we don't make much use of godocs.
* Addresses report https://groups.google.com/d/msgid/jaeger-tracing/020db716-6bbc-4aed-a61c-35715f0a5c1fn%40googlegroups.com
* Resolves #2599
> Remove md-to-godoc

- cmd/ingester/app/consumer/deadlock_detector.go
> Clarify deadlock panic message

- cmd/agent/app/servers/tbuffered_server.go
Use of `sync.Pool` requires a `.Put` for every `.Get`.
On success, the downstream `ThriftProcessor` invoked `.Put` via `.DataRecd`
but in error cases there seems to be a leak.
I think I found a leak when reviewing this code for deadlock-related issues. 
Free memory in error cases.
> Return buffers to pool on network errors or queue overflow

- cmd/agent/app/agent_test.go
- cmd/agent/app/servers/tbuffered_server.go
Make a tiny state machine to detect the transition init -> stopped (not via serving)
Not 100% sure about this, I don't now this code and the origin issue mentions an issue `thrift_processor` too, but that might have been fixed already?
Fixes #2601
Related #103
> Avoid deadlock if Stop is called before Serve

- pkg/config/tlscfg/cert_watcher_test.go
- Fixes #2586 
- Explicitly wait for at least two matching log events, since the test asserts on the existence of these two log entries.
> Fix flaky TestAddCertsToWatch_remove_ca test

- cmd/ingester/app/consumer/consumer.go
- cmd/ingester/app/consumer/consumer_test.go
- Closes #1314
Prevent deadlock between the `handleErrors()` and `Close()` functions trying to acquire the `partitionLock` and access the partition WaitGroup by:
- Removing per-partition WaitGroups
- Removing the need for acquiring the `partitionLock` within `Close()`
Additional improvements:
- More correct ordering of `close` calls: Ensure underlying sarama consumer is closed first to prevent repartitioning, causing potentially new partition consumers to be created that attempt to write to already closed channels.
- Instead, `Close()` will rely on `Consumer`-scoped WaitGroups to determine graceful closure of message and error handlers. These WaitGroups will be managed through goroutines monitoring `messagesDone` and `errorsDone` channels, …
> Fix sarama consumer deadlock

- pkg/config/tlscfg/cert_watcher.go
- pkg/config/tlscfg/cert_watcher_test.go
- Fixes #2622
Fixes the flaky `TestReload` test by:
- Firstly logging _after_ the modified certificate has finished reloading, as suggested by @chlunde; and use this log entry as our signal for cert file mod completion.
- Adds assertion on `keyFile` log entry, and make both assertions more specific along with diagnostic data on failure to help with debugging if the race condition presents itself again in future.
Repeated the following test 3x with no errors.:
```
go test -test.count=5000 -test.run=TestReload$ ./pkg/config/tlscfg/
```
> Fix flaky TestReload

- cmd/opentelemetry/go.sum
- go.mod
- go.sum
Update dependency related to CVE-2020-14040.
> Update x/text to v0.3.4

- scripts/travis/build-all-in-one-image.sh
Usually we don't do that and only bump UI for a release, but is there any harm in staying on top of ui/master for the snapshot builds?
> Bump to latest UI for snapshop builds

- CHANGELOG.md
- Prepares master for 1.21.0 release
- Fixes #2627 
Updated the changelog in preparation for release.  Per discussions in the bi-weekly we will not actually merge this PR and build images until early next week, but I wanted this up in case we needed to discuss the changelog.
- ~[ ] Merge #2482 before this PR so it's in 1.21.0~
- ~Since we are pinning jaeger-ui at a commit that is not a release I went ahead and included a jaeger-ui changelog as well.  It appears that normally we just refer to the UI changelog, but that was not an option here~
- I did not include the following lines in the changelog.  Since this is my first time, I'm including them here in case we wanted to keep any of these:
```
* Fix flaky TestReload ([#2624](https://github.com/jaegertracing/jaeger/pull/2624), …
```
> Preparing release 1.21.0

- cmd/agent/app/agent_test.go
Signed-off-by: zouyu <zouy.fnst@cn.fujitsu.com>
- Fix unit test fail
When I run unit test for `cmd/agent/app/agent.go`:
```
--- FAIL: TestAgentSamplingEndpoint (0.01s)
/home/zouyu/WorkSpace/fork/CNCF/jaeger/cmd/agent/app/agent_test.go:68: 
Error Trace:	agent_test.go:68
agent_test.go:129
agent_test.go:46
Error:      	Received unexpected error:
Get "http://[::]:46579/sampling?service=abc": EOF
Test:       	TestAgentSamplingEndpoint
--- FAIL: TestAgentMetricsEndpoint (0.01s)
/home/zouyu/WorkSpace/fork/CNCF/jaeger/cmd/agent/app/agent_test.go:79: 
Error Trace:	agent_test.go:79
agent_test.go:129
agent_test.go:76
Error:      	Received unexpected error:
Get "http://[::]:44179/metrics": EOF
Test:       	TestAgentMetricsEndpoint
FAIL
FAIL	github.com/jaegertracing/jaeger/cmd/agent/app	0.025s
FAIL …
```
> Fix unit test fail

- cmd/collector/main.go
- Fixes #2640
- Handle error from `Start` call in collector.
- Fixes symptom of collector not reporting error and exiting if port 14250 is taken.
Tested happy path where no port conflicts exist as well as failure case:
- Start [jaeger all-in-one](https://www.jaegertracing.io/docs/latest/getting-started/#all-in-one)
- Logs error and returns non-0 exit status code:
```
$ SPAN_STORAGE_TYPE=memory go run ./cmd/collector/main.go
...
{"level":"fatal","ts":1606280888.116083,"caller":"collector/main.go:100","msg":"Failed to start collector","error":"could not start gRPC collector failed to listen on gRPC port: listen tcp :14250: bind: address already in use","stacktrace":"main.main.func1\n\t/Users/albertteoh/go/src/github.com/albertteoh/jaeger/cmd/co …
```
> Handle collector Start error

- plugin/storage/kafka/writer.go
- Fix https://github.com/jaegertracing/jaeger/issues/2653
> fix collector panic due to sarama sdk

- cmd/agent/app/servers/tbuffered_server_test.go
Which problem is this PR solving?
Fixes #2631 
The order for error and second valid packet is changed in `fakeTransport`. Now having second packet dropped guarantees that the error is already processed, which absence was the reason for flaky test
> Fix flaky tbuffered server test

- .github/workflows/protogen-tests.yml
Add GH Actions workflow for protogen tests.
Part of https://github.com/jaegertracing/jaeger/issues/2645
> Add protogen validation test github actions workflow

- .github/workflows/all-in-one-build.yml
- .github/workflows/es-integration-tests.yml
- RELEASE.md
- scripts/travis/build-all-in-one-image.sh
- scripts/travis/es-integration-test.sh
This PR adds the build job of all-in-one image to github actions. 
Part of https://github.com/jaegertracing/jaeger/issues/2645
1. To make the docker login action work we need to add two environment variables like this 
2. To get the branch name we are using github action https://github.com/nelonoel/branch-name which populates env var `BRANCH_NAME`
3. I tried using nodejs official github action (https://github.com/actions/setup-node) instead of calling `scripts/travis/install-ui-deps.sh` but it didn't work and I wasn't able to make it work after several retries. So thought do it in the same way how we do in travis for now.
> Add github action for jaeger all-in-one image

- .github/workflows/all-in-one-build.yml
- scripts/travis/build-all-in-one-image.sh
This add fix and improvements suggested in https://github.com/jaegertracing/jaeger/pull/2663
> Fix and minor improvements to all-in-one github action

- scripts/travis/upload-to-docker.sh
Remove docker login command since that is being done as part of GitHub Actions.
Also remove the extra check for deleting the config.json. I think it was done to prevent any previous docker login session in the same travis runner machine.
> Fix docker login issue with all-in-one build

- scripts/travis/upload-to-docker.sh
Fix https://github.com/jaegertracing/jaeger/pull/2669#issuecomment-735603504
/cc @yurishkuro
> Fix issue with all-in-one build

- pkg/config/tlscfg/cert_watcher_test.go
- Fixes #2654 
- Local testing revealed that `"Failed to load certificate"` is logged every time; however some tests in CI are not logging this failure state, perhaps due to disk I/O variability.
- Given the failure signal is unreliable, this PR removes the failure assertion and only performs an assertion identical to the `waitUntil` condition which should make this test more reliable.
> Move cert loading failure assertion on client public key write

- pkg/config/tlscfg/cert_watcher_test.go
- Addresses remaining comments from @yurishkuro in #2655.
- Shorten best case scenario conditional wait time.
- Leverage `assert`'s formatted string support.
> Address review comments from #2655

- scripts/travis/build-all-in-one-image.sh
When someone creates a PR from fork's master branch, first part of the if condition succeeds and then it looks for DOCKERHUB_LOGIN variable which is only set when we push to master (ie. not for pr) here: https://github.com/jaegertracing/jaeger/blob/master/.github/workflows/ci-all-in-one-build.yml#L38-L41
This is causing unbound variable error. Setting it default to `false` will help in solving the error.
This is currently happening for this PR: https://github.com/jaegertracing/jaeger/pull/2657
> Fix the unbound variable error on all-in-one image build

- Makefile
- plugin/storage/es/Dockerfile
- plugin/storage/es/Dockerfile.rollover
- plugin/storage/es/requirements.txt
Around 10 hours back, python:3-alpine image was upgraded which bumped the pip version from 20.2 to 20.3. 
elasticsearch-curator library has hard requirement of elasticsearch lib v7.1.0 (https://github.com/elastic/curator/blob/master/setup.cfg#L26) which isn't compatible with our escleanup.py.
You can see the failure build where elasticsearch-py is being downgraded to v7.1.0.
```
Collecting elasticsearch
Downloading elasticsearch-7.10.0-py2.py3-none-any.whl (321 kB)
Requirement already satisfied: urllib3<2,>=1.21.1 in /usr/local/lib/python3.9/site-packages (from elasticsearch) (1.24.3)
Collecting elasticsearch-curator
Downloading elasticsearch_curator-5.8.3-py2.py3-none-any.whl (106 kB)
Requirement already satisfied: …
```
> Fix issue for Elasticsearch CI failures

- cmd/opentelemetry/go.sum
- go.mod
- go.sum
go-plugin was accidentally downgraded in a previous merge.
go get github.com/hashicorp/go-plugin@v1.3.0; go mod tidy; git add go.sum go.mod
cd cmd/opentelemetry/; go mod tidy; git add go.sum
Fixes #2593
> Bump go-plugin to 1.3.0

- .github/actions/setup-branch/action.yml
- .github/workflows/ci-all-in-one-build.yml
- .github/workflows/ci-crossdock.yml
- scripts/travis/build-crossdock.sh
Part of https://github.com/jaegertracing/jaeger/issues/2645
Since each takes around 10 minutes, keeping them as separate jobs to let run in parallel.
> Add gh action for crossdock and crossdock otel ci jobs

- cmd/collector/app/span_processor.go
- cmd/collector/app/span_processor_test.go
- Fix https://github.com/jaegertracing/jaeger/issues/1778
> Dedup collector tags

- cmd/agent/main.go
- cmd/all-in-one/main.go
- cmd/collector/main.go
- cmd/ingester/main.go
- cmd/query/main.go
- cmd/status/command.go
- cmd/status/command_test.go
- Resolves https://github.com/jaegertracing/jaeger/issues/2361
- Add status command. 
Usage: `<command> status` checks the localhost and the port of the corresponding component.
`<command> status --status.http.host-port` checks for a specific port or URL.
> Add status command

- plugin/storage/grpc/README.md
I was struggling to generate the gRPC Storage Plugin bindings from the
storage.proto in the Jaeger repo so I created an question on the repo.
Yuri Shkuro helped me out by providing some additional suggestions and
information and requested that I add what I discovered to the README.
Therefore, this update is just a documentation update to the gRPC
Storage Plugin README.md to include details on how one can utilize the
Docker Protobuf image to generate gRPC bindings in C# (which is what my
use-case was).
Resolves #2686
Signed-off-by: Justin Stauffer <justin.stauffer@gmail.com>
> Updated gRPC Storage Plugin README with example

- plugin/storage/es/options.go
- Fixes #2138
- The documentation states that `es.max-span-age` is not taken into account when `use-alias` is enabled, which causes users to think that all indices under the `jaeger-...-read` alias are searchable. However, `es.max-span-age` is used to define the starting window of ES queries like [in this example](https://github.com/jaegertracing/jaeger/blob/6c2be456ca41cdb98ac4b81cb8d9a9a9044463cd/cmd/opentelemetry/app/internal/reader/es/esspanreader/span_reader.go#L101).
- We address this by explicitly documenting that `es.max-span-age` _does_ influence search window start times, without being too specific to implementation.
> Fix misleading use-alias help doc

- .github/workflows/ci-hotrod.yml
- scripts/travis/hotrod-integration-test.sh
Add GitHub Actions for HotRod application.
> Add github actions for hotrod ci job

- cmd/agent/README.md
- pkg/clientcfg/clientcfghttp/handler_test.go
- Resolves https://github.com/jaegertracing/jaeger/issues/285
- Clean-up the outdated "tcollector".
> Clean-up "tcollector" references

- plugin/storage/memory/memory.go
- plugin/storage/memory/memory_test.go
Copying allows spans to be freely modified by adjusters and any other code without accidentally altering what is stored in the in-memory store itself. Resolves #2719.
> Copy spans from memory store, fixes #2719

- pkg/kafka/auth/config.go
Hello Jaeger Team,
This tiny patch will simply add "plaintext" as one of the supported Kafka authentication in the CLI options. 
Thanks for your awesome work on this project.
Signed-off-by: Pierre De Paepe <pierre.de-paepe@ovhcloud.com>
> plaintext as supported kafka auth option

- pkg/discovery/grpcresolver/grpc_resolver.go
- pkg/discovery/grpcresolver/grpc_resolver_test.go
Resolves #2025.
At first this was just adding extra logging, but per the next comment the logging indicated that it's indeed a timing issue.
Also did some clean-up of the code, like pre-allocating arrays with the right sizes.
> [tests] Increase timeout for TestGRPCResolverRoundRobin

- cmd/ingester/app/flags_test.go
- cmd/opentelemetry/app/exporter/kafkaexporter/kafka_exporter.go
- cmd/opentelemetry/app/receiver/kafkareceiver/kafka_receiver.go
- go.mod
- go.sum
- pkg/kafka/auth/config.go
- pkg/kafka/auth/options.go
- pkg/kafka/auth/plaintext.go
- plugin/storage/kafka/factory_test.go
- plugin/storage/kafka/options_test.go
- Resolves #2722 
- Resolves #2046
- Closes #2110 (replaces it)
- The smallest modification on the current version.
- Different from the previous PR #2110, I just modified `pkg/kafka/auth/plaintext.go`  , `pkg/kafka/auth/options.go` and `pkg/kafka/auth/config.go`, and not add any new file.
- More clearly for option name, using option name is `mechanism` (reference from Kafka parameter name rules )
- About the Prefix, I think to keep using `plaintext` better than `scarm`, because these are both belong to `SASL`, in the future, it can change to `sasl` if needed. Actually, using `plaintext` is ok, it will not be confusing, because it name is `SASL_PLAINTEXT` that from Kafka official security protocol parameter name
- About the parameters limit of `mechanism`,  I followed Kafka name rules …
> Add support for Kafka SASL/PLAIN authentication via SCRAM-SHA-256 or SCRAM-SHA-512 mechanism

- GOVERNANCE.md
- README.md
@jaegertracing/jaeger-maintainers
> Add ability to remove inactive maintainers; introduce Emeritus status

- README.md
According to the policy established in #2733.
Once this is merged, the @jaegertracing/jaeger-maintainers group will be updated accordingly.
> Transition black-adder and tiffon to Emeritus Maintainers

- .github/stale.yml
Resolves #2717 
@jpkrohling PTAL
> Enable stale bot for PRs and questions

- plugin/storage/es/spanstore/writer.go
- plugin/storage/es/spanstore/writer_test.go
- Unable to specify a cache duration for the service or index caches
- Our use case requires that we can set these
- Added ability to pass ttl duration for both service and index caches for the elastic spanstore writer
- If not specified it will use the previous defaults of 12h and 48h
> Expose cache ttl for es span writer index+service

- .github/actions/setup-branch/action.yml
- .github/workflows/ci-build-binaries.yml
- .github/workflows/ci-docker-build.yml
- .github/workflows/ci-release.yml
- scripts/travis/package-deploy.sh
- scripts/travis/upload-all-docker-images.sh
- Adds gitbub action to build docker images and packages
- Part of https://github.com/jaegertracing/jaeger/issues/2645
- Release part is still pending. Looking at it, I think we need to use https://github.com/actions/upload-release-asset action but not quite sure how to make it work without changing our current release process.
> Github action for jaeger packages and docker image

- CHANGELOG.md
- cmd/flags/admin.go
Fixes part of https://github.com/jaegertracing/jaeger/issues/2738
Signed-off-by: pradeepnnv <pradeepnnv@gmail.com>
> Remove healthCheckHTTPPortWarning

- CHANGELOG.md
- cmd/collector/app/builder_flags.go
- cmd/opentelemetry/go.sum
- ports/ports.go
- ports/ports_test.go
Signed-off-by: Jacob Goldsworthy <jtgolds6@gmail.com>
-  Resolves part of  #2738 
- Removed the deprecated ```collectorHTTPPort``` flag and the associated warning flag ```collectorHTTPPortWarning```
- Separated the hostPort formatting from ```GetAddressFromCLIOptions``` into its' own function called ```FormatHostPort```
- Wrapped retrieval of the ```CollectorHTTPHostPort``` property with a call to ```FormatHostPort```
- Added tests for the ```FormatHostPort``` function
> Remove deprecated collector flags

- CHANGELOG.md
- plugin/storage/es/options.go
- plugin/storage/es/options_test.go
- Remove deprecated `--es.max-num-spans` flag in v1.21.0 - resolves #2457
- Fixes part of #2738
- Remove deprecated ES option `--es.max-num-spans`
> Remove deprecated es.max-num-spans

- .github/workflows/ci-build-binaries.yml
As described https://github.com/jaegertracing/jaeger/pull/2740#issuecomment-770567346
```
GOOS=linux GOARCH=amd64 make build-platform-binaries
make[1]: Entering directory '/home/runner/work/jaeger/jaeger'
fatal: No names found, cannot describe anything.
```
Each build job of jaeger component's binary adds BUILD_INFO (part of which is extracted from git tag i.e. GIT_CLOSEST_TAG) in Makefile. Hence we need to pull the git tags before building binaries.
> Fix errors in build-binaries task

- CHANGELOG.md
- cmd/agent/app/reporter/flags.go
- cmd/opentelemetry/app/processor/resourceprocessor/flags.go
- cmd/opentelemetry/app/processor/resourceprocessor/resource_processor.go
- cmd/opentelemetry/app/processor/resourceprocessor/resource_processor_test.go
> Remove deprecated --jaeger.tags CLI flag

- .github/workflows/ci-build-binaries.yml
Right now build-binaries is taking around 30 minutes to complete. This should do this in parallel.
Moving each platform binaries build into separate job.
> Divide build-binaries job to multiple jobs per platform

- .github/labeler-needs-triage.yaml
- The `needs-triage` label was added, hoping that it would help us better triage the new issues. Unfortunately, it's not helping much, and I'm afraid it's actually making the situation worse, as it's causing unnecessary noise.
- Remove the action that adds a new label to all new issues.
> Remove needs-triage labeler

- cmd/opentelemetry/go.sum
- go.mod
- go.sum
Previous versions are vulnerable to CVE-2021-3121, aka "skippy peanut butter." This isn't a big issue, as this library is used only during the code generation.
> Update gogo/protobuf to 1.3.2

- go.mod
- go.sum
Temporarily use a personal fork of Apache Thrift, tagged with 1.13.1, which includes the fix for THRIFT-5322 (apache/thrift#2292).
Fixes #2638 and fixes #2452.
The issue to track the reversion of this PR is #2781.
> Use fork of Apache Thrift

- CHANGELOG.md
- pkg/cassandra/config/config.go
- plugin/storage/cassandra/factory_test.go
- plugin/storage/cassandra/options.go
- plugin/storage/cassandra/options_test.go
- plugin/storage/integration/cassandra_test.go
- Relates to #2738
- Removes deprecated cassandra flags
> Remove deprecated cassandra flags

- CHANGELOG.md
- pkg/config/tlscfg/flags.go
- pkg/config/tlscfg/flags_test.go
- plugin/storage/es/mappings/gen_assets.go
- scripts/travis/es-integration-test.sh
- Relates to #2738
- Remove deprecated TLS flags
> Remove deprecated TLS flags

- scripts/travis/upload-to-registry.sh
The PR #2783 introduced a change where container images are also pushed to Quay, but unfortunately, the username was incorrectly set. In order to use the same account that the jaeger-operator uses, I'm changing this here instead of creating a new robot account.
> Fix default username when pushing container images to Quay.io

- plugin/storage/es/factory.go
- plugin/storage/es/factory_test.go
Signed-off-by: santosh <bsantosh@thoughtworks.com>
Resolves #2814 
- Adds a check to make sure that --es.use-ilm is always used in conjunction with--es.use-aliases
Add validation at the top of each ES reader and writer constructor with the following logic:
if cfg.GetUseILM() && !cfg.GetUseReadWriteAliases() {
return nil, fmt.Errorf("the error message")
}
> 2814 - Throw an error when --es.use-ilm is set without --es.use-aliases

- plugin/sampling/strategystore/static/strategy_store.go
- plugin/sampling/strategystore/static/strategy_store_test.go
- Follow up to this discussion: https://github.com/jaegertracing/jaeger/pull/2818#discussion_r579978925
- From the [golang docs on context](https://golang.org/pkg/context/):
> Do not store Contexts inside a struct type; instead, pass a Context explicitly to each function that needs it. The Context should be the first parameter, typically named ctx
- Fixes an anti-pattern where ctx is stored in a struct rather than passed as a first parameter to the goroutine using the struct.
> Pass context to goroutine

- CHANGELOG.md
- Prepares master for 1.22.0 release
- Fixes #2734
- Update changelog following instructions from [RELEASE.md](https://github.com/jaegertracing/jaeger/blob/master/RELEASE.md)
- The excluded PRs (not including dependabot PRs) generated from `make changelog` are as follows:
```
* Pass context to goroutine ([#2823](https://github.com/jaegertracing/jaeger/pull/2823), [@albertteoh](https://github.com/albertteoh))	
* 2814 - Throw an error when --es.use-ilm is set without --es.use-aliases ([#2820](https://github.com/jaegertracing/jaeger/pull/2820), [@bhiravabhatla](https://github.com/bhiravabhatla))	
* Add hotrod in release and push all tags ([#2812](https://github.com/jaegertracing/jaeger/pull/2812), [@Ashmita152](https://github.com/Ashmita152)) …
```
> Preparing release v1.22.0

- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/feature_request.md
- README.md
- RELEASE.md
- SECURITY.md
From Gitter -> Slack.
URL obtained by right-clicking #jaeger channel -> "Copy link".
> Update Jaeger community support URL

- plugin/storage/integration/integration.go
Signed-off-by: Jacob Goldsworthy <jtgolds6@gmail.com>
- Addresses: #2760
- Increase timeout of storage integration tests to allow for longer storage settle time
> Increasing test timeout for TestKafkaStorage

- pkg/es/config/config.go
- plugin/storage/es/factory.go
- plugin/storage/es/options.go
- plugin/storage/es/options_test.go
- plugin/storage/es/spanstore/reader.go
- plugin/storage/es/spanstore/reader_test.go
- plugin/storage/integration/integration.go
- Enables elasticsearch [cross-cluster querying](https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-cross-cluster-search.html)
Resolves #1883
Updates to PR #1892
The cross cluster query api functions by appending a pre-configured remote cluster to an index e.g. cluster_one:index_name. This change simply applies a prefix for each remote cluster and for each index. You will end up with `total_indicies = indicies * remote_clusters`. Also added a special case local which will not append a prefix and query the local cluster.
This works with both standard and rollover indices since it mostly comes down to a simple string manipulation.
> [es] Add remote read clusters option for cross-cluster querying

- docker-compose/jaeger-docker-compose.yml
…llector because http-port no exists
- 
2021/03/23 07:18:54 maxprocs: Leaving GOMAXPROCS=2: CPU quota undefined
Error: unknown flag: --collector.zipkin.http-port
Usage:
jaeger-collector [flags]
jaeger-collector [command]
Available Commands:
docs        Generates documentation
env         Help about environment variables.
help        Help about any command
status      Print the status.
version     Print the version.
Flags:
--admin.http.host-port string                     The host:port (e.g. 127.0.0.1:14269 or :14269) for the admin server, including health check, /metrics, etc. (default ":14269")
--cassandra-archive.connect-timeout duration      Timeout used for connections to Cassandra Servers (default 0s)
--cassandra-archive.connections-per-host int      The number of Cassandra …
> Fix host-port flag in docker-compose

- Makefile
Signed-off-by: Kevin Earls <kearls@redhat.com>
- Currently if you redirect the output of make test to a file (which can be useful for analyzing test failures) that file gets control characters added, which can make grepping for things such as "PASS:" not work correctly
- Allow overriding the COLORIZE value externally.
> Permit overriding COLORIZE in make

- go.mod
- go.sum
- pkg/kafka/auth/plaintext.go
Follow up on https://github.com/xdg-go/scram/issues/3. Use new package name and go.mod version.
> Use go.mod version of github.com/xdg-go/scram

- pkg/healthcheck/handler.go
- pkg/healthcheck/handler_test.go
Signed-off-by: logeable <logeable@gmail.com>
- Resolve #2924 
- set header before call WriteHeader
> Set Content-Type in healthcheck's http response

- cmd/tracegen/main.go
- As seen in #2928, the Jaeger Client for Go creates metrics but tracegen isn't exposing them. 
- This PR starts a new HTTP server on port 2112 with the Prometheus handler on /metrics
> Expose Prometheus metrics for tracegen

- plugin/storage/es/mappings/mapping.go
Signed-off-by: Guangwen Feng <fenggw-fnst@cn.fujitsu.com>
- Fix a typo
- Fix typo in comment in mapping.go
> Fix typo in comment in mapping.go

- Makefile
- Addresses comment from https://github.com/jaegertracing/documentation/pull/500.
Outputs the following if `esc` is not installed:
```
esc: Command not found.
Check:
- esc is installed: 'make install-tools'
- add $GOPATH into $PATH: 'export PATH=$PATH:$(go env GOPATH)/bin'
```
> Add warning if esc not installed

- Makefile
- model/proto/metrics/README.md
- model/proto/metrics/otelmetric.proto
- model/proto/metrics/otelspankind.proto
- model/proto/metrics/service.proto
- Please refer to https://github.com/jaegertracing/jaeger/issues/2954 for context on the use case.
- Addresses review comments from https://github.com/jaegertracing/jaeger-idl/pull/73, one of which is to place the API definition in the main jaeger repository during the prototype phase.
- Defines a vendor-neutral API specification for querying from a metrics backing store.
- Add README to explain the motivation, approach taken and rationale for approach.
- Update Makefile to generate client/server code from new proto files.
- Tested on a working prototype with both gRPC and HTTP clients.
> Add metrics query API spec

- cmd/esmapping-generator/app/flags.go
- cmd/esmapping-generator/app/flags_test.go
- cmd/esmapping-generator/app/renderer/render.go
- cmd/esmapping-generator/app/renderer/render_test.go
- plugin/storage/es/esRollover.py
- plugin/storage/es/mappings/fixtures/jaeger-service-7.json
- plugin/storage/es/mappings/fixtures/jaeger-span-7.json
- plugin/storage/es/mappings/jaeger-service-7.json
- plugin/storage/es/mappings/jaeger-span-7.json
- plugin/storage/es/mappings/mapping.go
- plugin/storage/es/mappings/mapping_test.go
- plugin/storage/integration/es_index_rollover_test.go
- Resolves https://github.com/jaegertracing/jaeger/issues/2967
- Add an option `--ilm-policy-name` to `esmapping-generator`, to set the policy name in the mappings file;
- Set the mapping's option in the rollover script (using an env var - `ES_ILM_POLICY_NAME`).
- The policy name defaults to `jaeger-ilm-policy` (both in the mapping generator and in the `init` action of the rollover script), so no breaking changes are added.
> Allow the ILM policy name to be configurable

- cmd/query/app/grpc_handler.go
- cmd/query/app/grpc_handler_test.go
Fixes a problem where FindTraces misbehaves if sent no query.
> Verify FindTraces() received a query

- cmd/all-in-one/Dockerfile
Closes https://github.com/jaegertracing/jaeger/issues/3022
Setting env var SAMPLING_STRATEGIES_FILE with default value and removing default argument in all-in-one's Dockerfile.
> Passing default sampling strategies file as environment variable

- cmd/query/app/server.go
- Fixes #3025 
- Add expected `cmux.ErrServerClosed` error when connection is closed when waiting to `Accept`.
> Add cmux.ErrServerClosed

- docker/Makefile
Part of https://github.com/jaegertracing/jaeger/issues/3031
All those CVEs are due to alpine:3.12.3. Hence bumping it to latest release of 3.13.
```
❯ trivy image alpine:3.13
2021-05-27T02:14:21.045+0800    INFO    Detected OS: alpine
2021-05-27T02:14:21.045+0800    INFO    Detecting Alpine vulnerabilities...
2021-05-27T02:14:21.051+0800    INFO    Number of PL dependency files: 0
alpine:3.13 (alpine 3.13.5)
===========================
Total: 0 (UNKNOWN: 0, LOW: 0, MEDIUM: 0, HIGH: 0, CRITICAL: 0)
```
> Bump alpine 3.12 -> 3.13 in base image

- pkg/prometheus/config/config.go
- plugin/metrics/prometheus/factory.go
- plugin/metrics/prometheus/factory_test.go
- plugin/metrics/prometheus/metricsstore/reader.go
- plugin/metrics/prometheus/metricsstore/reader_test.go
- plugin/metrics/prometheus/options.go
- Relates to #2954.
- Adds TLS encryption to Prometheus server.
- As [documented](https://prometheus.io/docs/guides/tls-encryption/), Prometheus does not natively support TLS encryption for connections to its HTTP API, however, it does suggest an alternative means of enforcing TLS encryption at the proxy layer with something like nginx.
- This PR was tested using nginx as a reverse proxy to Prometheus, as suggested above.
```
$ METRICS_STORAGE_TYPE=prometheus ./cmd/query/query-darwin-amd64 \
--prometheus.server-url http://localhost:9090
$ METRICS_STORAGE_TYPE=prometheus ./cmd/query/query-darwin-amd64 \
--prometheus.server-url https://example.com/prometheus \
--prometheus.tls.ca=example.com.crt \
--prometheus.tls.enabled
$ …
```
> Add TLS support for Prometheus Reader

- cmd/query/app/querysvc/query_service_test.go
- Relates to #2954.
- Refactor QueryService tests for easier maintenance and reduce required changes when introducing metrics reader to query service:
- Return a `testMocks` struct rather than return multiple mock objects.
- Only use what's required, instead of multiple blank identifiers for unwanted mocks.
- Introduce functional options on a single test bootstrapping function instead of mostly duplicated functions for specific combinations of parameters.
> Refactor QueryService tests

- cmd/query/app/default_params.go
- cmd/query/app/grpc_handler.go
- cmd/query/app/grpc_handler_test.go
- cmd/query/app/http_handler.go
- cmd/query/app/server.go
- cmd/query/app/util.go
- model/proto/metrics/metricsquery.proto
- proto-gen/api_v2/metrics/metricsquery.pb.go
- Relates to #2954.
- Adds the gRPC handler.
> Add MetricsQueryService  grcp handler

- go.mod
- go.sum
Closes #3101 
Not needed, the 0.14.2 is already pulled in.
> Remove not needed replace thrift dependency

- cmd/agent/app/reporter/grpc/flags.go
- cmd/collector/app/builder_flags.go
- cmd/query/app/flags.go
- pkg/config/tlscfg/flags.go
- pkg/config/tlscfg/flags_test.go
- pkg/kafka/auth/config.go
- pkg/kafka/auth/options.go
- plugin/metrics/prometheus/options.go
- plugin/storage/cassandra/options.go
- plugin/storage/es/options.go
- Resolves #3104.
- Removes the redundant `Show*` TLS config flags, which appear to all be `true` and don't seem to have changed for months (in some cases, years) since its [introduction](https://github.com/jaegertracing/jaeger/commit/d553583ce1716285cf71e894f45bc980b67b7012), and cannot see evidence where this could be changed by users via config parameters; i.e. it can only be changed in code.
- If there is still a use case for keeping these flags, please advise and I suggest we document these reasons in a sensible place somewhere in code.
> Remove Show* TLS configs

- README.md
@objectiser has expressed his desire to resign as a maintainer of the Jaeger project, and this PR formalizes the vote/move. Once this PR is merged, I'll change the GitHub group accordingly.
Thank you very much for your contributions, @objectiser, including the over 200 PRs you created and 300 issues you opened.
> gbrown as emeritus maintainer

- cmd/agent/app/builder.go
Fix incorrect naming
```diff
-       zipkinThrift "github.com/jaegertracing/jaeger/thrift-gen/agent"
+       agentThrift "github.com/jaegertracing/jaeger/thrift-gen/agent"
```
> Fix package naming

- cmd/agent/app/builder.go
- cmd/agent/app/httpserver/srv.go
- cmd/agent/app/httpserver/srv_test.go
- cmd/collector/app/server/http.go
- cmd/collector/app/server/zipkin.go
- cmd/flags/admin.go
- cmd/query/app/server.go
> Define `http.Server.ErrorLog` to forward logs to Zap

- docker/Makefile
- docker/debug/Dockerfile
- scripts/build-all-in-one-image.sh
- scripts/build-upload-docker-images.sh
- scripts/hotrod-integration-test.sh
Signed-off-by: Krishna Harsha Voora <krishvoor@in.ibm.com>
Re-adding the support for ppc64le arch, as it was missing in the following files.
* updates `docker/Makefile`, `scripts/build-all-in-one-image.sh`, `scripts/build-upload-docker-images.sh`, `scripts/hotrod-intergration-test.sh` & `docker/debug/Dockerfile`
>  Add ppc64le support on multiarch docker images

- plugin/sampling/strategystore/static/strategy_store.go
- plugin/sampling/strategystore/static/strategy_store_test.go
Help with #2197 
```
$ go run ./cmd/all-in-one --sampling.strategies-file cmd/all-in-one/sampling_strategies.json
...
{"level":"info","ts":1627395862.803787,"caller":"static/strategy_store.go:138","msg":"Loading sampling strategies","filename":"cmd/all-in-one/sampling_strategies.json"}
...
```
> Log the source of sampling strategies

- plugin/storage/es/Dockerfile
- plugin/storage/es/Dockerfile.rollover
> Pin elasticsearch-py to older version without elastic.co product check

- cmd/all-in-one/all_in_one_test.go
- cmd/query/app/apiv3/grpc_gateway.go
- cmd/query/app/apiv3/grpc_gateway_test.go
- proto-gen/api_v3/query_service.pb.gw.go
Implementation for https://github.com/jaegertracing/jaeger-idl/pull/82
> Add /api prefix for /v3 API

- plugin/storage/es/spanstore/reader.go
- plugin/storage/es/spanstore/reader_test.go
Resolves #3152
@albertteoh could you please review?
> Set lookback in ES rollover to distant past

- docker/Makefile
- docker/debug/Dockerfile
Resolves #3188 
Per the [docs][1], delve can now be installed via `go install`
[1]: https://github.com/go-delve/delve/blob/master/Documentation/installation/README.md
> Use golang:1.16-alpine and `go install` to install delve

- pkg/es/config/config.go
- plugin/storage/es/options.go
- plugin/storage/es/options_test.go
Signed-off-by: Nathanael Marchand <nathanael.marchand@outlook.com>
Resolves #3191 
This PR configures the property SendGetBodyAs on the elastic search client to allow sending HTTP requests with a body with another verb than GET (which might cause networking issue on some WAF or load balancers).
In order to do that, I've created an option -es.send-get-body-as to specify the verb to use.
I open this PR early to gather feedback as Go is not my native development language ;)
> Add SendGetBodyAs flag on elasticsearch storage

- .github/workflows/ci-elasticsearch.yml
- pkg/es/config/config.go
- plugin/storage/es/esRollover.py
- plugin/storage/integration/elasticsearch_test.go
- scripts/es-integration-test.sh
Updates #3044 
* Automatically set ES version to 7 if OpenSearch 1x is used
* Add OpenSearch to itests
> Automatically detect OpenSearch version

- cmd/es-index-cleaner/app/flags.go
- cmd/es-index-cleaner/app/flags_test.go
- cmd/es-index-cleaner/app/index_client.go
- cmd/es-index-cleaner/app/index_client_test.go
- cmd/es-index-cleaner/app/index_filter.go
- cmd/es-index-cleaner/app/index_filter_test.go
- cmd/es-index-cleaner/main.go
Updates #3179
Sharing this early to get some reviews. The only missing part in this PR is to increase the test coverage.
Future PRs:
* add support for user/pass and TLS
* add docker build and include this in ES integration tests
* remove old python implementation
> Add es-index-cleaner golang implementation

- Makefile
Reverts jaegertracing/jaeger#3205
These targets are defined here https://github.com/jaegertracing/jaeger/blob/master/docker/Makefile
> Revert "Remove nonexisting make targets"

- cmd/collector/app/builder_flags.go
- cmd/collector/app/builder_flags_test.go
- cmd/collector/app/collector.go
- cmd/collector/app/options.go
- cmd/collector/app/server/grpc.go
- cmd/collector/app/server/grpc_test.go
Resolves #3210 
Added a new CLI option for the gRPC Collector to override the default
max receive message size which is normally 4MB since some users of
Jaeger may want to record Spans which exceed the default max size.
Signed-off-by: Justin Stauffer <justin@epic.com>
> Add CLI Option for gRPC Max Receive Message Size

- .github/workflows/ci-all-in-one-build.yml
- .github/workflows/ci-crossdock.yml
- .github/workflows/ci-docker-build.yml
- .github/workflows/ci-hotrod.yml
- .github/workflows/ci-release.yml
- docker/Makefile
- scripts/hotrod-integration-test.sh
Updates #3209 
This PR adds make target to configure docker buildx command. The idea is to allow contributors to run the build locally the same way how it runs on CI.
> Add docker buildx make target

- go.mod
- go.sum
Bump badger to v3.2103.1
This version of badger removes datadog/ztsd and uses klauspost/compress, hence removes CGO completely.
> Bump badger to v3.2103.1

- .github/workflows/ci-cassandra.yml
- docker-compose/jaeger-docker-compose.yml
- plugin/storage/cassandra/Dockerfile
- plugin/storage/cassandra/schema/create.sh
- plugin/storage/cassandra/schema/v004.cql.tmpl
- plugin/storage/integration/cassandra_test.go
- scripts/cassandra-integration-test.sh
- scripts/es-integration-test.sh
Resolves https://github.com/jaegertracing/jaeger/issues/3080
We don't need to add v003tov004.sh because the change (removal of dclocal_read_repair_chance config) is in table metadata which gets handled seemlessly within cassandra upgrade (tested locally) when users upgrade their cassandra cluster from v3.11 to v4.0. So there won't be any scenario, where existing user will need migrate their data.
> Add cassandra v4 support

- cmd/flags/flags.go
- cmd/flags/flags_test.go
If `--agent.tags` (or other tags) are malformed, display the invalid value as part of the panic.
No related Github issue.  Found this while testing the operator.  Improves an error message that will appear in the pod log if a misconfiguration keeps the Jaeger Query deployment from starting.
Old message:
```
panic: runtime error: index out of range [1] with length 1
```
New Message
```
panic: invalid Jaeger tag pair "dummy", expected key=value
```
Reproduce by building locally and running `~/go/src/github.com/jaegertracing/jaeger/cmd/query/query-darwin-amd64 --agent.tags=dummy`
> Check for invalid --agent.tags

- cmd/collector/app/handler/grpc_handler.go
- cmd/collector/app/handler/grpc_handler_test.go
Resolves #3235
Import gzip compressor in cmd/collector/app/handler. That way gzip compressor is linked into every binary that exposes collector GRPC endpoint.
> Enable gzip compression for collector grpc endpoint.

- plugin/storage/integration/grpc_test.go
Resolves #3221 
- If PLUGIN_CONFIG_PATH env var is set, its value is passed to --grpc-storage-plugin.configuration-file flag.
> Added ability to pass config file to grpc plugin in integration tests

- cmd/es-index-cleaner/.gitignore
- plugin/storage/es/.gitignore
- plugin/storage/factory.go
- plugin/storage/factory_config.go
- plugin/storage/integration/elasticsearch_test.go
- scripts/es-integration-test.sh
> Add 'opensearch' as a supported value for SPAN_STORAGE_TYPE

- cmd/es-index-cleaner/main.go
> Use UTC in es-index-cleaner

- cmd/agent/app/servers/thriftudp/socket_buffer.go
- cmd/all-in-one/all_in_one_test.go
- cmd/query/app/ui/actual.go
- cmd/query/app/ui/placeholder.go
- pkg/config/tlscfg/certpool_unix.go
- pkg/config/tlscfg/certpool_windows.go
- plugin/storage/badger/stats.go
- plugin/storage/badger/stats_test.go
- plugin/storage/integration/es_index_cleaner_test.go
- plugin/storage/integration/es_index_rollover_test.go
- plugin/storage/integration/token_propagation_test.go
- tools.go
Fixes #3268.
Signed-off-by: Pablo Baeyens <pablo.baeyens@datadoghq.com>
> Re-add `// +build` style build flags for building with Go 1.16

- docker-compose/monitor/otel-collector-config.yml
Signed-off-by: Ashmita152 <ashmita.bohara@logz.io>
- Fixing otel configuration in docker-compose
- As per this https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/5428 they have modified the tls configuration key.
> Fixing otel configuration in docker compose

- plugin/storage/cassandra/schema/v004.cql.tmpl
#2966 Added support for adaptive sampling which included 3 new cassandra tables. Meanwhile #3225 created a new cassandra schema template file v004.cql.tmpl. Because these two PRs were in flight at the same time the v004.cql.tmpl file did not include the tables necessary for adaptive sampling.  Adding them here.
> Add adaptive sampling tables to v4

- plugin/storage/es/spanstore/reader.go
- plugin/storage/es/spanstore/reader_test.go
Resolves #3270
Version 1.26 introduced an automatic configuration for the query lookback
when using ElasticSearch with aliases enabled.  When aliases are enabled,
the ES plugin will look back 100 years.  This pre-dates the Unix epoch, and
while such dates can be modeled as negative timestamps, the model defined
in `jaeger/model/time.go` only supports unsigned timestamps.  As a result,
the 100-year lookback ends up overflowing the time model, resulting in a
distant-future lookback date, rather than a distant-past lookback date.
While the time model could be updated to support negative timestamps, it
seems unlikely that any Jaeger users would reasonably need to search for
spans from the 1920s.  This reduces the automatic lookback to 50 years to
remove the overflow issue while still …
> Close #3270: Prevent rollover lookback from passing the Unix epoch

- cmd/all-in-one/main.go
- cmd/collector/main.go
- cmd/env/command.go
- docker-compose/jaeger-docker-compose.yml
- plugin/sampling/strategystore/factory.go
- plugin/sampling/strategystore/factory_config.go
- plugin/sampling/strategystore/factory_config_test.go
- plugin/sampling/strategystore/factory_test.go
As suggested here: https://github.com/jaegertracing/documentation/pull/526
This PR renamed `SAMPLING_TYPE` env var to `SAMPLING_CONFIG_TYPE`. Additionally it extends the collector help text to include information about this new env var.
New text:
```
$ go run ./cmd/collector env
2021/10/04 10:00:45 maxprocs: Leaving GOMAXPROCS=8: CPU quota undefined
All command line options can be provided via environment variables by converting
their names to upper case and replacing punctuation with underscores. For example:
command line option                 environment variable
------------------------------------------------------------------
--cassandra.connections-per-host    CASSANDRA_CONNECTIONS_PER_HOST
--metrics-backend                   METRICS_BACKEND
The following configuration options are …
```
> Changed sampling type env var and updated collector help text

- docker/Makefile
Signed-off-by: Nont <nontkrub@gmail.com>
This is update of [my previous PR](https://github.com/jaegertracing/jaeger/pull/3303), Bumping the version of the image from alpine-3.13 to alpine-3.14 for both the root and the go images.
> Upgrade to alpine-3.14

- CHANGELOG.md
- Makefile
- RELEASE.md
- Added 1.27.0 release notes
- Added note for `make changelog` that only default token permissions are needed
> Prepare release 1.27.0

- Makefile
- plugin/sampling/strategystore/adaptive/processor.go
- plugin/sampling/strategystore/adaptive/processor_test.go
- Immutability bug discovered in PR https://github.com/jaegertracing/jaeger/pull/3350
- correct slight immutability issue discovered while enabling test shuffling
> [bugfix] Treat input throughput data as immutable

- CHANGELOG.md
- RELEASE.md
- Add 1.28.0 release notes.
- Rotate release managers.
- Pin to Jaeger UI v1.18.0.
> Prepare release 1.28.0

- Makefile
- scripts/release-notes.py
- When generating release notes, the most relevant commit messages for the release are those that are before the previous release tag.
- `make changelog` nicely outputs these relevant changes, however, the release manager either needs to scroll to the top where the relevant commits are then copy-paste them.
- `make changelog` depends on a personal docker image and would be a burden to the owning engineer to keep publishing improvements/updates.
- In most cases, `dependabot` version bumps are not relevant to a changelog.
This PR proposes the following improvements:
- Uses argparse to manage arguments, providing sensible defaults, which has the following benefits:
- More robust parameter handling.
- Better help documentation.
- Given …
> Improve release notes script

- docker/Makefile
- docker/debug/Dockerfile
- scripts/build-all-in-one-image.sh
* Install `build-base` in debug image to provide GCC required by delve
* Resolves #3401
* Clean up after https://github.com/docker-library/golang/issues/383 has been resolved.
> Fix debug image builds by installing `build-base` to enable GCC

- .codecov.yml
- .github/workflows/ci-all-in-one-build.yml
- .github/workflows/ci-build-binaries.yml
- .github/workflows/ci-cassandra.yml
- .github/workflows/ci-crossdock.yml
- .github/workflows/ci-docker-build.yml
- .github/workflows/ci-elasticsearch.yml
- .github/workflows/ci-grpc-badger.yml
- .github/workflows/ci-hotrod.yml
- .github/workflows/ci-kafka.yml
- .github/workflows/ci-protogen-tests.yml
- .github/workflows/ci-unit-tests.yml
- .github/workflows/codeql.yml
- .github/workflows/fossa.yml
- CHANGELOG.md
- GOVERNANCE.md
- README.md
- RELEASE.md
- SECURITY.md
- cmd/query/app/ui/placeholder/index.html
- docker-compose/monitor/README.md
- examples/hotrod/README.md
- monitoring/jaeger-mixin/README.md
- scripts/build-crossdock.sh
- scripts/build-upload-a-docker-image.sh
- scripts/compute-tags.sh
- scripts/hotrod-integration-test.sh
- scripts/release-notes.py
> Prepare to rename master to main

- .github/workflows/ci-opensearch.yml
The integration tests don't seem to be as stable on opensearch as they are for elasticsearch, and restarting it would restart the entire matrix. This PR splits the opensearch test execution from those of elasticsearch, making it easier to re-run only that portion of the matrix. It would also help us determine whether opensearch is the only stable variant for this integration test.
> Split opensearch tests from elasticsearch

- cmd/collector/app/builder_flags.go
- cmd/collector/app/builder_flags_test.go
- cmd/collector/app/collector.go
- cmd/collector/app/server/grpc.go
Closes #1678 by adding two new flags, allowing operators to control the max-connection-age and max-connection-age-grace durations for the collector's gRPC server. Setting the max-connection-age to a few seconds/minutes will cause clients to rediscover collector nodes periodically, by forcing the subchannels to go away after it reaches a certain age. The grace option allows in-flight connections to complete before being forcefully closed.
> Add MaxConnectionAge[Grace] to collector's gRPC server

- .github/workflows/ci-build-binaries.yml
- Makefile
- scripts/package-deploy.sh
Signed-off-by: Jean-Hadrien Chabran <jh@chabran.fr>
Hello 👋 (reopening this with a proper feature branch)  
I noticed that the release binaries do not include darwin/arm64, which is just about adding it to the build scripts. 
I added a target in the Makefile and patched a few other scripts. You can see a successful binary build here https://github.com/jhchabran/jaeger/runs/4216116176?check_suite_focus=true and the release workflow uploads here: https://github.com/jhchabran/jaeger/releases/tag/v1.28.1 
Please tell me if I have missed anything!
> Build binaries for darwin/arm64

- Makefile
- docker/Makefile
Resolves #3445
With this change, I can build on a Mac.  The biggest problem is that the Mac doesn't let the containers see the real _localhost_, but instead puts the Mac's localhost at _host.docker.internal_.
First, I must tell Docker to let host.docker.internal be insecure:
```bash
cat <<EOF | > /tmp/buildkitd.toml
[registry."host.docker.internal:5000"]
http = true
EOF
docker buildx create --use --config /tmp/buildkitd.toml
```
I then build using
make build-binaries-linux
PLATFORMS=linux/amd64 DOCKER_REPO=host.docker.internal:5000 make docker-images-jaeger-backend
(Note that I am confident about every change except for the `--load`.  I am not sure what that is needed!  Without it, the build complained that "No output specified for …
> Let build be customized by env vars for OSX

- .gitmodules
- This PR set the git sub-module branches, some git libraries have problems with git sub-modules that doesn't provide information about their branch, it wrong assumes that the branch is master and fails to update the sub-modules when it doesn't exist. Because we removed our master branches it will fail:
See for example this : https://github.com/gitpython-developers/GitPython/issues/1058 
- Set `branch=main` on `.gitmodules` file
> Specify branch in submodules

- cmd/agent/app/configmanager/grpc/manager_test.go
- cmd/agent/app/processors/thrift_processor_test.go
- cmd/agent/app/reporter/grpc/builder.go
- cmd/agent/app/reporter/grpc/reporter_test.go
- cmd/anonymizer/app/query/query.go
- cmd/collector/app/handler/grpc_handler_test.go
- cmd/collector/app/server/grpc_test.go
- cmd/query/app/apiv3/grpc_gateway.go
- cmd/query/app/apiv3/grpc_handler_test.go
- cmd/query/app/grpc_handler_test.go
- cmd/query/app/server_test.go
- examples/hotrod/services/driver/client.go
- pkg/discovery/grpcresolver/grpc_resolver_test.go
- plugin/storage/grpc/config/config.go
This change keeps staticcheck linter from failing when grpc is updated to v1.43 or higher.
Because after that version, grpc.WithInsecure is marked as deprecated.
See: https://github.com/grpc/grpc-go/pull/4718
Closes #3450
Signed-off-by: Benedikt Bongartz <benne@klimlive.de>
> Prepare grpc bump to v1.43 or higher

- cmd/es-rollover/app/flags.go
- cmd/es-rollover/app/flags_test.go
- cmd/es-rollover/app/index_options.go
- cmd/es-rollover/app/index_options_test.go
- pkg/es/client/index_client.go
- pkg/es/client/index_client_test.go
- Resolves #3441 
- Fixes the bug where read aliases are not rolled over, and remain on the first index.
- Update unit tests.
- Reproduced the bug locally; output of aliases after 3 rollovers with prefixes (note write aliases successfully rollover, but read aliases remain pointing to first index):
```
foo-jaeger-service-write foo-jaeger-service-000003 - - - -
foo-jaeger-span-read     foo-jaeger-span-000001    - - - -
foo-jaeger-service-read  foo-jaeger-service-000001 - - - -
foo-jaeger-span-write    foo-jaeger-span-000003    - - - -
```
- After the fix, the aliases look like the following after 3 rollovers (note each rolled over index is tracked by the read alias):
```
foo-jaeger-service-read  foo-jaeger-service-000001 - - - - …
```
> Fix prefixed index rollover

- README.md
Now that Jaeger SDKs are officially deprecated, we should point less to OpenTracing.
> Tone down OpenTracing aspects

- README.md
- RELEASE.md
Dear Jaeger Community, dear fellow Jaeger maintainers (@jaegertracing/jaeger-maintainers),
After [almost four years](https://github.com/jaegertracing/jaeger/issues/849) as a Jaeger maintainer, I'm resigning today. It's a tough decision, but one that I think is in the best interest of the project. As Jaeger moves toward v2, it needs people who can actually provide engineering work to the project, and I cannot realistically provide it.
My contributions to the OpenTelemetry community, especially the OpenTelemetry Collector, started as a way to build the features there that I thought would be useful to Jaeger v2, such as the auth and multitenancy capabilities. My involvement there kept growing, to the point where I was way more active there than here. Even before moving to Grafana Labs, I …
> jpkrohling as emeritus maintainer

- pkg/kafka/auth/config.go
- pkg/kafka/auth/plaintext.go
> Use existing functions from xdg-go/scram pkg

- go.mod
- go.sum
Resolves #3492
Updates gocql version to latest in order to add support for more Cassandra authenticators.
> Bump gocql version

- cmd/es-index-cleaner/app/index_filter.go
- cmd/es-rollover/app/index_options.go
- cmd/es-rollover/app/index_options_test.go
- cmd/esmapping-generator/app/renderer/render.go
- plugin/storage/es/dependencystore/storage.go
- plugin/storage/es/dependencystore/storage_test.go
- plugin/storage/es/factory.go
- plugin/storage/es/mappings/fixtures/jaeger-dependencies-7.json
- plugin/storage/es/mappings/jaeger-dependencies-7.json
- plugin/storage/integration/elasticsearch_test.go
- plugin/storage/integration/es_index_cleaner_test.go
- plugin/storage/integration/es_index_rollover_test.go
Currently the dependency store has no support for index aliases / rollover indices.
Resolves https://github.com/jaegertracing/jaeger/issues/2143#
Use the already existing and used config variable `UseReadWriteAliases` to switch between the current behavior and using non-dated "-read" and "-write" index names. This aligns with the behavior that is already in place for spans and services.
> Add support for ES index aliases / rollover to the dependency store (Resolves #2143)

- .github/workflows/ci-all-in-one-build.yml
- .github/workflows/ci-build-binaries.yml
- .github/workflows/ci-cassandra.yml
- .github/workflows/ci-crossdock.yml
- .github/workflows/ci-docker-build.yml
- .github/workflows/ci-elasticsearch.yml
- .github/workflows/ci-grpc-badger.yml
- .github/workflows/ci-hotrod.yml
- .github/workflows/ci-kafka.yml
- .github/workflows/ci-opensearch.yml
- .github/workflows/ci-protogen-tests.yml
- .github/workflows/ci-release.yml
- .github/workflows/ci-unit-tests.yml
- .github/workflows/fossa.yml
> Bump Go compiler in CI to 1.17.6

- plugin/storage/integration/integration_test.go
I'm using the integration test framework to test my custom [grpc plugin](https://github.com/johanneswuerbach/jaeger-s3), which is working great, except that it can't really deal with traces hours in the future.
Traces in the future are happening if you run the tests before 16:00 UTC as on fixture loading only the date is replaced with the current day, but not the time.
If I run my tests after 17:00 UTC all tests pass as all spans are now in the past.
- Adjusted the timeframe to be yesterday and the day before to ensure no spans are generated in the future.
> fix(integration): no spans in the future

- pkg/config/tlscfg/ciphersuites.go
- pkg/config/tlscfg/ciphersuites_test.go
- pkg/config/tlscfg/flags.go
- pkg/config/tlscfg/flags_test.go
- pkg/config/tlscfg/options.go
- pkg/config/tlscfg/options_test.go
Signed-off-by: Ashmita <ashmita.bohara@logz.io>
Part of  https://github.com/jaegertracing/jaeger/issues/3019
In golang's tls package, there are two kinds of ciphers: secure and insecure, we need to support both hence we are creating a map of all ciphers (mapping cipherName to cipherID) 
I will raise min tls version support as separate pr.
> Add support for ciphersuites in tls config

- pkg/config/tlscfg/ciphersuites.go
- pkg/config/tlscfg/ciphersuites_test.go
- pkg/config/tlscfg/flags.go
- pkg/config/tlscfg/flags_test.go
- pkg/config/tlscfg/options.go
- pkg/config/tlscfg/options_test.go
Signed-off-by: Ashmita152 <ashmita.bohara@logz.io>
- Closes https://github.com/jaegertracing/jaeger/issues/3566
- Add support for minimum tls version
> Add minimum and maximum tls version support in tls config

- cmd/all-in-one/all_in_one_test.go
- docker/base/Dockerfile
- docker/debug/Dockerfile
Signed-off-by: Ashmita152 <ashmita.bohara@logz.io>
- Resolves https://github.com/jaegertracing/jaeger/issues/3563
- net/http depends on mime-type to set the Content-Type for a http response (https://github.com/golang/go/blob/master/src/net/http/fs.go#L173-L176)
- mime-type is calculated using https://pkg.go.dev/mime#TypeByExtension (https://github.com/golang/go/blob/master/src/net/http/fs.go#L235)
- In alpine, there is no default installation of mime-type library hence net/http was setting application/text for favicon.ico which was leading to 500. Adding mailcap package will install /etc/mime.types (https://pkgs.alpinelinux.org/contents?branch=edge&name=mailcap&arch=x86_64&repo=main) and fix the issue by setting the right content-type.
cc @yurishkuro
> Fix favicon returning 500 inside container

- plugin/sampling/strategystore/adaptive/factory.go
- plugin/storage/factory.go
- plugin/storage/factory_config.go
- plugin/storage/factory_config_test.go
- plugin/storage/factory_test.go
- Adds support for a new environment variable `SAMPLING_STORAGE_TYPE`. This allows the user to independently configure
their `SPAN_STORAGE_TYPE` and `SAMPLING_STORAGE_TYPE`. e.g. the user could choose to store their spans in elasticsearch while putting their adaptive sampling data in cassandra. This also paves the way for simpler to operate sampling storage types like redis or memcached.
- Add support for `SAMPLING_STORAGE_TYPE` to plugin/storage/factory_config.go
- Add support to plugin/storage/factory.go to return the correct factory or fall back to previous behavior if unspecified.
- Add relevant testing.
> Add SAMPLING_STORAGE_TYPE environment variable

- plugin/storage/es/factory.go
- plugin/storage/es/factory_test.go
clone of https://github.com/jaegertracing/jaeger/pull/3599 from another source branch to fix CI
With ILM, index patter overridden without lifecycle policy set by collector if not explicitly disabled with --es.create-index-templates=false
Proposal
> Ilm disable template

- .github/workflows/ci-all-in-one-build.yml
- .github/workflows/ci-build-binaries.yml
- .github/workflows/ci-cassandra.yml
- .github/workflows/ci-crossdock.yml
- .github/workflows/ci-docker-build.yml
- .github/workflows/ci-elasticsearch.yml
- .github/workflows/ci-grpc-badger.yml
- .github/workflows/ci-hotrod.yml
- .github/workflows/ci-kafka.yml
- .github/workflows/ci-opensearch.yml
- .github/workflows/ci-protogen-tests.yml
- .github/workflows/ci-release.yml
- .github/workflows/ci-unit-tests.yml
- .github/workflows/fossa.yml
This PR pins our CI to use 1.17.x. This should resolve recent issues with golangci-lint:
> Pin CI to use Go 1.17

- CHANGELOG.md
- RELEASE.md
Updates changelog, release.md and jaeger ui for the 1.33.0 release.
> Prepare release 1.33.0
